### ISSUE TITLE
Git: fetch all branches before switching to the given revision, if branch=None

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2848]
This ticket is a migrated Trac ticket [2750](http://trac.buildbot.net/ticket/2750)

People contributed to the original ticket: @djmitche, @sa2ajj
Ticket created on: `Apr 07 2014`
Ticket last modified on: `Sep 09 2014`

---

See https://github.com/buildbot/buildbot/pull/1074

`branch=None` is a bit of a degenerate case, referring vacuously to the "default branch", which in Git really means master.  However, it's also the default, and there's no reason to make that default fail in the interest of an optimization (not fetching every commit).

---

_Comment from_: @sa2ajj
_Date_: `Sep 08 2014`

Maybe the meaning of `branch=None` should be reconsidered:
* if revision is not specified -> **default branch**
* if a revision is specified -> fetch that particular revision and set it as the one to work on

---
_Comment from_: @dustin
_Date_: `Sep 09 2014`

Maybe I misunderstand, but you can't instruct git to fetch a specific revision from a remote repository -- only to fetch some named revision (and its parents).

---
_Comment from_: @sa2ajj
_Date_: `Sep 09 2014`

Maybe, I misremembered something.

I'll investigate and update the ticket.

---
_Comment from_: @sa2ajj
_Date_: `Sep 09 2014`

It looks like

    git fetch <remote> <SHA-1>:FETCH_HEAD

works just fine.

    $ git --version
    git version 2.1.0

---
_Comment from_: @dustin
_Date_: `Sep 09 2014`

Hah, well, I stand corrected!

**Comment by Frodox** [comment]
Just my 50 cents. Default  branch isn't  always ` master` one :)

**Comment by djmitche** [comment]
Yeah, I think if you're using a branch other than master, then `branch=None` is not a good choice :)
