### ISSUE TITLE
gerritStartCB don't work

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2851]
This ticket is a migrated Trac ticket [2755](http://trac.buildbot.net/ticket/2755)

People contributed to the original ticket: @djmitche, @unknown_contributor
Ticket created on: `Apr 13 2014`
Ticket last modified on: `Jun 18 2014`

---

Hi,

I try the code in http://docs.buildbot.net/latest/manual/cfg-statustargets.html about update Gerrit Status.

No problem with gerritReviewCB or gerritSummaryCB with last trunk
but gerritStartCB don't work

I look the code
and in master/buildbot/status/status_gerrit.py

            # Gerrit + Git
            if build.getProperty("gerrit_branch") is not None:  # used only to verify Gerrit source

build.getProperty("gerrit_branch") is always None with [[GerritStart]]CB

---

**Comment by p12tic** [comment]
Buildbot 4.0 will no longer have gerritStartCB.
