### ISSUE TITLE
buildbot.test.integration.test_slave_comm.TestSlaveComm.test_duplicate_slave is flaky

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2854]
This ticket is a migrated Trac ticket [2761](http://trac.buildbot.net/ticket/2761)

People contributed to the original ticket: @djmitche, @tardyp
Ticket created on: `Apr 20 2014`
Ticket last modified on: `Dec 14 2016`

---

    Traceback (most recent call last):
    Failure: twisted.trial.util.[[DirtyReactorAggregateError]]: Reactor was unclean.
    Selectables:
    <Broker #1 on 28977>

Disabled in #2748.

---

_Comment from_: @tardyp
_Date_: `Dec 14 2016`

https://github.com/buildbot/buildbot/pull/2545

**Comment by seankelly** [comment]
Fixed in #2545.
