### ISSUE TITLE
buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait is flaky

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2855]
This ticket is a migrated Trac ticket [2762](http://trac.buildbot.net/ticket/2762)

People contributed to the original ticket: @djmitche, @sa2ajj, @unknown_contributor
Ticket created on: `Apr 20 2014`
Ticket last modified on: `Aug 27 2015`

---

    ===============================================================================
    [ERROR]
    Traceback (most recent call last):
    Failure: twisted.trial.util.[[DirtyReactorAggregateError]]: Reactor was unclean.
    [[DelayedCalls]]: (set twisted.internet.base.[[DelayedCall]].debug = True to debug)
    <[[DelayedCall]] 0x80c0d3b90 [3599.75786614s] called=0 cancelled=0 [[BuildSlave]].doKeepalive()>
    
    buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
    ===============================================================================
    [ERROR]
    Traceback (most recent call last):
    Failure: twisted.trial.util.[[DirtyReactorAggregateError]]: Reactor was unclean.
    Selectables:
    <Broker #0 on 10145>
    
    buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait

Disabled in #2748.

---

_Comment from_: @dustin
_Date_: `Apr 11 2015`

Fixed in #3246.

---
_Comment from_: @unknown_contributor
_Date_: `Aug 15 2015`

http://blackjml.livejournal.com/23029.html may describe a better fix.

---
_Comment from_: @sa2ajj
_Date_: `Aug 26 2015`

Should we port this to nine?

---
_Comment from_: @dustin
_Date_: `Aug 27 2015`

For the most part, we already do wait for connections to stop.

But looking at the code here, the client's cleanup is just:

        def cleanup(self, res=None):
            if self.buildsetStatus:
                self.buildsetStatus.broker.transport.loseConnection()

with no waiting for that to complete.

---
_Comment from_: @dustin
_Date_: `Aug 27 2015`

The test seems to fail (hang) repeatably now, actually:

    612 2015-08-27 09:36:09-0400 [-] Unhandled error in Deferred:
    613 2015-08-27 09:36:09-0400 [-] Unhandled Error
    614 Traceback (most recent call last):
    615   File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    616     self.mainLoop()
    617   File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
    618     self.run[[UntilCurrent]]()
    619   File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in run[[UntilCurrent]]
    620     call.func(*call.args, **call.kw)
    621   File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in __call__
    622     d = defer.maybeDeferred(self.f, *self.a, **self.kw)
    623 --- <exception caught here> ---
    624   File "/home/dustin/code/buildbot/t/buildbot/sandbox/lib/python2.7/site-packages/twisted/internet/defer.py", line 141, in maybeDeferred
    625     result = f(*args, **kw)
    626 exceptions.[[TypeError]]: <lambda>() takes no arguments (1 given)

---
_Comment from_: @dustin
_Date_: `Aug 27 2015`

That was a bug in the tests.

The `[[RemoteBuildRequest]].remote_subscribe` method tries to subscribe to `builders.<builderid>.builds` which doesn't exist.  In other words, this code is pretty badly broken.

---
_Comment from_: @dustin
_Date_: `Aug 27 2015`

OK, I added a subscription for that pattern, and I'm trying to reproduce the flake.

---
_Comment from_: @dustin
_Date_: `Aug 27 2015`

https://github.com/buildbot/buildbot/pull/1828

**Comment by seankelly** [comment]
Fixed in #1828.
