### ISSUE TITLE
LatentSlaveBuilder status does not get reset to LATENT when detached

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2856]
This ticket is a migrated Trac ticket [2770](http://trac.buildbot.net/ticket/2770)

People contributed to the original ticket: @djmitche, @unknown_contributor, @sa2ajj
Ticket created on: `Apr 30 2014`
Ticket last modified on: `Sep 04 2014`

---

When insubstantiating a latent slave, its slavebuilders' status doesn't get reset to LATENT. On subsequent builds, the SlaveBuilder list passed to nextSlave will incorrectly note the slave as IDLE instead of LATENT.

---

_Comment from_: @sa2ajj
_Date_: `Sep 04 2014`

I am not sure I understand the desired behaviour: when the build is finished, but the buildslave is not shut down, it'd show IDLE.  As soon as it's down, it'd become LATENT.

---
_Comment from_: @unknown_contributor
_Date_: `Sep 04 2014`

Clarifying the description a bit more:

In the list of SlaveBuilder objects passed to !nextSlave, the slave's status after finishing a build is IDLE. When a slave is insubstantiated, however, the slave's status remains as IDLE. The status attribute in the SlaveBuilder object is not reset to LATENT, the state it has before first substantiation.

**Comment by seankelly** [comment]
The states changed in 0.9 and from what I can tell, latent workers have the right state transitions. There is no IDLE or LATENT anymore. Because of that, I think this is fixed in nine.
