### ISSUE TITLE
Failed FileUpload step generates a 0-sized file in the destination.

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2860]
This ticket is a migrated Trac ticket [2826](http://trac.buildbot.net/ticket/2826)

People contributed to the original ticket: @djmitche, @unknown_contributor
Ticket created on: `Jun 18 2014`
Ticket last modified on: `Jun 20 2014`

---

I have a build step like this:

factory.addStep([[FileUpload]](slavesrc="file.png", workdir=dir_on_the_source, mode=0777, name="Upload", masterdest=[[WithProperties]]("~/web/dump/gfxapi_testresults/diff-%(buildnumber)s-"+builder+".png"), url=[[WithProperties]]("http://myserver.com/gfxapi_testresults/diff-%(buildnumber)s-"+builder+".png"), halt[[OnFailure]]=False, flunk[[OnFailure]]=False, hide[[StepIf]]=lambda results, s: results == FAILURE))

Observed:
If the source file 'file.png' does not exist on the build slave, the build master will still create a new file to the destination, but the size of that file will be zero.

Also, if I remove the flunk[[OnFailure]], halt[[OnFailure]] and hide[[StepIf]] directives, the log will not indicate a reason for the failure (e.g. "File upload failed, because source file was not found")

Expected:

No zero-sized files should be generated in the destination and a descriptive error message should be displayed in the output.

---

**Comment by ewongbb** [comment]
Can someone please clarify if this is still an issue?  I'm looking at the code and noticing that
in master/buildbot/process/remotetransfer.py, the FileWriter's cancel() method unlinks those
files.  Did I miss something?

**Comment by seankelly** [comment]
Someone needs to verify that happens.

**Comment by gavanfantom** [comment]
This is still an issue in BuildBot 3.5.0
