### ISSUE TITLE
move github_buildbot out of contrib

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2861]
This ticket is a migrated Trac ticket [2828](http://trac.buildbot.net/ticket/2828)

People contributed to the original ticket: @djmitche, @sa2ajj, @ewongbb
Ticket created on: `Jun 22 2014`
Ticket last modified on: `Jan 14 2017`

---

This really should be a part of core Buildbot, as a web hook..

---

_Comment from_: @dustin
_Date_: `Jun 22 2014`

I especially like the addition of support for --secret, which allows Buildbot to at least trust that the request is from GitHub.

---
_Comment from_: @sa2ajj
_Date_: `Sep 08 2014`

See also #2889.

---
_Comment from_: @unknown_contributor
_Date_: `Jan 14 2017`

With master/buildbot/www/hooks/github.py, is this still necessary?

**Comment by seankelly** [comment]
There is a web hook now plus github_buildbot moved to [buildbot/buildbot-contrib](https://github.com/buildbot/buildbot-contrib/blob/master/master/contrib/github_buildbot.py) with #2827.
