### ISSUE TITLE
Buildbot does not consistenly do logging

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2862]
This ticket is a migrated Trac ticket [2839](http://trac.buildbot.net/ticket/2839)

People contributed to the original ticket: @djmitche, @sa2ajj, @unknown_contributor
Ticket created on: `Jul 20 2014`
Ticket last modified on: `Feb 03 2015`

---

In many places a `log.{msg,err}` (log is import from twisted.python) is used to log various information that might be useful later.

However there's a significant chunk of code that uses `print` to produce all kind of debug/error output.

I'm not sure this is a *major* ticket, I just wonder if there're any kind of guidelines about how logging should be performed and if there's a need to convert those `print`s to either `log.msg` or `log.err`?

---

_Comment from_: @dustin
_Date_: `Jul 20 2014`

`print` in a twistd environment ends up in the logfile.

However, in production code we should always be logging, not printing.  Based on a quick grep, I see that we *almost* always adhere to this standard.  Legitimate exceptions are:
* scripts and clients like 'create-master' or 'debug' that actually want to produce stdout
* contrib (it can do whatever it wants)

Cleaning up any other occurrences would be a good fix.

**Comment by seankelly** [comment]
I think this is fixed. One instance in `db/pool.py` with a comment about why; one instance in `manhole.py` which is for debugging; a number of instances in `scripts/`; a number of instances in `test/`; and one instance in `util/croniter.py` in the `__main__` section for debugging.
