### ISSUE TITLE
Add forward-compatibility with Python 3.3+

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2863]
This ticket is a migrated Trac ticket [2860](http://trac.buildbot.net/ticket/2860)

People contributed to the original ticket: @unknown_contributor, @djmitche, `northlomax@...`
Ticket created on: `Aug 05 2014`
Ticket last modified on: `Feb 13 2016`

---

Buildbot is Python-2.x only because Twisted is, but Twisted is making great progress toward 3.x.

When that happens, we should be ready to run on Python-3.x.

We can start now by running the code through 2to3 and fixing the easy, backward-compatible stuff -- print -> print(), range -> xrange, etc.

We can also run tests with the `-3` flag, which will warn about non-forward-portable stuff (unfortunately, it warns about a lot of non-Buildbot code, too!)

We can use the `six` package for a lot of this, and factor out some utility functions for other problematic bits.

---

_Comment from_: @dustin
_Date_: `Feb 13 2016`

We made great progress on this last year, but as somewhat expected, got caught up in porting Twisted.  I don't think there's enough left here for a GSoC project.

**Comment by seankelly** [comment]
Next release, 0.9.5, will support Python 3.5+ on master and worker. This will be in the docs once #2821 is merged.
