### ISSUE TITLE
Gitlab hook is receiving commits in the wrong order

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2867]
This ticket is a migrated Trac ticket [2886](http://trac.buildbot.net/ticket/2886)

People contributed to the original ticket: @djmitche, @unknown_contributor, @sa2ajj
Ticket created on: `Sep 05 2014`
Ticket last modified on: `Feb 03 2015`

---

When I receive a push on the Gitlab hook with multiple commits, they are processed in the wrong order and buildbot ends up building a revision that is not the latest.

In the JSON Gitlab is sending, the last commit is the first in the array; it looks like Buildbot expects the reverse.

Thanks!

---

**Comment by seankelly** [comment]
Based on the [webhook docs](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/project/integrations/webhooks.md), the commits in the `commits` key appear to be ordered oldest to newest. Closing because there active users and haven't seen new reports about this problem.
