### ISSUE TITLE
Make GitHub hook listen to other kind of events as well

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2868]
This ticket is a migrated Trac ticket [2887](http://trac.buildbot.net/ticket/2887)

People contributed to the original ticket: @djmitche, @sa2ajj
Ticket created on: `Sep 07 2014`
Ticket last modified on: `Jun 22 2015`

---

That would allow to build around Buildbot systems aware of a particular workflow.

Cf.: [[Bors] and [https://github.com/barosl/homu Homu|https://github.com/graydon/bors]]

---

_Comment from_: @dustin
_Date_: `Sep 07 2014`

This would be a powerful improvement, if the events and reactions to them were easily configurable.

**Comment by anish** [comment]
would also be nice if the event was available as a property for the build (pr vs push vs comment for eg)
