### ISSUE TITLE
Modernize Dockerfile

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2875]
This ticket is a migrated Trac ticket [2937](http://trac.buildbot.net/ticket/2937)

People contributed to the original ticket: @unknown_contributor, @sa2ajj
Ticket created on: `Oct 10 2014`
Ticket last modified on: `Nov 19 2014`

---

Docker has evolved quite quickly before reaching 1.0, and the Dockerfile in master/contrib/Dockerfile is no longer following best practices. According to [[GitHub]] discussions, it:

* does not publish master's web status port (8010)
* creates an ssh service (omg this is so 2013!)
* does not expose the config in a separated volume
* uses echo > /path/to/config instead of ADD command
* hardcodes the password

Someone should read the current Docker docs and come up with a better solution. It looks like tardyp will be able to review it.

---

**Comment by seankelly** [comment]
This has been modernized. See either the Dockerfile for the [master](https://github.com/buildbot/buildbot/blob/master/master/Dockerfile) or [worker](https://github.com/buildbot/buildbot/blob/master/worker/Dockerfile).
