### ISSUE TITLE
Provide latent Docker build slave

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2879]
This ticket is a migrated Trac ticket [2956](http://trac.buildbot.net/ticket/2956)

People contributed to the original ticket: @sa2ajj, `benoit.allard@...`
Ticket created on: `Oct 22 2014`
Ticket last modified on: `Nov 26 2014`

---

There's a number of options already implemented:
* https://github.com/dz0ny/docker-buildbot (not really latent one)
* https://github.com/elbaschid/dockbot (which seems to be the most mature)

(There's one more that I can't find atm)

---

_Comment from_: @Ben
_Date_: `Oct 22 2014`

I'm slowly wrapping my head around that concept, was wondering what advantage it would bring, or how could we integrate Docker as a slave or such ... What would help me most would be a blog post to lay down some basis I guess, then, once I got a clear idea of the possible links between Docker and Buildbot, I could try to think about binding them as a Latent slave ...

In that direction, the drone project ([[drone.io|https://drone.io/]]) is based around Docker slave, they provide some base image, and you just tell in your config which one you wanna use ... Something like that ?

---
_Comment from_: @sa2ajj
_Date_: `Oct 23 2014`

Latent build slaves have a special feature: reproducible environment, which is a parameter:
* AMI specification for [[AWS|http://docs.buildbot.net/latest/manual/cfg-buildslaves-ec2.html]]
* `base_image` for [[libvirt|http://docs.buildbot.net/latest/manual/cfg-buildslaves-libvirt.html]]
* `image` for [[OpenStack|http://docs.buildbot.net/latest/manual/cfg-buildslaves-openstack.html]]

The "normal" build slaves would have to create such an environment (e.g. [[Buildbot's builder configuration|https://github.com/buildbot/metabbotcfg/blob/master/builders.py#L27]]).

I agree though that either a blog post or an addition to the documentation would be helpful for more people to start using this kind of build slaves.

---
_Comment from_: @Ben
_Date_: `Oct 23 2014`

So you mean something like taking that class into core buildbot: https://github.com/elbaschid/dockbot/blob/make_single_command_executable/dockbot/slaves/dockerslave.py, or do you mean something more there ? (i.e. being able to install the minimal slave stuff into any base image ?)

---
_Comment from_: @sa2ajj
_Date_: `Oct 23 2014`

Yes, I am talking about taking that particular class (with amendments since it seems to do a bit too much with respect to parameters) and adding a test case.

---
_Comment from_: @Ben
_Date_: `Oct 24 2014`

Looking forward to it !

I'm struggeling with nine for the moment, but as I have it working, I could have a look at that !

---
_Comment from_: @Ben
_Date_: `Oct 28 2014`

I started looking onto it, unfortunately, I hit a few blockers with master (#2970).

A question I had is about the completness of the docker image. Should we try to create-slave + start at each substiantiation ? Or should the image have a pre-created slave and it should only be started during substantiation ?.

In other words: Should the docker image be buildbot-aware, or should any (well, with limitations) docker image be made buildbot-aware ?

---
_Comment from_: @sa2ajj
_Date_: `Oct 28 2014`

Replying to [[Ben|comment:6]]:
> I started looking onto it, unfortunately, I hit a few blockers with master (#2970).
Let's see how it's resolved.

> A question I had is about the completness of the docker image.
> Should we try to create-slave + start at each substiantiation ?
> Or should the image have a pre-created slave and it should only be started during substantiation ?.
I think the best is make all latent build slaves behave in a similar way; this means that it's a responsibility of the user to create an image with build slave in it as well as to provide a way for the build slave to authenticate against master:
* some latent build slaves have this information "hardcoded", that's it: one image can only provide one build slave
* majority of images I saw use environment variables or a bootstrap script to configure the authentication

> In other words: Should the docker image be buildbot-aware, or should any (well, with limitations) docker image be made buildbot-aware ?
I think, the former: that's in line with, for example, AWS images.

---
_Comment from_: @Ben
_Date_: `Nov 10 2014`

Been working on that over the weekend. With nice results !

1 trouble: We need to hardcode the master hostname, the slave name and password in the Dockerfile. For the master name, it would be good to use the `--add-hosts` cli parameter, unfortunately I found no way to give it through the docker API :( probably worth a bug by docker. Or the doc I found is not up-to-date.

I also would love to add the possibility to build a container if the requested one is not found. Probably through giving a Dockerfile as parameter to the slave. This would allow us to require no preliminary setup on the docker side.

I still need to write the doc, add some tests, and we're ready to go !

---
_Comment from_: @sa2ajj
_Date_: `Nov 10 2014`

I do not think we need to hardcode anything.

A common Docker approach is to pass parameters via environment variables.  In case of latent Docker slave, we'd have to pass 4 parameters (names are examples):
* `BUILDBOT_MASTER_HOST`
* `BUILDBOT_MASTER_PORT`
* `BUILDBOT_SLAVE_NAME`
* `BUILDBOT_SLAVE_PASSWORD`

and modify `buildbot.tac` to use these parameters when they are present.

---
_Comment from_: @sa2ajj
_Date_: `Nov 10 2014`

And, by the way, this modification can go to master: `buildslave create-slave` can put the provided values so that they are used as defaults, while the abovementioned environment variables would override these defaults.

---
_Comment from_: @Ben
_Date_: `Nov 10 2014`

See GH:1344.

---
_Comment from_: @sa2ajj
_Date_: `Nov 10 2014`

As agreed, environment variables is going to be in a separate PR.

---
_Comment from_: @Ben
_Date_: `Nov 26 2014`

Can this now be closed ?

---
_Comment from_: @sa2ajj
_Date_: `Nov 26 2014`

See above my comment about environment variables.  I have a branch, I just need to polish it and submit, then this can be closed when the change is merged.

---
_Comment from_: @sa2ajj
_Date_: `Nov 26 2014`

But first I want to take care of #2851.

**Comment by seankelly** [comment]
There is a Dockerfile for both the [master](https://github.com/buildbot/buildbot/blob/master/master/Dockerfile) and [worker](https://github.com/buildbot/buildbot/blob/master/worker/Dockerfile). The image gets used by bbtravis testing in Hyper.
