### ISSUE TITLE
Support a single config across the cluster, or something like that

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2880]
This ticket is a migrated Trac ticket [2959](http://trac.buildbot.net/ticket/2959)

People contributed to the original ticket: @djmitche, @sa2ajj, `benoit.allard@...`
Ticket created on: `Oct 22 2014`
Ticket last modified on: `Feb 08 2015`

---

The www interface is showing all builders that ever where there. This is a difference with eight were only the 'active' builders were displayed on the web interface. I believe the latter is wished.

---

_Comment from_: @dustin
_Date_: `Oct 23 2014`

This is a little tricky -- we don't want builders to "disappear" if the master that happens to be hosting them goes down.  Although we could do that now, with a rather complex set of queries.

I suspect that the better plan will be to have builders disappear using the same kind of "horizon" cleanup we do for logs and builds.

---
_Comment from_: @Ben
_Date_: `Oct 23 2014`

Provided this 'horizon' cleanup would be implemented in 0.9.+, this would then, if I understand correctly, prevent me to look at builders where build didn't happen for some time, even if the builders are still 'active' (defined in my config).

Anyway, the trouble I'm having now, is that at each reconfig where I renamed a builder, the old one stay there. Those were previous tests from me, and have no value anymore once the renamed builder is there.

I need a way to cleanup my interface, and anyone who experiment a bit with their configuration also does.

---
_Comment from_: @dustin
_Date_: `Oct 24 2014`

I wonder what would be the best interface for that.  The options I see are:

* horizons: delete builders which have no active master and no builds
* immediate disappearance: if there are no active masters with a builder configured, it disappears
* command-line cleanup: `buildbot delete-builder XXX`
* web UI: administrators can delete builders from the web UI

I'm not sure which of these options is best..

---
_Comment from_: @sa2ajj
_Date_: `Oct 24 2014`

FWIW, two last options look the most appealing to me (cli & web ui options):
* people do make mistakes -> give them a chance to see that something is wrong
* in a multi-master setup it's more likely to make a mistake

---
_Comment from_: @Ben
_Date_: `Oct 25 2014`

During a reconfig, we should be able to flag the dead builders as dead, or not ?

---
_Comment from_: @Ben
_Date_: `Oct 25 2014`

Same is valid for the slaves by the way. Even worst, the slaves still show on the web interface a connection with the builders they were connected to (when they existed). I.e.: `configured_on: [{"builderid":1,"masterid":1},{"builderid":2,"masterid":1},{"builderid":3,"masterid":1}] ` But that slave is absolutely not configured there ...

Those slave got new names / passwords, hence disapeared, and have been replaced by other ones ...

---
_Comment from_: @dustin
_Date_: `Oct 26 2014`

Reconfig happens on one master at a time, so it's still tricky at that point.  Probably the worst outcome would be to have a builder deleted while its builderid was still cached in RAM in another master -- any new inserts with that ID would fail.

So, yes, I think a way to delete builders (and slaves) manually would be good.

---
_Comment from_: @Ben
_Date_: `Nov 07 2014`

I believe, we need to move to a next-generation multi-master configuration.

The more we move stuff in the db, the more we are having this kind of troubles which boils down to:

    We do have a decentralized system without coordinating entity (well, the db, but it's only passive).

What if we would require for the master.cfg to always contains the whole definition, and then, during `buildbot start` we would add a parameter to tell the master which one he actually is ?

---
_Comment from_: @dustin
_Date_: `Nov 07 2014`

What are some good models for this, among other clustered applications?

I think your suggestion is to use the same master.cfg for all masters, with runtime flags that cause it to be interpreted differently.  But, how would you enforce that?  And how would you accomplish a rolling configuration update?

**Comment by Frodox** [comment]
+1!!!
Any progress here..?

**Comment by tardyp** [comment]
For me this has already been fixed for a while

**Comment by tardyp** [comment]
![image](https://cloud.githubusercontent.com/assets/109859/24270177/620e34ee-1014-11e7-87dc-a4847a037ac1.png)

There is a show old builders checkbox, unchecked by default to not display old builders.

@Frodox please +1 on things that are really a problem, and give more input of what is the current status in your opinion

**Comment by Frodox** [comment]
@tardyp ok! :)
I thought you and seankelly have closed all "resolved" tickets already:)
