### ISSUE TITLE
use swagger.io for data api specification

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2887]
This ticket is a migrated Trac ticket [3007](http://trac.buildbot.net/ticket/3007)

People contributed to the original ticket: @tardyp
Ticket created on: `Nov 05 2014`
Ticket last modified on: `Nov 05 2014`

---

Our data api is specified in 4 places.

- Documentation
- data unit tests
- mq unit tests
- implementation

There is an attempt to extract the spec from implementation with the cmdline "buildbot dataspec", so that it can be used in frontend unit tests, but the format is proprietary.

http://swagger.io/ Implements a specification for REST apis which is pretty solid. I think this can address all our usecase, so that we can have 2 specifications.

- swagger spec
- implementation

The other usecases (doc, tests, js spec) shall all derive from the swagger spec.

Put to 0.9.+ as this is not particularly needed for 0.9.0. Current solution works, but is fairly inefficient

---

**Comment by seankelly** [comment]
Is this superseded by RAML?

**Comment by indrajeet307** [comment]
@tardyp is this still a relevant issue ?

**Comment by p12tic** [comment]
This is no longer relevant as we use RAML for data API specification.
