### ISSUE TITLE
Add integration test cases for master/buildbot/buildslave/*

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2889]
This ticket is a migrated Trac ticket [3016](http://trac.buildbot.net/ticket/3016)

People contributed to the original ticket: @sa2ajj, `benoit.allard@...`
Ticket created on: `Nov 10 2014`
Ticket last modified on: `Nov 10 2014`

---

Quoting Dustin from GH:1341:

  I think that the best way to catch this sort of thing is integration testing -- hook up a master and a fake slave and make something happen. Much of that is already built in `buildbot.test.integration.test_slave_comm`, but that only tests some of the connection-handling code (specifically around duplicate slaves).

Essentially, our coverage for the `base.py` is 52.78% at the moment.

---

**Comment by seankelly** [comment]
Closing because worker/base.py coverage is now at 87%. The biggest missing part appears to be tests for locks and shutting down.
