### ISSUE TITLE
group builders per tags

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2892]
This ticket is a migrated Trac ticket [3027](http://trac.buildbot.net/ticket/3027)

People contributed to the original ticket: @delanne, @djmitche
Ticket created on: `Nov 14 2014`
Ticket last modified on: `Sep 06 2015`

---

For the waterfall/console web page the builders must be grouped per tags (like in eight)

Tags support is added in PR https://github.com/buildbot/buildbot/pull/1334

---

**Comment by p12tic** [comment]
Closing as duplicate of #3470 and #3471. These pages have a little more information.
