### ISSUE TITLE
Master deactivation iterates over all builds

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2905]
This ticket is a migrated Trac ticket [3121](http://trac.buildbot.net/ticket/3121)

People contributed to the original ticket: @djmitche
Ticket created on: `Dec 27 2014`
Ticket last modified on: `Dec 27 2014`

---

When a master is deactivated, it performs a query for all builds on that master, and marks them as RETRY.  However, that query is not optimized down to the DB level, so in practice we select *all* builds, ever, into a Python list and then filter that in Python.  That's very inefficient!

The fix is to trace the 'masterid' and 'results' parameters through the data API endpoint and into the DB API.

---

_Comment from_: @dustin
_Date_: `Dec 27 2014`

(based on https://github.com/buildbot/buildbot/pull/1408/files#r21196716)

**Comment by seankelly** [comment]
Fixed in #1449.
