### ISSUE TITLE
[AngularJS project] Use angular dashboard framework for nine homepage

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2910]
This ticket is a migrated Trac ticket [3147](http://trac.buildbot.net/ticket/3147)

People contributed to the original ticket: @shenal, @sa2ajj, @tardyp
Ticket created on: `Jan 11 2015`
Ticket last modified on: `Mar 12 2015`

---

Angular dashboard framework provides nice user interface for letting the user customize their homepage.

show page of this project:
http://sdorra.github.io/angular-dashboard-framework

It is compatible with the boostrap CSS framework that we are based on, and has a nice api  for defining new widgets.

This project is about integrating this framework in buildbot, and creating a few widgets.

Example widgets could be:
- Status for a builder (last build)
- List of building builds
- List of disconnected slaves
- Stats about people responsible of failed builds
- Stats about people responsible of fixing failed builds

---

_Comment from_: @shenal
_Date_: `Mar 12 2015`

Hi ,

I am interested in this project and I  have prior experience with bootstrap and Angular

**Comment by Frodox** [comment]
ref #3454

**Comment by p12tic** [comment]
This issue is no longer relevant with the switch to React for the frontend, as Angular Dashboards project cannot be used anymore.
