### ISSUE TITLE
Latent Slaves are started serially.

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2913]
This ticket is a migrated Trac ticket [3169](http://trac.buildbot.net/ticket/3169)

People contributed to the original ticket: `caktux@...`, @djmitche, @unknown_contributor, @tomprince
Ticket created on: `Jan 21 2015`
Ticket last modified on: `Apr 05 2016`

---

Because `[[BuildRequestDistributor]]._activityLoop` waits for `self._maybe[[StartBuildsOnBuilder]]` to finish with a lock held, only one slave can start at a time.

---

_Comment from_: @tom.prince
_Date_: `Feb 04 2015`

I've noticed that changing this interacts poorly with the logic to find a slave that has an available lock.

---
_Comment from_: @unknown_contributor
_Date_: `Apr 01 2015`

This also affects every other build, which all hang while waiting for a latent buildslave to become available. This is a blocking issue in every sense.

---
_Comment from_: @unknown_contributor
_Date_: `Mar 28 2016`

For anyone watching this, there's an open PR attempting to address this at https://github.com/buildbot/buildbot/pull/2072

**Comment by seankelly** [comment]
Fixed I think in #2212.
