### ISSUE TITLE
Fix call to subprocess.Popen in git_buildbot.py

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2917]
This ticket is a migrated Trac ticket [3180](http://trac.buildbot.net/ticket/3180)

People contributed to the original ticket: @djmitche, `verm@...`
Ticket created on: `Feb 02 2015`
Ticket last modified on: `Feb 05 2015`

---

[3add6d54] changed `git_buildbot.py` to use subprocess.Popen.  On Windows I believe it is always `shell=True` which is why passing the arguments as a string works.  On Unix it must be a list (as far as I know).  I do not know if it will cause any issues on Windows.

skelly on IRC mentioned this may have been meant as `os.popen` instead of `subprocess.Popen`

See [[git_buildbot.py:242|https://github.com/buildbot/buildbot/blob/master/master/contrib/git_buildbot.py#L242]].

This is on FreeBSD 10.1 under Python 2.7.

---

_Comment from_: @dustin
_Date_: `Feb 05 2015`

I don't think it *must* be a list -- https://docs.python.org/2/library/subprocess.html#subprocess.Popen

Perhaps we could just set shell=True?

Some tests would be great, too.

I'm setting this to minor since it's a contrib script the functionality for which is also available in Buildbot proper.

---
_Comment from_: @unknown_contributor
_Date_: `Feb 05 2015`

Replying to [[dustin|comment:1]]:
> I don't think it *must* be a list -- https://docs.python.org/2/library/subprocess.html#subprocess.Popen

It doesn't need to be a list if it's a single command with no args eg `ls` but you need to do `[['-l'|'ls',]]` for args otherwise it runs `"ls -l"` and you get a no such file or directory error.

> Perhaps we could just set shell=True?

Not sure what the ramifications of this are if none it makes sense.

> Some tests would be great, too.

I will see about that and a patch.

> I'm setting this to minor since it's a contrib script the functionality for which is also available in Buildbot proper.

OK.

**Comment by seankelly** [comment]
This is in contrib, but was fixed in #1791.
