### ISSUE TITLE
Rewrite status_push to use Data API

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2918]
This ticket is a migrated Trac ticket [3186](http://trac.buildbot.net/ticket/3186)

People contributed to the original ticket: @djmitche
Ticket created on: `Feb 07 2015`
Ticket last modified on: `Sep 06 2015`

---

Blocks #2648

`master/buildbot/status/status_push.py` is designed to push build status changes to an external web API.  However, it's still mostly expecting the old Status hierarchy to exist, rather than the new Data API.

It needs to be rewritten to listen for appropriate events from the Data API and submit them to Gerrit, with any additional information fetched through the Data API's "get" method. 

The module also uses `master/buildbot/status/persistent_queue.py`, which has demonstrated some odd behaviors in the past.  If this poses more problems, there are probably better alternatives available as pre-built distributions on pypi.

---

**Comment by seankelly** [comment]
`StatusPush` got redone as `HttpStashPush` and it supports the data API.
