### ISSUE TITLE
Update example for using codebases with the force scheduler

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2924]
This ticket is a migrated Trac ticket [3201](http://trac.buildbot.net/ticket/3201)

People contributed to the original ticket: @djmitche, @sa2ajj
Ticket created on: `Feb 14 2015`
Ticket last modified on: `Feb 14 2015`

---

In particular, we've now deprecated the `branch` argument, preferring to use codebases -- but the example in the documentation still lists a `branch` argument.

This will need some research and experimentation to get the new configuration right to give the same behavior as the old.

---

_Comment from_: @sa2ajj
_Date_: `Feb 14 2015`

Related to #2945?

---
_Comment from_: @dustin
_Date_: `Feb 14 2015`

Yes, but this specific example is now wrong.

**Comment by Frodox** [comment]
[Already resolved](http://buildbot.readthedocs.io/en/latest/manual/cfg-schedulers.html#forcescheduler-scheduler)
