### ISSUE TITLE
rewrite StashStatusPush to use Data API

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2927]
This ticket is a migrated Trac ticket [3204](http://trac.buildbot.net/ticket/3204)

People contributed to the original ticket: @sa2ajj
Ticket created on: `Feb 15 2015`
Ticket last modified on: `Feb 15 2015`

---

This new status target was added as GH:1538.

According to #2648, it needs to be re-written.

---

**Comment by seankelly** [comment]
I think this was done when it was rewritten to use HttpStatusPush in #2057.
