### ISSUE TITLE
forward-port change hooks to nine

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2929]
This ticket is a migrated Trac ticket [3211](http://trac.buildbot.net/ticket/3211)

People contributed to the original ticket: @djmitche, `verm@...`, @sa2ajj
Ticket created on: `Feb 25 2015`
Ticket last modified on: `Mar 06 2015`

---

The change-hook code is still in place in `master`, but it's not hooked up to anything -- you can't access them from the web.

We should hook that up.

---

_Comment from_: @sa2ajj
_Date_: `Feb 25 2015`

Unless somebody else manages to start working on this earlier, I'd like to do the implementation (to better understand how new web backend works).

---
_Comment from_: @unknown_contributor
_Date_: `Mar 06 2015`

I have been working on this for the past week off and on.  I have something working now.  I need to write tests.  It should work without changing any of the current hooks.

**Comment by seankelly** [comment]
They have been ported to nine.
