### ISSUE TITLE
KeyError in github_buildbot.py on commits by non-Github users

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2931]
This ticket is a migrated Trac ticket [3228](http://trac.buildbot.net/ticket/3228)

People contributed to the original ticket: `buildbot.net@...`, @djmitche
Ticket created on: `Mar 12 2015`
Ticket last modified on: `Mar 17 2015`

---

When a commit by an user not known to github (e.g. [[this|https://github.com/The-Compiler/qutebrowser/commit/4fa64350ca26a79569a000312740c57adc660e90]]) is pushed, github_buildbot.py has a [[KeyError]] when trying to get the username of the change:

    Traceback (most recent call last):
    File "/usr/local/bin/github_buildbot.py", line 138, in render_POST
    self.process_change(payload, user, repo, repo_url, project, request)
    File "/usr/local/bin/github_buildbot.py", line 166, in process_change
    change[[change['author']['email'|'author']['username'],]])
    [[KeyError]]: 'username'

---

**Comment by seankelly** [comment]
This is in [contrib](https://github.com/buildbot/buildbot-contrib), but was fixed in #1801.
