### ISSUE TITLE
BuildStep should properly interrupt steps

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2935]
This ticket is a migrated Trac ticket [3248](http://trac.buildbot.net/ticket/3248)

People contributed to the original ticket: `vlovich@...`, `jared.grubb@...`, @sa2ajj
Ticket created on: `Apr 14 2015`
Ticket last modified on: `Aug 16 2015`

---

For some reason the interruption logic is unnecessarily delegated to !Logging[[BuildStep]] which means anyone inheriting from a regular BuildStep has to implement interruption themselves.

The interruption logic relies on no functionality within !Logging[[BuildStep]] & should live in BuildStep itself.

---

_Comment from_: @unknown_contributor
_Date_: `Aug 16 2015`

I think I have a patch for this; posted at https://github.com/buildbot/buildbot/pull/1822 and up for test if you want.

**Comment by seankelly** [comment]
Fixed in #1822.
