### ISSUE TITLE
Support Buildbot for testing pull requests

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2938]
This ticket is a migrated Trac ticket [3270](http://trac.buildbot.net/ticket/3270)

People contributed to the original ticket: @unknown_contributor, @sa2ajj, @unknown_contributor
Ticket created on: `Jun 05 2015`
Ticket last modified on: `Jun 15 2015`

---

Currently Buildbot (advertised as a "Continuous Integration" tool) uses Travis CI to do CI and pull request testing.  This implies that Buildbot is not fully functional for automated testing; adding support for using Buildbot to tests pull requests would fix this perception.  

There has been [[some effort toward this|http://sourceforge.net/p/buildbot/mailman/message/31751592/]], but nothing officially supported.

Creating this ticket so that I can get notification if/when this feature comes online; no urgency is implied.

---

_Comment from_: @sa2ajj
_Date_: `Jun 05 2015`

See #2887

---
_Comment from_: @unknown_contributor
_Date_: `Jun 15 2015`

Agree, it is suspicious that the Buildbot uses the different continuous integration platform.

The official support for this feature will be great item in nine upgrade changelog.

+CC to get notifications

**Comment by seankelly** [comment]
This happens by using [buildbot_travis](https://github.com/buildbot/buildbot_travis) and [Hyper](https://hyper.sh).
