### ISSUE TITLE
When requesting builds from Data API, build's properties should be returned for each

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2939]
This ticket is a migrated Trac ticket [3284](http://trac.buildbot.net/ticket/3284)

People contributed to the original ticket: @unknown_contributor
Ticket created on: `Jun 23 2015`
Ticket last modified on: `Jun 23 2015`

---

Currently when requesting on Data API for builds (api/v2/builds) each item (build) returned from the JSON structure does not contain the "properties" field.

The drawback of it, is that one's got to request for each build its properties, which is costly in terms of performance and network usage (in particular on big range of data).

It should be computed and served from the back-end (Data API).

A pull-request is available here: https://github.com/buildbot/buildbot/pull/1739

---

**Comment by seankelly** [comment]
Fixed in #1739.
