### ISSUE TITLE
Port Gltlab status plugin for nine

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2940]
This ticket is a migrated Trac ticket [3286](http://trac.buildbot.net/ticket/3286)

People contributed to the original ticket: @djmitche, @tardyp
Ticket created on: `Jun 23 2015`
Ticket last modified on: `Apr 11 2016`

---

Port the gitlab status plugin from eight to nine

---

_Comment from_: @dustin
_Date_: `Sep 06 2015`

..or document that it's not available in 0.9.0

---
_Comment from_: @tardyp
_Date_: `Apr 11 2016`

PR documenting it is not ported yet.

https://github.com/buildbot/buildbot/pull/2108

changing milestone to 0.9.+

**Comment by seankelly** [comment]
Ported in #2140.
