### ISSUE TITLE
Buildbot master/slave Python 2/3 Compatible Migration

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2941]
This ticket is a migrated Trac ticket [3290](http://trac.buildbot.net/ticket/3290)

People contributed to the original ticket: @unknown_contributor, @sa2ajj
Ticket created on: `Jun 24 2015`
Ticket last modified on: `Jun 25 2015`

---

Buildbot to allow this behavior in Python 2/3.

---

_Comment from_: @sa2ajj
_Date_: `Jun 25 2015`

Could you please elaborate what this ticket is about?

---
_Comment from_: @unknown_contributor
_Date_: `Jun 25 2015`

Replying to [[sa2ajj|comment:1]]:
> Could you please elaborate what this ticket is about?

If you install a pip python3 buildbot command in a virtual environment is not installed error and execution. This store was created buildbot forking the tickets you try to be able to install and operate in the virtual environment of the Python 3.

**Comment by seankelly** [comment]
See #2863.
