### ISSUE TITLE
make ChangeManager from master/buildbot/changes/manager.py inherit from MeasuredBuildbotServiceManager

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2942]
This ticket is a migrated Trac ticket [3308](http://trac.buildbot.net/ticket/3308)

People contributed to the original ticket: @unknown_contributor
Ticket created on: `Jul 16 2015`
Ticket last modified on: `Jul 16 2015`

---

The code looks similar enough to deserve some factorization

---

**Comment by seankelly** [comment]
Mostly fixed in #2605. It inherits from `MeasuredBuildbotServiceManager`, but the reconfiguration is ad hoc.
