### ISSUE TITLE
buildbot.tac do not allow 'print <string>' lines anymore

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2946]
This ticket is a migrated Trac ticket [3318](http://trac.buildbot.net/ticket/3318)

People contributed to the original ticket: @rutsky, @unknown_contributor
Ticket created on: `Jul 21 2015`
Ticket last modified on: `Jan 31 2016`

---

Due to https://github.com/buildbot/buildbot/commit/201f0d9cbcffefb4062668c03ca95558f6a6b8c7

old style
'print <string>'
statements in buildbot.tac files

raise an exception when calling
% buildbot checkconfig

which breaks the backward compatibility

---

_Comment from_: @rutsky
_Date_: `Jan 31 2016`

I think this issue should be fixed in eight branch and in nine should have resolution "won't fix" with adding appropriate notice into the nine release notes (if it is not yet documented).

**Comment by p12tic** [comment]
We've dropped Python 2.x for master long ago, closing the bug.
