### ISSUE TITLE
buildbot 0.9b1 tries to build deleted branch?

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2947]
This ticket is a migrated Trac ticket [3327](http://trac.buildbot.net/ticket/3327)

People contributed to the original ticket: `vlovich@...`, @djmitche
Ticket created on: `Aug 04 2015`
Ticket last modified on: `Feb 17 2016`

---

In 0.8.x it looks like buildbot filtered out changes from the change hook (at least [[GitLab]]) for deleted branches.  In 0.9b1 this doesn't look to be the case anymore so it's triggering builders that can't succeed.  Is this intended behaviour?  I can see why someone might want this.  If it's intentional, it's probably worth calling out in the release notes with documentation in the migration notes about how to filter them out for builders that don't want them.

For the time being I've updated my custom [[GitLab]] change hook to ignore deletion events.

---

**Comment by seankelly** [comment]
Fixed in #1682.
