### ISSUE TITLE
buildbot.test.integration.test_trigger.TriggeringMaster.test_trigger is flaky

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2949]
This ticket is a migrated Trac ticket [3339](http://trac.buildbot.net/ticket/3339)

People contributed to the original ticket: @djmitche, @sa2ajj
Ticket created on: `Aug 25 2015`
Ticket last modified on: `Sep 01 2015`

---

And it causes **two** errors:

    [FAIL]
    Traceback (most recent call last):
      File "/home/buildbot/slave/py27-tw1320/sandbox-python2.7-Twisted==13.2.0samigr-0.7.1/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
        result = g.send(result)
      File "/home/buildbot/slave/py27-tw1320/build/master/buildbot/test/integration/test_trigger.py", line 61, in test_trigger
        self.assertEqual(dump.getvalue(), expectedOutput % dict(loglines=loglines))
      File "/home/buildbot/slave/py27-tw1320/sandbox-python2.7-Twisted==13.2.0samigr-0.7.1/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 356, in assertEqual
        % (msg, pformat(first), pformat(second)))
    twisted.trial.unittest.[[FailTest]]: not equal:
    a # u"*** BUILD 1 ***=> finished (success)\n    *** STEP shell *** ==> 'echo hello' (success)\n        log:stdio (29)\n    *** STEP trigger *** ==> triggered trigsched (success)\n       url:trigsched #2 (http://localhost:8080/#buildrequests/2)\n       url:success: build #1 (http://localhost:8080/#builders/2/builds/1)\n    *** STEP shell_1 *** ==> 'echo world' (success)\n        log:stdio (0)\n*** BUILD 2 *** ==> finished (success)\n    *** STEP shell *** ==> 'echo ola' (success)\n        log:stdio (29)\n"
    b # "*** BUILD 1 ***=> finished (success)\n    *** STEP shell *** ==> 'echo hello' (success)\n        log:stdio (29)\n    *** STEP trigger *** ==> triggered trigsched (success)\n       url:trigsched #2 (http://localhost:8080/#buildrequests/2)\n       url:success: build #1 (http://localhost:8080/#builders/2/builds/1)\n    *** STEP shell_1 *** ==> 'echo world' (success)\n        log:stdio (29)\n*** BUILD 2 *** ==> finished (success)\n    *** STEP shell *** ==> 'echo ola' (success)\n        log:stdio (29)\n"
    
    
    buildbot.test.integration.test_trigger.[[TriggeringMaster]].test_trigger

    [ERROR]
    Traceback (most recent call last):
      File "/home/buildbot/slave/py27-tw1320/sandbox-python2.7-Twisted==13.2.0samigr-0.7.1/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
        result = g.send(result)
      File "/home/buildbot/slave/py27-tw1320/build/master/buildbot/test/util/integration.py", line 133, in tearDown
        raise self.failureException(dump.getvalue())
    twisted.trial.unittest.[[FailTest]]: FAILED! dumping build db for debug
    *** BUILD 1 *** ==> finished (success)
        *** STEP shell *** ==> 'echo hello' (success)
            log:stdio (29)
            *********** LOG: stdio *********
            ********************************
        *** STEP trigger *** ==> triggered trigsched (success)
           url:trigsched #2 (http://localhost:8080/#buildrequests/2)
           url:success: build #1 (http://localhost:8080/#builders/2/builds/1)
        *** STEP shell_1 *** ==> 'echo world' (success)
            log:stdio (29)
            *********** LOG: stdio *********
            ********************************
    *** BUILD 2 *** ==> finished (success)
        *** STEP shell *** ==> 'echo ola' (success)
            log:stdio (29)
            *********** LOG: stdio *********
            ********************************
    
    
    buildbot.test.integration.test_trigger.[[TriggeringMaster]].test_trigger

---

_Comment from_: @dustin
_Date_: `Sep 01 2015`

Marked as flaky in https://github.com/buildbot/buildbot/commit/2844506f75aba94d32b7dd4258bac1e6015e8d14

**Comment by p12tic** [comment]
Test has been re-enabled since 8340b88e48616ac0ed49cd3587d63246f21ae54b and I don't remember seeing any failures.
