### ISSUE TITLE
[MOSS Project] Better handling of EC2 to avoid cost overruns

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2961]
This ticket is a migrated Trac ticket [3392](http://trac.buildbot.net/ticket/3392)

People contributed to the original ticket: @djmitche
Ticket created on: `Dec 19 2015`
Ticket last modified on: `Jul 08 2016`

---

This involves shutting down the instances, particularly when the master is stopped and/or crashes.  This will help users keep their EC2 costs contained.

Users should be able to rely on Buildbot to only spend the necesary amount on EC2 instances, without any surprises at the end of the month.  Successful completion of this project will address the known bugs below, but also provide some failsafe or monitoring mechanisms that an OSS project could use to head off any overbilling.

## project scope

Completing this project will involve:

* Establishing and documenting a recommended way to run Buildbot in EC2, encompassing worker configuration and startup
* Providing support for shutting down an instance when it cannot connect to the master for a prolonged period (#2962) [edit: updated to reference GH issue @djmitche]
* Correcting spot-instance handling so that instances are not "lost" by the buildbot master (#2874) [edit: updated to reference GH issue @djmitche]
* Providing a failsafe method of managing EC2 instances that will reliably prevent over-provisioning and lost EC2 instances.  Proposals should outline one or more specific approaches to this problem.

## bounty

Bounty: US$5,000 - see [[BountyProgram]]

---

_Comment from_: @dustin
_Date_: `Dec 19 2015`

This bounty project is still under construction and additional components may be added.  We should have complete details in about a week.  The bounty amount is US$5000.

---
_Comment from_: @dustin
_Date_: `Jul 08 2016`

I've updated the bug description -- this bounty is ready for applications!

**Comment by djmitche** [comment]
Both of the dependents are done, and this is done too.
