### ISSUE TITLE
Shut down EC2 instances after prolonged disconnection from master

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2962]
This ticket is a migrated Trac ticket [3393](http://trac.buildbot.net/ticket/3393)

People contributed to the original ticket: @djmitche, @tardyp
Ticket created on: `Dec 19 2015`
Ticket last modified on: `Aug 02 2016`

---

Right now, there are a number of ways for an EC2 instance to become "stranded", where it's not connected to the master, but still running and thus costing the user perfectly good beer money.

The buildslave should optionally have a way to halt the host it is running on when it is disconnected for a while.  Config knobs:

* `halt[[WhenDisconnectedFor]]` - # of seconds of continuous disconnection
* `halt[[WhenDisconnectedCommand]]` - command line to use for halting (e.g., `sudo halt`)

---

_Comment from_: @dustin
_Date_: `Aug 02 2016`

https://github.com/buildbot/buildbot/pull/2329 may also address this.

---
_Comment from_: @tardyp
_Date_: `Aug 02 2016`

I *think* this is addressed, however, I did not test ec2 recently

**Comment by djmitche** [comment]
https://docs.buildbot.net/latest/manual/installation/worker.html#cmdoption-buildbot-worker-create-worker-maxretries is the option for this.

**Comment by tardyp** [comment]
Doc to ec2 worker: http://docs.buildbot.net/current/manual/cfg-workers-ec2.html

doc to systemd: http://docs.buildbot.net/current/manual/installation/worker.html?highlight=systemd#cmdoption-buildbot-worker-create-worker-maxretries

**Comment by tardyp** [comment]
https://github.com/buildbot/buildbot-contrib/blob/master/master/contrib/systemd/buildbot.service

**Comment by tardyp** [comment]
I added a worker.service in the contrib directory and linked the doc to that..
