### ISSUE TITLE
build.complete always false in coffeescript

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2975]
This ticket is a migrated Trac ticket [3443](http://trac.buildbot.net/ticket/3443)

People contributed to the original ticket: @unknown_contributor
Ticket created on: `Feb 08 2016`
Ticket last modified on: `Feb 08 2016`

---

In the following code, the two log.debug statements (towards the end) in onChange are outputting two different values for build.complete. When the build instance is printed to console (see attached png) it is true for a cancelled build, but build.complete reports false. 

    class _buildStatus extends Controller
        constructor: ($scope, $attrs, dataService, $log, RESULTS, $interval) ->
            $scope.builder = $attrs.builder
            $scope.name = $attrs.name
            $scope.status = 'unknown'
            $scope.pvalue = 0
    
            builders = $attrs.builders.split(',')
    
            data = dataService.open().close[[OnDestroy]]($scope)
    
            estimates = {}
            pending = {}
            last[[BuildResult]] = null
    
            arePending = ->
                for builderId, startedTimes of pending
                    for startedTime in startedTimes
                        return true
                return false
    
            filterOutliers = (someArray) ->
                # Copy the values, rather than operating on references to existing values
                values = someArray.concat()
                # Then sort
                values.sort (a, b) ->
                    a - b
    
                ### Then find a generous IQR. This is generous because if (values.length / 4) 
                # is not an int, then really you should average the two elements on either 
                # side to find q1.
                ###
    
                q1 = values[[/ 4)|Math.floor(values.length]]
                # Likewise for q3. 
                q3 = values[[* 3 / 4)|Math.ceil(values.length]]
                iqr = q3 - q1
                # Then find min and max values
                maxValue = q3 + iqr * 1.5
                minValue = q1 - (iqr * 1.5)
                # Then filter anything beyond or beneath these values.
                values.filter((x) -> x <= maxValue and x >= minValue)
                
            computeEstimate = ->
                if not arePending()
                    return
    
                totalElapsed = 0.0
                total[[BuildTimes]] = 0.0
                nowTime = (Date.now() / 1000)
    
                totalPending = 0
                for builderId, startedTimes of pending
                    estimated[[BuildTime]] = estimates[builderId]
                    if not estimated[[BuildTime]]
                        return
    
                    for startedTime in startedTimes
                        totalPending += 1
                        elapsedTime = nowTime - startedTime
                        totalElapsed += elapsedTime
                        total[[BuildTimes]] += estimates[builderId]
    
                #$log.debug('totalPending: ' + totalPending)
                #$log.debug('total[[ElapsedTime]]: ' + totalElapsed)
                #$log.debug('total[[BuildTimes]]: ' + total[[BuildTimes]])
    
                $scope.pvalue = Math.min(100, Math.round((totalElapsed / total[[BuildTimes]]) * 100))
    
                #$log.debug('pvalue: ' + $scope.pvalue)
    
            intervalPromise = null
            updateState = ->
                if intervalPromise != null
                    $interval.cancel(intervalPromise)
                    intervalPromise = null
    
                if arePending()
                    $scope.status = 'active'
                    intervalPromise = $interval (->
                        computeEstimate()
                        ), 1000, 0, true
                else if last[[BuildResult]] != null
                    if last[[BuildResult]] != RESULTS.SUCCESS
                        $scope.status = 'failure'
                    else
                        $scope.status = 'success'
                else
                    $scope.status = 'unknown'
    
            for builder in builders
                data.getBuilders(name: builder, limit:1).onNew = (builder) ->
                    builder[[BuildTimes]] = [[                    filtered[[BuilderBuildTimes]] = [|]]]
                    pending[[= [|builder.builderid]]]
    
                    xs = data.getBuilds(builderid: builder.builderId, complete: true, order: '-buildid', limit:500)
                    xs.onNew = (build) ->
                        builder[[BuildTimes]].push(build.complete_at - build.started_at)
                        filtered[[BuilderBuildTimes]] = filterOutliers(builder[[BuildTimes]])
                        if filtered[[BuilderBuildTimes]].length > 0
                            average[[BuildTime]] = (filtered[[BuilderBuildTimes]].reduce (x, y) -> x + y) / filtered[[BuilderBuildTimes]].length
                            estimates[builder.builderid] = average[[BuildTime]]
    
                    ys = data.getBuilds(builderid: builder.builderid, order: '-buildid', complete: false)
                    ys.onNew = (build) ->
                        pending[builder.builderid].push(build.started_at)
                        updateState()
                    ys.onChange = (builds) ->
                        pending[[= [|builder.builderid]]]
                        for build in builds
                            $log.debug('build: ', build)
                            $log.debug('build.complete: ', build.complete)
    
                            if build.state_string == 'finished'
                                continue
                            pending[builder.builderid].push(build.started_at)
                        updateState()
    
                    zs = data.getBuilds(builderid: builder.builderId, order: '-buildid', limit:1)
                    zs.onNew = (build) ->
                        last[[BuildResult]] = build.results
                        updateState()
                    zs.onChange = (builds) ->
                        for build in builds
                            last[[BuildResult]] = build.results
                            updateState()
                            break
    

---

_Comment from_: @unknown_contributor
_Date_: `Feb 08 2016`

browser console output

**Comment by p12tic** [comment]
AngularJS frontend has been deprecated and will be removed soon.
