### ISSUE TITLE
0.9.0b6 released with incorrect version inside

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2978]
This ticket is a migrated Trac ticket [3449](http://trac.buildbot.net/ticket/3449)

People contributed to the original ticket: @tardyp, @rutsky, @tardyp
Ticket created on: `Feb 11 2016`
Ticket last modified on: `Feb 12 2016`

---

    $ pip install buildbot-pkg==0.9.0b6
    Downloading/unpacking buildbot-pkg==0.9.0b6
      Downloading buildbot-pkg-0.9.0b6.tar.gz
      Running setup.py (path:/home/bob/stuff/buildbot/bb-test/build/buildbot-pkg/setup.py) egg_info for package buildbot-pkg
        
      Requested buildbot-pkg==0.9.0b6, but installing version 999.0-version-not-found
    Installing collected packages: buildbot-pkg
      Found existing installation: buildbot-pkg 0.9.0b5
        Uninstalling buildbot-pkg:
          Successfully uninstalled buildbot-pkg
      Running setup.py install for buildbot-pkg
        
    Successfully installed buildbot-pkg
    Cleaning up...
    $ pip freeze
    argparse==1.2.1
    buildbot-pkg==999.0-version-not-found
    wsgiref==0.1.2
    $

(note `999.0-version-not-found`)

In 0.9.0b5 version is correct.

Is it due to the fact that 0.9.0b5 was released as wheel, and 0.9.0b6 as source package?
0.9.0b5 can be reuploaded (I think uploading wheel will fix it for clients that support wheel) to fix this issue, but it's not required since it's beta and new beta will be released soon.

The main purpose of this issue is to prevent such error in future releases.
How this can be achieved?

---

_Comment from_: @tardyp
_Date_: `Feb 12 2016`

ok, I will try to create some checks on the release scripts for the version.

**Comment by seankelly** [comment]
The 0.9.4 docs list the version as 0.9.14. Perhaps a script to do the substitution would be useful.

**Comment by pmatos** [comment]
I am getting this with `buildbot-pkg 0.9.5`:
```
$ pip install --no-cache-dir buildbot-pkg
Collecting buildbot-pkg
  Downloading buildbot-pkg-0.9.5.tar.gz
Requirement already satisfied: setuptools>=21.2.1 in /home/pmatos/.pyenv/versions/3.6.0/envs/buildbot3-venv/lib/python3.6/site-packages (from buildbot-pkg)
Requirement already satisfied: six>=1.6.0 in /home/pmatos/.pyenv/versions/3.6.0/envs/buildbot3-venv/lib/python3.6/site-packages (from setuptools>=21.2.1->buildbot-pkg)
Requirement already satisfied: packaging>=16.8 in /home/pmatos/.pyenv/versions/3.6.0/envs/buildbot3-venv/lib/python3.6/site-packages (from setuptools>=21.2.1->buildbot-pkg)
Requirement already satisfied: appdirs>=1.4.0 in /home/pmatos/.pyenv/versions/3.6.0/envs/buildbot3-venv/lib/python3.6/site-packages (from setuptools>=21.2.1->buildbot-pkg)
Requirement already satisfied: pyparsing in /home/pmatos/.pyenv/versions/3.6.0/envs/buildbot3-venv/lib/python3.6/site-packages (from packaging>=16.8->setuptools>=21.2.1->buildbot-pkg)
Installing collected packages: buildbot-pkg
  Running setup.py install for buildbot-pkg ... done
Successfully installed buildbot-pkg-999.0-version-not-found
```

Note the `buildbot-pkg-999.0-version-not-found`

**Comment by Frodox** [comment]
What about this ticket? I thinks we should close it now as EOL.

**Comment by tardyp** [comment]
I think this bug is still present actually

**Comment by Frodox** [comment]
What is correct hot-fix now?
I do not think someone would repack package after a year..

**Comment by tardyp** [comment]
I mean the same problem exist for 0.9.8

**Comment by p12tic** [comment]
I think this has been fixed now. I haven't seen similar issues for a while now. This bug may only happen if a release happens from a wrong git commit, but our release checklist prevents this.
