### ISSUE TITLE
[AngularJS Project] Improve AngularJS unit testing framework

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2981]
This ticket is a migrated Trac ticket [3453](http://trac.buildbot.net/ticket/3453)

People contributed to the original ticket: @djmitche
Ticket created on: `Feb 13 2016`
Ticket last modified on: `Feb 13 2016`

---

The unit tests for Buildbot's Angular components need to be expanded.  That means more tests, but it also means more support code for those tests.  In particular, a realistic means of simulating the Buildbot server backend.  Ideally that would be a fake backend, and one that is guaranteed to match the real thing by use of RAML or JSON-Schema or similar API-description techniques.

This project would involve picking the API-description technique, applying it in the Python code, and then writing the fake backend in CoffeeScript.  And writing tests that use the backend, to show that it works.

There are other options here -- perhaps running the Buildbot master in a "test backend" mode that allows extra API calls.  The end result should be a way to realistically test Angular components against the Buildbot Data API.

---

**Comment by p12tic** [comment]
With switch to React this has been addressed. Most React components get things to be displayed as props which makes testing them trivial.
