### ISSUE TITLE
setup IRC bot that would repost questions from StackOverflow into Buildbot IRC channel

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2983]
This ticket is a migrated Trac ticket [3458](http://trac.buildbot.net/ticket/3458)

People contributed to the original ticket: @unknown_contributor, @rutsky
Ticket created on: `Feb 16 2016`
Ticket last modified on: `Feb 16 2016`

---

It would be nice to see in IRC short summary of a question (title?) and link on question with #buildbot tag on [[StackOverflow]].

Other [[StackExchange]] sites may be considered, e.g. [[ServerFault]].

---

**Comment by thefinn93** [comment]
I threw together [a Sopel plugin to do this](https://github.com/thefinn93/Sopel-StackExchange). I've got it running on a Sopel bot that I already operate on Freenode, I could enable it for `#buildbot` if y'all are amenable.

**Comment by noc0lour** [comment]
Pretty cool! Probably you could put this on the agenda for tuesday https://titanpad.com/buildbot-agenda. Then we can discuss how to operate the bot (maybe even on bb infra?).

@thefinn93 you might want to remove the key from the repo if it is your personal API key

**Comment by thefinn93** [comment]
The API key can be distributed, there's a client_secret that can't be. The page where it shows me the key says this, right below the key:

>This is not considered a secret, and may be safely embed in client side code or distributed binaries.

I was working through a whole setup/authentication flow, but it turns out no user auth is needed and the key (used with API requests to get the limit above 300/ip/day) can be distributed. ¯\_(ツ)_/¯

**Comment by noc0lour** [comment]
hm, intereseting, then this should be fine :)

**Comment by p12tic** [comment]
I don't think after 4 years anyone is still going to set up such IRC bot.
