### ISSUE TITLE
verify that all entry points of Buildbot are at least importable

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2986]
This ticket is a migrated Trac ticket [3470](http://trac.buildbot.net/ticket/3470)

People contributed to the original ticket: @rutsky
Ticket created on: `Feb 24 2016`
Ticket last modified on: `Feb 24 2016`

---

We have big bunch of plugins exported in setup.py, and looks like not all plugins are exported correctly: https://github.com/buildbot/buildbot/pull/2006/files#diff-9030ee1b7d992477393062826c5decfeL345

It would be nice to have test or check for that.

---

**Comment by seankelly** [comment]
This *might* be fixed. I reviewed it for missing entry points when I added `RpmLint`. However, something to verify this in the tests would be great.

**Comment by rutsky** [comment]
I would insist that this should be automated. Even if it is correct now, it will be broken later, if nothing will check this regularly.

**Comment by muarachmann** [comment]
@tardyp i would love to work on this please. Can i know the way forward. From what i understand write a test to see modules that have been imported  or not.?

**Comment by tardyp** [comment]
http://docs.buildbot.net/current/developer/quickstart.html

**Comment by muarachmann** [comment]
Thanks i will look into this and get started

**Comment by Sebastiangka** [comment]
@tardyp if you give me the ok - i would like to start solving this.

**Comment by p12tic** [comment]
@Sebastiangka Thanks for bringing this up.

I think this is already addressed in the `buildbot.test.integration.test_setup_entrypoints` test.

I will close the bug report, but if you think it's still valid, please reopen it.
