### ISSUE TITLE
Use Sphinx' "checklink" builder to check external links in documentation for correctness

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2987]
This ticket is a migrated Trac ticket [3478](http://trac.buildbot.net/ticket/3478)

People contributed to the original ticket: @djmitche, @rutsky
Ticket created on: `Mar 07 2016`
Ticket last modified on: `Mar 08 2016`

---

There is already `checklink` target in `master/docs/Makefile`, and here is the docs for this builder: http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.linkcheck.[[CheckExternalLinksBuilder]]

---

_Comment from_: @rutsky
_Date_: `Mar 07 2016`

I created branch `3478-linkcheck` and [[PR|https://github.com/buildbot/buildbot/pull/2035]] for this issue, feel free to take and resolve it.

**Comment by seankelly** [comment]
Fixed in #2138.

**Comment by albert2126** [comment]
Just after the initial Sphinx configuration, you can use:

`make linkcheck`

This will run the [CheckExternalLinksBuilder](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) builder.
