### ISSUE TITLE
buildbot upgrade-master does not display errors

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#2990]
This ticket is a migrated Trac ticket [3499](http://trac.buildbot.net/ticket/3499)

People contributed to the original ticket: @rutsky, @unknown_contributor
Ticket created on: `Mar 23 2016`
Ticket last modified on: `Mar 24 2016`

---

I can propose you the following scenario to reproduce the issue:

- checkout the master branch
- create a database, you should have 45 in migrate_version
- download the pull request https://github.com/buildbot/buildbot/pull/2063 and add a raise [[ValueError]]('hey') just after the upgrade() in master/buildbot/db/migrate/versions/046_mysql_innodb_compatibility.py
execute buildbot upgrade-master. 
- rerun buildbot upgrade-master

---

_Comment from_: @rutsky
_Date_: `Mar 24 2016`

Related pull requests:
https://github.com/buildbot/buildbot/pull/2068,
https://github.com/buildbot/buildbot/pull/2063

**Comment by seankelly** [comment]
#2068 says it fixed this issue.
