### ISSUE TITLE
provide sample Apache conf (websockets)

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3001]
This ticket is a migrated Trac ticket [3561](http://trac.buildbot.net/ticket/3561)

People contributed to the original ticket: @unknown_contributor
Ticket created on: `Jun 07 2016`
Ticket last modified on: `Jun 07 2016`

---

A working Apache 2.4 conf in doc would be useful, next to http://docs.buildbot.net/latest/manual/cfg-www.html#reverse-proxy-configuration

---

**Comment by seankelly** [comment]
Added in #2267.
