### ISSUE TITLE
fix compatibility fix flake8 2.6.0

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3003]
This ticket is a migrated Trac ticket [3566](http://trac.buildbot.net/ticket/3566)

People contributed to the original ticket: @tardyp
Ticket created on: `Jun 17 2016`
Ticket last modified on: `Jun 21 2016`

---

flake8 2.6.0 broke travis, and we need to remove the fix to 2.5.5

---

_Comment from_: @tardyp
_Date_: `Jun 21 2016`

https://github.com/buildbot/buildbot/pull/2280

**Comment by seankelly** [comment]
Fixed in #2280.
