### ISSUE TITLE
Create a Build list for a Worker Page

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3018]
This ticket is a migrated Trac ticket [3638](http://trac.buildbot.net/ticket/3638)

People contributed to the original ticket: @unknown_contributor, @tardyp
Ticket created on: `Oct 29 2016`
Ticket last modified on: `Nov 01 2016`

---

Hello,

I have been using the "Slaves", now Workers overview on 0.8.x to quickly look at the Windows builds, or in case of a trouble with a worker, where e.g. one Python version was not intact, to filter for it.

In 0.9.0 there is no such link or content anymore, which is a petty.

I understand that for Windows builds, using a tag would be good (not yet looked at that), but looking at one workers builds, would be really nice.

Also I have been using that page to see which builds run on a worker currently. That also seems not possible anymore.

Is this intentionally removed, or just not yet there again anymore?

Yours,
Kay

---

_Comment from_: @tardyp
_Date_: `Nov 01 2016`

The worker page have not been ported yet by lack of time.

Also probably there will be a need for some data api optimization in order to sort the builds per worker.

This is no huge work but it needs to be done.

patches are welcome!

**Comment by noc0lour** [comment]
I see a workers page in buildbot 0.9.5 now, so this feature is back in buildbot nine and this issue solved :) ?

**Comment by tardyp** [comment]
it has in 0.9.4 indeed!
