### ISSUE TITLE
Inconsistency in foreign key when inserting entry in scheduler_changes table

### ISSUE THREAD

**Issue by mthalmei** [buildbot/buildbot#3021]
The trac ticket http://trac.buildbot.net/ticket/3532 already adresses a problem when inserting entries into scheduler_changes table.

Although this issue is fixed for SingleBranchScheduler it seems to be still unfixed for the Nightlyscheduler we are using and still getting the same errors.

This ticket is a migrated Trac ticket 3660

**Comment by wstering** [comment]
PostgreSQL 9.4 shows the following error, when processing a change for the NightlyScheduler:
```
ERROR:  insert or update on table "scheduler_changes" violates foreign key constraint "scheduler_changes_schedulerid_fkey"
DETAIL:  Key (schedulerid)=(18) is not present in table "schedulers".
STATEMENT:  INSERT INTO scheduler_changes (schedulerid, changeid, important) VALUES (18, 721, 1)
```

Picking up changes works OK for SingleBranchScheduler, as noted above.
