### ISSUE TITLE
hyperlatent should cleanup previous containers in case of master crash

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3023]
This ticket is a migrated Trac ticket [3603](http://trac.buildbot.net/ticket/3603)

People contributed to the original ticket: @tardyp
Ticket created on: `Aug 26 2016`
Ticket last modified on: `Feb 08 2017`

---

Should label the containers with the id of the master, and then search for old containers at service start.

This should be done only once per master

---

**Comment by p12tic** [comment]
Support for hyper has been removed long ago. Closing the issue.
