### ISSUE TITLE
buildbot.bat in Scripts-Directory is missing on windows

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3024]
This ticket is a migrated Trac ticket [3611](http://trac.buildbot.net/ticket/3611)

People contributed to the original ticket: @unknown_contributor, @tardyp
Ticket created on: `Sep 20 2016`
Ticket last modified on: `Feb 08 2017`

---

When I upgraded from buildbot-0.9.0rc2 to rc3, the "buildbot.bat"-File that is used to start the buildbot under Windows goes missing in the virtualenv's Scripts-Directory. With a downgrade to rc2 it reappears.

Upgrade Procedure: pip install buildbot==0.9.0rc3 --upgrade

---

_Comment from_: @unknown_contributor
_Date_: `Sep 20 2016`

Python version is 2.7.11(XXX macro: "BR")

Pip 8.1.2 (XXX macro: "BR")

As a workaround you can just use the buildbot.bat from rc2

---
_Comment from_: @tardyp
_Date_: `Sep 27 2016`

It is possible that you did upgrade using the wheels, and install using the tarball.

can you verify on a clean virtualenv using pip install --no-use-wheel to force tarball use?

---
_Comment from_: @unknown_contributor
_Date_: `Sep 28 2016`

I tested several variants of installing/upgrading it - some worked, some didn't - every test ("---") was performed in a clean env. "=>" shows the (intermediate) result. If there's anything else I can provide, let me know.

    
    ---
    
    pip install --no-use-wheel buildbot==0.9.0rc3
    => proper buildbot.bat
    
    ---
    
    # this is essentially my case, only starting earlier and updates until rc3 (with pip install) worked:
    easy_install buildbot==0.9.0rc2
    => proper buildbot.bat
    pip install buildbot==0.9.0rc3 --upgrade
    => no buildbot.bat
    
    ---
    
    pip install buildbot==0.9.0rc3
    => no buildbot.bat
    
    ---
    pip install buildbot==0.9.0rc1
    => proper buildbot.bat
    pip install buildbot==0.9.0rc2 --upgrade
    => proper buildbot.bat
    pip install buildbot==0.9.0rc3 --upgrade
    => no buildbot.bat
    
    ---
    
    pip install buildbot==0.9.0rc2
    => proper buildbot.bat
    pip install buildbot==0.9.0rc3
    => no buildbot.bot
    
    ---
    
    pip install buildbot==0.9.0rc3
    => no buildbot.bat
    
    ---
    
    pip install --no-use-wheel buildbot==0.9.0rc2
    => proper buildbot.bat
    pip install --no-use-wheel buildbot==0.9.0rc3 --upgrade
    => proper buildbot.bat
    
    ---
    
    easy_install buildbot
    => proper buildbot.bat (uses 0.9.0rc3)
    
    ---
    
    pip install buildbot
    => proper buildbot.bat (uses 0.8.14)
    
    ---
    
    easy_install buildbot==0.9.0rc2
    => proper buildbot.bat
    easy_install buildbot==0.9.0rc3
    => proper buildbot.bat
    
    

---
_Comment from_: @tardyp
_Date_: `Sep 28 2016`

Waow thanks for the extensive tests!

This is definititly a problem of the wheels which does not contain the bat.

This is confirmed by looking at the setup.py code buildbot.bat is only published in sdist.

At this point of the rc, I dont want to risk changing setup.py.

So I will do the fix only on master branch

Could you please help to test it?

---
_Comment from_: @tardyp
_Date_: `Sep 28 2016`

https://github.com/buildbot/buildbot/pull/2415

---
_Comment from_: @unknown_contributor
_Date_: `Sep 28 2016`

If you can give me bullet points of what I have to do, I'll test it (my python ecosystem knowledge is very limited). I'm guessing I have to build a wheel from master (+ patch) somehow and install it?

---
_Comment from_: @tardyp
_Date_: `Sep 28 2016`

You can create you own wheel using 

python setup.py bsdist_wheel

you need to fist install wheel package in venv
pip install wheel

---
_Comment from_: @tardyp
_Date_: `Sep 28 2016`

We can talk on irc #buildbot on freenode

---
_Comment from_: @tardyp
_Date_: `Sep 28 2016`

https://www.irccloud.com

---
_Comment from_: @unknown_contributor
_Date_: `Sep 29 2016`

Wheel from master+patch now properly installs a buildbot.exe in the scripts-folder. When the patch is merged, this ticket is solved.

**Comment by seankelly** [comment]
Fixed in #2415.
