### ISSUE TITLE
Intermittent issues launching Docker latent workers as of 0.9.0b2

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3026]
This ticket is a migrated Trac ticket [3621](http://trac.buildbot.net/ticket/3621)

People contributed to the original ticket: @unknown_contributor, @tardyp
Ticket created on: `Oct 07 2016`
Ticket last modified on: `Feb 08 2017`

---

Works as of 0.9.0b1, with 0.9.0b2 Docker volume specifications intermittently fail during the worker_prepare phase.

Gist logs: https://gist.github.com/Hexxeh/6d7c4bc6ca7433536b9b5103d6a5c97f

Relevant config chunk: volumes=["/cache:/cache:rw"]

---

_Comment from_: @tardyp
_Date_: `Oct 07 2016`

<lmcloughlin>  I think #3621 is a regression from https://github.com/buildbot/buildbot/commit/42120f3b59616745220b4432166b2cb14a7bb1e5

<lmcloughlin> still a problem with 0.9.0

**Comment by tardyp** [comment]
@Hexxeh do you still reproduce the problem with 0.9.5?

**Comment by seankelly** [comment]
The code has moved around a little bit. The volume checking in `checkConfig` is not the same as in `_thd_parse_volumes`. Not seeing why it would error for the example given (`volumes=["/cache:/cache:rw"]`).

Also, I see checking for `:ro` or `:rw`, but `:Z` and `:z` are also valid options.

**Comment by p12tic** [comment]
I don't think this happens anymore.
