### ISSUE TITLE
[Nine] HttpPushStatus fails on CheckConfig

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3027]
This ticket is a migrated Trac ticket [3625](http://trac.buildbot.net/ticket/3625)

People contributed to the original ticket: @unknown_contributor, @tardyp
Ticket created on: `Oct 12 2016`
Ticket last modified on: `Feb 08 2017`

---

I've been trying to add an `[[HttpPushStatus]]` service to my buildbot but there was no way I could get it to work.

Using the very simple [from buildbot.plugins import reporters
sp = reporters.[[HttpStatusPush]](serverUrl="http://example.com/submit")
c[[example shown in the doc|'services'].append(sp)]], I added the following lines to my master.cfg file:

    from buildbot.plugins import reporters
    
    c[[= [|'services']]]
    sp = reporters.[[HttpStatusPush]](serverUrl="http://localhost:16161/")
    c['services'].append(sp)

This causes the master.cfg file to fail on $ buildbot checkconfig master.cfg :

    $ buildbot checkconfig master.cfg
    :0: [[UserWarning]]: You do not have a working installation of the service_identity module: 'No module named service_identity'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module and a recent enough pyOpenSSL to support it, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
    error while parsing config file:
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 149, in maybeDeferred
        result = f(*args, **kw)
      File "/Library/Python/2.7/site-packages/buildbot/scripts/checkconfig.py", line 57, in checkconfig
        return _loadConfig(basedir=basedir, configFile=configFile, quiet=quiet)
      File "/Library/Python/2.7/site-packages/buildbot/scripts/checkconfig.py", line 27, in _loadConfig
        config.[[FileLoader]](basedir, configFile).loadConfig()
      File "/Library/Python/2.7/site-packages/buildbot/config.py", line 161, in loadConfig
        self.basedir, self.config[[FileName]])
    --- <exception caught here> ---
      File "/Library/Python/2.7/site-packages/buildbot/config.py", line 118, in load[[ConfigDict]]
        exec(f, localDict)
      File "/Users/dgm/code/spideroak/buildbot-sandbox/master/master.cfg", line 597, in <module>
        sp = reporters.[[HttpStatusPush]](serverUrl="http://localhost:16161/")
      File "/Library/Python/2.7/site-packages/buildbot/util/service.py", line 122, in __init__
        self.checkConfig(*args, **kwargs)
    exceptions.[[TypeError]]: checkConfig() takes exactly 4 arguments (2 given)
    
    Configuration Errors:
      error while parsing config file: checkConfig() takes exactly 4 arguments (2 given) (traceback in logfile)

Removing said lines allows the master.cfg file to pass checkconfig. I don't know if this is a bug in the Nine port or just a wrong documentation.

---

_Comment from_: @unknown_contributor
_Date_: `Oct 13 2016`

Further investigating this:

I managed to get things working by using:

`sp = reporters.[[HttpStatusPush]](serverUrl="http://localhost:16161/", user='diego', password='password')`

It seems like `user` and `password` are mandatory parameters in `[[HttpStatusPush]]`; however, the documentation is inconsistent in this regard, because the example shown does not include them.

---
_Comment from_: @tardyp
_Date_: `Oct 18 2016`

This is a bug. user password should not be mandatory

**Comment by p12tic** [comment]
No longer happens on master, likely fixed in 9dd96eb1251ecc0e1e84903d7347345e66406df9.
