### ISSUE TITLE
Setting timeout=None to the CopyDirectory step has no effect.

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3032]
This ticket is a migrated Trac ticket [3669](http://trac.buildbot.net/ticket/3669)

People contributed to the original ticket: `benoit.allard@...`
Ticket created on: `Feb 28 2017`
Ticket last modified on: `Feb 28 2017`

---

According to the documentation, this should disable the timeout altogether.

Unfortunately, the timeout value is given to the worker only if the value evaluates to 'True-ish'. The worker on its side, when not given a value uses 120sec. Making the timeout=None useless.

---

_Comment from_: @Ben
_Date_: `Feb 28 2017`

The workaround is to use a bigger value, like 1200.

**Comment by leopoldwe** [comment]
Is this issue still open? I'd like to work on it.

**Comment by tardyp** [comment]
hi @leopoldwe there is an old PR that was seems to have a wrong fix at #3855.
this was never finished. Please let us know your first investigations

**Comment by leopoldwe** [comment]
I think the problem exists in buildbot/master/steps/worker.py, where on line 124 we have:
`    def __init__(self, src, dest, timeout=None, maxTime=None, **kwargs):`
where the timeout defaults to None. Later, in the start function (lines 135 and 136), the truthiness of timeout is evaluated:
`        if self.timeout:`
`            args['timeout'] = self.timeout`

Later, the get statement in fs.py that is modified by the old pull statement finds args['timeout'] empty, and sets timeout to 120.

The solution I can think of is to set the default to 120 (to be in line with documentation) and remove the if statement. The tests would also need to be updated, as they expect timeout to be None if no argument is passed.

**Comment by tardyp** [comment]
@leopoldwe I agree on your root-cause finding. removing the if self.timeout will fix the issue. Can you please submit a PR?
