### ISSUE TITLE
Add tzdata package to the docker image.

### ISSUE THREAD

**Issue by oprietop** [buildbot/buildbot#3055]
The package is needed for ppl on different timezones i think it's worth his place in the docker alpine image.
https://bugs.alpinelinux.org/issues/5543

**Comment by tardyp** [comment]
Hi @oprietop The dockerfile is stored there: https://github.com/buildbot/buildbot/blob/master/master/Dockerfile#L27

Would you like to submit a PR for this issue?

**Comment by jbergstroem** [comment]
Think this is safe to close -- wasn't referenced as 'fixed' as part of the merge.
