### ISSUE TITLE
buildbot repository on github does not have a LICENSE

### ISSUE THREAD

**Issue by anish** [buildbot/buildbot#3061]
I would like to contribute to this project via my corporate id, but I cannot get approval without having a license assigned to this project.

**Comment by noc0lour** [comment]
It doesn't have a license in the root repo, but e.g. master has LICENSE information as every source file:

https://github.com/buildbot/buildbot/blob/master/master/COPYING

**Comment by anish** [comment]
I am aware, this issue it to add a LICENSE file to the root directory

**Comment by anish** [comment]
apparently I was misreading -www & -website. Leaving this note here in case someone else comes along with the same issue : 
```
12:42 <@tardyp> anish: the problem is if I put a LICENSE which states sub licenses for sub directories, github will probably not detect the actual license.
```
subcomponents of the buildbot repo use different licenses.

**Comment by tardyp** [comment]
fixed in https://github.com/buildbot/buildbot/pull/3063
