### ISSUE TITLE
Console_view lines don't change position on expansion

### ISSUE THREAD

**Issue by noc0lour** [buildbot/buildbot#3062]
If I expand a changeset in `console_view` the horizontal separation line between changes won't expand as well and then the UI looks weird.

**Comment by tardyp** [comment]
@noc0lour please upload screenshoots when sending UI bugs
I hope that #3108 fixes you issue, but I can't be sure

**Comment by noc0lour** [comment]
![20170410103938](https://cloud.githubusercontent.com/assets/4438327/24874601/17a23b66-1dda-11e7-80c1-c5cc05c809fb.png)

**Comment by noc0lour** [comment]
I'll try the fixes later :)

**Comment by tardyp** [comment]
dammit, you don't have the same bugs as I see and fixed in #3108.

I can reproduce your bug, though, which is not fixed yet in #3108

**Comment by noc0lour** [comment]
also, this also looks weird, we should scale the width with the available screen width.
![20170410124757](https://cloud.githubusercontent.com/assets/4438327/24879499/f8531b4c-1deb-11e7-9aca-85631fab3844.png)
