### ISSUE TITLE
DockerLatentWorker: pull specified image if it is not yet on the system

### ISSUE THREAD

**Issue by noc0lour** [buildbot/buildbot#3071]
This is merely an enhancement, but it would be nice if the specified image is pulled from dockerhub if it is not on yet on the host system. 
This should be pretty easy to accomplish using docker-py, but I don't know if this a desired feature.

**Comment by Frodox** [comment]
Generally +1, but I'm voting for config-option also, to disable/enable behavior. It is not always desired, because sometime LatentWorker should take identical custom docker-image, not latest one from dockerHub. And in case there is no one - host is bit miss-configured and it s an error :)

**Comment by tardyp** [comment]
in my understanding, this is already the case. If its not, this code is pretty simple, and you should easily be able to fix it

**Comment by noc0lour** [comment]
Yeah, I looked into the code yesterday but didn't have the time to figure it out, also a spotted another bug with docker images, but that one I can fix myself
