### ISSUE TITLE
Github change hook broken in 0.9.5 if payload is not ascii (PY2)

### ISSUE THREAD

**Issue by vbraun** [buildbot/buildbot#3078]
I just updated to 0.9.5 and the github changehook doesn't work any more (this is the sagemath.org buildbot). I can simulate it with wget, the github webhook console contains the same Error 400 with body "ascii": 
~~~~
$ wget -S -O - --header="Content-Type: application/json" --header="X-Github-Event: push" --post-file=/tmp/payload.json http://build.sagedev.org/change_hook/github
--2017-03-25 22:49:02--  http://build.sagedev.org/change_hook/github
Resolving build.sagedev.org (build.sagedev.org)... 128.208.160.249
Connecting to build.sagedev.org (build.sagedev.org)|128.208.160.249|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 400 ascii
  Date: Sat, 25 Mar 2017 21:49:54 GMT
  Content-Length: 5
  Content-Type: text/html
  Server: TwistedWeb/16.3.0
2017-03-25 22:49:03 ERROR 400: ascii.
~~~~
The log doesn't contain any error (I was hoping for a backtrace, but no luck):
~~~~
...
2017-03-25 21:40:54+0000 [_GenericHTTPChannelProtocol,435,91.66.84.148] X-GitHub-Event: push
2017-03-25 21:40:54+0000 [_GenericHTTPChannelProtocol,435,91.66.84.148] New revision: 16c0bfa0
...
~~~~
But buildbot doesn't actually pick up any changes.

If I manually strip out non-ascii characters then the payload goes through.

The payload is http://sagepad.org/pub/payload.json

**Comment by seankelly** [comment]
What was your previous version? 0.9.4?

Checking the JSON file and it decodes as valid UTF-8. Not sure why it would fail now.

**Comment by seankelly** [comment]
FYI, 0.9.5 is when the GitHub change_hook was converted to support Python 3.

This is the [offending line](https://github.com/buildbot/buildbot/blob/v0.9.5/master/buildbot/www/hooks/github.py#L202):

    'author': '{} <{}>'.format(commit['author']['name'],                   
                               commit['author']['email']),                 

The name in this case contains a non-ascii character, ü,

```
>>> "{} <{}>".format(u"Julian Rüth", u"b")                                             
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 8: ordinal not in range(128)
>>> u"{} <{}>".format(u"Julian Rüth", u"b")                                            
u'Julian R\xfcth <b>'
```

**Comment by vbraun** [comment]
I'm not entirely sure which version I had previously, might have been 0.9.2 or 0.9.3

**Comment by rodrigc** [comment]
@vbraun can you make this patch to your 0.9.5 setup under Python 2 and provide feedback:

```
diff --git a/master/buildbot/www/hooks/github.py b/master/buildbot/www/hooks/github.py
index 57ff7a3..74f35c0 100644
--- a/master/buildbot/www/hooks/github.py
+++ b/master/buildbot/www/hooks/github.py
@@ -203,7 +203,7 @@ class GitHubEventHandler(object):
             log.msg("New revision: {}".format(commit['id'][:8]))
 
             change = {
-                'author': '{} <{}>'.format(commit['author']['name'],
+                'author': u'{} <{}>'.format(commit['author']['name'],
                                            commit['author']['email']),
                 'files': files,
                 'comments': commit['message'],
```

Longer term, I would suggest that if you are doing anything which could possible have
non-ASCII characters, you should move your buildbot nine setup to use Python 3.
The "python 3 way" of doing unicode is a bit easier to deal with all over the buildbot code than
Python 2.
