### ISSUE TITLE
Grid View plugin

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3084]
Buildbot eight had a grid view dashboard, which has not yet be ported to nine.
There are few people asking if it is available. 

This issue is to gather feedback of why it is needed, how it is different from console view.
Goal is not to reproduce 1:1 the eight grid view, but rather to build a dashboard useful to most users.

Please write comment if you have constructive feedback. Dont write +1 comment, but rather use github's +1 reaction  to count people interested with gridview
![image](https://cloud.githubusercontent.com/assets/109859/24395445/f9d4ff2c-139f-11e7-9b2e-fcf90f1b0dff.png)

**Comment by Frodox** [comment]
Can you please add a screenshot, how it was/can looks like?

**Comment by tardyp** [comment]
Here is the xemacs gridview on 0.8.12
![image](https://cloud.githubusercontent.com/assets/109859/24427826/a0938920-140c-11e7-8502-a55c6bf81e45.png)

**Comment by incandescant** [comment]
The Yocto Project makes heavy use of the transposed grid view. We have a primary builder on which we set properties and force schedule, which then triggers several (~45) other builders. 

We find the tgrid gives us the best/most usable overview of builds, with each row in the grid representing all of the builds triggered by our (nightly) force scheduler.

You can see our tgrid here: https://autobuilder.yoctoproject.org/main/tgrid

It doesn't appear (from browsing nine.buildbot.net) that the new nine UI offers a dashboard which would offer us a similar view into all related builds?

**Comment by tardyp** [comment]
@incandescant did you see the new version of the console view?
https://nine.buildbot.net/#/console

would it address your requirement?
I have made change so that it does not require changesource to be configured anymore.
It will use the got_revision property if no change is associated to the build.

**Comment by incandescant** [comment]
@tardyp the new version of the console view looks like it addresses our requirements perfectly. I'm hoping to try it out in the next few weeks.

**Comment by tardyp** [comment]
@incandescant \o/

**Comment by rjarry** [comment]
A grid view plugin for nine would be awesome :)

The console view is suitable for servers with few builders, but it does not scale well when there are a lot of them:

![image](https://cloud.githubusercontent.com/assets/472286/26790449/07d0cade-4a14-11e7-9c88-5aeeca447ece.png)

**Comment by tardyp** [comment]
There is this tutorial which present how to develop a grid view plugin:
https://www.youtube.com/watch?v=xsejw4JIRwg&index=2&list=PLn5is82WglzsiqUWvTy5R0PsDGNGV56Kf

I will not have the time to work on it the next few month. Please feel free to work on it.

**Comment by Frodox** [comment]
I'm interested in and like `console view plugin` a lot!
Just need to tune it a bit to scale correctly with a lot of builders a bit (I'll try somewhen later)

**Comment by Frodox** [comment]
* I can't select any text on console view (date, author, revision, comments - nothing) // Ubuntu 16, Chromium
* I see column for old (not existed) builders. I think it is not relevant here
* Description of elements overlapped with sidebar (see picture)
![screenshot_2017-06-15_12-26-50](https://user-images.githubusercontent.com/3653069/27174968-75abe656-51c6-11e7-9b72-fe02de94920f.png)

**Comment by Frodox** [comment]
@rjarry should this still be open?
