### ISSUE TITLE
secrets: support usage of secrets in buildbot services

### ISSUE THREAD

**Issue by noc0lour** [buildbot/buildbot#3131]
I don't know if this is even a feature the secrets management is built for. 
Currently putting secrets into various services won't work since it is a Interpolate object and e.g. the `GitHubStatusPush` concatenate the token with a string.

Also it is not clear when the Interpolate object is rendered, is it even rendered?

In general it would be handy to have this support so one would only have to setup the secrets provider and could access the secrets everywhere.

**Comment by tardyp** [comment]
+ @protatremy 

@noc0lour The secretmanager design is not fully implemented.

The way it is supposed to work is that the services needs to be changed to support it.
as secret manager can be defined anywhere in the master.cfg, you cannot interpolate the secrets at init. you need to interpolate them at reconfiguration stage.
You would need to render the secret at that stage similar to some other stuff which are rendered at reporting stage

**Comment by noc0lour** [comment]
I'm aware of that, I just wanted to give it a shot (: but the master didn't even come up because it already failed to init services which have a token

**Comment by tardyp** [comment]
That would be cool if you want to try yourself at updating one or two services. I think that part will be pretty straightforward.
