### ISSUE TITLE
SecretManager is not fully finished

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3143]
remaining work:

- hide the secrets from the logs
- some docs inconsistencies #3130
- provide a new 'secrets' class attribute, similar to 'renderables', which will be automatically rendered by BuildbotService's reconfigService to  make it very easy for reporters and changesource to support secrets #3131

- PushSecretToWorker step which will push a secret to a worker in a file.

**Comment by protatremy** [comment]
I am started to work on those 2 points:
hide the secrets from the logs (finishing unit tests)
some docs inconsistencies #3130  => what about the SecretInFile change for now?

**Comment by protatremy** [comment]
PushSecretToWorker step was created, it is called download_secret_to_worker
