### ISSUE TITLE
workers webui sometimes fails to show all currently active builds

### ISSUE THREAD

**Issue by mostynb** [buildbot/buildbot#3168]
I have a buildbot 0.9.6 instance with two builders and two workers, the worker page only shows one active build (throbbing yellow), but if I click through to each of the workers I can see that there are active builds in both.

Related bug: on the worker page with the active build that is missing in the summary page, the current build is shown as active at the top of the list of builds, but is missing from the recent builds section at the top.

**Comment by tardyp** [comment]
Hi mostynb,
Can you post screenshots of the issues. It is not very clear to me how I can reproduce and help.
You can easily copy paste screenshot images within GH UI.

**Comment by mostynb** [comment]
The workers overview page shows only one active build:
![1](https://cloud.githubusercontent.com/assets/6337887/25665871/25a8fdb0-301f-11e7-9b0b-903b57f570a5.png)

The first worker shows one active build:
![2](https://cloud.githubusercontent.com/assets/6337887/25665877/29b52640-301f-11e7-8cb5-da78d2a37638.png)

The second worker has one active build, but only shown in the list (it should be shown as yellow in the summary at the top, and also in the first image):
![3](https://cloud.githubusercontent.com/assets/6337887/25665885/320f4b72-301f-11e7-93e2-e980970b2fb9.png)

**Comment by seankelly** [comment]
I think I have seen this as well. At the moment, on our 0.9.3 install, two builds are shown as active but it should be four: the spawner and three triggered builds. Refreshing the page fixes it.

**Comment by mostynb** [comment]
Refreshing/reloading the page didn't seem to help for me.

**Comment by tardyp** [comment]
Thanks for the details.
The problem comes from this line:
https://github.com/buildbot/buildbot/blob/master/www/base/src/app/workers/workers.tpl.jade#L24-L25
The UI only show 7 recent builds, but orders by number, which does not make sense, as we are using several builders, we should rather order by buildid or started_at

**Comment by tardyp** [comment]
that 7 number is also pretty arbitrary :-/

Would you like to try and change the template with this order?
would it make more sense for you?

                    span(ng-repeat="build in worker.builds | orderBy : ['complete', '-buildid'] |limitTo: '7' ")

**Comment by mostynb** [comment]
Ordering by -buildid instead of -number fixes the issue.

I think it probably makes more sense to include in progress builds than to only show completed builds in the summary.

**Comment by tardyp** [comment]
Thanks!
Would you like to send a patch and get more credits for your findings?
