### ISSUE TITLE
RolesFromEmails doesn't work with GitHub auth (and maybe others)

### ISSUE THREAD

**Issue by samizzo** [buildbot/buildbot#3177]
I've got a setup like this:

```
auth = util.GitHubAuth(CLIENT_ID, CLIENT_SECRET)
authz = util.Authz(
    allowRules = [ util.AnyControlEndpointMatcher(role = "admins") ],
    roleMatchers = [
        util.RolesFromEmails(
            admins = [ "sam@humbug.net" ]
        )
    ]
)
```

`sam@humbug.net` is my primary email address. This doesn't work; I have to use my username, `samizzo`, as the email address in the `RolesFromEmails`.

Looking through the code, I can't see how this has ever worked. The authentication mechanism ends up calling [`UserInfoProviderBase.getUserInfo`](https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/auth.py#L83) which returns the username as the email address in the user info.

I'm not sure what the right fix for this is; I don't know the buildbot code very well. I've switched over to using `RolesFromUsername` which is more convenient anyway.

**Comment by tardyp** [comment]
I think the reason is that Github do not provide email address in the oauth server.
There is no need to know buildbot very well to fix it if you can look at the github API and find a way to get the email address (maybe it evolved since first implementation)
Else, could you please submit a documentation PR to tell that GitHubOauth is only compatible with RolesFromUsername and RolesFromGroups?

**Comment by samizzo** [comment]
GitHub actually does return the correct values these days, and the GitHubAuth [code](https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/oauth2.py#L192) correctly parses it as well. So it seems to me that it should be possible to make it work (maybe originally GitHub didn't return the correct values).

I think the main problem is that `OAuth2LoginResource` [here](https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/oauth2.py#L60) passes in the username to `getUserInfo`, which then gets set as the value for `email` rather than the email address. So I suppose at that point it should be passing in the email instead. But `getUserInfo` seems to expect a username rather than an email string.

I'll look into it and see if it is safe to pass in the email address instead.

**Comment by tardyp** [comment]
Are you sure that userInfoProvider.getUserInfo is actually called?
Normally there is no need for additional userInfoProvider with githubAuth.

userInfoProvider is made for kerberos or similar auth method, which cannot provide additional user infos.

Double checking with the links you provided, it looks like Github auth should actually work with emails

**Comment by samizzo** [comment]
That line was definitely called, from line 60 in oauth2.py. I added debug log calls right after, before the `details` dict is updated, and `details` has the email address, but `infos` has the username as the email address. So it gets overwritten there.

So perhaps the problem is that the `userInfoProvider` is set when it shouldn't be? I agree GitHub auth looks like it should work; all the plumbing is there. I'll try and debug this further.

**Comment by samizzo** [comment]
I see you made a fix, that looks like it should solve it, thanks! I'll test this out on my installation.
