### ISSUE TITLE
SecretsInAFile: usability suggestions

### ISSUE THREAD

**Issue by Lekensteyn** [buildbot/buildbot#3178]
The current SecretInAFile provider seems a good start at separating the keys from the main config file. Some observations/suggestions:

 - Strip trailing newlines (or just read the first line from the config file). When the secrets provider is used to read passwords, this seems appropriate and it makes editing passwords with `vim` or `echo sikrit > foo` easier.
 - (Python 3 compatibility note: a str is read, so the secrets framework will/should likely only work with strings rather than arbitrary byte data, making the "read a line" suggestion even more plausible.)
 - Perhaps resolve relative paths to `basedir` by default (and document this behavior). Saves a call to `os.path.join(basedir, dirname)` in master.cfg

For use as password database, maybe it is also an idea to implement a passwd(5)-like file (with lines such as `key:password`).

**Comment by tardyp** [comment]
Hi @Lekensteyn Secret management is very new in Buildbot and indeed it will need some tweaks to make it awesome to use.
I agree with all your suggestions.

Would you like to help and provide those little tweaks?

**Comment by Lekensteyn** [comment]
@tardyp I'll try to give it a go, was checking if you were okay with these changes. Thanks for the feedback.

**Comment by tardyp** [comment]
strip is fine. I would add a strip option to SecretInFile with default to True. Just in case some people actually need the `\n`, and want to set it to False.

I also agree to try and make as small PRs as possible, and thus send one PR per tweak.

**Comment by Lekensteyn** [comment]
Apparently it is not possible to access "basedir" during the checkConfig phase (because the "master" object) is not available (https://irclogs.jackgrigg.com/irc.freenode.net/buildbot/2017-05-16#i_4111140).

So that idea is dropped for now, `os.path.join(basedir, "whatever")` is the current compromise.
