### ISSUE TITLE
doStepIf is not renderable

### ISSUE THREAD

**Issue by trefzer** [buildbot/buildbot#3188]
according to the documentation I expected doStepIf to bee renderable, but it's not !

**Comment by trefzer** [comment]
I don't think this is a documentation issue, I rather think the this step should be rendable, otherwise this option would not make any sense for me since you could replace it with a simple 'if' statement in the configuration code. Or said differently, if this option is not rendrable you could simply delete the option since it has no additional value.

**Comment by Frodox** [comment]
@trefzer I think is it resolved now :) 
I see noting in docs about renderer, [just](http://docs.buildbot.net/current/manual/cfg-buildsteps.html)
 
> To do this, set the step’s doStepIf to a boolean value, or to a function that returns a boolean value or Deferred. 

So, it looks like `def myfunc(step):` didn't work too?

**Comment by trefzer** [comment]
according to me its solved.
the problem was that the rendering did happen after doStepif was used (in short he did: IF doStepIf true, THEN render doStepIf).
