### ISSUE TITLE
lz4 log compression triggers unnecessary warnings in twisted.log

### ISSUE THREAD

**Issue by bertranddemiddelaer** [buildbot/buildbot#3201]
When running buildbot 0.9.5 with lz4 log compression (package 0.9.0 installed), I have this warning many times in twisted.log:

`
exceptions.DeprecationWarning: Call to deprecated function or method dumps (use lz4.block.compress instead).
`

It seems that when I comment those line in master/buildbot/config.py, I don't have those warnings anymore:

` 
if self.logCompressionMethod == "lz4":
            try:

                import lz4
                [lz4]
            except ImportError:
                error(
                    "To set c['logCompressionMethod'] to 'lz4' you must install the lz4 library ('pip install lz4')")
`

**Comment by tardyp** [comment]
I think I have fixed this bug in recent version of buildbot

**Comment by tardyp** [comment]
https://github.com/buildbot/buildbot/pull/3040

**Comment by tardyp** [comment]
you can also downgrade lz4

**Comment by bertranddemiddelaer** [comment]
I am running buildbot 0.9.5, the issue and fixes you are mentioning seems older.

**Comment by tardyp** [comment]
@bertranddemiddelaer 
This message is really related to #3040. I can't understand why you would have this issue though
