### ISSUE TITLE
Github status push does not process git url correctly

### ISSUE THREAD

**Issue by samvasko** [buildbot/buildbot#3215]
When using URL with form `git@github.com:<org>/<repo>.git` 
the github reporter sends a request to:
`POST /repos/git@github.com:<org>/<repo>/statuses/<sha>`
but the actual url should be:
`POST /repos/<org>/<repo>/statuses/<sha>`

```
Buildbot version: 0.9.7
Twisted version: 17.1.0
```

**Comment by tardyp** [comment]
indeed, it is only tested for the hook. Please feel free to send a patch to fix this issue.

**Comment by samvasko** [comment]
👍  I will take a look at it

**Comment by Frodox** [comment]
But how BuildBot GitHub works then? :confused:

**Comment by samvasko** [comment]
https I guess

**Comment by samvasko** [comment]
Would it be acceptable to replace the url parsing code for github, bitbucket and gitlab with something like [giturlparse.py](https://github.com/FriendCode/giturlparse.py)? 
Although it looks the package is not maintained I would rather go ahead and invest time in incorporating a more flexible solution than improve a half baked library that buildbot has.

**Comment by tardyp** [comment]
I think giturlparse is too complicated, and a more simple solution with just splits should be enough.

**Comment by tardyp** [comment]
see #3305

**Comment by p12tic** [comment]
I think this has been fixed in #3148.
