### ISSUE TITLE
kill poller process(es) on timeout

### ISSUE THREAD

**Issue by Enlik** [buildbot/buildbot#3281]
Because of a network issue, git executable spawned from GitPoller hanged which made polling stop working.

After killing the hanged processes all was fine again.

I remedied the issue by doing `GitPoller(bindir=xxx, …)` where `xxx` is a script that executes git through the timeout utility. (It should do the job, although a minor issue is that at least sometimes git when stalled and killed does not print anything, so nothing interesting in logs, but the characteristic exit status should be enough to determine what has happened, and otherwise that could be improved in the script.)

Anyway, please consider whether Buildbot itself could make sure it does not occur, in the git poller and possibly also other ones.

**Comment by p12tic** [comment]
This has been addressed in db93fb275189ee63a7f1017f17846d01d1ad95a8 which has been released in v3.2.0.
