### ISSUE TITLE
GitHub authentication not working on re-logins.

### ISSUE THREAD

**Issue by s0undt3ch** [buildbot/buildbot#3300]
I've set my nine installation to use GitHub for authentication.
I login using GitHub, authorize my oauth application to forward my login details to buildbot and I'm authenticated.
I logout and I'm never able to login again. I added some logging statements and when I try to re-login, I see that GitHub calls the right handler on buildbot and sends all the right details and buildbot even populates the groups correctly, but the UI never shows me as authenticated.

To solve this I have to delete all user tokens from my oauth application on GitHub and re-login.

Additionally, after the first successful authentication, I'm unable to login from other devices(browsers).

I also added some debug logs to twisted, namely `twisted.web.http.Request.write()` where I log the cookies and from a device which is not initially authenticated, using the same account which was previously authorized, I try to login, I see the GitHub request to buildbot show up, the `TWISTED_SESSION` cookie get's set for path `/` and then the requests for the several buildbot REST endpoints start to show on logs but they do not contain the `TWISTED_SESSION` cookie header.

This nine install is being proxied by nxing using SSL. The nxing configuration mimics the one provided on buildbot docs.

**Comment by tardyp** [comment]
It might be a problem of secure vs insecure cookie.
secure cookies are only sent to https.

**Comment by s0undt3ch** [comment]
So, buildbot is setting an insecure cookie because it's being served through HTTP and not HTTPS which the browser then rejects because it's accessing the website through HTTPS?

Can we force the secure cookie bit somewhere?

**Comment by tardyp** [comment]
it is handled by twisted web. I think It should work if the reverse proxy is correctly telling that the connection is actually https baked

**Comment by s0undt3ch** [comment]
So, I've set the forward headers in nginx and created https://github.com/buildbot/buildbot/pull/3302, however I notice something.
This works as supposed on Chromium, but doesn't on Firefox so, #3302 might not actually be required?!

**Comment by seankelly** [comment]
Per last comment and from #3306, marking as closed.
