### ISSUE TITLE
Can't read non ascii charachers in logs from GitLab / Base web change hook (PY2)

### ISSUE THREAD

**Issue by Frodox** [buildbot/buildbot#3301]
env:
* distro: `CentOS 7.3`
* `python-2.7.5-48.el7.x86_64`
* `buildbot-0.9.7`
* web hook setup
```
c['www'] = {
        'port': 8010,
        'plugins':dict(waterfall_view={}, console_view={}),
        'change_hook_dialects': {
            'base': True,
            'gitlab' : True,
        }
}
```

I use GitLab (8.5) web hook changes and it works fine, except I can't read non acsii characters in `twisted.log`. It looks like:

2017-06-07 14:21:49+0300 [-] injected change Change(revision=u'cde4e528089b8cf2dceeaab33b32a5cabb1b90f6', who=u'\u0420\u044b\u0431\u043d\u0438\u043a\u043e\u0432 \u0412\u0438\u0442\u0430\u043b\u0438\u0439 \u0412\u0438\u043a\u0442\u043e\u0440\u043e\u0432\u0438\u0447 <vit.ry@local>', branch=u'master', comments=u'fix: \u043c\u0435\u043b\u043a\u0438\u0435 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u044b \u0438 todo\n', when=1496834509, category=None, project=u'', repository=u'git@gitlab:ss/test.git', codebase=u'')

Well, it is completely not easy to dubug/develop. Any way to specify encoding fit gitlab-web-hook (like utf8) to use in everywhere? I'm free to test any suggestions and patches

**Comment by Frodox** [comment]
I think it may be related to #3078 

testing
```
'author': u'%s <%s>' %(commit['author']['name'],
                                   commit['author']['email']),
```
has no effects.

@rodrigc ?

**Comment by rodrigc** [comment]
As discussed on IRC, I don't think there is a better option for this than to switch to Python 3, which has better unicode support.

In Python 2, if I do this:

```
repr(u'\u0420\u044b\u0431\u043d\u0438\u043a\u043e\u0432 \u0412\u0438\u0442\u0430\u043b\u0438\u0439 \u0412\u0438\u043a\u0442\u043e\u0440\u043e\u0432\u0438\u0447')
```

I get:

```
u'\u0420\u044b\u0431\u043d\u0438\u043a\u043e\u0432 \u0412\u0438\u0442\u0430\u043b\u0438\u0439 \u0412\u0438\u043a\u0442\u043e\u0440\u043e\u0432\u0438\u0447'
```

but in Python 3, I get:

```
'Рыбников Виталий Викторович'
```

Buidbot uses the Twisted logger, which works better with unicode in Python 3 than in Python 2.

**Comment by Frodox** [comment]
Ok, I'll test it after you succeed with #3416 :D

**Comment by rodrigc** [comment]
@Frodox if you use a py3 master and py3 worker you will not encounter the problem in #3416
