### ISSUE TITLE
oauth2 logout + login fails on Firefox

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3306]
as discussed in #3302

On firefox, the second login with oauth keeps the user in anonymous.

Needs to investigate further

**Comment by tardyp** [comment]
So problem comes from the fact that during login procedure the ws connection is closed, and the JS in charge of detecting that triggers, which triggers polling of / and once a success full xhr on / is done, the JS will reload the page. In the middle of that the github oauth is still going out, but is then interrupted by that JS reload.

![image](https://user-images.githubusercontent.com/109859/26972698-2a455fe2-4d13-11e7-9282-775b7cfd1a83.png)


We need to make sure we disable all angularJS callbacks before going to login page.

**Comment by s0undt3ch** [comment]
Makes sense now.

**Comment by tardyp** [comment]
@s0undt3ch please see the fix in #3307. this fixes the problem for me on nine.buildbot.net. Please report back your own results.

**Comment by s0undt3ch** [comment]
#3307 fixes the problem I was experiencing, Thanks!
