### ISSUE TITLE
Using LZ4 in docker-compose config errors out

### ISSUE THREAD

**Issue by blag** [buildbot/buildbot#3316]
I am using Buildbot via Docker Compose, which uses [the Dockerfile](https://hub.docker.com/r/buildbot/buildbot-master/~/dockerfile/) from [buildbot-master](https://hub.docker.com/r/buildbot/buildbot-master/) on Dockerhub.

When I turned on lz4 compression for logs in `master.cfg`:

```python
####### LOGS

c['logCompressionMethod'] = 'lz4'
```

I got the following error:

```
buildbot_1  | checking master.cfg
buildbot_1  | Errors loading configuration:
buildbot_1  |   To set c['logCompressionMethod'] to 'lz4' you must install the lz4 library ('pip install lz4')
```

I think this would be fixed if the [`py-lz4`](https://pkgs.alpinelinux.org/package/v3.5/community/x86_64/py-lz4) package were installed in the docker image.

I tried reporting this on Buildbot's Trac but it told me I was a bot, that my registration was spam, and continuously gave me captchas to solve even when I correctly submitted them.<sup>1</sup>

<sup>1</sup> I have considered the fact that I might be a robot.<sup>2</sup>
<sup>2</sup> I'm pretty sure I'm not a robot.

**Comment by tardyp** [comment]
Hi,
We now use github to store our issues because of the spam issues we have on trac. so you are in the right place.

As per docker image, there are a lot of additional dependencies for buildbot. The documentation usually state what python package a component might need.
We chose to publish the minimal docker image on docker hub, and let users customize their own based on their need.

**Comment by blag** [comment]
You may want to update the guidelines for contributing to this repository to remove the pointer to Trac. That's why I tried submitting this issue there to begin with.

Maintaining minimal docker images is just fine, I just wanted to bring it to your attention.

Thanks!

**Comment by blag** [comment]
Whoops, I forgot to include the link to the [contributing guidelines](https://github.com/buildbot/buildbot/blob/master/CONTRIBUTING.rst).

Specifically, the [Issues, Bugs, and Tickets](https://github.com/buildbot/buildbot/blob/master/CONTRIBUTING.rst#issues-bugs-tickets) section needs updating.

**Comment by rodrigc** [comment]
@blag https://github.com/buildbot/buildbot/pull/3318

**Comment by tardyp** [comment]
@blag thanks for the heads up. I  updated contributing.rst in #3315
