### ISSUE TITLE
Add a `region` arg to `OpenStackLatentWorker`

### ISSUE THREAD

**Issue by MikaYuoadas** [buildbot/buildbot#3336]
Would be nice to allow passing a region_name to novaclient in `OpenStackLatentWorker`.

**Comment by tardyp** [comment]
@seankelly isn't that possible already?

**Comment by seankelly** [comment]
There is `nova_args` for arbitrary options, but I think that's only for creating an instance. I think it's not possible right now.

**Comment by seankelly** [comment]
I recall cmouse raising this in irc too so I think it requires code changes.

**Comment by MikaYuoadas** [comment]
What we currently do is inherit from `OpenStackLatentWorker` and override the `__init__()` to add `self.novaclient.client.region_name = region` at the end.
