### ISSUE TITLE
canStartBuild example (RemoteCommand) does not work 

### ISSUE THREAD

**Issue by nazarewk** [buildbot/buildbot#3339]
`RemoteCommand` implementation has changed and `canStartBuild` [example](http://docs.buildbot.net/0.9.8/manual/customization.html#canstartbuild-functions) stopped working because `self.step is None` in [here](https://github.com/buildbot/buildbot/blob/a5237a9cc02740e474cb0b3b717ed7296889f708/master/buildbot/process/remotecommand.py#L278)

**Comment by Frodox** [comment]
[permanent link](https://github.com/buildbot/buildbot/blob/a5237a9cc02740e474cb0b3b717ed7296889f708/master/buildbot/process/remotecommand.py#L278)

**Comment by nazarewk** [comment]
thanks, updated both links to be permanent

**Comment by tardyp** [comment]
@nazarewk looks like indeed a patch is needed in cleanup so that it is just a nop if self.step.build is None. Would you like to do this patch?

**Comment by seankelly** [comment]
Fixed in #3343.
