### ISSUE TITLE
manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by mttdbrd** [buildbot/buildbot#3342]
When trying to pull the latest Buildbot Docker image, I get the following errors:

Trying to pull repository docker.io/buildbot/buildbot-master ... 
manifest unknown: manifest unknown

Docker version 1.12.6, build ae7d637/1.12.6
Linux localhost.localdomain 4.11.5-200.fc25.x86_64 #1 SMP Wed Jun 14 17:17:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I'm running the latest available kernel from Fedora. Not sure what's going on. I'm wondering what version you used to build the buildbot-master image.

I'm able to download the buildbot-worker image with no problems.

**Comment by tardyp** [comment]
Hi,
We do not have :latest tag for buildbot-master. We only have :master, which follows the master branch.
```
1 % docker pull buildbot/buildbot-master
Using default tag: latest
Error response from daemon: manifest for buildbot/buildbot-master:latest not found
1 % docker pull buildbot/buildbot-master:master
master: Pulling from buildbot/buildbot-master
6f821164d5b7: Already exists
[...]
```
It is however advised to use a specific tagged version as found as:
https://hub.docker.com/r/buildbot/buildbot-master/tags/

Actually the best advice is to build your own version from the dockerfile, as our image are pretty minimalist.
