### ISSUE TITLE
HGPoller fails with some Mercurial repositories

### ISSUE THREAD

**Issue by stevegcarpenter** [buildbot/buildbot#3366]
HGPoller crashes on some repositories when using Python3 based Buildbot. Using the same master.cfg file, Python2 based Buildbot masters don't experience the same crash. I tested this with two different Mercurial repositories on the Python3 based Buildbot and only one of those experienced the crash - I am not certain how to explain that detail, but the permissions on each repository were configured identically.

[master.cfg.txt](https://github.com/buildbot/buildbot/files/1099078/master.cfg.txt)
[err.txt](https://github.com/buildbot/buildbot/files/1099083/err.txt)

**Comment by rodrigc** [comment]
Can you patch hgpoller.py with this change and try again with Python 3 and
Python 2
and report the result:

diff --git a/master/buildbot/changes/hgpoller.py
b/master/buildbot/changes/hgpoller.py
index 63126072c..82f2b2ad0 100644
--- a/master/buildbot/changes/hgpoller.py
+++ b/master/buildbot/changes/hgpoller.py
@@ -279,6 +279,7 @@ class HgPoller(base.PollingChangeSource):
                        r'--template={rev}:{node}\n']
         results = yield utils.getProcessOutput(self.hgbin, revListArgs,
                                                path=self._absWorkdir(),
env=os.environ, errortoo=False)
+        results = bytes2unicode(results, self.encoding, "replace")

         revNodeList = [rn.split(':', 1) for rn in results.strip().split()]


--
Craig

**Comment by stevegcarpenter** [comment]
@rodrigc I applied the patch you recommended for Python3 as well as Python2 and it worked well for each. For reference, I'm specifically testing on Python 3.5.2 and Python 2.7.9.
