### ISSUE TITLE
EC2LatentWorker security_name

### ISSUE THREAD

**Issue by vigsterkr** [buildbot/buildbot#3382]
when specifying `security_name='latent_buildbot_slave'` i'm getting the following error:

```
botocore.exceptions.ClientError: An error occurred (InvalidGroupId.Malformed) when calling the DescribeSecurityGroups operation: Invalid id: "latent_buildbot_slave" (expecting "sg-...")
```

**Comment by tardyp** [comment]
looks like ec2 is requiring that you setup security_name starting with 'sg-...'

**Comment by vigsterkr** [comment]
@tardyp mmm if i do that then i get:

```
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateSecurityGroup operation: Value (sg-10de0577) for parameter GroupName is invalid. Group names may not be in the format sg-*.
```

**Comment by vigsterkr** [comment]
so it's in a way a catch 22

**Comment by tardyp** [comment]
Aren't you supposed to pre-create this security group somewhere in AWS? I am not sure as I am no EC2 expert.

**Comment by vigsterkr** [comment]
@tardyp they are already pre-created... since i was using this with buildbot 0.8.12 previously without a problem

**Comment by tardyp** [comment]
so probably this is a regression that needs to be investigated. Would you like to help on that?

**Comment by vigsterkr** [comment]
lemme know how

**Comment by tardyp** [comment]
I guess, you would have to dig into the code and see what is the difference between 0.8 and 0.9.

**Comment by vigsterkr** [comment]
i've just debugged #3380 and there i've figured out what was the root cause... from that i believe here the problem is that there's a bad way of using the `security_name` parameter of `EC2LatentWorker` internally. meaning for the `DescribeSecurityGroups` to AWS one should use the corresponding security group id (this requires an extra lookup), but for `CreateSecurityGroup` one should use directly the supplied name...
and then in the instance request one should use the supplied name for the `SecurityGroups` parameter of the `LaunchSpecification`.

**Comment by vigsterkr** [comment]
i'm closing this as this bug cannot be reproduced in 0.9.12
