### ISSUE TITLE
Clean shutdown can make the master hangs forever.

### ISSUE THREAD

**Issue by MikaYuoadas** [buildbot/buildbot#3383]
If you start a clean shutdown (stop --clean) buildbot will stop starting new build and wait for currently running build to stop before exiting.

But if you have a build which triggers sub-builds and waits on them, the master can hangs forever.
The main build is waiting on builds that will never starts as the master is gracefully shutting down and the master is waiting on this main build before exiting.

**Comment by tardyp** [comment]
I think normally the buildsets that have a parent_buildid set should still be scheduled.
If not then indeed there is a bug (or a regression)

**Comment by MikaYuoadas** [comment]
I'll double check if I can reproduce then.

**Comment by Frodox** [comment]
@MikaYuoadas Any success?

**Comment by ryandesign** [comment]
Yup, I just ran into this on 0.8.12.

**Comment by alexlarsson** [comment]
This still happens with 1.6.0.

**Comment by tardyp** [comment]
Problem comes from https://github.com/buildbot/buildbot/blob/fecc7d05b89bc5227b0998af6b1676aa9a93fc1a/master/buildbot/process/botmaster.py#L79

The brd is completely stopped, while it should be kept around, and only block the buildrequests that do not have parent_buildid set.
