### ISSUE TITLE
sqlalchemy.exc.IntegrityError when setting properties

### ISSUE THREAD

**Issue by vigsterkr** [buildbot/buildbot#3384]
this is an error again that appeared when upgrading from 0.8.12 to 0.9.4.... 
i have couple of nightly jobs where i set various properties from the command line and then use those values to generate a new property.

currently all these jobs fail with the following error:

```
2017-06-27 04:09:10+0200 [-] releaseLocks(SetPropertyFromCommand(property='DAY_TIMESTAMP', command='date +%Y%m%d%H%M', hideStepIf=True)): []
2017-06-27 04:09:10+0200 [-]  step 'setproperty_2' complete: success (None)
2017-06-27 04:09:10+0200 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	Failure: sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '259-SetProperty_1' for key 'steps_name'") [SQL: u'INSERT INTO steps (number, name, buildid, started_at, complete_at, state_string, urls_json) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: (4L, u'SetProperty_1', 259L, None, None, u'pending', '[]')]
```

**Comment by seankelly** [comment]
Is it the same duplicate key error every time?

**Comment by vigsterkr** [comment]
@seankelly yes it's always `[BUILDNUMBER]-SetProperty_1`

**Comment by tardyp** [comment]
This error is normal if you have duplicate step names, and should be caught here: 

https://github.com/tardyp/buildbot/blob/log_scroll_bug/master/buildbot/db/steps.py#L90
The error is still generically logged in the lower layer.

Are you sure your step isn't failing because of another issue?

what if you uniquely name your steps?

**Comment by vigsterkr** [comment]
@tardyp naming each step with a unique name solved the problem! thnx!
