### ISSUE TITLE
0.9.8: MailNotifier info gets "overwritten" if builders argument is the same

### ISSUE THREAD

**Issue by larver-imvu** [buildbot/buildbot#3398]
I have a function `mk_MailNotifiers` like this:

```
    red_builders = ["foobuilder"]
    green_builders = ["foobuilder"]
    mns = []
    red_modes = ["failing", "warnings", "exception", "cancelled"]
    if red_builders:
        mns.append(reporters.MailNotifier(
            relayhost='smtp.corp.imvu.com',
            fromaddr='buildbot-red@imvu.com',
            sendToInterestedUsers=False,
            extraRecipients=["larver@imvu.com"],
            lookup="imvu.com",
            builders=red_builders,
            mode=red_modes,
            messageFormatter=formatter))
    if green_builders:
        mns.append(reporters.MailNotifier(
            relayhost='smtp.corp.imvu.com',
            fromaddr='buildbot@imvu.com',
            sendToInterestedUsers=False,
            extraRecipients=["larver@imvu.com"],
            lookup="imvu.com",
            builders=green_builders,
            mode='passing',
            messageFormatter=formatter))
    return mns
```

and I assign it in my buildmaster config to the `c['services']` key.

If I run a build and cancel it, I do not get an email. If the build passes, then I do get an email.

If I reverse the order of the `if` branches, so that the green builder MailNotifier gets added first to the list, then I do get an email if I cancel a build.

So it looks like if the `builders` argument is the same for the two MailNotifiers, the one that comes last overwrites the earlier one(s).

I realize that in my case both `red_builders` and `green_builders` is the same, and that I should probably be using something more like `mode="all"` with just 1 MailNotifier, but I can't because I want red builds to have a different `fromaddr` argument (`buildbot-red@imvu.com`) than green builds.

Is this a legitimate bug or am I not using the MailNotifier correctly?

**Comment by larver-imvu** [comment]
I tested on 0.9.9 also and the same behavior is present.

**Comment by larver-imvu** [comment]
As a point of comparison, in Buildbot 0.8.5 (from which my code example above originates from), the behavior works as expected (no overwriting of settings).

**Comment by tardyp** [comment]
looks like this is an issue with the algorithm with sets a name automatically for your notifier.

please see associated PR. can you set explicitly a name for your reporter as a workaround?

**Comment by larver-imvu** [comment]
Unfortunately, setting an explicit name (I used `name="green-mailer"` and `name="red-mailer"`) for each reporter does not change the behavior (on 0.9.9).

**Comment by larver-imvu** [comment]
Could it be that the new logic in e4c125a is not enough (maybe we need a `self.name = name` if `name` is not `None`)?

**Comment by larver-imvu** [comment]
FWIW, I applied the patch in `e4c125a` locally and it does indeed fix the issue! I guess setting `name=...` is a more involved problem.
