### ISSUE TITLE
Release process is broken

### ISSUE THREAD

**Issue by 0xABAB** [buildbot/buildbot#3409]
https://docs.buildbot.net/current/manual/installation/installation.html#installation-from-tarballs is not consistent with https://pypi.python.org/pypi/buildbot/0.9.9.post1 (source files are missing, there is only a wheel).

Please modify either the documentation or correct your release process to make it impossible to have such problems ever again.

**Comment by tardyp** [comment]
Sorry, buy post1 release was a bit hectic as this is the first time we have to create a post release.
I uploaded the missing tarball.

Note that in the future I would prefer a more friendly tone when reporting issues. We are all humans and can make mistake.

**Comment by 0xABAB** [comment]
@tardyp Making a mistake in human process is OK. Making the mistake of continuing to do it manually after it has been pointed out to you that you can automate the process is negligence. 

I'd appreciate a response like "Yes, we opened a ticket to make sure this won't happen again" or "We prefer to continue to make unnecessary mistakes". 

You are free to make your mistakes, but users would like to know the risks they are exposed to. 

Note, that I am not saying that buildbot hasn't been useful to some people. I also appreciate the quick feedback.

**Comment by tardyp** [comment]
The process is now fully automated (see "make release" in our Makefile)

The last stage of uploading signed packages is not as it requires my
decrypted PGP key.

For post1 I had to fix several of our setup.py, which did not support
postxx version numbers. This was unexpected and was quite upset about that.

Some of the packages worked, and were uploaded, but I couldn't re-run the
upload automatically, as pypi already had some of the package uploaded.
So during manual I missed that for some reason the buildbot tar.gz package
did not upload. I'm not sure why.

For next release I expect the automation will work again, unless there is
another release script bug, which I can only test to the end every month,
when I release.

**Comment by nand0p** [comment]
@tardyp looks like source tarballs are also missing for a few things:

https://pypi.python.org/pypi/buildbot-console-view/0.9.9.post1
https://pypi.python.org/pypi/buildbot-pkg/0.9.9.post1
https://pypi.python.org/pypi/buildbot-waterfall-view/0.9.9.post1
https://pypi.python.org/pypi/buildbot-grid-view/0.9.9.post1

do we have an automated release mechanism? or is this still manual at this point?

**Comment by tardyp** [comment]
@nand0p the post1 release only changed the buildbot package. could you rather use the 0.9.9 version for the other packages?
I am in the middle of a company move at work, so I don't have much time to work on that.

it might be easier to just create a post2,(with the automation), with the few bug fixes that went in since last week.

**Comment by tardyp** [comment]
I eventually created a post2 release. This time, the full release script succeeded so I didn't have to hack and fix stuff while the release was half uploaded.
