### ISSUE TITLE
Relax builder name length restriction

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3413]
As per http://docs.buildbot.net/latest/manual/installation/nine-upgrade.html#identifiers, builder name can be only up to 20 characters. 

This is not at all practical. For builder names to be readable, it usually contains many keywords (like platform name, os, architecture, version, type etc.). In our instance we have over 100+ builders and builder-names of upto 65 characters. Reducing them to 20 characters is just not possible.

Looking at http://trac.buildbot.net/wiki/SuccessStories, a lot of people use long builder names. Here are list of few buildbot instance and corresponding maximum builder name length:

53 characters: http://lab.llvm.org:8011/builders
52 characters: https://buildbot.openlighting.org/builders
44 characters: https://gdb-build.sergiodj.net/builders
40 characters: https://build.webkit.org/builders/
35 characters: http://testing.evergreen-ils.org/buildbot/builders
34 characters: http://buildbot.python.org/all/builders
34 characters: http://buildbot.openafs.org:8010/builders
32  characters: https://build.macports.org/builders
30 characters: https://buildbot.askmonty.org/buildbot/builders
32 characters: https://ci.apache.org/builders

Having this impractical restriction would make it more difficult for people to upgrade to buildbot 0.9 (only 1 out of ~50 buildbots linked on http://trac.buildbot.net/wiki/SuccessStories has upgraded yet).

I suggest increasing the limit to 100 (or atleast 70) characters for builder names.

**Comment by tardyp** [comment]
Having larger buildername gives more problems in term of UI. It is already quite hard to make a UI able to display up to 20 characters.
For our nine.buildbot.net, we decided to use abbreviation for our builder names. see
http://nine.buildbot.net/#/console
having 70 characters buildernames would have made this console view completly unreadable.

There are already the builder description and builder tags for the needed additional information for a builder.

actually the restriction is 50 chars as far as I can see from here: https://github.com/buildbot/buildbot/blob/master/master/buildbot/data/builders.py#L86
You can try to increase it, but I dont think it is a good idea for the above reasons

**Comment by seankelly** [comment]
I think documenting the length is actually 50 is fine. Only two Buildbot instances from the list above exceed 50 characters.

**Comment by ila321** [comment]
I think we should relax the restriction since there would be many more private Buildbot instances hitting this limit.

Also, is there really a restriction in the first place?  Builder name seems to be stored as sa.Text in db without a length restriction: https://git.io/vA8ZF
