### ISSUE TITLE
buildStarted method doesn't receive any useful information in buildbot 0.9

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3420]
When someone subscribe to methods like buildStarted, buildFinished through base.StatusReceiverMultiService, they receive a BuildStatus object containing information about the Build.

In buildbot 0.8, it used to contain a lot of useful information about the build including build properties, build number etc.

In buildbot 0.9, BuildStatus object which is received doesn't have properties at all (removed in https://git.io/vQr0e). Also, the build number seems to be always zero  (probably because of https://git.io/vQr0n). The BuildStatus doesn't even have buildid. 

I am receiving following data in buildStarted through BuildStatus object:
```
build_status.asDict(): 
'{'logs': [], 'builderName': u'My Debug TryBot', 'text': [], 'sourceStamps': [], 'results': None, 'number': 0, 'currentStep': None, 'times': (1499357455.647606, None), 'blame': [], 'reason': None, 'eta': None, 'steps': [], 'worker': '???'}'
```

Above data doesn't seems to have any information to identify the build. It just tells me that some build started. In buildbot 0.9 it used to have so much useful info.

It seems like BuildStatus class is getting deprecated (as per comment in https://git.io/vQr0e). We should pass object of build class instead of build_status to watcher in buildStarted.

buildStarted method will be useful if it has complete build information (like buildbot 0.8).

**Comment by aakashja** [comment]
Looking at https://git.io/vQrzZ , it receives Build object, but doesn’t use it at all. Instead of passing self, it should pass 'build' at https://git.io/vQrzR. And then, assert in https://git.io/vQrzS should be updated from s.builder to s.build_status.builder

**Comment by tardyp** [comment]
statusAPI is not supported in buildbot nine, so StatusReceiverMultiService will never work.
You should use the reporter API.
There are still some reliques in the code that shall be cleaned

**Comment by aakashja** [comment]
Is there a reporter API having the same (or better) functionality provided by StatusReceiverMultiService?

We have watchers which currently subscribe to buildStarted, buildFinished events using StatusReceiverMultiService and do various custom operations based on build properties.

**Comment by tardyp** [comment]
The reporter api expects a reporter to register to events, then to call the data api to get the exact info it needs. The best for doing that is to look at existing reporters. You can look at HttpStatusBase, which is pretty simple, and maybe already suit your needs as a base class for what you want to achieve.
I could provide more info if I knew exactly what is the purpose of your reporter.

**Comment by aakashja** [comment]
Thanks. It worked.

Also, I filed https://github.com/buildbot/buildbot/issues/3441
