### ISSUE TITLE
QuantifiedCode service will shutdown at 22 Juli 2017

### ISSUE THREAD

**Issue by 0xABAB** [buildbot/buildbot#3425]
FYI, see https://www.quantifiedcode.com/.

**Comment by tardyp** [comment]
@0xABAB thanks for the heads-up. I tried the service to see how much it can help. It does, but not that much more than pylint/flake8. So I understand why its owner has hardtime to make it sustainable :-(

**Comment by p12tic** [comment]
@tardyp: I see no references to this in the buildbot codebase. Maybe it makes sense to close the issue?
