### ISSUE TITLE
First Run tutorial is maybe missing something for it to work on Ubuntu 16.04

### ISSUE THREAD

**Issue by mehemken** [buildbot/buildbot#3428]
Hi All,

If this is not the right place for this, please let me know a better place to ask for help. I'm interested in helping adjust the Docs if this question uncovers anything of substance.

Disclaimer, this is my first experience with buildbot. I'm going through the [First Run](http://docs.buildbot.net/current/tutorial/firstrun.html) tutorial and I'm running into a wall before I can run the `runtests` build. As far as I can tell I'm following the instructions to the T, but **the Waterfall view is empty for me**. I've got a little more detail in this [stackoverflow question](https://stackoverflow.com/questions/45002472/buildbot-firstrun-web-ui-does-not-show-forcescheduler-in-waterfall-view). I'm running with Python 3.5.2 and I'm getting no errors anywhere.

Perhaps I'm overlooking something obvious?

Thanks,
Marco

**Comment by tardyp** [comment]
I answered in the stackoverflow question

**Comment by mehemken** [comment]
Hello tardyp, thanks for answering so quickly. However, the problem is the force button does not appear on the builder page. I apologize for the confusion. The force button does not appear anywhere in the Web UI.

Do you have any other suggestions?

**Comment by tardyp** [comment]
If you go to the home page, do you have a warning?
If you go to the chrome developer console (F12) do you see any error?

**Comment by mehemken** [comment]
Hey tardyp! I'm checking it now, let me see...

**Comment by mehemken** [comment]
The warning on the home page is always there. It says
    Warning: c['buildbotURL'] is misconfigured to
    http://localhost:8010/
    Should be:
    http://ec2-34-208-31-94.us-west-2.compute.amazonaws.com/

The F12 console says:
    WebSocket connection to 'ws://ec2-34-208-31-94.us-west-2.compute.amazonaws.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by mehemken** [comment]
However, when I fix the first error, I still don't see the runtests in waterfall or force in builders pages.

**Comment by mehemken** [comment]
The handshake error is something I have not known to look for though. What does it mean?

**Comment by tardyp** [comment]
Do you have some sort of proxy which relays port 80 to port 8010?

You need to configure it so that it correctly forward the web socket protocol.

for example:
http://docs.buildbot.net/latest/manual/cfg-www.html#reverse-proxy-configuration

**Comment by mehemken** [comment]
Thanks! I'll try this. I'll report back if I have any further issues.

**Comment by chrisvire** [comment]
Fixed by https://github.com/buildbot/buildbot/pull/3541
