### ISSUE TITLE
How to graceful shutdown one/all workers?

### ISSUE THREAD

**Issue by PunChaFeng** [buildbot/buildbot#3429]
> In previous version, like 0.8.7, there is way to graceful shutdown one workers through web UI, but in v0.9.8, I didn't find the button. Is it not implemented or removed?

The core functionality is here but not yet mapped to data API / UI.
A similar functionality is the stop build/cancel buildrequest #1656

- It is about adding 2 actions to the worker endpoint.
- In order to make multi-master work, those actions should send a message to the mq
- Then a button should be added to the UI

Work is ongoing. Remaining tasks:

- [x] DB model and API for status of worker (add paused status, shutdown status, connected status, while we are at it to avoid check for the master worker table)
- [x] Data API for status of worker (map status db api, send mq updates about them)
- [x] UI for reflecting worker status

(edited by @tardyp)

**Comment by Frodox** [comment]
I vote +1 for idea of graceful shutdown workers from cli (needed for some massive update/upgrade/host reboot/shutdown).

Currently I see only one way to gracefully stop worker - [configure it to wait for special file update or sighup](http://docs.buildbot.net/latest/manual/installation/worker.html#cmdoption-buildbot-worker-create-worker--allow-shutdown). 

Looks like `buildbot-worker stop` just kills it.

And yes, there is [note in docs](http://docs.buildbot.net/latest/manual/installation/misc.html#shutdown)

> A worker may also be gracefully shutdown from the web UI. This is useful to shutdown a worker without interrupting any current builds. The buildmaster will wait until the worker is finished all its current builds, and will then tell the worker to shutdown.

and looks like it is really outdated/not implemented for 0.9

**Comment by aakashja** [comment]
I also vote +1 for graceful shutdown feature. It was a useful feature in 0.8. I do not see this feature in 0.9. 

Same for "Pause Slave" feature.
