### ISSUE TITLE
Documentation for Pushover reporter says "sends email"

### ISSUE THREAD

**Issue by mbunkus** [buildbot/buildbot#3435]
The documentation for the [Pushover reporter](https://docs.buildbot.net/current/manual/cfg-reporters.html#pushover-notifications) talks about sending emails:

> The following simple example will send an email upon the completion of each build. The email contains a description of the Build, its results, and URLs where more information can be obtained.

It should probably talk about sending a Pushover message or something like that.

**Comment by rodrigc** [comment]
Can you submit a patch to fix this?  The text is in https://github.com/buildbot/buildbot/blob/master/master/docs/manual/cfg-reporters.rst

**Comment by mbunkus** [comment]
Sure. Here it is.
