### ISSUE TITLE
DockerLatentWorker documention inonsistent

### ISSUE THREAD

**Issue by ASMfreaK** [buildbot/buildbot#3439]
Please, add to `DockerLatentWorker` information on env variables, passed to container on launch.

**Comment by tardyp** [comment]
could your please be more specific? The documentation on environement variable is on top of the file, as it applies to all the docker related latent workers.

http://docs.buildbot.net/latest/manual/cfg-workers-docker.html#reuse-same-image-for-different-workers

**Comment by ASMfreaK** [comment]
Wow. I guess I overlooked it. Sorry about that.
