### ISSUE TITLE
Performance issues with buildbot web server

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3444]
I am noticing performance issues with buildbot web server. Opening buildbot webpages (e.g.: console view, build page, buildbot landing page) are extremely slow. Sometimes the page would load in few seconds (see screenshot), but the data would load after 20-30s (or more). Currently, there are very few users accessing these webpages.

My buildbot configuration is:
- buildbot 0.9.9.post2 (same for buildbot, buildbot-www, buildbot-console-view, buildbot-waterfall-view)
- single master
- postgresql db
- 20 builders (queues)
- 25 workers  (~1 worker per queue)
- decent hardware on master (16 gb ram, 8 cpu)

I noticed similar performance issues earlier in https://github.com/buildbot/buildbot/issues/3395, but at that time it was root-caused to large number of pending buildrequests.  In this scenario I do not have pending buildrequests.

We never had any performance issues with buildbot 0.8.12 with same configuration.

<img width="771" alt="buildbot_page_loaded_without_data" src="https://user-images.githubusercontent.com/3098702/28251374-911ffe40-6a30-11e7-88ec-4bb418cdf2ae.png">

**Comment by aakashja** [comment]
Looking at htop output, I noticed that only one the Buildbot process seems to be consuming most (~100%) of the cpu. Buildbot doesn't seems to be using all the cpu (see attached screenshot). Is there any buildbot configuration so as to use all the cpus/cores efficiently (apart from using multi-master)?
<img width="1435" alt="htop_only_one_cpu_being_used_by_buildbot" src="https://user-images.githubusercontent.com/3098702/28251409-806ee218-6a31-11e7-87e8-12016b02cbe2.png">

**Comment by tardyp** [comment]
Could you please run buildbot profiler?

https://pypi.python.org/pypi/buildbot-profiler/

Le dim. 16 juil. 2017 23:17, Aakash Jain <notifications@github.com> a
écrit :

**Comment by aakashja** [comment]
Thanks for suggesting buildbot profiler.
I rebooted the machine, so I don't have the exact performance issue right now (maybe I will see the issue again after some time).

Meanwhile, I did run buildbot profiler. Its output is below. Do you see anything unusual or any suggestions for things to debug? 

(Note: it doesn't have memory info because of https://github.com/buildbot/buildbot/issues/3445)

<img width="892" alt="buildbot_profiler" src="https://user-images.githubusercontent.com/3098702/28252740-ef02f41e-6a4d-11e7-9bdf-392359bbde82.png">

**Comment by aakashja** [comment]
Another profile. In this case I did not open any web page (However load is ~100%).

In both of these cases ~10 builders were running builds. Each build generate a lot of logs.

<img width="889" alt="buildbot_profiler_without_web_load" src="https://user-images.githubusercontent.com/3098702/28252829-18d3d3e2-6a50-11e7-9f1a-e7dac0f93731.png">


Does the red color on buildbot/db/logs.py (appendLog) indicate too much load?

**Comment by tardyp** [comment]
Looks like indeed you are reaching the limits of buildbot log storage capabilities. In my tests this only happens with huge amount of logs (~10k lines of logs /s).

You can improve the performance by:

- use pypy: you will get an improvement of ~15-20%
- use multimaster, with a master dedicated to the web UI.
- limit the logging in your builds.

**Comment by aakashja** [comment]
I was able to semi-reproduce the performance issue again (web pages were slow but not so bad).

Here are the profiles I collected. Does it indicate buildbot is spending lot of cpu in appending logs to database (and compressing logs in one instance) ?

The builds on each worker does generate a lot of logs  (~30,000 log lines / build, build takes about 15 minutes). About 20 such workers running in parallel. Is that a lot for buildbot?

Is there any postgres tuning recommended?

<img width="888" alt="buildbot_19builds_with_web_traffic" src="https://user-images.githubusercontent.com/3098702/28258681-5918c732-6a87-11e7-8e8d-e73ccd7b02e0.png">
<img width="877" alt="screen shot 2017-07-17 at 12 15 34 am" src="https://user-images.githubusercontent.com/3098702/28258682-59364c80-6a87-11e7-9324-b18b24c43b01.png">
<img width="897" alt="screen shot 2017-07-17 at 12 13 23 am" src="https://user-images.githubusercontent.com/3098702/28258683-593716f6-6a87-11e7-98ac-a56ec0189fe8.png">

**Comment by tardyp** [comment]
So you are generating about 7k lines of logs per second, which is near, but well under the limit I have measured. my bench was only doing logging, so maybe this is a reason for the difference.
In my measurement, I haven't seen big measurable UI latencies (not > 1s)

Another thing that you can try is to switch the compression to lz4. It is much more efficient.
The postgres config that I used was the default from the official docker image. It should matter that much as your cpu strike in on buildbot process, not on pg.

If you manage to reproduce the big latencies, please post the json dump, so that I can look at it in details.

**Comment by tardyp** [comment]
sorry, I messed up my calculation. you lines of log per second is:

```
>>> 30./(15*60)*20.
0.6666666666666666
```
so this is 600 lines per second, which is far away from the limit. are you using bzip2 as the compression? Please send the json so that I can look

**Comment by aakashja** [comment]
Sent you some json dumps on IRC. I switched to lz4 for log compression now.

Also, I noticed that we might be producing much more logs than I previously calculated.

Some of our builders are producing ~80,000 log lines in less than 10 minutes. Few builders also produce about ~160,000 lines in 15 minutes. There is a lot of variation from worker to worker (depending on configuration). There are about 15-20 builds in parallel.

Seems like that might be between 2000 to 4000 log lines/second (might need detailed analysis to get precise number).

**Comment by tardyp** [comment]
Can you please post the dump here?

Le mar. 18 juil. 2017 20:06, Aakash Jain <notifications@github.com> a
écrit :

**Comment by aakashja** [comment]
Seems like github doesn't support json format as attachment (gives me error: "We don’t support that file type.").

Here are the data with lz4 and gz: https://goo.gl/65aV3c

This doesn't have the performance issue reproduced, but nevertheless profiles shows load on buildbot. I will collect more profile with the performance issue reproduced.

**Comment by tardyp** [comment]
After looking at your profile, it does not look like there is something problematic. It is a rather quiet profile with less than 30% cpu most of the time.

We really need to capture an overcapacity sequence in order to really understand what happens.
2k, 4k log lines/s looks like well under my tests maximums.

**Comment by tardyp** [comment]
I just re-run my performance test at home on my 4 cores: Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz

This light system can easily absorb 23k lines of log/s

Despite high cpu load (buildbot 130% cpu, load average 6, 30 builds always running on docker all on a single machine ), the system and the web UI are very responsive.

The bench is published here:
https://github.com/tardyp/ci_perfs/tree/master/single_master

**Comment by aakashja** [comment]
I also think that the root-cause of the performance issue I am seeing is not the log processing. I did switched to lz4 yesterday and it seemed to help, but I noticed the performance issue again this afternoon.

Also, I noticed that when the performance issue happened today, there were only 10 builds running. However, after some time, even with 15 builds buildbot was extremely fast. So, buildbot seems to be easily handling the amount of logs we are generating. 

Fortunately, I was able to run buildbot profiler at the time when the performance issue reproduced (extremely slow webpages). Here are the profiles: https://goo.gl/oCzfo2

It contains three profiles: two profiles with the issue reproduced, and one profile after some time when buildbot was fast again.

Is there any  periodic tasks (like cronjob) run by buildbot (maybe some periodic cleanup or optimization)? 

Hopefully the profiles would give us more insight. Can you please have a look?

**Comment by seankelly** [comment]
There is a janitor that will prune logs but I don't think it's set up by default.

**Comment by tardyp** [comment]
I published a new 1.1.1 version of buildbot_profiler. You can now install it on prod without the UI.
it will dump a json file every 30min. You can enable and disable via reconfig.

see details at:

https://pypi.python.org/pypi/buildbot-profiler/

**Comment by aakashja** [comment]
Thanks for the improvements in Profiler. However, it seems to be almost unusable in Service mode because of https://github.com/buildbot/buildbot/issues/3504

**Comment by aakashja** [comment]
Can the performance issue be due to Twisted Reactor 'epoll'? Can changing it from 'epoll' to 'select' make a significant difference?

**Comment by seankelly** [comment]
`epoll` was created to replace `select` because the design of `select` can't scale well. My guess is you won't see much difference but more likely that `select` will be slower.

**Comment by tardyp** [comment]
after analysing the profile, and fixing some issues with the profiler. 
I saw that the master spends lots of time in LineBoundaryFinder.

Meanwhile, @aakashja found out a buggy step which flood stdout with status lines using backspace (\b), without first making sure the stdout is a terminal (ispty).
I created bug https://github.com/buildbot/buildbot/issues/3517 to fix the issue

**Comment by aakashja** [comment]
Thanks a lot @tardyp  for the fix.
I applied the changes from https://github.com/buildbot/buildbot/issues/3517 on my local instance and it works very well :)
