### ISSUE TITLE
Documentation wrong - GitHubAuth (and any using oauth2?) requires requests

### ISSUE THREAD

**Issue by samizzo** [buildbot/buildbot#3455]
I get `ImportError: No module named requests` when using GitHubAuth on 0.9.9post2. I was using 0.9.8 (or 
 maybe 0.9.7) previously and it was working. The documentation mentions this for GoogleAuth but not GitHubAuth.

**Comment by rodrigc** [comment]
@samizzo How did you install buildbot?

**Comment by samizzo** [comment]
With `pip install 'buildbot[bundle]' --upgrade`.

The docs specifically mention to `pip install requests` for GoogleAuth.

**Comment by rodrigc** [comment]
Sounds like the docs and maybe some of the dependency information inside setup.py needs to be updated.  Did you install this on a bare system or inside a virtualenv?

**Comment by samizzo** [comment]
This was inside a virtualenv.

**Comment by rodrigc** [comment]
Thanks for providing all the info.  I need to see what the approach should be.  `requests` is only used in a few places in buildbot.  `txrequests` and `treq` are libraries similar to `requests`, but are asynchronous, and also used in buildbot.
@tardyp do we want to add `requests` to the default dependencies, or change the code to use `treq` or `txrequests`?

**Comment by tardyp** [comment]
all the oauth implementations require requests. Indeed this might be better documented (PR welcome!)

We try to maintain the dependency list minimal in setup.py, this is why for some component we require people to add additional dependencies.

I doubt the ``pip install --upgrade buildbot[bundle]``of a virtualenv would break a working install. There might have been something else done during the upgrade.
