### ISSUE TITLE
how can I pass filelist of a build to mailnotifier?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3456]
I use `P4` as CVS and plan to send mail when builds finish. In a buildstep, I can use `self.build.allFiles(`) to get the filelist but I couldn't figure out a way to do so in the mailnotifier.

**Comment by tardyp** [comment]
The reporters need to use the data api in order to fetch the needed values.

```
changes = yield self.master.data.get("builds", buildid, "changes")
files = []
    for c in changes:
        files.extend(c['files'])
```
