### ISSUE TITLE
latentworker cannot escape "preparing worker" if the worker created but never connects

### ISSUE THREAD

**Issue by jonnyyu** [buildbot/buildbot#3459]
in some edge case, the created worker did created, so the code returns from substantiate method and starts waiting for attached event.

but for some various reasons, the worker didn't launch successfully, thus it didn't connect back to buildbot master.  In this situation, this build seems stuck waiting for the worker to connect forever, without any timeout mechanism.

**Comment by tardyp** [comment]
There is a missing_timeout that the latent worker are using to detect if the latent fail to connect. which latent worker are you using?

**Comment by seankelly** [comment]
And what version of Buildbot?

**Comment by jerrykan** [comment]
I'm seeing this problem with the `DockerLatentWorker` in buildbot v0.9.10.

The build seems to try and continue forever and even clicking on cancel doesn't stop it.

**Comment by jstacoder** [comment]
👍🏼

**Comment by vdsbenoit** [comment]
I have the same kind of issue with Buildbot Travis. I use Docker for my latent workers. 

I have a spawner job that runs 4 build jobs. Systematically at least 1 of the 4 latent workers fails at creating a container. The job is stuck on "preparing worker" and there is no way to manually stop the build (stop button has no effect). The build is cancelled after 1h timeout (very long).

![image](https://user-images.githubusercontent.com/44053930/60273910-6c21a880-98f7-11e9-9c3b-7cff517209a4.png)

This happens only with Windows Docker containers. When I perform a `docker ps` I can see that only 3 containers exist while the 4th job is still stuck on "preparing worker". 

Maybe Buildbot could try to create another container if it receives no responses from Docker. Or at least, there could be a way to force a build stop.

Here is my configuration:
Buildbot version: 2.0.1
Twisted version: 18.9.0
Buildbot-travis version: 0.6.4 
Docker Windows Server version: 18.09.2, build 6247962

**Comment by vdsbenoit** [comment]
The hard fix on my side was to set the DEFAULT_MISSING_TIMEOUT in AbstractWorker to 60. 

After 60 seconds, Buildbot try to create the container again, and it works.

**Comment by tardyp** [comment]
This can happen if the docker container does not start correctly, cannot
contact the master, etc.
The missing timeout is used for that kind of issue as well.

So this is usually an infra issue that you need to try and debug.
You can look at the container list on your docker machine and look at the
log to see any issue
docker ps
docker logs
etc.

Pierre

**Comment by vdsbenoit** [comment]
Hi Pierre,

Thank you for your reply. Actually, I can't read the logs of these containers as I don't see them in the `docker ps -a` list. I guess Buildbot removes the exited containers from the container list or uses the --rm parameter when launching a container. Therefore, I don't know if the containers are quickly created and then removed due to a bug or if they either are never instantiated.

**Comment by p12tic** [comment]
I think this has been fixed in #5599.
