### ISSUE TITLE
Waterfall view should be filterable by tags

### ISSUE THREAD

**Issue by jangmarker** [buildbot/buildbot#3471]
Similar to #3470 the waterfall view would be more useful in large buildbot configurations if it could be filtered by tags.

**Comment by tardyp** [comment]
grid view already implements this. This should be easy to port

**Comment by alorbach** [comment]
Any news on this? 
I would really like to be able to filer by tags like in old buildbot 0.8

**Comment by tardyp** [comment]
@alorbach nobody has taken the ticket AFAIK. Feel free to help. Here is a tutorial that should put you on the right direction:
https://medium.com/buildbot/buildbot-ui-plugin-for-python-developer-ef9dcfdedac0

**Comment by alorbach** [comment]
Thanks for the details.

**Comment by mojca** [comment]
This seems to be the same as #2892.

**Comment by rajdeepbharati** [comment]
@p12tic @jangmarker Do you want me to add negative filtering too, like in https://buildbot.buildbot.net/#/builders ?

**Comment by p12tic** [comment]
@rajdeepbharati I think negative filtering makes sense, but I guess that's low priority.
