### ISSUE TITLE
Waterfall view: status indicator bar of builders is hard to read

### ISSUE THREAD

**Issue by jangmarker** [buildbot/buildbot#3475]
The colorful bars in the screenshot below are tiring to read, especially if red and orange bars are right next to each other.
![spectacle q10081](https://user-images.githubusercontent.com/6429953/28609419-36101a04-71aa-11e7-8c4b-32dd823686eb.png)

Suggested solution:
They could be larger or the builder names could have a background of the indicator's color.

**Comment by tardyp** [comment]
looks like an easy fix. would you like to take a look at it?
https://medium.com/buildbot/buildbot-ui-plugin-for-python-developer-ef9dcfdedac0
