### ISSUE TITLE
[docs] Add example how to create API-call to trigger ForceScheduler

### ISSUE THREAD

**Issue by Frodox** [buildbot/buildbot#3479]
According to [docs](http://buildbot.readthedocs.io/en/latest/developer/rest.html#id13) my request is:
```
$ curl -d '{"method": "force", "owner":"t <t@test.com>", "jsonrpc": "2.0", "id":843, "params":{"project":"group/project", "username":"t <t@test.com>"} }' -H "Content-Type: application/json"  -X POST http://bb-master/api/v2/forceschedulers/force-scheduler:force
```
where `force-scheduler` - name of my scheduler. But I get an error:
```
{"jsonrpc": "2.0", "id": 843, "error": {"message": "Invalid path: forceschedulers/force-scheduler:force", "code": -32600}}
```

The only example I find - @tardyp 's [ci_perfs](https://github.com/tardyp/ci_perfs/blob/7b86295b7478ed7d6299b0f4d0034ff2643de737/stress.py#L26), but it uses non-doc URL and there is no scheduler name, so I can't understand how it working.

**Comment by tardyp** [comment]
You should remove :force in the end...

**Comment by Frodox** [comment]
AAaaaaahhh... ok, now much better, thank you :D Looks like docs need to be fixed. Now I can't set `project` to `group/project` ...

my scheduler:
```python
...
codebases=[
        util.CodebaseParameter(
            "",
            name="Repository credentials",
            repository=util.FixedParameter(name="repository", default=""),
            branch=util.FixedParameter(name="branch", default=""),
            revision=util.FixedParameter(name="revision", default=""),

            project=util.StringParameter(
                name="project",
                label="group/project:",
                size=100,
                required=True,
                regex='.+/.+',
), ),  ],
...
```

and curl:
```
$ curl -d '{"method": "force", "owner":"t <t@test.com>", "jsonrpc": "2.0", "id":843, "params":{ "project":"mygroup/myproject", "username":"t <t@test.com>"} }' -H "Content-Type: application/json"  -X POST http://bb-master/api/v2/forceschedulers/force-scheduler

# answer
{"jsonrpc": "2.0", "id": 843, "error": {"message": {"Repository credentials_project": "'group/project:' needs to be specified"}, "code": -32602}}
```

Should do I url-encode every params, so they would be url-decoded? Or, what can be wrong here..?

P.s. when actual `id` value in jsonrpc request would be important here?

**Comment by Frodox** [comment]
I know, it fails on [`collector.maybeRaiseCollectedErrors()`](https://github.com/buildbot/buildbot/blob/a3c65326c9f7ecd716dcddf2608105baf8b3ae07/master/buildbot/schedulers/forcesched.py#L790), and there is my data actually in `buildbot/data/forceschedulers.py` side:
```
74          except forcesched.CollectedValidationError as e:
 75                 print("FAIL: self: {}".format(self))
 76                 print("FAIL: action: {}".format(action))
 77                 print("FAIL: args: {}".format(args))
 78                 print("FAIL: kwargs: {}".format(kwargs))
 79                 print("FAIL: sched: {}".format(sched))
 80                 print("FAIL: msg: {}".format(str(e)))
...

2017-07-28 18:30:15+0300 [-] FAIL: self: endpoint for 
2017-07-28 18:30:15+0300 [-]         /forceschedulers/i:schedulername
2017-07-28 18:30:15+0300 [-]     
2017-07-28 18:30:15+0300 [-] FAIL: action: force
2017-07-28 18:30:15+0300 [-] FAIL: args: {u'project': u'mydesiredproject', 'owner': 'anonymous', u'variation_id': u'antares-amd64'}
2017-07-28 18:30:15+0300 [-] FAIL: kwargs: {'schedulername': 'force-scheduler'}
2017-07-28 18:30:15+0300 [-] FAIL: sched: <buildbot.schedulers.forcesched.ForceScheduler object at 0x7f44f4865590>
2017-07-28 18:30:15+0300 [-] FAIL: msg: Repository credentials_project:'group/project:' needs to be specified
```

so, look like problem call is [`gatherPropertiesAndChanges`](https://github.com/buildbot/buildbot/blob/a3c65326c9f7ecd716dcddf2608105baf8b3ae07/master/buildbot/schedulers/forcesched.py#L787)

and after little debugging looks like there is bug in it.
I see my data in kwargs
```
734         print('DBGP-0: kwargs: {}'.format(kwargs))
..
DBGP-0: kwargs: {u'project': [u'myproject'], u'repository': [u'myrepo'], u'branch': [u'test-branch'], u'variation_id': [u'some-extra-property']}
```

but after calling [`collector.collectValidationErrors`](https://github.com/buildbot/buildbot/blob/a3c65326c9f7ecd716dcddf2608105baf8b3ae07/master/buildbot/schedulers/forcesched.py#L735)

the sourcestamp doesn't have such info. Plus *requred* argument just disappear from sourcestamp!
```
746         changeids = [type(a) == int and a or a.number for a in changeids]
747 
748         print('DBGP-1: sourcestamp: {}'.format(sourcestamps))
...
DBGP-1: sourcestamp: {'': {'project': '', 'branch': '', 'revision': ''}}
```
(in this test I mark repository as required. In prev one *project* was required)

**Comment by Frodox** [comment]
Ok, I got it. For my ForceScheduler there is problem with [this line](https://github.com/buildbot/buildbot/blob/a3c65326c9f7ecd716dcddf2608105baf8b3ae07/master/buildbot/schedulers/forcesched.py#L146), because `fullName` in this case is `Repository credentials_repository`, but not `repository` as I expect and sends in API call. So [this test](https://github.com/buildbot/buildbot/compare/master...Frodox:frodox/fix-force-scheduler-api-call-bug) would fail now. How should it be fixed? What is `name` argument actually for?

**Comment by Frodox** [comment]
So, something like 
```bash
curl -d '{"method": "force", "jsonrpc": "2.0", "id":843, "params":{ "Repository credentials_repository":"git@gitlab...git"... } }' -H "Content-Type: application/json"  -X POST http://bb-master/api/v2/forceschedulers/force-scheduler
```

works fine in this case. But I spend 4 days to figure it out! :)

**Comment by lancelodliu** [comment]
According to [doc](http://buildbot.readthedocs.io/en/latest/developer/rest.html#id13), When I tried to trigger the forcescheduler `ForceBuild_Scheduler` by REST API, I got a error messsage:
![image](https://user-images.githubusercontent.com/19603852/29763742-05a6c404-8c07-11e7-8a58-8fc2f08dc712.png)
P.S.: The `get` request is ok:
![image](https://user-images.githubusercontent.com/19603852/29763800-4218a81c-8c07-11e7-95dc-adfa71ccbb8d.png)
@tardyp Could you take a look at this?

**Comment by lancelodliu** [comment]
Oh, sorry, I forgot to enable the `allowed_origins` in `www` section.

**Comment by tardyp** [comment]
fixed in https://github.com/buildbot/buildbot/commit/73a5fb92b6ea59696895f3b81f7dbdf84805c535

**Comment by Frodox** [comment]
Not exactly, but ok. I want to add api call example to api docs

**Comment by Frodox** [comment]
@lancelodliu it is interesting that I needn't to specify `allowed_origins` for ForceScheduler before. But since some moment I'm getting an error in web UI 'invalid origin', but cli-api works fine
