### ISSUE TITLE
GitHubPullrequestPoller docs reference obsolete project attribute

### ISSUE THREAD

**Issue by asomers** [buildbot/buildbot#3481]
Change e908d9d77ef5c7894b3a6c42cca4ba8f00a67ee3 removed the `project` attribute from `GitHubPullrequestPoller`.  However, the documentation still references this attribute.  It should be removed.
https://docs.buildbot.net/current/manual/cfg-changesources.html#id40

**Comment by rodrigc** [comment]
Can you submit a pull request against https://github.com/buildbot/buildbot/blob/master/master/docs/manual/cfg-changesources.rst to fix this?
