### ISSUE TITLE
P4 with python 3.6 under windows fails on worker

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#3493]
Trying to migrate from python 2.7 to python 3.6 on worker and getting following error in Perforce sync command:

'b'p4'' is not recognized as an internal or external command,
operable program or batch file.

Which is interesting because the command is

b'p4' b'-p' b'192.168.1.10:4000' b'-u' b'ABC' b'-c' b'ABC-buildbot09-build-targets' b'client' b'-i'
 in dir D:\buildbot\build-targets\build (timeout 1200 secs)
 watching logfiles {}
 argv: [b"b'p4'", b"b'-p'", b"b'192.168.1.10:4000'", b"b'-u'", b"b'ABC'", b"b'-c'", b"b'ABC-buildbot09-build-targets'", b"b'client'", b"b'-i'"]
 writing 547 bytes to stdin
 using PTY: False

Which has doubly-quoted binary items here.

Not sure if the problem is the binary string or something else. Master is running 3.4.3

**Comment by sphet** [comment]
I found that if I modified line 245 in buildbot/p4.py  which reads:

 command = [encodeArg(c) for c in command]

and simply don't encode each argument the problem is fixed.

However, I suspect this would break python 2.7.

Any ideas?

**Comment by rodrigc** [comment]
I think your patch is on the right track.

Can you try your patch in python 2 and python 3 setups and verify if it works with perforce?
I don't have an actual p4 environment to test against.

Alternatively, if you can give me some quick steps I can do to set up p4 to test, I can try that.

**Comment by seankelly** [comment]
I think `encodeArg` isn't doing it right then. I last touched that line, but it was there before so I don't know the original reason.

**Comment by sphet** [comment]
@seankelly I am no python expert but I wonder if the encodeArg is there to handle unicode strings in some of the client names, etc. In 2.7 it would need to be encoded as ascii, but in 3.x the encode is making it a byte-string which I think needs to be decoded as ascii. Other commands in p4 in the same file have no such encoding.

@rodrigc I don't have python 2 setup here anymore - but I think it would be moot test for me - we don't have utf-8/multibyte client or machine names here since we are in North America. The concern would be more with langues that use unicode to handle accents or non-latin text.

Maybe someone who knows more about this can decide what to do -- I suspect we need to decode the resulting byte string into ascii but I have not use 2.7 for a looonnng time.

**Comment by seankelly** [comment]
I am wondering if `encodeArg` is needed. The rest of the source steps aren't doing the same thing. GitPoller, SVNPoller, and P4Poller all use `encodeArg`/`encode`, but HgPoller doesn't.

**Comment by seankelly** [comment]
Are you using P4Poller to monitor changes too?

**Comment by sphet** [comment]
Yes. It works fine. The initial p4 -V is fine too. Its simply the final
command is doubly encoded.

**Comment by sphet** [comment]
@rodrigc The existing function in util was only used by perforce, so I thought bringing it local to perforce made more sense. I will admit I failed to delete the now-unused item in perforce. Can you point me to 'one of the existing functions' to use?

**Comment by rodrigc** [comment]
@asomers can you provide me with a very small recipe for creating a Perforce repository which can be polled with buildbot with this: http://docs.buildbot.net/latest/manual/cfg-buildsteps.html#p4

I want to try to fix some of the issues preventing this from working with Python 3

**Comment by bdbaddog** [comment]
Wow.. I went to look at perforce docs (which used to be well organized) and they've degraded significantly. I did p4 admin work a while back.

**Comment by bdbaddog** [comment]
O.k. look at this page:
http://answers.perforce.com/articles/KB/2451?startURL=%2Farticles%2FKB_Article%2FExample-Unix-Installation

And:
http://answers.perforce.com/articles/KB/2439

I think the latter may be what you want.

**Comment by seankelly** [comment]
I've been working on this off-and-on and have something that can create a repository that Buildbot can poll. This is what I have in a Dockerfile:

    /opt/perforce/sbin/configure-helix-p4d.sh master -n -p 1666 -r /srv/perforce/master -u super -P SuperSuper
    echo 'SuperSuper' | p4 login
    p4 configure set security=0
    p4 depot -i < /root/perforce/test-depot
    p4 client -i < /root/perforce/client
    mkdir -p /root/work/test
    cd /root/work/test
    echo 00 > 00
    P4CLIENT=buildbot_test p4 add 00
    P4CLIENT=buildbot_test p4 submit -i < /root/perforce/submit
    p4dctl stop -a

The redirected files aren't important. So long as an editor is set, Perforce will open something usable.

**Comment by asomers** [comment]
@rodrigc I'm travelling right now, but I can give it a shot next Thursday if you haven't solved it yet.

**Comment by sphet** [comment]
Thanks for following up on this.

**Comment by rodrigc** [comment]
I created a perforce repository by doing:
```
export P4HOST=localhost
export P4PORT=1666
mkdir /tmp/sample-p4-repo
p4d -r /tmp/sample-p4-repo
```

On client, I was able to do:

```
export P4HOST=localhost
export P4PORT=1666
p4 info
```

In master.cfg, I was able to add:

```
p4source = changes.P4Source(p4base='//depot/project/', 
                                                     p4port="localhost:1666",
                                                     pollInterval=15, pollAtLaunch=True,
                                                     split_file=lambda branchfile: branchfile.split('/',1))
c['change_source'].append(p4source)
```

What else do I need in master.cfg to get this to work?

**Comment by sphet** [comment]
The problems I had were not from the change_source, but actually from the
sync command issues by steps.P4:

 steps.P4( ) - it was the sync operation that caused it.

**Comment by rodrigc** [comment]
OK, I added a steps.P4 to my master.cfg, and I have a working setp where I can reproduce your problem.

**Comment by rodrigc** [comment]
I see the problem.  One place where the double encoding is here:
https://github.com/buildbot/buildbot/blob/v0.9.9/worker/buildbot_worker/util/__init__.py#L75

**Comment by rodrigc** [comment]
https://github.com/buildbot/buildbot/pull/3543
