### ISSUE TITLE
How to get BooleanParameter value set in a buildstep or buildfactory?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3496]
I want to include several build steps if the `BooleanParameter` is set to `True` in the `ForceScheduler`. How to achieve this?

**Comment by Frodox** [comment]
I think it should be accessible as property in build env. And you can add some steps with [`doStepIf`](http://docs.buildbot.net/latest/manual/cfg-buildsteps.html#common-parameters) renderable function

And via `step.build` you would get  buildbot.process.build.Build object, and then `step.build.properties` should contain dict with props. 

Here is my example of using doStepIf:
```python
def bb_master_files_changed(step):
    files = step.build.allFiles()
    for f in files:
        if f.startswith(u'buildbot/'):
            print("Triger bb-master restart due to file changed: {}".format(f))
            return True

    return False
```

**Comment by lancelodliu** [comment]
My case is the `ForceScheduler` is depended by a `Dependent` scheduler and the choice of `Step` is made in the `Dependent` scheduler. I have tried `build.properties` and there's no BooleanParameter info. But I do find something in `buildrequest.options`. However I dont think it is the right way to do so.

**Comment by lancelodliu** [comment]
if you use a nested param, then the config will be set to property as a option object which contains the nested config.
