### ISSUE TITLE
Clarify Gitlab change_request secret expectation

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3506]
Hi,

I noticed that my secret was not working. I had this in my config:
```
           'change_hook_dialects': { 'gitlab': { 'secret': 'UOziotZbojm' } }
```

However, asking gitlab to send this secret was resulting in `Invalid secret`. I added a couple of log messages in `gitlab.py`:
```python
        if expected_secret:
            received_secret = request.getHeader(_HEADER_GITLAB_TOKEN)
            log.msg('Received secret: "{}"'.format(received_secret))
            log.msg('Expected secret: "{}"'.format(expected_secret))
            if received_secret != expected_secret:
                raise ValueError("Invalid secret")
```

And I see the problem:
```
2017-08-10 15:55:51+0200 [_GenericHTTPChannelProtocol,0,127.0.0.1] Received secret: "b'UOziotZbojm'"
2017-08-10 15:55:51+0200 [_GenericHTTPChannelProtocol,0,127.0.0.1] Expected secret: "UOziotZbojm"
```

What's the expectation here? Certainly not that the user should specify a bytestring given the documentation shows:
```python
c['www'] = dict(...,
    change_hook_dialects={
        'gitlab' : {
            'secret': '...',
        },
    },
)
```

We either change the documentation, or convert the bytestring to a string before comparison. What's the consensus on this? I am happy to provide a patch either way.

**Comment by pmatos** [comment]
And if I setup secret to be a bytestring the next issue is:

```
Hook executed successfully but returned HTTP 400 Error loading JSON: the JSON object must be str, not 'bytes'
```

I assume there was a change from Python 2 to Python 3 which converted strings to bytestrings and buildbot didn't catch up yet...

**Comment by seankelly** [comment]
What version of Python are you using?

**Comment by pmatos** [comment]
```
Python version: 3.5.2
Buildbot version: 0.9.10
Twisted version: 17.5.0
```

**Comment by tardyp** [comment]
can you repro using 2.7?

**Comment by pmatos** [comment]
Easier than expected. This doesn't happen with 2.7.11. I setup locally a buildbot master with `2.7.11`, changed  `c[www]` from the sample configuration file to:
```
c['www'] = dict(port=8010,
                plugins=dict(waterfall_view={}, console_view={}, grid_view={}),
                change_hook_dialects={ 'gitlab': { 'secret': 'UOziotZbojm' } })
```

Then I started `master` and did:
```
$ curl -H "Content-Type: application/json" -H "X-Gitlab-Event: Push Hook" -H "X-Gitlab-Token: UOziotZbojmVcV8OZQp6njZGFZsxu07uX8V3D49vYJgRsOGVC6Fz6UiziZQMqYbv" localhost:8010/change_hook/gitlab
Error loading JSON: No JSON object could be decoded
```

This is what you would expect when the secrets match.

**Comment by rodrigc** [comment]
For `request.getHeader()` there are two things to note:
  (1)  the argument to `getHeader()` must be  of type`bytes`
  (2)  the return value to `getHeader()` must be of type `bytes`

Obviously this is a source of py2 vs. py3 behavior in buildbot.
I cleaned up a lot of these cases during py3 porting, but I probably missed a few places, such as this one.

I don't have all the various setups to test, so appreciate feedback from users like you.

On a further note, my feeling is that in `master.cfg`, we should avoid requiring the user to prefix strings with `b''"` if they never had to do this before.  This would be a big headache for upgrading.

**Comment by rodrigc** [comment]
@pmatos please try this patch https://github.com/buildbot/buildbot/pull/3515/commits/79a35c59f49e90003208f2d43db31b6f46f774df and report back.  Thanks.

**Comment by rodrigc** [comment]
This should be fixed in https://github.com/buildbot/buildbot/pull/3515

Please try with latest buildbot from git and confirm that the fix works for you.

**Comment by rodrigc** [comment]
Fixed in https://github.com/buildbot/buildbot/pull/3515
