### ISSUE TITLE
ShellMixin destroys log obfuscation

### ISSUE THREAD

**Issue by mkter** [buildbot/buildbot#3510]
The ShellMixin class is currently not maintain obfuscated command arguments.
The recommended way for log obfuscation in the latest documentation is to use a tuple, e.g. ['print', ('obfuscated', 'password', 'dummytext')].

If you pass this list to ShellMixin as recommended in the documentation for new style build steps, this list will be flattened. As a result ['print', 'obfuscated', 'password', 'dummytext'] will be executed and logged.

The root of all evil lies in buildbot-0.9.10\buildbot\process\buildstep.py:1210
kwargs['command'] = flatten(kwargs['command'], (list, tuple))

It seems reasonable to flatten a possibly malformed list, but in this case it violates documentation procedures.

Best regards, 
Michael

**Comment by tardyp** [comment]
@mkter can you point the relevent documentation about that?

The recommended way to obfuscate passwords is now to use the secret manager
http://docs.buildbot.net/latest/manual/secretsmanagement.html

The tuple based obfuscation is still supported for legacy reason. You should not rely on it for new code.

**Comment by mkter** [comment]
I found it in the documentation for the RemoteShellCommand, which still seems supported for me.
http://docs.buildbot.net/latest/developer/cls-remotecommands.html (last paragraph)

If this style is not supported anymore, one should add a link to the secret management in that paragraph.

**Comment by tardyp** [comment]
Would you like to submit a pr with a sentence that this shelf is deprecated?

Le sam. 12 août 2017 15:32, Michael Reinhardt <notifications@github.com> a
écrit :
