### ISSUE TITLE
Reporter api doesn't work in multi-master mode

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3513]
I tried a very simple multi-master setup, with one master handling just the web server and another master handling rest of the stuff, both on the same machine.

However, the reporter api stopped getting any events as soon a switched to multi-master mode.  I tried to configure all the three combinations (only first master, only second master and both master registering to get reporter api events) , but none of them worked.

I switched back to single master and the reporter api started getting events again.

**Comment by tardyp** [comment]
hi @aakashja several companies have been using multimaster for a while. Reporter api is a very basic feature that shall work, provided multimaster is correctly configured.

For events to be properly forwarded between master, you need to use wamp mq protocol and setup a crossbar server.
Probably this is something not configured properly.

For other possible misconfiguration, I would need more details on your configuration.

**Comment by aakashja** [comment]
It was a configuration issue. It would be great if there is a setup guide for multi-master configuration.

**Comment by Frodox** [comment]
@aakashja
Could you share main points now, like newbie who just configured it?

**Comment by ivanov17** [comment]
> It was a configuration issue

@aj062 Exuse me, do you remember what the configuration problem was?

I'm trying to play with a similar multi-master setup that has one UI master and one buildmaster. So, I have a similar problem. I see in logs that the UI master connects to the websocket port, but the buildmaster does not. Buildmaster receives changes, but doesn't start a scheduler.  I have no idea why.
