### ISSUE TITLE
How to serve web behind nginx?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3516]
I want to make buildbot serve at `127.0.0.1:8010` and use nginx to redirect `http://www.outside.com/buildbot/` to it. However, to achieve this, I have to configure master.cfg as below:
```
c['buildbotURL'] = "http://127.0.0.1:8010/"
```
Unfortunately, this config is used to generate mail as `{{ build_url }}` which makes all the urls wrong.
Is there a workaround?

**Comment by lancelodliu** [comment]
I have found a tutial here: http://docs.buildbot.net/current/manual/cfg-www.html#reverse-proxy-configuration.
But I could not see the `builds` and chrome gave me this error:
`WebSocket connection to 'ws://xxx.yy.com/buildbot/project/ws' failed: Connection closed before receiving a handshake response`

**Comment by tardyp** [comment]
@lancelodliu Are you sure you correctly followed the tutorial?
This error usually means you forgot the lines about ws


        # required for websocket
        location /buildbot/ws {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:5000/ws;
            # raise the proxy timeout for the websocket
            proxy_read_timeout 6000s;
        }

**Comment by lancelodliu** [comment]
@tardyp Yes. But the `Builds-Builders` tab is 
```
    server {                                                                                                                                                                              
        listen       80; 
        server_name  asgtt.oa.com;

        # buildbot-qsm
        location /buildbot/qsm/ {
            proxy_http_version 1.1;
            proxy_pass         http://127.0.0.1:8010/;
            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }   
        location /buildbot/qsm/sse/ {
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_pass http://127.0.0.1:8010/sse/;
        }   
         # required for websocket
        location /buildbot/qsm/ws {
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_pass http://127.0.0.1:8010/ws;
             # raise the proxy timeout for the websocket
             proxy_read_timeout 6000s;
        }   
```
And my master.cfg is:
```
c['buildbotURL'] = "http://asgtt.oa.com/buildbot/qsm/"

# minimalistic config to activate new web UI
c['www'] = dict(port="tcp:8010:interface=127.0.0.1",
                plugins=dict(waterfall_view={}, console_view={}))
```

**Comment by lancelodliu** [comment]
And I can access to `http://asgtt.oa.com/buildbot/qsm/ws`. But the ws error still happens.
![image](https://user-images.githubusercontent.com/19603852/29264985-d0a4cce2-8111-11e7-9a66-da0b4e631177.png)

**Comment by tardyp** [comment]
I think this is a problem of config of nginx, even though I can't point it.
If the ws socket is not happening properly, then the UI will not display anything.

Maybe some nginx expert can point out the difference between our working example and your modified version.

maybe you should copy all the headers into each sub location (which is done globally in the example config)

```
        proxy_set_header HOST $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-Server  $host;
        proxy_set_header X-Forwarded-Host  $host;
```

**Comment by lancelodliu** [comment]
I tried add all the headers but it doesnt work. If I doesnt use nginx, the web works fine. So the problem must be the nginx rp.

**Comment by tardyp** [comment]
@lancelodliu did you finally manage to fix the nginx config?

**Comment by lancelodliu** [comment]
@tardyp It turns out that the gateway is not dealing with the websocket well.

**Comment by tardyp** [comment]
@lancelodliu what gateway? you mean nginx? or another thing specific to your own network? Can you close the bug if this is your  internals?

**Comment by lancelodliu** [comment]
@tardyp It's a private gateway.

**Comment by tardyp** [comment]
You can try https. It usually works better with Corp proxies
