### ISSUE TITLE
Builds column on builders page doesn't display recent builds for many builders 

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3545]
builder page (e.g.: https://nine.buildbot.net/#/builders) displays the recent builds corresponding to each builder. However, for many of the builders, this column is empty, even though the builder have many builds in the past.

In below screenshots builds are not displayed for many builders (e.g.  "buildbot py:3.6 sqla:l t:trial tw:trunk"). This seems to happens more frequently for the builders whose last build was little old as compared to rest of the builders. In these screenshot, the last build was few months ago, but this happens in many other cases as well. Build info would be missing for builders which had last build few hours ago, if there are many other builders which had their last build few minutes ago.

<img width="909" alt="screen shot 2017-08-19 at 8 03 52 am" src="https://user-images.githubusercontent.com/3098702/29487944-68abc296-84b6-11e7-8529-e16886456291.png">

<img width="785" alt="screen shot 2017-08-19 at 8 04 16 am" src="https://user-images.githubusercontent.com/3098702/29487950-81a6e29e-84b6-11e7-8c7b-2e2d3634d4c0.png">

Missing this important information makes it very hard to look at the builder page and see status of all the builders. In Buildbot 0.8, builders page always displayed last build of every builder.

**Comment by aakashja** [comment]
Is there a overall limit of 200 recent builds across all builders? 
as defined here: https://git.io/v5fnk

**Comment by aakashja** [comment]
This will be an issue on any buildbot instance have large number of builders. Even on https://nine.buildbot.net/#/builders with 50+ builders, this is clearly an issue.

Ideally, recent build information should be fetched and displayed for every builder. But if it affects performance significantly, then  instead of a fixed number '200', a multiple of NUMBER_OF_BUILDERS should be used (e.g.: 15 x number_of_builders).

**Comment by tardyp** [comment]
Indeed, in order to reduce the number of data api needed to display the builder page, we choose to only display the 200 last builds.

We should have this value configurable like we do for the other dashboards. I dont think we should try to be too smart at multiplying the number of builders. There are too many usecases this could hurt

**Comment by aakashja** [comment]
Yeah, having this value configurable in settings (or master.cfg) file would be good.

For now, how can we change this value in our CI. By using custom template?

**Comment by tardyp** [comment]
you can't really, as it is hardcoded in the coffeescript :-(

If you are really despaired, you can still try to find the string 'getBuilds(limit: 200' in scripts.js inside the virtualenv, and replace it with what you want, but please don't tell this was my idea 💩

**Comment by sphet** [comment]
I agree that having the default configurable from master.cfg would be great - it's too hard to explain to our large team why things are missing. Any chance this could happen?

**Comment by aj062** [comment]
https://github.com/buildbot/buildbot/commit/fcb1491223c079575d402dbbf0daca27e23c39d9 made the value 200 configurable in settings.

However, each user still need to configure it themselves. Explaining this Buildbot bug and need for this setting to each user of Buildbot is very difficult. This setting should be controlled by the admin, either through master.cfg file or a better default value.

The default value is still 200 which is very low for medium/large size instances. Each builder displays 20 build, even a small instance of 10 builders would need 200 builds. https://nine.buildbot.net/#/builders itself has this issue.

Default value should be increased to something like 15*number_of_builders

**Comment by aj062** [comment]
https://github.com/buildbot/buildbot/pull/3924 let us configure this value in master.cfg using 

c['www']['ui_default_config'] = { 
    'Builders.buildFetchLimit': 1000
}

Thanks @tardyp for the making the change.
