### ISSUE TITLE
Builder page should show the worker information

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3546]
In Buildbot 0.8, builder page used to show the slaves configured for that builder (and status of the slave, e.g.: "Connected", "Offline" etc.).

However, in Buildbot 0.9, builder page do not show the worker information at all. This is very useful information. This information should be displayed by default (or at least controlled by an option on settings page).

**Comment by aakashja** [comment]
Can this be configured in the template?

**Comment by Frodox** [comment]
"Builders" page show this information at the right column. Also, "Workers" page is useful enough.
Yes, it can be configured (not like in 0.8 exactly) - http://docs.buildbot.net/latest/developer/www-base-app.html + https://medium.com/buildbot/buildbot-ui-plugin-for-python-developer-ef9dcfdedac0

**Comment by aakashja** [comment]
I (and most of the people in my team) strongly feel that missing workers information on builder page is significant regression from buildbot 0.8.

It was very convenient to directly see the workers associated with the builder in 0.8, especially while debugging issue with a builder. In Buildbot 0.9, we need to open builders page and search for that builder. This introduces more steps in the workflow to get basic information.

It would be great if Buildbot can bring this feature back.

**Comment by tardyp** [comment]
please remember that Buildbot is 100% run by its community, which you are an important member. This feature is quite easy to add, if this will help your team to have it, please consider contributing it.
