### ISSUE TITLE
'buildbot try' prints no output

### ISSUE THREAD

**Issue by mrstanwell** [buildbot/buildbot#3550]
I'm not getting any output at all from the `buildbot try` command.  No error messages, progress, etc.  I'm wondering if something in the twisted logging framework isn't being initialized...?  When I edit `output()` in `master/buildbot/clients/tryclient.py` and replace the call to `log.msg()` with a call to `print()`, I get useful output.  Alternatively, putting `log.startLogging(sys.stdout)` in `Try.__init__` also gets me proper twisted logging to stdout.  But, out of the box, I get no output anywhere.  For example `buildbot try --get-builder-names --connect=pb --master=<host>:<port> --username=<user> --passwd=<pword>` just returns to a prompt.  If I hack the `output()` function as above, however, I get the expected builder names from master.   Am I missing something?

Thanks!

Using:
macOS 10.12.5, ubuntu 16.04
python 2.7.13, 2.7.12
buildbot 0.9.10
Twisted 17.5.0

**Comment by tardyp** [comment]
We recently had reports from people using osx who had bad configuration of locales.
could this be the problem?

https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python

**Comment by mrstanwell** [comment]
Thanks for the reply, Pierre.  I tried setting the LANG env vars per that link, but that doesn't change any behavior.  Also, I'm seeing the same problem on Ubuntu, so it's not a macOS-specific thing.  I'm pretty sure this has to do with the timing of the initialization of the twisted logging framework.  For example, if you just run `buildbot try --connect=badvalue`, you should get an error message saying `you must specify a connect style: ssh or pb`.  However, in both my macOS and Ubuntu installs I get no output at all -- just a return to command prompt.  All the output messages go through the `output()` function, which in turn uses the twisted logger.  From what I understand from [this doc](http://twistedmatrix.com/documents/current/core/howto/logging.html), the logger isn't initialized until the `twistd` daemon is started...  But I don't know if that's even happening in the tryclient, or if so where (I've got no experience with Twisted).  If I initialize the logger myself using `log.startLogging()` at the top of `Try.__init__`, it works fine.

Other details about my usage:  I'm running `buildbot try` within a virtual environment, and in this case it's only being used as a `try` client...  no master or worker is configured on this system.  The use case is for developers (currently unfamiliar with buildbot tool usage) to use `try` to trigger custom workspace builds on my `buildbot` CI server.

Thanks...

Ron

**Comment by tardyp** [comment]
I am not very familiar with the try command as there is more modern ways to trigger build (the forcescheduler being the most user friendly imho)

I am not very sure of what you are trying to achieve, and how you did configure your buildbot, so it is hard for me to help.

**Comment by mrstanwell** [comment]
The try command runs from within a developer's local checkout which might contain uncommitted changes.  It sends a patch with those changes to the buildbot which then runs a build containing the patch.  It's a way of answering the question "what would happen if I committed these changes?"  It's handy if your product builds on multiple platforms (win, android, ios, etc.) and devs don't have the capability to build on all platforms easily.  A dev with a successful build on Windows might want to know if his changes will build for Android and iOS as well.  Using `buildbot try` can answer that question prior to actually having to commit the code to trunk, which is the feature I'm trying to provide a dev team.  I don't believe this is something the forcescheduler can do, can it?

As for configuration, there's really nothing to configure to reproduce this problem, as it is independent of either the master or worker.  For a dev to use `buildbot try`, he only needs to install `buildbot` using pip.  The tryclient however doesn't start a daemon like the buildbot master or worker do, so I'm guessing that the twisted logger is never being initialized when the tryclient runs.

The only thing that isn't working is the logging.  If you get the syntax of the `buildbot try` command correct, it sends the job to the scheduler on the master and everything runs fine (although you get no output to this effect on the client end).  If you get the syntax wrong, you get no message telling you what you got wrong (which makes identifying the problem harder...).  As I said, if I initialize the logger explicitly in `Try.__init__`, logging works and I get useful output.  I don't know if this is the _correct_ solution to the problem, but it satisfies my need.  I'd be happy to fork and submit a pull request if it would be helpful.

Are you able to reproduce this behavior?  If you run `buildbot try --connect=badvalue`, do you get an error message?

**Comment by rodrigc** [comment]
Maybe related to https://github.com/buildbot/buildbot/pull/4038

**Comment by mrstanwell** [comment]
As of buildbot 2.1.0 at least, the `buildbot try` command is producing output.  I'm not actually attempting to use `try` anymore, but it looks like this particular logging issue has been fixed.
