### ISSUE TITLE
Buildbot should check for duplicates in addURL 

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3554]
In a step if we call self.addURL() multiple times with same URL, buildbot doesn't check if URL is already added, and adds the duplicate URL. Buildbot should check if the URL is already added before adding the URL.

This happens when a script parses a lot of output and generate links for various things. We can manually maintain a list ourself and check for duplicates before calling addURL(), but it feels so basic that buildbot should be doing this check instead of callers of addURL() checking for duplicates.

**Comment by tardyp** [comment]
feel free to add this improvement.
