### ISSUE TITLE
How to use username and password in REST API?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3560]
I want to use GET request to http://**username:password**@127.0.0.1:8010/api/v2/forceschedulers/{schedulername} to get   information of the specified scheduler. Is there any reference?
At this time, I got a error message like this:
![image](https://user-images.githubusercontent.com/19603852/29771538-eb3f949a-8c26-11e7-8167-cb637d9f60e2.png)

**Comment by lancelodliu** [comment]
If I set cookies `TWISTED_SESSION` to a value already got, it is ok. But I need to access this cookies autmatically. Is there a way to achive this like the [oauth2 ](http://buildbot.readthedocs.io/en/latest/developer/rest.html#authentication) way?

**Comment by lancelodliu** [comment]
Setting auth header doesn't work either.

**Comment by lancelodliu** [comment]
[Doc](http://docs.buildbot.net/current/developer/rest.html#authentication) says
> Once credentials have been established, a cookie will be set, which must be sent to the buildbot REST API with every request thereafter.

I found it could be done like this.
```python
import requests
import json

data = {
    "jsonrpc": "2.0",
    "method":"force",
    "id":843,
    "params":{
        "p1":1, 
    }
}
url = '127.0.0.1:8010'
s = requests.session()
s.head('http://{}/auth/login'.format(url), auth=('qsmobile', 'qsmobile'), proxies={'http':None})
r = s.post('http://{}/api/v2/forceschedulers/ForceBuild_Scheduler'.format(url), headers={'Content-Type':'application/json'}, data=json.dumps(data), proxies={'http':None})
```

**Comment by Frodox** [comment]
Could you please add your scheduler and auth-roles from master.cfg?
This definitely should be in docs!

@seankelly please, add `#documentation` `#needs docs` labels here :) (just not to miss it, and I want to fix it)

**Comment by lancelodliu** [comment]
@Frodox 
```python
c['www'] = dict(port=8010,
                plugins=dict(
                    waterfall_view=True, 
                    console_view=True),
                allowed_origins=["*"]
                )
c['www']['authz'] = util.Authz(
        allowRules = [
            util.AnyControlEndpointMatcher(role="admins")
        ],
        roleMatchers = [
            util.RolesFromUsername(roles=['admins'], usernames=['qsmobile', 'qsmobile'])
        ]
)
c['www']['auth'] = util.UserPasswordAuth([('qsmobile','qsmobile')])
```

**Comment by aj062** [comment]
I faced this as well while trying to figure out how to Authenticate the REST API. Current documentation doesn't explain that well. It would be nice to have the documentation updated.
