### ISSUE TITLE
Console UI Angular performance can be improved by disabling watchers

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#3564]
I am working on a custom implementation of the Console view (started out with the "console_view" source code and modifying from there")

One issue that I have been running in to is that performance on a page like this quickly degrades if you add a few more bits of information (e.g. I added more helpful tooltips to the build bubbles with ```uib-tooltip='{{c.buildToolTip(change,builder,build)}}'```, pulled up more of the change info onto the top level of the table.  The performance degradation was mainly noticable when clicking on the bubbles, as it would take a long time to pop up the build summary modal popup.

Upon profiling this using Chrome and the Batarang plugin, I discovered that the digest cycle was quite long and the numbers of watchers is high.  

I'm fairly new to Angular so this was a bit of an exploration for me, but one thing that surprised me is that the "build summary" dialog seemed to be slow because it was triggering a digest of the entire page repeatedly. (each of the json requests performed by the build summary to grab the logs appears to trigger a full digest cycle which recalculates not only the contents of the dialog but also the contents of the entire console grid which is greyed out in the background).  This problem is exacerbated by having more details in the grid (as my fork of the plugin does), changing the settings to show more changes/builds (as we typically do), and having many build steps each with their own logs causing more digest cycles before the dialog is fully displayed (our builders have many steps).

There may be a way to isolate the scope of the "digest" performed when the new data arrives so that only the dialog's contents are "digested" by Angular and not the full page, but I did not investigate that deeply, instead I delved more into how to decrease the number of watchers in the console's table.

I found two techniques which greatly improved the performance by reducing watchers

* **Using angular's "one-time binding"**.  (_"An expression that starts with :: is considered a one-time expression. One-time expressions will stop recalculating once they are stable, which happens after the first digest if the expression result is a non-undefined value"_ - https://docs.angularjs.org/guide/expression).  This approach is easy to anything which is not going to change (e.g. the build number in a bubble).  But I was not able to get the number of watchers down to a satisfactory number just using this technique.

* **Using custom angular directives which remove watchers when they are no longer needed**.    (I implemented something based on this article https://coderwall.com/p/d_aisq/speeding-up-angularjs-s-digest-loop).  Essentially the idea is that after a certain conditions are met you can disable the all watchers on a particular row of the table (in the Console's case, when all of the builders are currently building a change that is more recent than the row, the row's watchers can be suspended, although this has the caveat that if you go back and manually force a rebuild on a change row which has already been suspended, the UI may not update to reflect this unless you do a full F5 refresh of the page)

Although the original console_view's performance is decent since it does not have as many bells and whistles, perhaps it could still benefit from the techniques I'm describing, especially for users with lower-powered machines and/or higher needs in terms of the amount of buildbot changes/builds they wish to see on the page at one time.

The coffeescript code for the directives I use to suspend watchers appears below.

```
# Adding this directive allows the watchers under the scope to be suspended and resumed
#   but only catches the watchers directly within this scope, and not within descendent 
# scopes.
class Suspendable extends Directive
    constructor: ->
        
        return {
            restrict: 'A'
            scope: false

            link: ($scope, element, attributes) ->
                watchers = undefined
                suspended = false

                #element.append '<p class="suspendedTag">SUSPENDABLE</p>'

                suspend = ->
                  if !suspended
                    watchers = $scope.$$watchers
                    console.log 'disabling ' +watchers.length+  ' watchers on ' + $scope
                    $scope.$$watchers = []
                    suspended = true
                    element.append '<p class="suspendedTag">SUSPENDED</p>'
                  return

                resume = ->
                  console.log 'resuming watchers on ' + $scope
                  if watchers
                    $scope.$$watchers = watchers
                    watchers = undefined
                  suspended = false
                  return

                $scope.$on 'suspend', suspend
                $scope.$on 'resume', resume

                setTimeout (->
                    $scope.$broadcast('suspend')
                    ), 2000

                return
        }

# Allows for suspending watchers under the scope of this element and all 
#  descendents, but does not allow resuming after stopped.
class RecursiveSuspendable extends Directive
    constructor: ->
        
        return {
            restrict: 'A'
            scope: false

            link: ($scope, element, attributes) ->

                suspended = false

                suspendRecursive = (scope) ->
                    cs = scope.$$childHead
                    while cs
                        # cs is child scope
                        watchers = cs.$$watchers
                        if watchers
                            #console.log 'disabling ' +watchers.length+  ' watchers via recursion.'
                            cs.$$watchers = []
                        suspendRecursive cs
                        cs = cs.$$nextSibling

                #element.append '<p class="suspendedTag">RSUSPENDABLE</p>'

                suspend = ->
                  if !suspended
                    watchers = $scope.$$watchers
                    #console.log 'disabling ' +watchers.length+  ' watchers on ' + $scope
                    $scope.$$watchers = []
                    suspended = true

                    suspendRecursive $scope

                    #element.append '<p class="suspendedTag">SUSPENDED</p>'
                    element.addClass("suspended")

                  return

                $scope.$on 'suspend', suspend

                return
        }

# This directive basically cooperates with the RecursiveSuspendable directive, but 
#  has the domain specific knowledge about when it should suspend a change's row.
class AutoSuspendChange extends Directive
    constructor: ->
        
        return {
            restrict: 'A'
            scope: false

            link: ($scope, element, attributes) ->

                reevaluate = -> 
                    #console.log( "evaluating a AutoSuspendChange" )

                    if $scope.change.shouldSuspend
                        setTimeout (->
                            $scope.$broadcast('suspend')
                            ), 1000

                reevaluate()

                $scope.$on 'onChange', reevaluate


        }

```

in the jade template i mark each row as "recursive-suspendable":

```        tr(recursive-suspendable auto-suspend-change ng-repeat="change in c.filtered_changes | orderBy: ['-changeid'] track by change.changeid")```

in addition I'll offer this extra code that I wrote in the controller, which updates the "change.shouldSuspend" member variable.  (I run the suspendFinishedChanges function within the _onChange callback)    This implementation is probably specific to Perforce, since it compares revision numbers, whereas on Git the change.revision is a non-sequential ID.  Perhaps using a timestamp would be a better general-purpose implementation?

```
    hasCompletedBuild: (change, builderName) =>
        matchingBuilder = change.builders.find (builder) => (builder.name == builderName)
        if matchingBuilder
            completedBuild = matchingBuilder.builds.some (build) => build.complete
            return completedBuild
        return false

    suspendFinishedChanges: =>

        latestCompletedChanges = []

        # Find the latest completed change on each builder.
        for builder in @builders
            latestCompletedChangeForBuilder = @changes.find (change) => @hasCompletedBuild(change, builder.name)  
            latestCompletedChanges.push(latestCompletedChangeForBuilder.revision)

        latestRevisionToCompleteAllBuilders = Math.min.apply(null,latestCompletedChanges)      

        for change in @changes
            if change.shouldSuspend
                continue
            if change.revision <= latestRevisionToCompleteAllBuilders
                change.shouldSuspend = true

```

**Comment by uglycoyote** [comment]
Some additional notes about this:

One reason why my fork of Console suffered in performance from too many watchers is that I took out the code which filtered out changes which  don't have any builds associated with them.   Our users expect that if they check in a change it will 1) show up immediately, not whenever buildbot gets around to starting building it and 2) show up even if buildbot never builds it -- there are often a quick succession of changes and the way we have our builders set up they will always sync to latest so some changes never have a build associated with them.  So it would be nice to have a way of having these empty change rows visible without them tanking the performance of the page due to too many watchers.

**Comment by p12tic** [comment]
This issue is no longer relevant with the switch to React frontend. Performance issues may still remain, but the causes will be completely different.
