### ISSUE TITLE
Port GitLab reporter to GitLab API v4

### ISSUE THREAD

**Issue by estan** [buildbot/buildbot#3573]
The GitLab reporter is [currently](https://github.com/buildbot/buildbot/blob/a539811900caca95a7683e252614e3c0493763f9/master/buildbot/reporters/gitlab.py#L90) [using](https://github.com/buildbot/buildbot/blob/a539811900caca95a7683e252614e3c0493763f9/master/buildbot/reporters/gitlab.py#L107) version 3 of the GitLab API. I believe GitLab 10 will definitely remove the v3 API.

Version 4 has been the [recommended](https://docs.gitlab.com/ce/api/v3_to_v4.html) version to use since GitLab 9.0. The GitLab docs says that v3 may be removed in GitLab 9.5+. GitLab 9.5 was now just released, and I ~~don't~~ think (though not sure) that the v3 API is still there. But to be safe, Buildbot should switch to using the v4 API.

Does Buildbot want to maintain support for GitLab < 9.0 (where v4 was added)?

**Comment by tardyp** [comment]
I agree we should support v4

So what is the difference between v3 and v4 regarding the api that we use?
How hard would it be to support both version?

**Comment by estan** [comment]
I haven't looked at it. I don't think it would be hard to support both though. I could have a look at it.

**Comment by Frodox** [comment]
I vote for both supporting! We are still using GitLab 8.5 with v3, for example

**Comment by estan** [comment]
GitLab 10 was recently released. They decided to keep the v3 API until GitLab 11 (https://about.gitlab.com/2017/09/22/gitlab-10-0-released/), so feel free to down-prioritize this issue. I may have a look at it if there's time over.

**Comment by dankegel** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/43252 says this is due on Jun 22, 2018

**Comment by estan** [comment]
Yes, 11 is getting close. Sorry, I had no time to look at it :( We're trying to update our GitLab regularly, so would need this sooner rather than later. I'll try again to find some time to look at it, but no promises (lots at work right now).

**Comment by estan** [comment]
Closing this now since https://github.com/buildbot/buildbot/pull/4152 is merged. Many thanks @micaeljtoliveira!
