### ISSUE TITLE
What is the best way to log?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3584]
I need to:
1. log in some steps of builds.
2. process them based on some filters like Level Filter or Keyword Filter
3. send to interested people

My current implementation is to define a `log` method which accept a BuildStep instance and a message:
```python
@defer.inlineCallbacks
def log(step, msg):
  try:
    log = yield step.getLog('log')
  except KeyError:
    log = yield step.addLog('log')
  step.setProperty('log', msg)
  yield log.addStdout(msg)
```
And call `log` method in any step I need to log:
```python
class MyStep(BuildStep):
  @defer.inlineCallbacks  
  def run(self):
    # do something
    yield log(self, "some msg")
    # do other things
```
Finally, I can see these messages in the step page and use them by `Property`.
Is there any better solution to this?

**Comment by seankelly** [comment]
What sort of logging? Is this internal logging of the steps or logs from the commands the steps run?

**Comment by lancelodliu** [comment]
I mean the internal logging of the steps.

**Comment by tardyp** [comment]
I don't understand what this is for:

      step.setProperty('log', msg)

but for the rest, this is more or less what I used in my prod..

**Comment by ewongbb** [comment]
I'm guessing he's trying to figure out what the msg is so he stores it in the property to be displayed during the step resolution..
