### ISSUE TITLE
Grid View broken for Virtual Builders

### ISSUE THREAD

**Issue by btaidm** [buildbot/buildbot#3603]
Grid View is currently broken with virtual builders. 

New (0.9.11):
![image](https://user-images.githubusercontent.com/3837347/30231666-fd6991b6-94b9-11e7-860e-e493ff49d220.png)

Old (0.9.10):
![image](https://user-images.githubusercontent.com/3837347/30231708-1f8106a8-94ba-11e7-986e-dc106b753188.png)

**Comment by tardyp** [comment]
arg. Meanwhile, you can upgrade all other components, but keep gridview 0.9.10 :-/

**Comment by tardyp** [comment]
@rjarry do you have an idea what could be wrong?

**Comment by rjarry** [comment]
No, I don't see what could be the problem. It seems to be working on https://nine.buildbot.net/#/grid

Does it run on the latest version?

**Comment by btaidm** [comment]
No. It is on 0.9.10

**Comment by rodrigc** [comment]
nine.buildbot.net is running grid_view plugin 0.9.10

**Comment by rodrigc** [comment]
Fixed in https://github.com/buildbot/buildbot/pull/3689
