### ISSUE TITLE
ForceScheduler form asks for "Your name", requires email address

### ISSUE THREAD

**Issue by sound-fx** [buildbot/buildbot#3624]
Using 0.9.11.
The web form for the ForceScheduler includes a field labelled "Your name" that actually requires an email address.  If I enter just my name "Greg," a balloon pops up with the message

> Your name:
> username: please fill in email address in the form 'User <email@email.com>'

It seems either the field label should be changed from "Your name" to  "Your email" or "Your name and email", or the requirement should be relaxed to accept just names.

My master.cfg sets up the ForceScheduler as follows:

```
force_scheduler = schedulers.ForceScheduler(
                        name="user_forced",
                        builderNames=all_builders,
                        # will generate a text input
                        reason=util.StringParameter(name="reason",label="reason:<br/>",
                                                          required=True, size=80),
                        # in case you dont require authentication this will display
                        # input for user to type his name
                        # username=util.UserNameParameter(label="your name:<br/>", size=80),
                        # A completely customized util.Property list.  The name of the
                        # util.Property is the name of the parameter
                        properties=[
                            util.BooleanParameter(name="force_build_clean",
                                                        label="force a make clean", default=False),
                        ]
                    )

```

**Comment by tardyp** [comment]
The best is to properly setup an authentication plugin in order to get that info automatically.
You can also change UserNameParameter to StringParameter to remove the check.


    force_scheduler = schedulers.ForceScheduler(
                        name="user_forced",
                        builderNames=all_builders,
                        # will generate a text input
                        reason=util.StringParameter(name="reason",label="reason",
                                                          required=True, size=80),
                        # in case you dont require authentication this will display
                        # input for user to type his name
                        username=util.StringParameter(label="your name", size=80),
                        # A completely customized util.Property list.  The name of the
                        # util.Property is the name of the parameter
                        properties=[
                            util.BooleanParameter(name="force_build_clean",
                                                        label="force a make clean", default=False),
                        ]
                    )

**Comment by tardyp** [comment]
I just saw that UserNameParameter now has a need_email attribute that you can set to false to disable email validation.
 
force_scheduler = schedulers.ForceScheduler(
                    name="user_forced",
                    builderNames=all_builders,
                    # will generate a text input
                    reason=util.StringParameter(name="reason",label="reason",
                                                      required=True, size=80),
                    # in case you dont require authentication this will display
                    # input for user to type his name
                    username=util.UserNameParameter(label="your name", size=80, need_email=False),
                    # A completely customized util.Property list.  The name of the
                    # util.Property is the name of the parameter
                    properties=[
                        util.BooleanParameter(name="force_build_clean",
                                                    label="force a make clean", default=False),
                    ]
                )
