### ISSUE TITLE
Can't use secret interpolation in db_url

### ISSUE THREAD

**Issue by pmatos** [buildbot/buildbot#3627]
Trying to do something like this with 0.9.11 breaks:
```
c['db'] = {
    'db_url': util.Interpolate("mysql://gcc-buildbot:%(secret:mysql-pass)s@localhost/gcc_buildbot?max_idle=300")
    }
```

with:
```
2017-09-17 18:08:08+0200 [-] while starting BuildMaster
        Traceback (most recent call last):
          File "/home/gcc-buildbot/gcc-buildbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/home/gcc-buildbot/gcc-buildbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1442, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/home/gcc-buildbot/gcc-buildbot/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/home/gcc-buildbot/gcc-buildbot/venv/lib/python3.5/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
        --- <exception caught here> ---
          File "/home/gcc-buildbot/gcc-buildbot/venv/lib/python3.5/site-packages/buildbot/master.py", line 265, in startService
            yield self.db.setup()
        builtins.AttributeError: 'Interpolate' object has no attribute 'decode'
```

It seems that interpolate for some reason doesn't work well within the `db_url` configuration. However it is required if one wants to use secrets.

**Comment by tardyp** [comment]
Indeed, this is something that still needs to be implemented. 
There are still lots of places where secrets could be interpolated but they are not. It is not complicated to do. any help appreciated, let me know if you need directions.

**Comment by pmatos** [comment]
Interesting. Is this specific to secrets of properties can't be interpolated at this point either?

I will try to get my hands dirty. Any code you can point me to that implements the secret interpolation so I can understand how to do it for the `db_url` bit?

Thanks.

**Comment by tardyp** [comment]
You can look at this patch, which implements it for services in a generic way.

https://github.com/buildbot/buildbot/pull/3357/files#diff-6800b86c43276afcea4785bca315bd66R204

You basically have to put this at the right place. 
```
p = Properties()
p.master = self.master
db_url = yield p.render(db_url)
```
Before the db is initialized, but after the secret manager is initliazed.

**Comment by pmatos** [comment]
Thanks. I will take a look.

**Comment by kallisti5** [comment]
Any updates on this? It's kind of silly you "can't use the secrets provider for literally the first secret you will need to access"

**Comment by yan12125** [comment]
> Before the db is initialized, but after the secret manager is initliazed.

I got no luck with this approach. Maybe the reason is that db is initialized before the secret manager: https://github.com/buildbot/buildbot/blob/master/master/buildbot/master.py
