### ISSUE TITLE
Buildbot schedules build when a GitLab merge request is deleted

### ISSUE THREAD

**Issue by ngladitz** [buildbot/buildbot#3635]
My master installation is running 28958cffbdf703e29b76fb24344848bd65e8ea8a.
In the Buildbot configuration a "gitlab" change hook is registered and triggered by a GitLab configured "Merge Requests Event".

Currently builds are triggering when a merge request is created, updated or deleted.
Build should not be scheduled when a merge request is deleted.

**Comment by tardyp** [comment]
You should use a change filter in order to avoid to build upon deleted event. We keep deleted events as they can be used to cancel builds (even if this is not really simple to implement)

**Comment by ngladitz** [comment]
Thanks! That sounds promising but I don't seem to be able to find where the information that a change comes from a deleted merge request is stored (I checked "Builds/Last Changes", and "Debug", "Build Properties" and "Changes" (empty) under the Build itself).

Is there something I am missing?

**Comment by tardyp** [comment]
You can find the details of a change using the rest api:

e.g:
https://nine.buildbot.net/api/v2/changes?limit=100

**Comment by ngladitz** [comment]
Thanks. I created a dummy MR and deleted it right after.
This produced two distinct changes which I then diffed.
The only difference between them is the changeid and the content of parent_changeids:
```diff
5c5
<       "changeid": 906, 
---
>       "changeid": 907, 
9c9,11
<       "parent_changeids": [], 
---
>       "parent_changeids": [
>         906
>       ], 
```

As far as I can tell there is nothing that would indicate that the first is due creation and the second due to closing of the merge request.

**Comment by dankegel** [comment]
Does this MR come close to what you wanted?
https://github.com/buildbot/buildbot/pull/4097

Pierre: I love the idea of cancelling builds on close of the MR, but let's not trigger a build in that case for now :-)

**Comment by ngladitz** [comment]
@dankegel Thanks for looking into this!

If I understand correctly this seems to go a bit too far since it only triggers builds on open|reopen which would exclude "update" which I get when I push new commits(?)

**Comment by dankegel** [comment]
Yeah.  I finally figured out how to detect that conditions.  How's it look now?

**Comment by ngladitz** [comment]
Thanks! I haven't tested it but the intent looks good.

I must admit to having abused merge request updates without new commits to trigger builds as well but I'll try to look into some other (maybe even less hackish) way to do that.
