### ISSUE TITLE
Multiple IRC bots cannot be registered 

### ISSUE THREAD

**Issue by chapuni** [buildbot/buildbot#3648]
It is regression from 0.8.

reporters.IRC has the name "IRC" and load_services() is unaware of different instance of same service name.

**Comment by tardyp** [comment]
I believe you should name them differently.
reporters.IRC(name='irc1', ...)
reporters.IRC(name='irc2', ...)

**Comment by chapuni** [comment]
@tardyp, bingo! It works.

I think it's redundant. Could you identify the name from other parameters?

BTW, is it documented anywhere?
