### ISSUE TITLE
builder nextWorker, blocking on required resources, any ideas?

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#3658]
I have a series of tests that need to be run - they are all an identical builder that uses a property for the text command to execute, since the tests are products of a previous build step. This 'test atom' builder is configured to run on ten workers.

One or two of the tests require a specific worker with test hardware attached to run. I have implemented nextWorker to correctly return the worker to use in this case.

My problem is that the build request queue gets blocked if the hardware is busy -- even though there are ample other 'test atom' builders available for the non-hardware specific tests. 

For example consider the following suite of tests: HW0, HW1, HW2, VM0, VM1, VM2 where HW_n_ must run on test hardware, and VM_n_ can run in a virtual machine. If I have ten machines, 2 with test hardware and 8 which are virtual, the build request queue stalls out on HW2 waiting for HW0 and HW1 to complete, even though there are idle VM machines to handle VM0, VM1 and VM2.

I am starting to think I should have different builders here - test-atom-HW and test-atom-VM but my use case is a bit more elaborate. I have some tests that can run in *any* environment, so I would prefer to have the same builder in all cases. This allows us a pretty robust load-balancing of tests. 

Is there a mechanism to allow my stalled out build requests to be processed while there are available builders that match their 'requirements'? I see that in addition to nextWorker there is a nextBuild, but it isn't clear to me how to articulate 'find the next buildrequest that can start immediately'.

**Comment by seankelly** [comment]
I think two builders would be better. Have on generic builder that runs the tests that can run on the VMs (I'll call it "test atom"). Then once the tests pass, trigger the other builder, "test atom hw", to run the hardware specific tests. Running them second means the more limited resource has a filter so they'll only be used once it's determined the code is at least mostly there.

I think this might fix your build queue getting blocked. I'm assuming there will still be a queue for the new "test atom hw" builder, but it should operate as expected on the incoming changes.

**Comment by sphet** [comment]
I am still struggling with this concept a bit - I ended up doing two builders. However, I think I can close this issue.
