### ISSUE TITLE
Buildbot 0.9 doesn't display timestamp for any build step

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3662]
Buildbot 0.8 used to have timestamp for each build step, build and builder. For the build it even used to have timing information
e.g.:
<img width="612" alt="screen shot 2017-09-29 at 10 36 11 am" src="https://user-images.githubusercontent.com/3098702/31028334-53dd391e-a502-11e7-9e65-aad88696802e.png">

Timestamp for every build on builder page:
<img width="171" alt="screen shot 2017-09-29 at 10 36 59 am" src="https://user-images.githubusercontent.com/3098702/31028441-d8d1fa4c-a502-11e7-9181-8ea339fc19b7.png">

Buildbot 0.9 doesn't display timestamp for any build step.  Also for the builds Buildbot doesn't show the timestamp, it just show "Finished x hours ago". Same issue with the builder page. e.g.:
<img width="345" alt="screen shot 2017-09-29 at 10 39 35 am" src="https://user-images.githubusercontent.com/3098702/31028381-8932f5ea-a502-11e7-9281-c44382e16c6f.png">

Timestamp is very useful when debugging any issue. For e.g.: "when did a particular issue start happening".

Exact timestamp should be displayed for the build-steps (or atleast for the builds). or there should be a setting to turn on timestamp.

**Comment by seankelly** [comment]
Note that you can hover over the "2 hours ago" to get the exact time.

**Comment by aj062** [comment]
Thanks. that works.
