### ISSUE TITLE
In buildbot web UI, no-select CSS rules prevent selection of text in many cases where you might want to.

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#3663]
The buildbot UI uses a no-select CSS rule in many places where it seems unnecessary and prevents selection of things that a user may want to copy.

Here are some examples

In the Build Summary pages:
- build or step names 
- contents of HTML, when an HTML log is the result of a build step 

In the console view:
- Change description or any other information about the change (when expanding the full change details)

One case where the no-select rule is used appropriately is on line numbers in preformatted log output blocks.  I don't see any good reason to prevent a user from selecting just about anything else in the UI.   Generally I think users of any webpage expect to be able to select whatever text they like without the browser preventing them from doing so.  

We have certainly found this to get in the way when trying to copy information from the buildbot page, for example, into an email.

**Comment by adydychk** [comment]
+1 to fix it :)

**Comment by uglycoyote** [comment]
I added a pull request to address this.

**Comment by adydychk** [comment]
Great!

**Comment by uglycoyote** [comment]
Thanks for merging.  Issue is fixed.
