### ISSUE TITLE
Buildbot should scream loudly if its WebSocket connection fails

### ISSUE THREAD

**Issue by zware** [buildbot/buildbot#3672]
I was not aware that Buildbot 9 uses WebSockets to drive nearly the entire UI, and was very confused and unimpressed with @rodrigc's work in python/buildmaster-config#12 until I eventually realized from the Chrome developer console that there was a WebSocket connection failing.  After fixing Apache's proxying of the WebSocket connection, everything works beautifully.

It would be nice if there were some indication that a WebSocket connection had failed, rather than silently not filling most of the UI.

**Comment by Frodox** [comment]
@zware could you share your apache config, please?
I regularly get 502 error handshake error, and I can't find the reason 
![2017-10-04_13-15-39](https://user-images.githubusercontent.com/3653069/31170801-2ee2e6ce-a906-11e7-921d-407444d74cf2.png). F5 helps me time to time

**Comment by zware** [comment]
@Frodox, my apache config is not appreciably different from http://docs.buildbot.net/latest/manual/cfg-www.html#reverse-proxy-configuration aside from a lack of SSL handling.

**Comment by tardyp** [comment]
> It would be nice if there were some indication that a WebSocket connection had failed, rather than silently not filling most of the UI.

The problem of such messages is that it is hard to distinguish websocket connections lost from websocket connection initial failure. websocket connection lost is when you re-open your laptop in the morning, and this is handled and shall correctly reload the view to get the latest info.

As it is only a problem for first installation, this has not been the first priority, indeed.
This is the kind of frustration that you only get once per person, so it does not reach anybody's let-fix-it threshold (only reaches the lets-report-it threshold :) ).

**Comment by zware** [comment]
Fair enough, and perhaps "scream loudly" is a bit too strong :).  Even in the case of a properly configured server and routine connection loss, it would be nice to have an indication of "Connection lost, attempting to reconnect..."

**Comment by tardyp** [comment]
On Wed, Oct 4, 2017 at 7:12 PM Zachary Ware <notifications@github.com>
wrote:

> Fair enough, and perhaps "scream loudly" is a bit too strong :). Even in
> the case of a properly configured server and routine connection loss, it
> would be nice to have an indication of "Connection lost, attempting to
> reconnect..."
>
That is already the case. You can trigger it easily by restarting your bot.

**Comment by jdpipe** [comment]
I never saw any warning about "connection lost" in relation to #3727.

**Comment by tardyp** [comment]
@jdpipe The connection lost only happen after there is at least one connection.
please re-read https://github.com/buildbot/buildbot/issues/3672#issuecomment-334189647

**Comment by p12tic** [comment]
There's a visual indication when connection fails now. Closing.
