### ISSUE TITLE
[grid_view] updating 0.9.10 to 0.9.12 leaves the grid with a single row

### ISSUE THREAD

**Issue by aureliendavid** [buildbot/buildbot#3688]
Hello, 

with 0.9.10 I have a grid view that looks like this:

![bbgrid1](https://user-images.githubusercontent.com/7168263/31344179-3637e388-ad12-11e7-9885-e9a55c58d668.png)

after updating to 0.9.12 (with pip) I get

![bbgrid2](https://user-images.githubusercontent.com/7168263/31344195-4355c56c-ad12-11e7-81f6-6a3538824f44.png)

any idea what happened?

Thanks in advance.

**Comment by bdbaddog** [comment]
I didn't have grid enabled under 0.9.10, but I see the same with 0.9.12.

**Comment by rodrigc** [comment]
I can confirm this problem.  For example, look at: http://buildbot.python.org/all/#/grid

It looks like maybe this patch is causing problems:
https://github.com/buildbot/buildbot/pull/3558

@rjarry can you comment?

**Comment by rodrigc** [comment]
Same issue reported here:
https://github.com/buildbot/buildbot/issues/3603

**Comment by rjarry** [comment]
Hi @rodrigc ,

After a quick `git bisect`:

```
ad04194769415097deabdd8f249103e9db4bfbf7 is the first bad commit
```

Indeed, the [merge commit](https://github.com/buildbot/buildbot/commit/ad04194769415097deabdd8f249103e9db4bfbf7#diff-841a6c04c85578283ace7ae9cd9525eaL142) looks bad :)

I'll fix that right away.

**Comment by tardyp** [comment]
I'll release 0.9.12.post1 for grid_view when we have a working fix.

**Comment by tardyp** [comment]
0.9.12.post1 is on pypi now.

**Comment by aureliendavid** [comment]
great, it's back to normal now

thanks all
