### ISSUE TITLE
BuilderStatus is bitrotten & broken

### ISSUE THREAD

**Issue by csnover** [buildbot/buildbot#3695]
I was asked to open this ticket on IRC, though given the [coverage report](https://codecov.io/gh/buildbot/buildbot/src/master/master/buildbot/status/builder.py) I’m not sure there is necessarily a need for a specific ticket about this.

I was trying to create a `prioritizeBuilder` function that would prioritise builders based on the failure status of their last build. I saw that builders have a BuilderStatus object on their `builder_status` property, and that BuilderStatus has some helpful-looking functions like `getLastFinishedBuild`, but this function (and some others like `getBuildByRevision`) crash because there is no `self.nextBuildNumber`. There also seem to be never-used `lastBuildStatus` and `nextBuild` properties set in the BuilderStatus constructor.

In the end, this function wouldn’t really help my use case anyway, since it doesn’t ever retrieve information from the database, but it seems like there is a lot of dead code here that could probably just be deleted outright, since it’s untested and broken.

**Comment by p12tic** [comment]
BuilderStatus and similar classes have been removed at around Buildbot v3.0 release.
