### ISSUE TITLE
HttpStatusPush reporting wrong steps

### ISSUE THREAD

**Issue by svogl** [buildbot/buildbot#3707]
Hi all, maybe you can help me out: 
I want to integrate buildbot (0.9.12) with an external reporting tool for automating programming excercise feedback. 
I use HttpStatusPush sending updates to a small node.js glue-code that picks up compilation progress and reports full details on errors (on the other end, it reacts to github webhooks, creating change sources and builders and reconfigures buildbot). The relevant portion of the config looks like:

`# connection to gluebot:
from buildbot.plugins import reporters
sp = reporters.HttpStatusPush(serverUrl="http://localhost:3223/bb", wantSteps=True, wantLogs=True)
c['services'].append(sp)
`
When multiple builds are running (quite common - I have 80 students in a class), the steps that are reported back reference other builds, mixing everything up. (the logs array is empty as well, btw)

For now, I have moved everything to shell scripts and pick up results from the filesystem, which works somehow but is not a nice solution.

Maybe you can give me a hint what I'm doing wrong - thanks!

p.s. I do see the correct building steps via the web interface later on.

pps.: I cross-checked with single consecutive builds; it seems that the reported steps are not from the current build, but one buildstep behind.

**Comment by p12tic** [comment]
@svogl FYI, I believe this bug has been fixed long ago, just not marked as fixed.

**Comment by svogl** [comment]
@p12tic thought so, yes.. I'm currently cleaning out my old tickets..
