### ISSUE TITLE
Upload from worker to master sometimes takes few hours instead of seconds

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3709]
I have a build-step which uses buildbot.steps.transfer.FileUpload to upload a zip file  (~30MB) from worker to the master.

This step usually takes about 10s. But sometimes this upload takes upto few **hours** (varies significantly). Upload is always successful. However, this makes these builders very inefficient.

It seems that my master is using 100% cpu (on one of the core) consistently. Multiple workers from different builders might be doing upload at the same time.

Buildbot master: 0.9.12, Twisted: 17.5.0, Python: 2.7.5
workers: 0.8.12

What could be the reason for such inefficiency during upload?

**Comment by tardyp** [comment]
FileUpload is not very efficient as it goes via pb. I would advise you to use scp instead of FileUpload in a case of high load. (or Artifactory/Nexus)

**Comment by anish** [comment]
Hackish workaround that is not recommended, but try doing this in your buildbot.tac : 
```
from twisted.spread import banana
banana.SIZE_LIMIT = 1024*1024*40
```

**Comment by tardyp** [comment]
@anish You would need to do that on both workers and master, right?

**Comment by anish** [comment]
Yes. If you do it only on one side, depending on chosen value it might fail the whole upload. This also is still a lot slower than scp

**Comment by krf** [comment]
Could you explain what the problem with `FileUpload` is, in detail? We're just experiencing this issue, but we do not want to resort to using `scp` yet. We need a (ideally) builtin-in and cross-platform solution for file uploads...

**Comment by kallisti5** [comment]
FileUpload is *very* slow.  We really wanted to move to it since our buildbot-master lives in a container. It's a lot cleaner from a design standpoint to allow buildbot to upload artifacts to buildbot and place in a shared persistent docker volume.

At the moment we are seeing 104KB/s upload on a link that should be able to do a "few MB/s".

**Comment by kallisti5** [comment]
The default blocksize is 16KB.  I tried bumping to 64KB to see if we see an improvement in speeds:

* 16KB   -   104 KB/s averaged over 10 seconds by monitoring destination tmp file.
* 64KB   -   353 KB/s averaged over 10 seconds by monitoring destination tmp file.

In the world of static go binaries and other large artifacts, I think raising the default blocksize might be prudent?

**Comment by tardyp** [comment]
Using FileUpload for large files is not recommended. Artifactory or Nexus are two nice options for such things .

Problem with FileUpload is that it uses the only worker/master tcp stream so when a big files is being transfered, if you happen to have other builds on the same machine at the same time, the updates may stall during the transfer, up to the point you could have the 20min no update timeout for shell commands. (I experienced that some time ago)

**Comment by seankelly** [comment]
But that change must be done across all existing workers. A better solution would be to support workers connecting via HTTP.

**Comment by krf** [comment]
Not that it helps resolving this particular issue a lot, but I thought I'd share the workaround we're doing right now (we just use rsync & pscp to transfer files):

```
# ...
def getPackagesList(step):
    return ...; # returns the list of packages which shall be transferred to the remote host
def getProjectPath(step):
    # note: projectname is a custom property
    return os.path.join(step.getProperty('projectname'), step.getProperty('platform'))

def getPackagesPath(step):
    return os.path.join('public_html/packages', getProjectPath(step))

class PackagesUpload(ShellCommand):
    """Uses rsync on Unix and pscp on Windows, to upload files to the remote host

    @brief Upload packages in $BUILD_DIR/packages to master instance"""

    name = description = descriptionDone = 'packages upload'
    haltOnFailure = True 

    def __init__(self, dest, **kwargs):
        ShellCommand.__init__(self, locks=[workerUploadStepLock.access('counting')], **kwargs)

        self.dest = dest 

    def start(self):
        packagesList = getPackagesList(self)

        if self.getProperty('platform').startswith("windows"):
            self.command = ["pscp", "-r", "-v"]
        else:
            self.command = ["rsync", "-avr", "-e", "ssh"]
        self.command += packagesList + [self.dest + ":" + getPackagesPath(self)]
        ShellCommand.start(self)

    def finished(self, results):
        for package in getPackagesList(self):
            packageBaseName = os.path.basename(package)
            packagePath = os.path.join(getProjectPath(self), packageBaseName)
            self.addURL(packageBaseName, getPackagesUploadLocationPrefix() + packagePath)
        ShellCommand.finished(self, results)
# ...

# Usage:
factory.addStep(PackagesUpload(dest=BUILDMASTER_USER+"@"+BUILDMASTER_HOST)
```

PS: We have tons of custom code for dealing with things like that; I hope I gave you a sufficient idea how that is implemented/works.

**Comment by tardyp** [comment]
I don't think there is a huge reason beyond the fact that huge downloads will block the worker master pipe for that worker. If you don't see any drawbacks in your prod for a while, I'd say we should move to this new default
