### ISSUE TITLE
[ui] Running build show wrong time

### ISSUE THREAD

**Issue by pohmelie** [buildbot/buildbot#3714]
When build is active (yellow) and you click on pulsing bubble, then window below appear. First 500-1000 ms its building time string looks like at picture (and this is exactly negative time since epoch). Looks easy to fix for those who is familiar with codebase.
![screenshot_2017-10-24_18-02-22](https://user-images.githubusercontent.com/2385765/31951103-da95aa58-b8e5-11e7-9237-5f1be76b9471.png)

**Comment by tardyp** [comment]
It is indeed probably not a complicated fix. 
Anybody wanting to take a look, the problem probably is easily fixable here: 

https://github.com/buildbot/buildbot/blob/master/www/base/src/app/common/filters/moment/moment.filter.coffee

**Comment by nasirhemed** [comment]
Can I work on this ?

**Comment by tardyp** [comment]
@nasirhemed yes please! don't hesitate to send a PR.

instruction to start developing JS in buildbot can be found here: 
https://docs.buildbot.net/latest/developer/quickstart.html#hacking-the-buildbot-javascript

**Comment by nasirhemed** [comment]
@tardyp 
This issue has been fixed. I wasn't able to reference this issue.

**Comment by pohmelie** [comment]
You can reference commit message here.

**Comment by nasirhemed** [comment]
Merge pull request #5272 from nasirhemed/bug/ui-negative-epoch

**Comment by pohmelie** [comment]
I can't check this fix, but will close the issue. Feel free to reopen if need.
