### ISSUE TITLE
Cannot Checkout from a repo based on revision

### ISSUE THREAD

**Issue by XuryaX** [buildbot/buildbot#3722]
I am trying to setup buildbot for my repositories. I am using bitbucket and using bit bucket poller( Had to fix it a bit because it did not have authentication parameters support).
The changes are identified properly and the build starts but when buildbot tries to checkout based on revision I get the following error.

```
git reset --hard a065177ac0979bf6ae550e410f6c40ee5497e66b --
 in dir /home/shaurya/buildbot/master/worker/runtests/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['git', 'reset', '--hard', 'a065177ac0979bf6ae550e410f6c40ee5497e66b', '--']
```

And I get the following error and it fails.
```
fatal: Could not parse object 'a065177ac0979bf6ae550e410f6c40ee5497e66b'.
```

But If I start a force build manually on the revision, I get the same error. But when I run the same command on CLI on my repo, the command works.

**Comment by seankelly** [comment]
This usually happens when the wrong branch is checked out. See which branch Buildbot is using and check that revision is in that branch.
