### ISSUE TITLE
AJAX requests buggy/inconsistent in 0.9.12

### ISSUE THREAD

**Issue by jdpipe** [buildbot/buildbot#3727]
I am in the process of setting up buildbot with latest Buildbot 0.9.12 on Ubuntu 14.04 LTS, Python 3.4.3 and Apache2. I have set up Apache2 with HTTPS and the reverse proxy service. However, I omitted to set up mod_proxy_wstunnel. In this case, the web UI fails silently, no AJAX data appears. Only an error in the web browser javascript console can be used to guide the user to find the error.
Can I suggest the AJAX UI be modified to report errors in the AJAX requests, somehow, so that the user can more readily debug issues with this critical part of the web interface?

**Comment by tardyp** [comment]
I think it is duplicate to https://github.com/buildbot/buildbot/issues/3672

**Comment by jdpipe** [comment]
Agreed.
