### ISSUE TITLE
Git Step Skips Fetching Tags for Previously Seen Commits

### ISSUE THREAD

**Issue by rayalan** [buildbot/buildbot#3731]
Current behavior: 

Currently, `Git` (`steps/source/git.py`) does the following for a fetch:
1. Check if the commit for the branch is already available.
2. If not, fetch the branch and any associated tags. 

That means that tags are not always fetch, specifically in this case:
1. Prepare a branch A for release and push it. 
2. Buildbot sees A and builds it.
3. Tag the branch.
4. Advance master.
5. Push master. 

At this point, buildbot will try to build master (which is correct). It will then see that it already has the commit (because it built A) which is correct. However, the problem is this: Buildbot will then skip the fetch, including skipping fetching tags, and thus any part of the build that depends on knowing the latest tags will be wrong. 

---

A simple fix is to strip out the `fetch_required` check and always fetch the branch with its tags. I'm happy to submit that PR. Or is there another way that would be better to fix this issue?

**Comment by tardyp** [comment]
I think the git step is for checking out the source code at the exact point it is supposed to be tested.

So if you want to always fetch the tags, I guess the easiest it to just add a shell command which does 

git fetch --tags %(ss:branch)s

**Comment by estan** [comment]
Could it perhaps check if the build is due to a tag push event, and if so, do the fetch? I'm in the same boat as @rayalan, we want the `commit-description` property, which Buildbot populates using a `git describe`, to be the tag name for tagged builds (those that occur due to a tag push event),. But currently, since the tag is not fetched, it won't be :/ Would be nice if this worked out of the box without an extra manual `git fetch` build step.

**Comment by gavanfantom** [comment]
I'm in the same boat, needing the git tag to be fetched in response to a tag push event. Also, manually adding a git fetch step isn't too easy as it needs ssh credentials to be plumbed through.

I think that a parameter to disable the fetch_required check would do the job here, at least in so far is it would be possible to work around it from master.cfg.

**Comment by p12tic** [comment]
This has been addressed in https://github.com/buildbot/buildbot/pull/7236.
