### ISSUE TITLE
Merges to Master not tested

### ISSUE THREAD

**Issue by XuryaX** [buildbot/buildbot#3746]
I set up buildbot with BitbucketPRPoller & GitPoller. The Bitbucket Poller does not start build tests for PR merges to master. And that is why I setup a GitPoller. 
It seems the GitPoller is not able to checkout from bitbucket and gives the following error.
```
failed with exit code 128: Connection closed by 104.192.143.2^M
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
```

The Bitbucket repo is private and protected using ssh-key but the account the bitbucket instance is running on has ssh-key present and can normally clone. Also the build also requires private repos which get properly cloned but the GitPoller fails.

**Comment by p12tic** [comment]
Closing as GitPoller now supports ssh keys, so even it's keyless config does not work on Buildbot side, there's an obvious workaround.
