### ISSUE TITLE
When developing using "gulp dev proxy", Angular gets default configuration values instead of the ones from the server.

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#3754]
I am following the instructions for "Testing with real data" from [the documentation](https://docs.buildbot.net/current/developer/www-base-app.html), running `gulp dev proxy --host myserver`.  This is really great for productivity!

I'm also at times using a locally installed buildbot master & worker for testing the UI with "fake data"

I am trying to make it so that there's some configuration object passed in to the plugin from the master.cfg, which I can access from the javascript side.   I have this working when running on the local master, using the configuration from the local master.cfg.  

Unfortunately, when I run using `gulp dev proxy --host myserver` I'm not getting the plugin configuration from the remote server.  (nor am I getting the configuration from the local server).  I seem to just be getting hard-coded values that are in the python `MasterConfig` class.

These wrong config values are visible on the `#/about` page.   This bug should be easily reproducible by running 'gulp dev proxy --host nine.buildbot.net'  and looking at the about page on the web UI.     What I see when I do this is values like

```
 buildbotURL = http://localhost:8080/ 
 title = Buildbot 
 titleURL = http://buildbot.net 
```

which are these values 

```
class MasterConfig(util.ComparableMixin, WorkerAPICompatMixin):

    def __init__(self):
        # local import to avoid circular imports
        from buildbot.process import properties
        # default values for all attributes

        # global
        self.title = 'Buildbot'
        self.titleURL = 'http://buildbot.net'
        self.buildbotURL = 'http://localhost:8080/'
```

Furthermore I am sometimes running both the `gulp dev proxy` at localhost:8080 and the locally-installed master at localhost:8010.  When running the proxy, it messes up the configuration on the localhost:8010.  In order to get the locolhost:8010 to show the correct configuration from the local copy of master.cfg I need to kill the proxy and re-run `gulp` inside `www/base`.  I assume that this means that the configuration data is somehow being baked in to the javascript statically?

Is there any way that this could be made to work so that when running `gulp dev proxy` you get the plugin configuration from the remote machine?

Alternatively, is there any way I could get `gulp dev proxy` to use configuration from a local setup file ('proxy.cfg'?) so that it's not using the hard-coded defaults?

**Comment by p12tic** [comment]
We no longer use `gulp dev proxy`, there's a separate devproxy script which should not have issues like this. So I guess I can close the issue.
