### ISSUE TITLE
REST API reverse sorting is incompatible with field selection

### ISSUE THREAD

**Issue by mlabbe** [buildbot/buildbot#3761]
If I request `api/v2/builders/<valid id>/builds?field=number&field=results&order=-number`, I get back:

     {"error": "cannot order on un-selected fields"}

However, if I remove the `-` from `order=-number`, it works as expected.

tested on 0.9.3

**Comment by tardyp** [comment]
fixed since 0.9.4.
https://github.com/buildbot/buildbot/commit/611920a63ea1cf63fb2600848e6a41cdf0ba1287
