### ISSUE TITLE
Multiple nightly builds with the same time and builder do not work

### ISSUE THREAD

**Issue by Hnasar** [buildbot/buildbot#3762]
When multiple Nightly schedulers fire, I get an error in the logs, and none of them actually work.

In my config:
```
for distribution in [1.0, 2.0, 3.0]:
        Nightly(name="nightly-offline-updater-{}".format(distribution),
                builderNames=["Offline Updater"],
                properties={'update_release': distribution},
                hour=22)
```

In the logs:
```
2017-11-16 22:00:00-0500 [-] added buildset 712 to database
2017-11-16 22:00:00-0500 [-] added buildset 713 to database
2017-11-16 22:00:00-0500 [-] added buildset 714 to database
2017-11-16 22:00:01-0500 [-] tried to complete 2 buildrequests, but only completed 1
2017-11-16 22:00:01-0500 [-] Got fatal Exception on DB
        Traceback (most recent call last):
        Failure: buildbot.db.buildrequests.NotClaimedError:
```

I see some other person encountered this last year but I cannot find any bugs which seem like this issue:
https://lists.buildbot.net/pipermail/users/2016-October/000849.html

As a workaround I'll probably switch to a series of Triggerables with one Nightly Trigger, but the configuration is less elegant that way.

**Comment by Hnasar** [comment]
Notably, elsewhere in my config I have

```
for buildername in ("ISO Builder 7.2.0",
                    "ISO Builder Stable",
                    "ISO Builder Unstable"):
        Nightly(name="nightly-{}".format(as_identifier(buildername)),
                builderNames=[buildername],
                hour=22)
```

And that works fine. So it seems like the error only occurs when there is a single builder with multiple Nightly schedulers at the same time.

**Comment by ncondatore** [comment]
This issue still seems to be lingering. We hit it and resolved slightly differently by just adjusting the build kick off times to 1 min apart like so:

for i, buildconfig in enumerate(BUILD_CONFIG_LIST):
        schedulers.NightlyTriggerable(name=f"Nightly-{buildconfig}",
            builderNames=["Buildset"],
            hour=8, minute=i,
            properties={"config": f"{buildconfig}",})
            
Just an alternative solution if 1 minute apart kick off times is acceptable.
