### ISSUE TITLE
Return code ignored for Compile step

### ISSUE THREAD

**Issue by blikjeham** [buildbot/buildbot#3774]
I have a Compile buildstep that calls 'make check' and contains a decodeRC directive to transform the exit status to a warning. Besides the decodeRC, I also have a warningPattern to fetch errors/warnings from the checks. The command looks like this:

```python
make_check = Compile(
    command=['make', 'check'],
    warningPattern='^(WARNING|ERROR).*',
    haltOnFailure=False,
    warnOnFailure=True,
    warnOnWarnings=True,
    decodeRC={
        0: SUCCESS,
        1: WARNINGS,
        2: WARNINGS
    }
)
```

When the 'make check' command fails, e.g. there is no make target called 'check', the return code is 2, but the step is still successful. When the command runs successfully and output matches the warningPattern, the buildstep is set to warning correctly.

I see the following in the twistd.log when the command fails with return code 2:

[Broker,2,x.x.x.x] <RemoteShellCommand '['make', 'check']'> rc=2
step 'make check' complete: success (None)

What am I missing here? I am using buildbot 0.9.13.

**Comment by lancelodliu** [comment]
You may check the return value of your Compile buildstep. `decodeRC` works only for the `ShellCommand` step.

**Comment by tardyp** [comment]
Compile is a subclass of ShellCommand, so it should work. I just made a PR with a fix for this bug.

**Comment by tardyp** [comment]
@blikjeham could you please test if #3793 is working for you

**Comment by blikjeham** [comment]
@tardyp, I have verified that #3793 is working correctly. Thank you very much!
