### ISSUE TITLE
How to use properties generated from `NestedParameter` in `util.Interpolate`?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3779]
These properties come as a dictionary which can not be simply accessed by `util.Interpolate('%(prop:<propname>)s')`. My workaround is using `renderer`. However, is there a clean way to achieve this?

**Comment by tardyp** [comment]
@util.renderer is the clean way to achieve complex things that cannot be done via Interpolate. This allows you to use the full power of python to descrive what you need.

**Comment by XonqNopp** [comment]
Hello. Can you provide a MWE to do this with a renderer? I could not find anything in the docs to know how to get the values of my NestedParameter and I am having a hard time understanding what I am doing wrong...
