### ISSUE TITLE
SingleBranchScheduler with treeStableTimer=None does not build all change

### ISSUE THREAD

**Issue by ostermannc** [buildbot/buildbot#3780]
I would like to trigger a build for each change.
For this I have set treeStableTimer=None in my SingleBranchScheduler.
According documentation it shall do the trick.

Knowing that I have 2 slaves, If I have 4 changes:
The first 2 change are build properly,
The I can see that 2 other build are pending (this looks fine)
But after the 2 first build, then only 1 build is effectively started (that includes the 2 last changes)

I have tried to figure out why but some help would be appreciated

Thank you
Christophe

**Comment by tardyp** [comment]
This looks like related to the collapser, which is on by default.

http://docs.buildbot.net/latest/manual/cfg-builders.html#collapsing-build-requests

**Comment by ostermannc** [comment]
This was my pb.
Thank you very much for this very reactive and efficient support
