### ISSUE TITLE
Modernising our logo

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3785]
After I asked for a buildbot logo in SuperTinyIcons, @arturoacevedob was super kind to propose us two versions of it.
https://github.com/edent/SuperTinyIcons/issues/89

I will post the two versions as separate comments, please vote on the one you prefer.

For reference, old logo is:
<img src="https://raw.githubusercontent.com/buildbot/buildbot-media/master/coordinating-parallel-builds-with-buildbot/pictures/nut.png" width="256">

I think those are already very solid options, feel free to add your own color or shape variation!

**Comment by tardyp** [comment]
![image](https://user-images.githubusercontent.com/109859/33430560-3f87c6be-d5d1-11e7-8763-daf7fea1bd36.png)

**Comment by tardyp** [comment]
![image](https://user-images.githubusercontent.com/109859/33430577-4f8daf06-d5d1-11e7-96b4-b7255b87209c.png)

**Comment by shoelzer** [comment]
This is a nice update to the classic logo and I would be happy with either color. One thing I noticed is that at small sizes the light top face blends in with the light background, and it's hard to identify the hexagon shape. Maybe a slightly darker top face color would help with that?

**Comment by arturoacevedob** [comment]
@shoelzer Once one has been chosen, I'll tweak the shapes for visibility at small sizes. Like you said, one shape and color doesn't fit all :)

**Comment by arturoacevedob** [comment]
I got a feeling you will prefer this thicker version.

<img src="https://user-images.githubusercontent.com/19752150/33440344-58d74318-d5b5-11e7-99d2-01e93767a1e2.png" width="256"> <img src="https://user-images.githubusercontent.com/19752150/33440344-58d74318-d5b5-11e7-99d2-01e93767a1e2.png" width="64"> <img src="https://user-images.githubusercontent.com/19752150/33440344-58d74318-d5b5-11e7-99d2-01e93767a1e2.png" width="32"> <img src="https://user-images.githubusercontent.com/19752150/33440344-58d74318-d5b5-11e7-99d2-01e93767a1e2.png" width="16">

**Comment by sndgeek** [comment]
I like the flatter look concept and general design but, for some reason I can't put a finger on, have a real problem with the yellow/orange crescent slices in the center.  It doesn't declare shading to me, it just looks off.

**Comment by mojca** [comment]
I'm just a random user. I like both versions (violet slightly better). The only strange part is the inner side of the nut.

**Comment by tardyp** [comment]
@arturoacevedob Could you please try and provide a version without the accent color? I agree that it feel strange on 256x256, but it is good for 64x64 and 32x32

**Comment by arturoacevedob** [comment]
<img src="https://user-images.githubusercontent.com/19752150/33498644-c628a0b4-d697-11e7-8620-632bbcbfe3a4.png" width="256"><img src="https://user-images.githubusercontent.com/19752150/33498644-c628a0b4-d697-11e7-8620-632bbcbfe3a4.png" width="64"><img src="https://user-images.githubusercontent.com/19752150/33498644-c628a0b4-d697-11e7-8620-632bbcbfe3a4.png" width="32"><img src="https://user-images.githubusercontent.com/19752150/33498644-c628a0b4-d697-11e7-8620-632bbcbfe3a4.png" width="16">

**Comment by arturoacevedob** [comment]
<img src="https://user-images.githubusercontent.com/19752150/33498710-f80de10c-d697-11e7-95d9-fb98bda66cb5.png" width="256"><img src="https://user-images.githubusercontent.com/19752150/33498710-f80de10c-d697-11e7-95d9-fb98bda66cb5.png" width="64"><img src="https://user-images.githubusercontent.com/19752150/33498710-f80de10c-d697-11e7-95d9-fb98bda66cb5.png" width="32"><img src="https://user-images.githubusercontent.com/19752150/33498710-f80de10c-d697-11e7-95d9-fb98bda66cb5.png" width="16">

**Comment by tardyp** [comment]
@all please switch your vote if you prefer the version without accent color!

**Comment by ewongbb** [comment]
I'm more preferential to the lighter blue accent rather than the purple one..   but I'm not too keen on the inner part of the nut.  it's just strange.. it looks 'ok' in the two smaller sizes (I guess it makes zero difference)
but with the larger sizes.  it's just not natural.  either drop the bottom darker hint or make the whole inside dark.

**Comment by mojca** [comment]
This definitely looks much better than the yellow shade.

At smaller sizes the "shading" indeed makes absolutely no difference (it could just as well be dark without the upper brighter part). It's hard to say whether the additional ring/shading makes the logo better or not at the large sizes (compared to having just a single color).

At the biggest size there is theoretically even sufficient space to draw the threads, but those would only ever be seen on those huge magnification (as good as never), so it's probably not worth it - too complex detail.

Just brainstorming. If you want to avoid having a single color for the inner part, vertical smooth shading could also be used in the SVG :) Like the nut from this picture on wikipedia:

<img src="https://upload.wikimedia.org/wikipedia/commons/3/3f/Internal_and_External_Thread.jpg" width="200px">

Enough from me. The examples are nice as they are, the last batch is certainly better.

**Comment by arturoacevedob** [comment]
Thanks for the feedback! @mojca @ewongbb @sndgeek

I'll make more adjustments shortly.

**Comment by arturoacevedob** [comment]
I've adjusted for visibility at smaller sizes. The 3rd changes shape, saturation and uses @mojca vertical shading. The 4th also changes changes shape, saturation but uses an isometric perspective and drops all shading too.

![artboard2](https://user-images.githubusercontent.com/19752150/33538672-49aab3f4-d888-11e7-89b7-89d127c608dd.png) ![artboard3](https://user-images.githubusercontent.com/19752150/33538673-49be6110-d888-11e7-8533-6ae4622fbb43.png) ![artboard4](https://user-images.githubusercontent.com/19752150/33538674-49cf70e0-d888-11e7-9d5f-8602f5a1868b.png) ![artboard5](https://user-images.githubusercontent.com/19752150/33538675-49e18168-d888-11e7-85b1-08aba6d4fb56.png)

This is what is looks without any inner shading, as requested:

![no shading](https://user-images.githubusercontent.com/19752150/33538922-7a2f6dd4-d889-11e7-815b-df9b79d4ceb9.png) ![no shading 2](https://user-images.githubusercontent.com/19752150/33538923-7a4214de-d889-11e7-8f0f-17affbdfbcbf.png) ![no shading 3](https://user-images.githubusercontent.com/19752150/33538924-7a52ecdc-d889-11e7-92f8-d5f410f4810c.png) ![no shading 4](https://user-images.githubusercontent.com/19752150/33538925-7a64fddc-d889-11e7-978c-31520cc642bc.png)

**Comment by mojca** [comment]
I like the second version better, but it's fair that others cast their votes.

Just a note about small sizes. I have absolutely no idea how other websites deal with it (some apparently have super high resolution images and always scaled them down, some use SVGs, most don't care), but the scaled-down SVG looks better on a high definition screen than the specially-tuned PNG (where each pixel from the image would expand to four physical pixels).

Below are the (magnified) screenshots:

SVG: <img width="208" alt="highdef-svg-small" src="https://user-images.githubusercontent.com/15606/33541891-2c359d54-d8d1-11e7-8c48-e8a5c4dff4a2.png"> PNG: <img width="212" alt="highdef-png-small" src="https://user-images.githubusercontent.com/15606/33541884-230183ba-d8d1-11e7-94c6-39c6d1109fb6.png">

**Comment by tardyp** [comment]
Thanks everyone for the good discussion!
I think we are really enhancing the first proposals. I fear that the initial votes are misleading as probably not everyone did follow the quick activity. 
We will discuss how we move this forward tomorrow at the IRC meeting.
https://docs.google.com/document/d/1SAiv3Tk3lACPFVaCNExTjeU7z7NKCKCfP9_2AZ5lpjE/edit#

**Comment by ewongbb** [comment]
@arturoacevedob  Having seen the results of the adjustments,  I'm going to vote for the one without inner shading.  Thanks for the great work!

**Comment by arturoacevedob** [comment]
That's right @mojca.
Most websites have their graphics exported at different sizes and for different resolution screens, then they strip the metadata and compress them. But that's not enough, that's why I'm doing SVGs.

The ones in this thread are not exported for higher resolution screens (2x, 3x). That's why the SVGs turned PNGs look better. I wish I had a screen like that to see them work though. When this is settled, I'll provide SVGs and bitmaps in all sizes and resolutions.

I strongly advise to use SVGs whenever possible. As you may have noticed, they can be optimized to be under 1000 bytes, most cases under 600. That beats most bitmaps over a 48px 1x, and they will render perfectly anywhere.

**Comment by rjarry** [comment]
Hi all,

I personally prefer the blue version. The purple one is a little too similar to the old logo and I think this would be a good thing to change colors for the future 1.0 release.

![blue](https://user-images.githubusercontent.com/19752150/33498710-f80de10c-d697-11e7-95d9-fb98bda66cb5.png)

@arturoacevedob would it be possible to see the blue version without inner shading? Thanks!

**Comment by arturoacevedob** [comment]
@rjarry 

![256px_](https://user-images.githubusercontent.com/19752150/34227879-5a7984c6-e594-11e7-8197-2d93dcb095a4.png) ![64px](https://user-images.githubusercontent.com/19752150/34227910-74e38b72-e594-11e7-9efc-bea287e0b8a1.png) ![32px](https://user-images.githubusercontent.com/19752150/34227916-7d9fd1e4-e594-11e7-83fa-ba0818db91e7.png) ![16px](https://user-images.githubusercontent.com/19752150/34227922-82be5452-e594-11e7-845d-02733dd12f70.png)

**Comment by rjarry** [comment]
Thanks @arturoacevedob!

**Comment by tardyp** [comment]
I also prefer the blue version with inner shading. I just tried to implement the shading with an svg gradiant. I also added a light border to add a bit of contrast.
<div><img src="https://nine.buildbot.net/img/icon.svg" width="256">
<img src="https://nine.buildbot.net/img/icon.svg" width="64">
<img src="https://nine.buildbot.net/img/icon.svg" width="32">
<img src="https://nine.buildbot.net/img/icon.svg" width="16"></div>

I installed that in https://nine.buildbot.net, but I am not very happy with the 16pix scaled down version
![image](https://user-images.githubusercontent.com/109859/34321105-8edca570-e807-11e7-9fde-e04afd74ee3d.png)

@arturoacevedob any suggestion on how we can make a specific version for 32 and 16 widths?

**Comment by rjarry** [comment]
Awesome @tardyp !

**Comment by tardyp** [comment]
I played a bit with inkscape to try and make 16pix version:
![image](https://user-images.githubusercontent.com/109859/34325988-bc7156ac-e8a2-11e7-9353-d9ea6421ca55.png)


I simplified a lot the colors, so that there is only one color, and black.
With this, I can implement automatic selection of the favicon color accoding to the build results :)

![image](https://user-images.githubusercontent.com/109859/34325976-71fc7638-e8a2-11e7-9af9-36eeae861dbd.png)

I deployed that in https://nine.buildbot.net/#/builders/9/builds/1782/steps/6/logs/stdio

**Comment by rjarry** [comment]
Nice idea @tardyp :)

Shouldn't you be preparing Xmas Eve ? LOL
