### ISSUE TITLE
In buildbot web UI, inconsistent use of "pointer" mouse cursor

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#3795]
We have had feedback from some of our users that it's difficult to know which things in the Buildbot UI are supposed to be clickable and which ones are not.

One good example appears in the upper right of the Build Summary page:
![image](https://user-images.githubusercontent.com/2461007/33499051-36e79400-d688-11e7-98fd-edb2a257e5c7.png)

When you mouse-over this "..." yellow rectangle, the cursor changes to "pointer", leading the user to believe that they could interact with the element by clicking on it.   It actually does nothing when you click on it.  (User feedback indicates that the user is unsure that nothing happened, maybe something happened that they just did not notice.)    

By contrast the green rectangle next to it is actually a clickable link to the builder which triggered.  Both rectangles use the pointer cursor but only one is clickable.

On the other hand, on the "Builders" page there is an example of something which is clickable but does not use the "pointer" style

![image](https://user-images.githubusercontent.com/2461007/33499344-68031cca-d689-11e7-8697-71d386b9f3fd.png)

Looking in why the yellow rectangle changes to "pointer" I see that there is a css rule which says

```
.label {
  cursor: pointer
}
```

and the jade code which causes the yellow rectangle to appear is

```
                .label(ng-class="results2class(buildsummary.build)")
                  | {{results2text(buildsummary.build)}}

```
(from buildsummary.tpl.jade)

This css rule which says "all labels should use cursor:pointer" seems wrong, since clearly all labels are not clickable.  

I'm tempted to submit a pull request to just remove this css rule, but I'm not sure what negative impact it would have.  

For the green clickable rectangle, the code is:

the green (clickable) rectangle uses this code, so would probably have the 
```
                span(ng-if="buildsummary.parentbuild")
                    | #{' '}
                    a.label(ng-class="results2class(buildsummary.parentbuild)",
                    ui-sref="build({builder:buildsummary.parentbuilder.builderid, build:buildsummary.parentbuild.number})")
                          | {{buildsummary.parentrelationship}}:
                          | {{buildsummary.parentbuilder.name}}/{{buildsummary.parentbuild.number}}
```

and so it would probably still invoke the pointer icon since it has the explicit `a` (hyperlink).

But there are probably other places where the "label" style is used for something that's clickable using ng-click and removing `cursor:pointer` from `label` would cause the pointer to stop appearing in places where it should.  I was hoping someone with some more knowledge of the UI could comment on this.

My suggestion would be to have a more explicitly named style:

```
.clickable {
  cursor: pointer
}
```

and only apply it to things which are clickable but are not already using  `<a>`  to invoke the pointer-style cursor

**Comment by tardyp** [comment]
Hi @uglycoyote I think you did a good investigation already and you are very near a working PR.

You can watch the web dev tutorial here for a quick setup:
https://medium.com/buildbot/buildbot-ui-plugin-for-python-developer-ef9dcfdedac0

Then, you can edit https://github.com/buildbot/buildbot/blob/master/www/base/src/styles/styles.less#L28 to add the .clickable snippet.
Then grep in the .jade files looking for .label, and add the clickable if needed.
