### ISSUE TITLE
gulp-shell is considered an anti-pattern

### ISSUE THREAD

**Issue by simevo** [buildbot/buildbot#3802]
Please replace the `gulp-shell` dependency in `www` module with one of the alternative spells, see:
https://github.com/sun-zheng-an/gulp-shell/issues/55

Reducing the dependencies will also make it easier to update buildbot in debian/ubuntu, see:
https://bugs.debian.org/790241

Thanks !

**Comment by p12tic** [comment]
We no longer use gulp-based build system anymore.
