### ISSUE TITLE
Two workers pages

### ISSUE THREAD

**Issue by pmisik** [buildbot/buildbot#3818]
Is it intentional that after upgrade to 0.9.14 there are two worker pages?

![image](https://user-images.githubusercontent.com/14224662/33856118-5667756a-dec7-11e7-9e6e-45752efc8f60.png)

**Comment by minextu** [comment]
Seems to be caused by the addition of worker actions to the ui (https://github.com/buildbot/buildbot/commit/0576456e071549882c6807a74910b452e560b822)
