### ISSUE TITLE
Waterfall displays wrong builder names

### ISSUE THREAD

**Issue by kleag** [buildbot/buildbot#3819]
In the waterfall view of my project (using buildbot 0.9.14, updated from 0.8.12), some of the workers columns get the name from other ones. E.g.: the **console view** column "A" points to "http://host:8010/#/builders/14", but the **waterfall view** column "A" points to "http://host:8010/#/builders/10" which is in fact "B".

This happens for the 6 workers coming from a given git project but not for the 4 coming from another one.

**Comment by Hnasar** [comment]
I've seen this too. Thanks for filing a ticket

**Comment by tichy3000** [comment]
I've just filed the ticket #3942 which describes most likely the same problem.
But I named it "Waterfall displays wrong builder names", which is more appropriate, I think.

**Comment by kleag** [comment]
This makes the Waterfall view completely useless. Is this bug on someone's todo list ?

**Comment by tardyp** [comment]
Hi, @kleag looks like nobody has this bug in its todo list, yet. Feel free to take a look at it.

After a quick look, it is possible that the following scale calculation is not correct for your usecases.

https://github.com/tardyp/buildbot/blob/74f8f0f49a029590f95024c8a0a13aae5f471510/www/waterfall_view/src/module/scale/scale.service.coffee#L47

maybe the localeCompare is a smell. I am not sure.

For a quick start on plugin development:
https://medium.com/buildbot/buildbot-ui-plugin-for-python-developer-ef9dcfdedac0

**Comment by kleag** [comment]
Hi @tardyp, thanks for the information. I will maybe have a look later but I have never wrote nor sudied any javascript and I'm also not a powerful python developer even if I am getting some experience. The only experience I have in GUI coding is in C++ with Qt widgets. So, I'm not sure I will be able to understand the code enough to correct it.
