### ISSUE TITLE
umask for master process is set to 0

### ISSUE THREAD

**Issue by eugene-katsevman** [buildbot/buildbot#3878]
On my system when I do `buildbot restart master` twisted is run as a daemon and its umask is set to 0.

This leads to all work and build directories of local workers and master itself having 777 permissions

**Comment by tardyp** [comment]
Hi,
I cannot reproduce this.

I would appreciate a little bit more details.

in your buildbot.tac, do you have those lines:
```
# Default umask for server
umask = None
```

There is no difference between ```buildbot restart``` and ```buildbot start``` in how the process is starting.
You can add a log here to see if this is buildbot which is setting the umask:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/master.py#L230

**Comment by eugene-katsevman** [comment]
Hey, thanks for the quick response!
I've modified umask in buildbot.tac to have 0o22 value and by logging I can confirm that this value is being set (where you pointed at).
But!
I've connected with gdb to twisted process and `call/o umask(0)` gives me 0 immediately. Repo workdir is being created with 777 permission.
If it helps, I'm using a single LocalWorker.

I can provide any other info you need, I just don't know what to.

**Comment by eugene-katsevman** [comment]
an update - umask for localworker is False for whatever reason

    2018-01-06 17:37:16+0300 [-] Starting Worker -- version: 0.9.15
    2018-01-06 17:37:16+0300 [-] with the umask False

**Comment by tardyp** [comment]
can you try the fix in #3881 ?

**Comment by eugene-katsevman** [comment]
It works! Thanks!
