### ISSUE TITLE
The First Run with Docker instructions are pointing to the wrong port

### ISSUE THREAD

**Issue by alexwlchan** [buildbot/buildbot#3897]
I tried to follow §1.2.3 of http://docs.buildbot.net/current/tutorial/docker.html#first-run-docker-label to get Buildbot working with Docker. I used the following commands, copied from the tutorial:

```console
$ git clone --depth 1 https://github.com/buildbot/buildbot-docker-example-config
$ cd buildbot-docker-example-config/simple
$ docker-compose up
```

FWIW, this checks out that repo at commit c56d888dd3ddfab269aee0d7cfbb6a7a4dc75f3a.

A bunch of stuff appears in my console, and I can see I have several containers running:

```
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
d464ef0d84f7        buildbot/buildbot-worker:master   "/usr/local/bin/du..."   17 minutes ago      Up About a minute                            simple_worker_1
e7254585af13        buildbot/buildbot-master:master   "dumb-init /usr/sr..."   17 minutes ago      Up About a minute   0.0.0.0:8080->8080/tcp   simple_buildbot_1
51b5ffe20a1d        postgres:9.4                      "docker-entrypoint..."   17 minutes ago      Up About a minute   5432/tcp                 simple_db_1
```

The instructions then tell me to visit http://localhost:8010, and I'll see the web interface. That doesn't work, but if I visit http://localhost:8080 (as suggested by the output of `docker ps`), I see the web interface.

The instructions should be corrected to use the right port, or the docker-compose file should be changed to match the instructions.

**Comment by seankelly** [comment]
Pretty sure this is fixed.
