### ISSUE TITLE
Builder page should display worker name instead of id

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3901]
Builders page (http://nine.buildbot.net/#/builders) has workers column on the right which is very useful. However, it displays an id, instead of the worker name. On hover-over it displays the worker name. The worker name should be displayed by default.

Builders page is useful in providing a quick summary of all the builders and worker status. It shows a quick overview of which workers are up and which are down. Displaying worker name would be better as it would quickly show which particular worker are down, and which particular workers are associated with which builder. We can't expect people to remember the id of each worker, whereas name of worker is easily identifiable.

I believe it should be a simple change in https://git.io/vNg3p to always show worker.name

**Comment by rodrigc** [comment]
I agree with you!
