### ISSUE TITLE
Owner column is always empty on Builder page

### ISSUE THREAD

**Issue by ila321** [buildbot/buildbot#3904]
Owner column seems to be always empty on the Builder page. e.g.: https://nine.buildbot.net/#/builders/3

Also, we should remove this column and add columns for more meaningful information like revision, worker-name on this page.

**Comment by Frodox** [comment]
dup of #3311 actually

**Comment by krf** [comment]
Bump. Close this since it's a dup?

**Comment by p12tic** [comment]
Fixed.
