### ISSUE TITLE
Web UI User settings should have defaults configurable in master.cfg

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3908]
c['www']['default_ui_settings'] = {
'Builders.buildFetchLimit': 1000
}

This can be done easily by whitelisting in https://github.com/buildbot/buildbot/blob/master/master/buildbot/config.py#L807
And the the settings module in the UI can fetch its default value there (overriding the default hardcoded in the coffee)

**Comment by ila321** [comment]
This would be awesome.
