### ISSUE TITLE
Source steps override the branch kwarg specified by the developer

### ISSUE THREAD

**Issue by tterrace** [buildbot/buildbot#3922]
Hi, if I'm using a source step and I specify the branch parameter explicitly:

```
build.addStep(Git(repourl="ssh://.....chef-repo.git",
                               branch=Property('chef_branch'),
                               mode='full',
                               method='fresh')) 
```

Buildbot is overriding my branch kwarg with whatever happens to be in the "branch" property at runtime, which seems wrong. Wouldn't it be better to only override if the branch kwarg is None? 

Am i missing some other way to use two Git steps to check out from two separate repositories in the same build?

**Comment by tardyp** [comment]
Hi,
Buildbot automatically setup branch to be the one from the change, if your build is triggered from a change.

You need to use codebases if you want to use several source steps.
http://docs.buildbot.net/latest/manual/concepts.html#codebase
Basically, you will just have to tell your step that the codebase="chef" is to be used for that git checkout, and buildbot will not replace your branch configuration by the one from the change.

**Comment by tterrace** [comment]
Thanks Pierre, I have everything working:

```python
    codebases=[
        CodebaseParameter(
            codebase='',
            branch=StringParameter(name=u"branch",
                                   label="branch (req):<br>",
                                   required=True,
                                   size=80),
            revision=FixedParameter(name=u"revision", default=""),
            repository=FixedParameter(name=u"repository", default=""),
            project=FixedParameter(name=u"project", default=""),
        ),
        CodebaseParameter(
            codebase='chef',
            branch=StringParameter(name=u"branch",
                                   label="Chef branch:<br>",
                                   required=True,
                                   size=80,
                                   default="master"),
            revision=FixedParameter(name=u"revision", default=""),
            repository=FixedParameter(name=u"repository", default=""),
            project=FixedParameter(name=u"project", default=""),
        ),
    ],
```

I'm going to close this out but I have another quick question if you don't mind: is there a way to get the branch for my chef codebase above as a property (previously with a single codebase I used: `WithProperties("%(branch)s")`)?

**Comment by tterrace** [comment]
I ended up making a custom class modeled off of `_SourceStampDict`:

```python
class WithCodebaseBranch(_SourceStampDict):
    implements(IRenderable)

    def __init__(self, codebase):
        super(WithCodebaseBranch, self).__init__(codebase)

    def getRenderingFor(self, build):
        ss = build.getBuild().getSourceStamp(self.codebase)
        assert ss
        return ss.branch
```
