### ISSUE TITLE
Configurable sorting/expanding behaviour for logs, in builds steps with multiple logs

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#3923]
Our build steps usually have a number of log file which can all be useful if you really need details about a build failure, but we also create a "Summary" log which is designed to be as concise as possible and include just the information that people would usually want to know about the failure.

When displaying the Build Summary, we would like to be able to change the sorting order of the logs so that our Summary log comes first.  We would also like to make it so that the summary log is automatically expanded.   I'm aware that there's something in '''buildsummary.tpl.jade''' (step.fulldisplay) which causes it to auto-expand a log when the step fails.   But I believe as it is currently implemented it only does this for steps that have only one log.    

With regards to the ordering of the logs, it currently seems that the ordering is identicaly to the order that the logs appear in the json data.  We investigated changing the order on the server side, but it seems difficult to get our summary log to be added before the stdio log, and seems like something more easily addressed on the javascript UI side.

The following questions are probably for @tardyp : 

I would like to implement our a custom behaviour for sorting and expanding the logs, but rather than hack '''buildsummary.tpl.jade''' and the related directive class, I'm wondering if there's a good way to make this configurable by some kind of a service or configuration object that's injected into the BuildSummary Controller class, such that I could contribute the changes back as a pull request without the specifics of the sorting behaviour being hard-coded.  

I'm imagining a service that implements a one function, which, given a build step and the collection of logs associated with it, returns the sorted list of logs, and communicated somehow which logs should be auto-expanded (perhaps by stuffing a new javascript property into the log object, or perhaps by returning an extra list or map of boolean values)

The default buildbot implementation could just return the logs in the same order that they were given and not change their sorting or expanded state. 

I'm wondering if there's any examples in the codebase of how you can have different versions of the same service, like a default service that gets overridden by a more specific implementation for configuration purposes?  When using ng-classify, it is generating those constructor calls by magic name-matching, so it's not clear to me how I could set something up where we can override a service for configuration purposes.  

Is dependency injecting different versions of the same service the way to go about making this configurable?   If not, what do you suggest as an alternative, and if so, do you have any examples of how to achieve this?

**Comment by tardyp** [comment]
Hi,
I think you usecase totally make sense in a generic manner. I mean probably it is not worth to try and implement it in a custom plugin.
I am not aware of a method where you can override a dependency injected stuff in angular. I think angular will just crash if you give it to stuff with the same name.

In order to resolve your problem, I think a reasonable way would be to claim that "summary" is a well-known name for summaries, and if there are multiple logs in a step, but one is named "summary", then only summary would be auto-expended.

Then if you really require several logs to be auto expended, I don't know how we can make it simple enough. 
I think you summary generator could just include the appropriate snippets from the other logs

**Comment by sphet** [comment]
@tardyp would it also make sense to put the summary log at the top of the list of logs if it is present? Seems sensible to me.

**Comment by uglycoyote** [comment]
@tardyp thanks for your input.  Since you think this behavior makes sense generally, I'll try to propose a pull request soon which behaves as follows:  if there are multiple logs and one is called "Summary", it 1) sort summary to top of list of logs 2) auto expand summary log if the step has failed.

I think Angular does generally support injecting different versions of the same service (or you might call them different services with the same interface, they would have to have different names).  After all, one of the main goals of dependency injection is to allow services to be mocked for testing purposes. The angular dependency injection docs also talk about it as a way to allow configurability.  But again I am having some struggles with squaring the angular examples with the way things are working in the coffee/ngClassify world.  I agree with you that for this specific application, this kind of configurability is not required if the idea of a summary log seems like a useful concept for other users.   Whatever code I add should not change the behavior for users who are not taking advantage of it.
