### ISSUE TITLE
How to navigate to plugin class in IDE?

### ISSUE THREAD

**Issue by baverman** [buildbot/buildbot#3925]
For example:
    
```
from buildbot.plugins import *
c['workers'] = [worker.Worker("worker", "pass")]
```

There is no way how to know where is `Worker` is defined, besides greping of buildbot sources. Why plugins should place themselves in strict tree and play with `entry_points` to picked by buildbot dynamically later? `master.cfg` can do static imports of needed classes. Inability to see code is complicated by poor documentation of various buildbot parts.

How about to drop `get_plugins()`?

**Comment by baverman** [comment]
Note: Flask deprecated extensions long ago. They bring more problems then solving any.

**Comment by tardyp** [comment]
The goal of plugin namespace has two goals:

- ability to have external plugins behave exactly like builtins.
- ability to later change the implementation location without breaking compatibility.

You can always import the real path, but this may break in the future (however unlikely)

dropping get_plugins will fail the goal of long term support goal, obviously, people will have to rewrite their master.cfg to use components where they are.

**Comment by baverman** [comment]
> ability to have external plugins behave exactly like builtins.

The only thing come to mind is ability to do something during plugin traversing and loading implicitly. It's good point, but explicit is better then implicit. Imports are a way cleaner and safer for that task.

> ability to later change the implementation location without breaking compatibility

Very weak argument. It's more likely that you change ISomething interface than import path. For hundreds other libraries and frameworks it is not a problem at all.

> people will have to rewrite their master.cfg to use components where they are.

Again, import path changes can be linked to major API tweaks for which users will have to upgrade master.cfg anyway. I can't imagine refactoring that will include only module renaming, it's ridiculous to guard users from such changes and force it to guess constructor arguments.

Buildbot is framework to create own CI/CD at first place, not a final solution for which you must keep backward configuration compatibility. Code navigation is vital part of configuration process.

Question for all developers. How to navigate to plugin class from master.cfg in IDE? How do you edit buildbot configurations?

**Comment by tardyp** [comment]
On Thu, Feb 1, 2018 at 12:49 PM Anton Bobrov <notifications@github.com>
wrote:

> Very weak argument. It's more likely that you change ISomething interface
> than import path. For hundreds other libraries and frameworks it is not a
> problem at all.
>
> I agree it is not a perfect argument.
Another argument I forgot in the first place, is to avoid the lots of
imports on top of master.cfg which people were complaining about. You just
import buildbot.plugins.* and that's it.

With the experience I agree that it adds more problem than it solves (most
important one to me is that we often, not to say always forgot to update
setup.py when we add a new component).
But.. now the decision has been taken it is difficult to go backward.

> people will have to rewrite their master.cfg to use components where they
> are.
>
> Again, import path changes can be linked to major API tweaks for which
> users will have to upgrade master.cfg anyway. I can't imagine refactoring
> that will include only module renaming, it's ridiculous to guard users from
> such changes and force it to guess constructor arguments.
>
[please avoid "ridiculous" or "very weak" or such terms in your internet
discussions, as it quickly involve emotions and non constructive
discussions]

What I mean here is that if we want to drop the plugin infrastructure, this
will break the compatibility for people who are happy with it.

We can also start documenting both way to access components, and let people
choose. That is a lot of work, which also has the drawback of adding
confusion for new users.

Buildbot is framework to create own CI/CD at first place, not a final
> solution for which you must keep backward configuration compatibility. Code
> navigation is vital part of configuration process.
>
> Question for all developers. How to navigate to plugin class from
> master.cfg in IDE? How do you edit buildbot configurations?
>
I just use the search all code feature of my ide, which usually answers
under 1s for buildbot.
But when I write master.cfg,  the documentation should be resolve 99% of
questions. If it is not we need to enhance the documentation.

**Comment by baverman** [comment]
@tardyp thank you for your answers. I apologize for being so emotional, my bad.
