### ISSUE TITLE
Buildbot should have API to fetch all builds for a revision

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3927]
Buildbot does not have a easy way to fetch all the builds corresponding to a revision. Please see: 
https://github.com/buildbot/buildbot/issues/3926

Buildbot should have a API to fetch all the builds information corresponding to the revision. e.g.: "/changes/i:revision/builds" or "/revisions/i:revision/builds"

**Comment by uglycoyote** [comment]
I agree, the way the data is laid out right now makes it very difficult to associate builds with changes
