### ISSUE TITLE
buildrequests API doesn't provide properties data

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3929]
[http://nine.buildbot.net/api/v2/builders/1/builds?limit=2&property=*](http://nine.buildbot.net/api/v2/builders/1/builds?limit=2&property=*) includes all the build properties.

However [http://nine.buildbot.net/api/v2/builders/1/buildrequests?limit=2&property=*](http://nine.buildbot.net/api/v2/builders/1/buildrequests?limit=2&property=*) does not include the build properties.

"property=*" filter seems to work only for builds, but not for buildrequests.

Also, there doesn't seems to be any way to fetch the buildrequest properties through the API.

Following buildrequests API also doesn't provide properties information:
[http://nine.buildbot.net/api/v2/buildrequests?limit=2&property=*](http://nine.buildbot.net/api/v2/buildrequests?limit=2&property=*)
[http://nine.buildbot.net/api/v2/buildrequests/1?property=*](http://nine.buildbot.net/api/v2/buildrequests/1?property=*)

**Comment by tardyp** [comment]
Hi, in the data model, there is no such thing as buildrequest properties actually.

Properties are attached to buildsets, and available via rest api like this:

http://nine.buildbot.net/api/v2/buildsets/1/properties
so you first need to get the buildsetid from the buildrequest data.
