### ISSUE TITLE
Buildbot can`t encode unicode character

### ISSUE THREAD

**Issue by adydychk** [buildbot/buildbot#3932]
I have the problem with unicode symbols.
My configuration of Buildbot starts the scripts which use unicode symbols such as ✅ (\u2705) in this case I get the following error in Buildbot`s web console:
```python
Traceback (most recent call last):
  ...
  File "C:\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
```

It was reproduced *only* on Windows (it is fine on Linux). If I start the script in Windows console - it is also works fine. I mean there isn\`t any exceptions.  
My Buildbot`s version is 0.9.15post1.

**Comment by adydychk** [comment]
Hm, I am not sure but maybe this issues is similar to: https://github.com/buildbot/buildbot/issues/3799

**Comment by lancelodliu** [comment]
Where is the unicode symbol used in your case?

**Comment by adydychk** [comment]
@lancelodliu My flow:  
When Buildbot is triggered before the build it starts special Python script (as `build_factory.addStep(steps.ShellCommand(command=...))`). This script checks sources and prints the output about the result of this check. In this output I use unicode symbols (like ✅ if check passed).
When I start this script in Windows console (for tests) I don\`t get any exceptions but if Buildbot starts it I see `UnicodeEncodeError` exception.  
  
So to reproduce it, start a script from Buildbot on Windows with following code `print(u"\u2705")` .

I hope that I explained it more clearly if you have more questions I am glad to answer on them.

**Comment by lancelodliu** [comment]
@adydychk My case is different from yours. The problem happens when the `command` contains unicode characters. And the code contains `print(u"\u2705")` works fine in my case.
I am using 0.9.11 and python 2.7.13.

**Comment by adydychk** [comment]
Great, we will test it in new Buildbot stable drop and will close this issue if our case will be fixed.
