### ISSUE TITLE
Add capability to override the default console view settings

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3933]
https://github.com/buildbot/buildbot/pull/3924 added ability to override the default UI settings through master.cfg

We should also have this ability for console view. Specifically "Number of builds to fetch" is too low for larger buildbot instances where there are large (few hundred builds) running every hour. In such instances most of the time console view does not display builds associated with recent changes. This makes the console view almost useless for the developers who open it to check the status of their recent commit.

Admin should have the ability to increase the default (of 200) to higher value through master.cfg instead of trying to educate each user about why console view doesn't work for them and what value to configure for this setting.

**Comment by tardyp** [comment]
#3924 also works for console view.

**Comment by aj062** [comment]
Thanks. Seems to work fine in Buildbot 1.0
