### ISSUE TITLE
Can't use secret interpolation in p4poller.P4Source and steps.P4

### ISSUE THREAD

**Issue by tichy3000** [buildbot/buildbot#3954]
I tried to use secrets for perforce passwords (using buildbot 1.0.0).

First I tried to use it in the P4 change source:
p4ChangeSource = p4poller.P4Source(p4port=p4Port,
                                                           p4user=p4User,
                                                           p4passwd=util.Secret('p4passwd'),
                                                           ...)
which fails with:
... [-] P4 poll failed ..
...
exceptions.TypeError: Arguments contain a non-string value

Then I tried to use the secret in the P4 source checkout step:
factory.addStep(steps.P4(p4port=p4Port,
                         ...,
                         p4passwd=util.Secret('p4passwd'),
                         ....)
This fails with:
Upon execvpe p4 ['p4', ..., '-P', Unpersistable('Unpersistable data: instance of class buildbot.process.properties.Secret deemed insecure'), ...] in environment id 56699632
:Traceback (most recent call last):
  File "/.../internet/process.py", line 445, in _fork environment)
  File "/.../internet/process.py", line 523, in _execChild os.execvpe(executable, args, environment)
  File "/.../lib/python2.7/os.py", line 353, in execvpe _execvpe(file, args, env)
  File "/.../lib/python2.7/os.py", line 380, in _execvpe func(fullname, *argrest)
TypeError: coercing to Unicode: need string or buffer, instance found

I suppose, the secrets are still not implemented for perforce functions.
Or am I doing something wrong?

**Comment by lancelodliu** [comment]
`p4passwd` is not renderable in these two class.

**Comment by aisoard** [comment]
This issue is still present in Buildbot version: 1.7.0
