### ISSUE TITLE
Version 1.0.0 of the buildbot/buildbot-worker docker image is missing.

### ISSUE THREAD

**Issue by chrwen-omicron** [buildbot/buildbot#3965]
I can't find a version 1.0.0 buildbot-worker docker image on Docker Hub.

https://hub.docker.com/r/buildbot/buildbot-worker/tags/

**Comment by tardyp** [comment]
thanks for report. I started it manually.
https://hub.docker.com/r/buildbot/buildbot-worker/builds/btcj7q5x4oyh3tpptyfnvff/

**Comment by chrwen-omicron** [comment]
Nice, thanks!
