### ISSUE TITLE
Turn "builder(s) XXX have no schedulers to drive them" into a warning?

### ISSUE THREAD

**Issue by Ricordel** [buildbot/buildbot#3966]
Sometimes, I want to deactivate a builder, for various reasons: it temporarily does not work, I temporarily don't need it, I'll probably never need it again but would prefer to keep it at hand for a few more days/weeks, ...

The most practical way I imagine would be to unlink it from any scheduler that uses it, but then I get this error message telling me that the builder has no scheduler to drive it. It's annoying since it's exactly my point: I don't want any scheduler to drive it.

So questions:
* is there a more intelligent way to temporarily deactivate a builder, that can be done at only one place in the code / config?
* otherwise, does it seem reasonable to you that this error be turned into a warning? Or potentially that we introduce a configuration flag to do so (but keeping the default behavior for people who like it)?

**Comment by tardyp** [comment]
You can setup the multimaster mode in order to disable this error.
http://docs.buildbot.net/latest/manual/cfg-global.html#multi-master-mode

**Comment by Ricordel** [comment]
Oh that's perfect, I was not aware it existed and was looking in this direction at all. Thank you!
