### ISSUE TITLE
POST request to shutdown a worker

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#3967]
Can we have a feature to shutdown a worker using POST request?
Buildbot 8 used to support it with buildmaster:8010/buildslaves/<slave-name>/shutdown

can we have it on buildbot 9 ?

**Comment by tardyp** [comment]
There is already this feature
It is documented there:
http://docs.buildbot.net/latest/developer/rest.html#id30

The best to get an example is to see how the UI is using it.
this function is available in the action menu of workers page.
