### ISSUE TITLE
Login sessions don't timed out

### ISSUE THREAD

**Issue by erkansari** [buildbot/buildbot#3980]
We have buildbot 0.9.14. When we loged in and loged out to buildbot by using an user, we can't login  with another user name. Sessions don't time out. Restarting buildbot or clearing cache of browser didn't solve our problem.

**Comment by tardyp** [comment]
Can you give use more info on your auth setup?
which auth plugin are you using?
what do you mean by logged out?

You can always clear authentication by clearing your cookies.

**Comment by erkansari** [comment]
I use this.
class MyAuth(CustomAuth):
    def check_credentials(self, user, password):
        if user == 'snow' and password == 'white':
            return True
        else:
            return False

and I clear everything again just to be sure. However, when I press login, It didn't ask for password and I logged in as snow.

**Comment by tardyp** [comment]
you need to clear your basicauth cache.

see this SA for possible methods:

https://stackoverflow.com/questions/5957822/how-to-clear-basic-authentication-details-in-chrome
