### ISSUE TITLE
Allow urlText on DirectoryUpload

### ISSUE THREAD

**Issue by dlmiddlecote** [buildbot/buildbot#3983]
`FileUpload` allows you to set the `urlText` for a `url` that is set in the buildstep, but this is not possible for the `DirectoryUpload`, and it is set as `os.path.basename(os.path.normpath(masterdest))` by default.

Can this be changed?

**Comment by tardyp** [comment]
This can be enhanced yes, please don't hesitate to dive in the code, as this is complicated, and you have an example with the FileUpload implementation

**Comment by dlmiddlecote** [comment]
Cool, I’ll submit a PR for it.
