### ISSUE TITLE
mailNotifier can't use Secrets

### ISSUE THREAD

**Issue by trevor-hook** [buildbot/buildbot#3985]
The following settings in my master.cfg prevent buildbot from starting.

```
###### SECRETS

c['secretsProviders'] = [secrets.SecretInAFile("/srv/buildbot/secrets")]

###### NOTIFIERS

mn = reporters.MailNotifier(
    fromaddr="{REDACTED}",
    sendToInterestedUsers=False,
    extraRecipients=[{REDACTED}],
    relayhost="mail3.gridhost.co.uk",
    useSmtps=True,
    smtpPort=465,
    smtpUser="{REDACTED}",
    smtpPassword=util.Interpolate("%(secret:fwm-ftp-password)s"),
    mode=('all')
)
c['services'].append(mn)
```

In the example above, I have changed the secret file being used from one which specifically represents my SMTP password to a different file which is successfully used later on in the same master.cfg so I know the file is accessible and readable by the SecretInAFile system.

I've attached the complete startup log from a typical failed startup.

[twistd.log - Error with Interpolate](https://github.com/buildbot/buildbot/files/1797122/twistd.log)

I have also attempted to use util.Secret() rather than util.Interpolate(). This also results in a failed startup but a slightly different failures. Interpolate reports NoneType errors, Secrets report KeyError. I think these different error types have the same root cause.

[twistd (1).log - Error with Secret](https://github.com/buildbot/buildbot/files/1797175/twistd.1.log)

Directly typing the password into master.cfg for smtpPassword rather than using Interpolate or Secret gives me a working mailNotifier so the rest of the mailNotifier setup is correct and the issue is in the use of Secrets.

Looking at the unittests for mailNotifier, I see there is a test for mailNotifier to be able to use Interpolate but not for it to be provided a full secret, I believe the issue here is in providing the secret rather than mailNotifier correctly swapping in strings hence the unittests passing.

Q. Looking at the mail.py file which implements mailNotifier, I see smtpUser is in the secret list as well, does that mean both fields have to be defined as secrets or is that list used to exclude fields from log messages? (don't know enough of the code to be able to tell without following it down the rabbit hole).

Trevor

**Comment by tardyp** [comment]
thanks for reporting! 
I neglected creating integration tests for this usecase, and indeed, there was an integration issue with that design (the order of configuration of services made the mailnotifier be configured before the secret service)
