### ISSUE TITLE
[Feature request] Filter visible builders in console view

### ISSUE THREAD

**Issue by adydychk** [buildbot/buildbot#4006]
Please, add possibility to filter visible builders in console view by user side.  

Our use-case:  
We have a lot of builders and we need to show them logically in different sets to better understanding the state of our build status. It is not possible on current console view.  
It would be nice if we have the possibility in settings to somehow group them. For example by configuring console view in Buildbot configuration and switching them in runtime by clicking special buttons.

Here is an example:
![image](https://user-images.githubusercontent.com/31437274/37652996-703d4f44-2c4e-11e8-98a8-2877be4209db.png)
In this example if I will press "Tests-view" (and unpress all another) I will see only "test" Builder if I will press "Api-latest view" (and unpress all another) I will see only "build-api-latest" Builder`s builds and so on. If I will press all buttons I will see all Builders.

It would be great if these buttons could be configured - if we could write special scenario for each button for filtering in Buildbot configuration file.

In addition it would be nice to have feature: if we filter (disable viewing) build which has triggered builds then triggered build will be not visible too.

I hope that our feature request is understandable. If you have any questions I will be glad to answer. We are really interested in this feature.

**Comment by mojca** [comment]
Is this the same feature request as #3470?

**Comment by adydychk** [comment]
@mojca Yeah, it seems to be the same.

**Comment by mojca** [comment]
OK, so it probably makes sense to close it as a duplicate then. Thank you.
