### ISSUE TITLE
Secrets leaked by `util.Secret`

### ISSUE THREAD

**Issue by jugglinmike** [buildbot/buildbot#4007]
The	`util.Secret` API is designed to allow users to reference sensitive information without exposing it in log files. In Buildbot versoin 1.1.0, the data is incorrectly emitted to the log files if it has not previously been rendered via the `util.Interpolate` API.

I've included the contents of a `master.cfg` file which demonstrates this behavior and a screenshot of a build created using that file.

    $ buildbot --version
    Buildbot version: 1.1.0
    Twisted version: 17.9.0

(Installed via pip)

```python
import os
from buildbot.plugins import *

secrets_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'secrets')

try:
    os.mkdir(secrets_dir)
except OSError:
    pass

with open('%s/my_secret' % secrets_dir, 'w') as handle:
    handle.write('this is a secret')

os.chmod('%s/my_secret' % secrets_dir, 0600)

secret = util.Secret('my_secret')
interpolation = util.Interpolate('%(secret:my_secret)s')
demo_factory = util.BuildFactory([
    steps.ShellCommand(name='Debug ShellCommand / util.Secret #1',
                       command=['echo', secret]),
    steps.ShellCommand(name='Debug ShellCommand / util.Secret #2',
                       command=['echo', secret]),
    steps.ShellCommand(name='Debug ShellCommand / util.Interpolate',
                       command=['echo', interpolation]),
    steps.ShellCommand(name='Debug ShellCommand / util.Secret #3',
                       command=['echo', secret]),
])

c = BuildmasterConfig = {}
c['schedulers'] = [
  schedulers.ForceScheduler(name='demo', builderNames=['demoBuilder'])
]
c['builders'] = [
    util.BuilderConfig(name='demoBuilder',
                       workernames=['moe'],
                       factory=demo_factory)
]
c['secretsProviders'] = [secrets.SecretInAFile(dirname=secrets_dir)]
c['workers'] = [worker.LocalWorker('moe')]
c['protocols'] = {'pb': {'port': 9989}}
c['services'] = []
c['title'] = 'Demo'
c['titleURL'] = 'Demo'
c['buildbotURL'] = 'http://localhost/'
c['www'] = {'port': 80}
c['db'] = {'db_url': 'sqlite:///state.sqlite'}
```

![screenshot-2018-3-20 buildbot builder demobuilder build 8](https://user-images.githubusercontent.com/677252/37677243-e7f3fe8c-2c50-11e8-9c48-a9551ec15e69.png)

**Comment by tardyp** [comment]
Hi good findings.

Would you like to make a patch for this issue?

It is about adding the line:

        properties.useSecret(secret_detail.value, self.secret_name)

from:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/properties.py#L500

in line 524:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/properties.py#L524

the fix the integration test to also test that Secret is not leaking values:

https://github.com/buildbot/buildbot/blob/master/master/buildbot/test/integration/interop/test_integration_secrets.py#L90

**Comment by endrift** [comment]
Hi, I just had to roll a password because of this. Please fix it, considering you seem to already know how to.

**Comment by jugglinmike** [comment]
Thanks!
