### ISSUE TITLE
'titleURL'  not working ?

### ISSUE THREAD

**Issue by zhouchengming1** [buildbot/buildbot#4009]
Hi, everyone:
I set the master config  c['titleURL']='http://homepage/',
but when I click on the title in the webpage, it doesn't go to my homepage.
So does anyone know why ? Thanks.

**Comment by adydychk** [comment]
Hi,
Buildbot\`s `titleURL` should represent main page of the **Buildbot** (but not the external "homepage").

**Comment by zhouchengming1** [comment]
@adydychk   ,  I thought c['buildbotURL'] is the main page of the Buildbot ?
So how can I set my homepage?  Thanks!

**Comment by adydychk** [comment]
@zhouchengming1 Oh, sorry, my fault. You are right. I checked my Buildbot configuration. For `titleURL` we use following string `f"https://github.com/{GITHUB_REPOSITORY}"`. That is a link on our repository :)
