### ISSUE TITLE
MultipleFileUpload makes directory component part of the filename

### ISSUE THREAD

**Issue by ngladitz** [buildbot/buildbot#4019]
When transferring files from a Windows Buildbot worker to a Linux Buildbot server via something like:

```python
MultipleFileUpload(
  glob=True,
  workersrcs='package/*.exe',
  masterdest="/mnt/buildbot/Installers")
```

Buildbot unexpectedly creates files named like e.g. `package\foo.exe` (where the backslash is part of the filename) at the destination.

**Comment by tardyp** [comment]
@ngladitz I can't test windows vs linux worker/master setup. Could you please verify the fix?

**Comment by ngladitz** [comment]
Seems to work for me, thanks!

**Comment by crossboss** [comment]
As mentioned in #4194, this bug still seems to exist in 1.3.0 (both worker and master)

**Comment by crossboss** [comment]
I think this issue should be re-opened

**Comment by crossboss** [comment]
I am sorry. My test case was flawed after all. Everything works as intended now as far as I can tell.
