### ISSUE TITLE
authz defaults

### ISSUE THREAD

**Issue by betafive** [buildbot/buildbot#4026]
Just installed buildbot v1.1.0 on Ubuntu 16.04 and followed the tutorial (http://docs.buildbot.net/latest/tutorial/index.html). I've added builders, a change source, a scheduler and a worker and builds are being triggered from my git repository correctly.

However, I can stop builds via the web interface. I can also pause/unpause workers. None of this required login. That's not really the default I'd expect.

Documentation on authentication plugins (http://docs.buildbot.net/latest/manual/cfg-www.html#authentication-plugins) says:

> By default, Buildbot does not require people to authenticate in order to see the readonly data. In order to access control features in the web UI, you will need to configure an authentication plugin.

So I would assume no authentication plugin configured == readonly access.

However, it looks like I need to explicitly set `c['www']['authz']` to enforce this. I've set what I think is the minimum configuration to enforce read-only access which is:

`c['www']['authz'] = util.Authz(allowRules=[util.AnyControlEndpointMatcher(role="admins")],roleMatchers=[])`

I now still see buttons for various operations (like 'Stop' on a build) but clicking these leads to errors like `Cannot Stop: you need to have role 'admins'` which now appears to be safe.

So,

1) Is this the correct change to lock down the web interface to become read-only?
2) Would it be possible to update the defaults so that buildbot is secure out-of-the-box?
3) Could the documentation be updated to make this clearer?

Let me know if you need any more info.

**Comment by tardyp** [comment]
Buildbot has an history of default all open, as most buildbot are accessible only from the intranet.

In order to avoid braking people setup, we decided to keep it that way when rewriting authz for buildbot nine.

I agree this sentence is confusing. Would you like to help and submit a better phrasing?

**Comment by betafive** [comment]
Something like this maybe:

> By default, Buildbot does not require people to authenticate in order to access control features in the web UI. To secure Buildbot, you will need to configure an authentication plugin.

Then there should be an example of a minimal, secure Buildbot master configuration. Here's what I've got in my master.cfg:

    # minimalistic config to activate new web UI
    c['www'] = dict(port=8010,
                    plugins=dict(waterfall_view={}, console_view={}, grid_view={}),
                    authz=util.Authz(allowRules=[util.AnyControlEndpointMatcher(role="admins")],roleMatchers=[]))

I think that's ok as I don't define any way for users to login and assume the 'admin' role.

**Comment by betafive** [comment]
Happy to submit a pull request if we're agreed on that as a valid example.

**Comment by tardyp** [comment]
looks good! thanks for the help!

**Comment by betafive** [comment]
Bit late since life has been busy, but I got there in the end :)
