### ISSUE TITLE
Changes page should have option to display more changes

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4027]
Changes page (e.g.: http://nine.buildbot.net/#/changes) shows last 50 changes by default. Users can't see more changes. It should have option for users to see more changes. There are + and - buttons, but they don't show more changes, they simply expand the current changes.

There should be some option to see more changes on this page. Either through a UI button, or configurable in Settings (http://nine.buildbot.net/#/settings).

**Comment by aj062** [comment]
Is the number 50 hard-coded here: https://github.com/buildbot/buildbot/blob/master/www/base/src/app/changes/changes.controller.coffee#L5 ?

**Comment by tardyp** [comment]
>Is the number 50 hard-coded here: https://github.com/buildbot/buildbot/blob/master/www/base/src/app/changes/changes.controller.coffee#L5 ?
@aj062 Right, looks like a good first PR!

Here is a very similar patch:
https://github.com/buildbot/buildbot/commit/fcb1491223c079575d402dbbf0daca27e23c39d9

**Comment by jubnzv** [comment]
>  There are + and - buttons, but they don't show more changes, they simply expand the current changes.

Should their current behavior be replaced to show more changes?

I did it with configuration in Settings tab (or in master.cfg): #4065
