### ISSUE TITLE
Support to MSBuild 141(Visual Studio 2017)

### ISSUE THREAD

**Issue by andre8359** [buildbot/buildbot#4033]
I would like to know if buildbot will have buildstep classes for vs2017 builds any time soon.

**Comment by tardyp** [comment]
MSBuild is community contributed. Feel free to make a PR!

here is an example patch that updated for VS2015
https://github.com/shoelzer/buildbot/commit/f3775208a2a1660afbf5a2c2cb9b56e36b65fe69#diff-6058c97cddb6f28613872a98dd9a6a9e

**Comment by bdbaddog** [comment]
The canonical way to locate vs 2017 installs is using vswhere.exe which should be located at: 
%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe

See vswhere's github repo for more info: https://github.com/Microsoft/vswhere

Note that it will also locate the install of some older versions of Visual Studio, but not all of the ancient ones..
