### ISSUE TITLE
buildbot-master docker container doesn't contain psycopg2 module

### ISSUE THREAD

**Issue by lorenjanwilson** [buildbot/buildbot#4057]
Hello! The latest buildbot-master docker container doesn't contain the psychopg2 module (and is probably missing other crucial modules too).

I believe this issue was introduced by this recent commit:
https://github.com/buildbot/buildbot/pull/4041/

if you look at the changes that are associated with that commit, there is a list of python apks that no longer get installed, one of which is py-sqlalchemy@edge ....the new method introduced by that commit is to use python-pip to install anything listed in the file "/usr/src/buildbot/requirements-docker-extras.txt" but currently that file only includes the "requests" module and nothing more.

**Comment by tardyp** [comment]
@rodrigc would you like to look at this?

**Comment by rodrigc** [comment]
@lorenjanwilson Did you do a pip list inside the running container?  There is a lot more than Python requests that gets installed in the running container.  pyscopg2 is not there though.

**Comment by lorenjanwilson** [comment]
Yes, you are right... many more python modules get installed.

Here is the complete list of python modules that are present in the "v1.1.1" container but not the "master" container, according to pip:

characteristic
egenix-mx-base
psycopg2
pycrypto

**Comment by tardyp** [comment]
pycrypto is important for handling https, I think we should have it.

egenix-mx-base looks like something that is probably related to your own business. I doubt we really had it in 1.1.1 container.

**Comment by lorenjanwilson** [comment]
I ran "pip list" on a fresh buildbot/buildbot-master:v1.1.1 pulled from docker hub on a completely fresh test node created with docker-machine:

```root@loren-test-node:~# docker run -t buildbot/buildbot-master:v1.1.1 pip list | grep egenix
Unable to find image 'buildbot/buildbot-master:v1.1.1' locally
v1.1.1: Pulling from buildbot/buildbot-master
550fe1bea624: Pulling fs layer
1c1339734f2e: Pulling fs layer
2b50f43fbc31: Pulling fs layer
4c57e57e08d1: Pulling fs layer
4c57e57e08d1: Waiting
550fe1bea624: Verifying Checksum
550fe1bea624: Download complete
4c57e57e08d1: Verifying Checksum
4c57e57e08d1: Download complete
1c1339734f2e: Verifying Checksum
1c1339734f2e: Download complete
550fe1bea624: Pull complete
2b50f43fbc31: Verifying Checksum
2b50f43fbc31: Download complete
1c1339734f2e: Pull complete
2b50f43fbc31: Pull complete
4c57e57e08d1: Pull complete
Digest: sha256:d5f89c18c8991a4ca8c56508fe2e05cc199ec919ba1e71a814cc55eb6aff64ef
Status: Downloaded newer image for buildbot/buildbot-master:v1.1.1
egenix-mx-base (3.2.9)
```

**Comment by rodrigc** [comment]
If I do `pip list` inside the container, I see:

```
cryptography            2.2.2 
```

so we already have it.

**Comment by rodrigc** [comment]
@lorenjanwilson can you try the latest Docker image and report your feedback?

**Comment by lorenjanwilson** [comment]
The one tagged "master" works for me now! (Just so you know though, the "latest" tag is about 8 months out of date... not sure why that is)
