### ISSUE TITLE
Restarting one master affects build running on other master

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4062]
I have a multi-master setup with one master handling only web-server and other master handling everything else.

Until 0.9.12, restarting the web-server master didn't used to affect any builds running on other master. However, now with 1.1.1, I am noticing that restarting web-server master does affect the builds running on other master. Specifically, the builds are marked as "Retry", but the builds still keep running and there is no way to cancel. See screenshot (the build in screenshot is still running):

<img width="1421" alt="screen shot 2018-04-24 at 3 28 34 pm" src="https://user-images.githubusercontent.com/3098702/39219344-aa0c5886-47de-11e8-87cc-cf563bba2fb7.png">

I suspect that 'buildbot start' on web-server master is messing up the ongoing builds. It also seems to impact Workers configured_on in https://github.com/buildbot/buildbot/issues/4059

**Comment by tardyp** [comment]
looks bad :-(

Can you revert this: https://github.com/buildbot/buildbot/commit/81bcf60a538b7c37a0c6f0358007c52380faaacd

and make sure this is similar issue?
