### ISSUE TITLE
Buildbot starts but webpage doesn't load

### ISSUE THREAD

**Issue by StevenPatz** [buildbot/buildbot#4064]
Following the directions here  I get this in the terminal after running docker-compose up

> buildbot_1  | 2018-04-25 07:21:10+0000 [-] /usr/lib/python2.7/site-packages/buildbot/config.py:102: buildbot.config.ConfigWarning: [0.9.0 and later] NOTE: `status` targets are deprecated and ignored They are replaced by reporters
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] Setting up database with URL 'postgresql+psycopg2://buildbot:xxxx@db/buildbot'
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] doing housekeeping for master 1 521262c8c859:/var/lib/buildbot
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] doing housekeeping for master 1 521262c8c859:/var/lib/buildbot
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] adding 1 new change_sources, removing 0
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] gitpoller: using workdir '/var/lib/buildbot/gitpoller-workdir'
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] adding 1 new builders, removing 0
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] adding 2 new schedulers, removing 0
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] initializing www plugin 'waterfall_view'
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] initializing www plugin 'console_view'
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] NOTE: www plugin 'grid_view' is installed but not configured
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] initializing www plugin 'waterfall_view'
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] initializing www plugin 'console_view'
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] NOTE: www plugin 'grid_view' is installed but not configured
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] while starting BuildMaster
> buildbot_1  |   Traceback (most recent call last):
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
> buildbot_1  |       current.result = callback(current.result, *args, **kw)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
> buildbot_1  |       _inlineCallbacks(r, g, deferred)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
> buildbot_1  |       result = result.throwExceptionIntoGenerator(g)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
> buildbot_1  |       return g.throw(self.type, self.value, self.tb)
> buildbot_1  |   --- <exception caught here> ---
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/buildbot/master.py", line 304, in startService
> buildbot_1  |       yield self.reconfigServiceWithBuildbotConfig(self.config)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
> buildbot_1  |       result = result.throwExceptionIntoGenerator(g)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
> buildbot_1  |       return g.throw(self.type, self.value, self.tb)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/buildbot/util/service.py", line 54, in reconfigServiceWithBuildbotConfig
> buildbot_1  |       yield svc.reconfigServiceWithBuildbotConfig(new_config)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
> buildbot_1  |       result = g.send(result)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/buildbot/www/service.py", line 228, in reconfigServiceWithBuildbotConfig
> buildbot_1  |       self.port_service = strports.service(port, self.site)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/application/strports.py", line 40, in service
> buildbot_1  |       endpoints.serverFromString(reactor, description), factory)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1703, in serverFromString
> buildbot_1  |       nameOrPlugin, args, kw = _parseServer(description, None)
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1621, in _parseServer
> buildbot_1  |       getPlugins(IStreamServerEndpointStringParser), endpointType
> buildbot_1  |     File "/usr/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1637, in _matchPluginToPrefix
> buildbot_1  |       raise ValueError("Unknown endpoint type: '%s'" % (endpointType,))
> buildbot_1  |   exceptions.ValueError: Unknown endpoint type: '8010'
> buildbot_1  |
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] BuildMaster startup failed
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] Initiating clean shutdown
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] No running jobs, starting shutdown immediately
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] BuildMaster is stopped
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] Main loop terminated.
> buildbot_1  | 2018-04-25 07:21:10+0000 [-] Server Shut Down.
> simple_buildbot_1 exited with code 0

**Comment by seankelly** [comment]
Fixed in buildbot/buildbot-docker-example-config#12.
