### ISSUE TITLE
Multiple duplicate builds for single sourcestamp while using multi-master configuration

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4067]
I have a multi-master setup with one master is handling only web-server and other master handling everything else.

I am noticing a lot of extra builds. It seems like Buildbot is building twice the amount of builds. For each sourcestamp buildbot seems to be having two buildsets, and therefore a lot of duplicate buildrequests.

For e.g.: for sourcestampid=108897, there were two buildsetsid 1801483 and  1801492. Each of these commit was from one of the master:

main master:
`twistd.log.24:2018-04-23 20:24:54-0700 [-] added buildset 1801492 to database`

web-server Master
`twistd.log.3:2018-04-23 20:24:12-0700 [-] added buildset 1801483 to database`

```
buildbot=> SELECT * from buildset_sourcestamps  WHERE buildsetid=1801483 LIMIT 1;
   id    | buildsetid | sourcestampid
---------+------------+---------------
 4102315 |    1801483 |        108897
```
```
buildbot=> SELECT * from buildset_sourcestamps  WHERE buildsetid=1801492 LIMIT 1;
   id    | buildsetid | sourcestampid 
---------+------------+---------------
 4102332 |    1801492 |        108897
```

This results in lot of extra builds for same sourcestamp, e.g.:
```
buildbot=> SELECT * from buildrequests WHERE buildsetid=1801483 LIMIT 8;
   id    | buildsetid | builderid | priority | complete | results | submitted_at | complete_at | waited_for 
---------+------------+-----------+----------+----------+---------+--------------+-------------+------------
 2327851 |    1801483 |       416 |        0 |        1 |       0 |   1524540249 |  1524547716 |          0
 2327843 |    1801483 |       193 |        0 |        1 |       0 |   1524540249 |  1524546561 |          0
 2327845 |    1801483 |       261 |        0 |        1 |       0 |   1524540249 |  1524544382 |          0
 2327837 |    1801483 |        34 |        0 |        1 |       0 |   1524540249 |  1524544343 |          0
 2327855 |    1801483 |       550 |        0 |        1 |       0 |   1524540249 |  1524544199 |          0
 2327850 |    1801483 |       415 |        0 |        1 |       2 |   1524540249 |  1524541204 |          0
 2327840 |    1801483 |       149 |        0 |        1 |       2 |   1524540249 |  1524541048 |          0
 2327839 |    1801483 |       107 |        0 |        1 |       2 |   1524540249 |  1524541037 |          0
```
``` 
 buildbot=> SELECT * from buildrequests WHERE buildsetid=1801492 LIMIT 8;
   id    | buildsetid | builderid | priority | complete | results | submitted_at | complete_at | waited_for 
---------+------------+-----------+----------+----------+---------+--------------+-------------+------------
 2327909 |    1801492 |       416 |        0 |        1 |       0 |   1524540249 |  1524548543 |          0
 2327902 |    1801492 |       193 |        0 |        1 |       0 |   1524540249 |  1524547111 |          0
 2327903 |    1801492 |       261 |        0 |        1 |       0 |   1524540249 |  1524545732 |          0
 2327881 |    1801492 |        34 |        0 |        1 |       0 |   1524540249 |  1524544975 |          0
 2327911 |    1801492 |       550 |        0 |        1 |       0 |   1524540249 |  1524545341 |          0
 2327907 |    1801492 |       415 |        0 |        1 |       2 |   1524540249 |  1524541200 |          0
 2327896 |    1801492 |       149 |        0 |        1 |       2 |   1524540249 |  1524541047 |          0
 2327890 |    1801492 |       107 |        0 |        1 |       2 |   1524540249 |  1524541038 |          0
``` 

Both the master have same schedulers defined for them. Both masters load the same config, and the web-master additionally sets "c['workers'] = c['builders'] = []" in its master.cfg

This issue wasn't present in Buildbot 0.9.12, and seems to have started after upgrading to Buildbot 1.1.1.

**Comment by tardyp** [comment]
I think it is similar issue with the other multimaster issues.
It looks like the master election mecanism that we have is broken.

I would guess you are operating in symetric multimaster mode, with scheduler configured on all masters.
You need to manually make sure that only one master has the scheduler configured

**Comment by aj062** [comment]
> I think it is similar issue with the other multimaster issues.

Do you think this issue is also related to 81bcf60 ?

> It looks like the master election mecanism that we have is broken.

Can you please point out where is the code for master election? 
Was it modified in last few months (since 0.9.12)?

**Comment by tardyp** [comment]
what I call the master election code is here:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/util/service.py#L255

it relies on a mechanism which every master runs, which ensures that the other masters are still alive.
if a master is not alive anymore (because it crashed or is disconnected from network), then the clustered services that were claimed by dead master are taken back by remaining masters.
Here, for some reason, the live detection do not work, which make each master forcibly unclaim the other master's stuff, and thus each master claim everything.
Looks like this was always broken, but the code which did the cleanup was disabled by mistake and 81bcf60 fixed that.

**Comment by aj062** [comment]
Thanks for the explanation.

Do you think reverting 81bcf60 would fix this issue (atleast as temporary workaround)?

**Comment by tardyp** [comment]
If we don't have a better workaround, I will revert it before the next release

**Comment by aj062** [comment]
> If we don't have a better workaround, I will revert it before the next release

probably it's time to revert this?
