### ISSUE TITLE
Send keepalive messages on websocket to prevent cloudflare disconnect

### ISSUE THREAD

**Issue by kpcyrd** [buildbot/buildbot#4078]
buildbot behind cloudflare is currently reloading for me every 100 seconds. This is due to a cloudflare limitation that is resetting websockets with 100 seconds of inactivity. It seems the only ways around that is either an upgrade to their enterprise plan or adding keepalive messages to the application.

https://community.cloudflare.com/t/cloudflare-websocket-timeout/5865

I'm on buildbot 1.0.0 due to openbsd -stable, I've grepped through the source on master and it seems there's already a ping command implemented on the server, but it's not automatically used by the client yet. The client should invoke it every 60 seconds to avoid a disconnect due to timeouts.

Thanks!

**Comment by etiktin** [comment]
This is also true for AWS ALB. The default active connection timeout is 60 seconds (instructions on how to change it: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout).
Sending pings every X seconds sounds good to me. I suggest ~45 seconds as the default value, but it would be nice if it's easily configurable.

**Comment by ASMfreaK** [comment]
This is same when proxying though nginx, as it sets [default timeout to 60 seconds](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout)

**Comment by vstinner** [comment]
See the issue #5991: "ws_ping_interval is not added in the set of allowed keys for ww".
