### ISSUE TITLE
How to customise the force build page with custom javascript?

### ISSUE THREAD

**Issue by rpurdie** [buildbot/buildbot#4104]
I work on the Yocto Project which is running an elderly hacked buildbot. One thing we did was add some customised javascript to the force build page to allow prepopulation of the form fields with certain combinations of values (but still allow the values to be changed).

Whilst we can add our custom fields to the form, I'm struggling to see a way of injecting any kind of scripting to the page without hacking buildbot code itself.

The hack to our old buildbot is basically: http://git.yoctoproject.org/cgit.cgi/yocto-autobuilder/commit/?id=8afbc6323a2977383e9cace1c040a5ce4d61f068

Is there some tip/trick I'm missing which would allow us to inject such code into the page from our master.cfg? or allow us just to customise the force build page? Would you consider adding a mechanism which would allow us to do this if it isn't possible today? I can think of a few different options but its really something I could use some guidance on.

Cheers, Richard

**Comment by rpurdie** [comment]
Hi, Thanks for the reply but I'm not quite show that solves the problem. Our force build page has multiple (8 x 3 and growing) text input form boxes for repo/branch/revision entries. Our force build page has a drop down which lets you select "pre-canned" configurations where the branches in particular get pre populated for a particular "known" config. This saves people having to remember that "rocko" needs bitbake set to the 1.34 branch for example. Would tags help solve that problem?

**Comment by tardyp** [comment]
There is the custom nested forcefield aka pizza selector, which does similar thing:

https://github.com/buildbot/buildbot/tree/master/www/nestedexample

this is meant to be copy pasted in its own plugin to implement your workflow logic.

**Comment by rpurdie** [comment]
That does look like it may solve the problem. I'll get my dev environment to the point I can build the UIs and give that a go. An example is just what I needed, thanks!
