### ISSUE TITLE
buildbot.util.service.HTTPClientService result.code is float

### ISSUE THREAD

**Issue by cmouse** [buildbot/buildbot#4112]
When doing a HTTP query using the HTTPClientService, the result.code is unexpectedly a float. This breaks tricks like `if result.code / 100 == 2`, because 202 / 100 = 2.02 when code is float.

BuildBot version: 1.1.1
Twisted version: 17.9.0
Python version: 2.7.9

**Comment by tardyp** [comment]
in py3 202/100 > 2.02

Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 202/100
2
>>>
# python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 202/100
2.02

So anyway doing the /100 hack is not a good idea.
