### ISSUE TITLE
Scheduler properties not available during build stage

### ISSUE THREAD

**Issue by 9prady9** [buildbot/buildbot#4127]
Please find the relevant code :
```
c['schedulers'].append(schedulers.Nightly(
            name="master-nogl-nightly",
            onlyIfChanged=False,
            hour=5,
            minute=0,
            builderNames=["windows-nogl-nightly", "linux-nogl-nightly"],
            properties={ 'cdash_mode': 'Nightly' },
            ))


@util.renderer
def get_cdash_mode(props):
    return props.getProperty('cdash_mode');


# Pulled out the respective step from factory creation.
steps.SetProperty(property='cd_mode', value=get_cdash_mode),
```

(https://gist.github.com/9prady9/6a329a697470ce4a533f23fe976b3f0b) - the gist contains only the scheduler creation, definition of renderer and `SetProperty` step of factory creation. 

I also tried fetching the scheduler property directly using `util.Property()` function but that also retuned `None`.

I have posted my query on the IRC channel but wasn't lucky enough to find a resolution. 

Any workaround or fix for my code(I don't believe there is anything wrong with the way I am setting properties based on documentation) is really appreciated. Thank you!

buildbot version details:
```
Python version: 2.7.14
Buildbot version: 1.1.2
Twisted version: 18.4.0
```
We are using [buildbot from docker](https://hub.docker.com/r/buildbot/buildbot-master/).

**Comment by tardyp** [comment]
The code looks correct to me. probably there is an issue elsewhere. Please post any relevent error in twisted.log, or step's log.

You can simplify the code by using util.Property

```
# Pulled out the respective step from factory creation.
steps.SetProperty(property='cd_mode', value=util.Property('cdash_mode')),
```

**Comment by 9prady9** [comment]
Not sure I understand what kind of error I should be looking forin the logs, because `util.Property('cdash_mode')` returns `None` and `buildbot reconfig` command runs successfully without throwing any errors with the above code.

**Comment by 9prady9** [comment]
yes, the property is listed in the build page, but it is empty.

**Comment by 9prady9** [comment]
Faced this problem again just today, one thing I can certainly say is that Nightly scheduler has issue with properties. ForceScheduler properties are made available to the builds as expected. The problem is with Nightly schedulers only.

**Comment by mrstanwell** [comment]
FWIW, I've got a 1.1.0 installation and a 1.3.0 installation which use Nightly schedulers that set properties, and those properties are communicated just fine to the builders.  Although, I notice that I'm using `util.Interpolate()` rather than `util.Property()`.  So, for example, in the factory I have something like (elided for clarity):
```
steps.ShellCommand(command='somecommand.sh', 
                   env={'SOMEVAR': util.Interpolate('%(prop:nightly_property)s')}
)
```
I've got another scenario in which I execute a Trigger step which sets a prop for the triggered scheduler using the `set_properties` arg, but it too uses `util.Interpolate()` to get the value of the prop set by the Nightly scheduler.

Hope that helps...

**Comment by 9prady9** [comment]
@mrstanwell thanks for the hints. We actually found a different way to set the required variable property without using scheduler properties.

I shall be closing this issue as it wasn't acknowledged as known issue and we found a different way to set the required property. If this is indeed an issue while using `util.Property`, you may reopen it.
