### ISSUE TITLE
steps.Git with "getDescription" failing: "fatal: no names found"

### ISSUE THREAD

**Issue by fradeve** [buildbot/buildbot#4133]
Hi all,
I have tried few different approaches before asking for help on IRC, and I've been suggested to open an issue here, sorry if this is obvious and I am missing something.

I am trying to get the GIT tag to use it during the build (to tag a Docker image). This is my GIT step:

```
    steps.Git(
        repourl='git@bitbucket.org:foo/bar.git',
        mode='full',
        method='clean',
        clobberOnFailure=True,
        progress=True,
        getDescription={'tags': True}
    )
``` 

What I see in the logs:

```
git --version
git version 2.7.4
```

```
git clean -f -f -d
```

```
git cat-file -e 731430c1bf0d576d85cf74859d2555511804bd60
```
```
git reset --hard 731430c1bf0d576d85cf74859d2555511804bd60 --
```

```
git checkout -B refs/heads/master
Reset branch 'refs/heads/master'
```

```
git rev-parse HEAD
731430c1bf0d576d85cf74859d2555511804bd60
```

```
git describe --tags HEAD
fatal: No names found, cannot describe anything.
```

My environment:

```
buildbot: 1.1.2
worker version: 2018.04.24
Twisted version: 17.9.0
```

**Comment by tardyp** [comment]
It looks like the fetch did not get the tags? Do you have them in the first place? Can you debug that on your worker environment?

**Comment by fradeve** [comment]
Hi Pierre,
thanks for asking.

Yes I have tags in the repo. From the clone on my local machine:

```
git describe --tags
0.9.2-3-g731430c
```

I have investigated what's happening on the worker, and the same command will fail in the worker with the same error I described. It looks like `mode=full` and `method=clean` are not fetching the tags, which is not the behaviour I was expecting. Am I missing something?

**Comment by tardyp** [comment]
it is possible that only incremental mode fetches the tag. That would be an overlook by the guy who implemented describe --tags

**Comment by fradeve** [comment]
I just realised that the worker had a stale copy of the code, without any tag. I am not sure why, but deleting the folder and forcing a build again solved the issue. Sorry for the waste of time, I think we can close this. Thanks @tardyp for your suggestions, that helped as well!
