### ISSUE TITLE
Hints in ForceBuild tab

### ISSUE THREAD

**Issue by marrak** [buildbot/buildbot#4136]
There is regression after 0.8.x version. There were usefull hints in fields e.g. targets. If someone once typed e.g. 'refs/tags/rel_1_2_3', next time it was available to select and easy to change to next release.
![obraz](https://user-images.githubusercontent.com/2847500/41029544-35d0cd16-697c-11e8-868a-3de183b25497.png)
On latests versions there are no hints at all :(
Any chance to restore that?

**Comment by tardyp** [comment]
This is not handled by Buildbot. 

This is a feature provided by chrome for Text entries, Chrome remembers the last items you wrote. This is per browser, and probably per website url. So  this is probably why you don't see it on nine instance.
