### ISSUE TITLE
GitLab API v3 is removed from gitlab.com

### ISSUE THREAD

**Issue by micaeljtoliveira** [buildbot/buildbot#4143]
Buildbot currently uses v3 of the Gitlab API, which has been deprecated for some time already and is now in the process of being removed. See https://gitlab.com/gitlab-org/gitlab-ce/issues/36819 for more details.

**Comment by tardyp** [comment]
I think probably a sed s/v3/v4/ will do the job (look like there are 3 or 4 lines affected in the code)

https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/gitlab.py#L94

Would you like to make a PR about it?

**Comment by micaeljtoliveira** [comment]
Just made the PR. Any chance of doing a release with this ASAP? The v3 API is not available on gitlab.com anymore since a few days and I had to patch my buildbot instances to have then working properly again. On the other hand, maybe there are not that many projects on gitlab.com using buildbot and this is not so critical.
