### ISSUE TITLE
How does bb connect a Parameter object to a web field?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#4147]
https://github.com/buildbot/buildbot/blob/08a99c7bf90e99cdb29974949eff763f780a1036/www/nestedexample/buildbot_nestedexample/__init__.py#L13-L35

A `NestedParamter` with a name of `nestedexample` generates a `nestedexamplefield` in the web. I want to know how buildbot connect these two? 
And this mechanism doesn't seems to affect `ChoiceStringParameter`. How could I extend `ChoiceStringParameter` and change the field generated in the web from `listfield` to `somethingiwantfield`?

**Comment by tardyp** [comment]
it is this attribute:
     type = "nestedexample" 

if you change it, the webui, will look for a type + "field" directive:

https://github.com/buildbot/buildbot/blob/master/www/base/src/app/common/directives/forcefields/forcefields.directive.coffee#L18
