### ISSUE TITLE
buildbot's hgpoller.py assumes too much about hgbin

### ISSUE THREAD

**Issue by ewongbb** [buildbot/buildbot#4149]
On CentOS 6.9, /usr/bin/hg (which it uses for hgpoller.py) is 1.4.  This doesn't have the -b option.
so when it goes to:

https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/hgpoller.py#L166

the call to utils.getProcessOutput() fails.  

I'm wondering if it's preferential to fallback on hg pull -r <branch> if it errors.

**Comment by tardyp** [comment]
mercurial 1.4 is from 2010. not sure we want to support such old versions..
