### ISSUE TITLE
BitbucketPullrequestPoller fails all requests in python3

### ISSUE THREAD

**Issue by veloutin** [buildbot/buildbot#4153]
`_getChanges` and `_processChanges` all perform `client.getPage` with str arguments, which fail because `client.getPage` expect to receive `bytes` for the `url` parameter.

I worked around the issue locally by replacing all the `client.getPage` calls by `self.getPage` which encodes the url to bytes when necessary, and returns `client.getPage`, but there may be a cleaner way to handle this.

**Comment by devrajatverma** [comment]
/home//anaconda3/envs//lib/python3.6/site-packages/buildbot/changes/bitbucket.py

in line 92 replaced

`return client.getPage(url, timeout=self.pollInterval)`
with

`return client.getPage(str.encode(url), timeout=self.pollInterval)`

2018-07-02 12:08:10+0530 [HTTPPageGetter (TLSMemoryBIOProtocol),client] BitbucketPullrequestPoller: json api poll failed

2018-07-02 12:08:10+0530 [HTTPPageGetter (TLSMemoryBIOProtocol),client] Unhandled Error
	Traceback (most recent call last):
	Failure: twisted.web.error.Error: 403 Forbidden

Any Work around ?

**Comment by tardyp** [comment]
This code should be converted to HTTPClientService which handles all that correctly, and is testable:

http://docs.buildbot.net/current/developer/utils.html#buildbot-util-httpclientservice

The workaround is fine, but if anybody wants to step up and fix it correctly, this would be great.

@devrajatverma : looks like you did pass wrong credentials

**Comment by devrajatverma** [comment]
@tardyp 
I didn't passed any
don't know where to pass them, in BitbucketPullrequestPoller or in steps.Git
in docs there is no kwarg naming username and password mentioned for BitbucketPullrequestPoller

**Comment by veloutin** [comment]
In case someone stumbles here until a fix is contributed, here is the version I made/used: https://gist.github.com/veloutin/419514e0ffecc52ce6da7738ca770ac6

It does add authentication and fixes this bug.

My priorities shifted away from this a while back, but I suppose a gist is better than nothing, even if it isn't a proper contribution :)

**Comment by tardyp** [comment]
hi @veloutin Thanks for sharing a fix. We need someone from the community to include this fix in a proper pullrequest and update the unit tests.

Thanks you!

**Comment by jerrylogansquare** [comment]
I'll take a look, thanks

**Comment by sjalloq** [comment]
Hi, what's the status with this bug. Is anyone actively looking at it?

I see that @p12tic has done quite a bit of refactoring since the original issues was reported by @veloutin but this bug still exists.  @p12tic , how are you using this module if this bug remains?  I might be missing something.

**Comment by sjalloq** [comment]
@tardyp is this something you have any visibility of or has it just dropped off the radar?  I've been trying to get it working from behind a proxy but the Twisted ProxyAgent class doesn't seem to work or I don't know how to drive it.  Curl, wget, Python requests all work without issue.  If someone can provide some pointers I'd be happy to have a look at fixing this.

**Comment by jerrylogansquare** [comment]
@sjalloq    from what I can tell, buildbot is no longer being actively maintained.  You can only fork and fix at this point I think.

**Comment by sjalloq** [comment]
@jerrylogansquare ouch, ok, then it might be easier to move to something else.

**Comment by p12tic** [comment]
> I see that @p12tic has done quite a bit of refactoring since the original issues was reported by @veloutin but this bug still exists. @p12tic , how are you using this module if this bug remains? I might be missing something.

I personally don't use Bitbucket, so like in any open source project the support for less popular features like Bitbucket depends on whether anyone has time to submit at least a test pull request. So far there has been none, so it seems that proper Bitbucket support upstream is not really needed by anyone.

**Comment by p12tic** [comment]
@sjalloq

> I see that @p12tic has done quite a bit of refactoring since the original issues was reported by @veloutin but this bug still exists. @p12tic , how are you using this module if this bug remains? I might be missing something.

I personally don't use Bitbucket, so like in any open source project the support for less popular features like Bitbucket depends on whether anyone has time to submit at least a test pull request. So far there has been none, so it seems that proper Bitbucket support upstream is not really needed by anyone. If someone could add a failing test case and fix it with needed code changes that would be a great start.

**Comment by sjalloq** [comment]
@p12tic 

I've had a look at the unit tests and they all seem to monkey patch `client.getPage` which is why no failures have been seen.  What's the solution here?  To just update the fake client.getPage?

Moving forward, I also need to update the class to accept a proxy.  Do any of the available http classes use the http[s]_proxy environment variables?  Twisted seems to want you to use ProxyAgent which doesn't fit well with how BitbucketPullRequestPoller has been written.

**Comment by p12tic** [comment]
@sjalloq 

> I've had a look at the unit tests and they all seem to monkey patch client.getPage which is why no failures have been seen. What's the solution here? To just update the fake client.getPage?

Yes, the intention is that we have a set of known good data to test against. As a result we don't use network when running tests. On the bad side, we can't detect when upstream API changes.

If currently the only problem is what's listed in https://github.com/buildbot/buildbot/issues/4153#issuecomment-401697608 , then the best course of action is this:

 - you apply the fix on your buildbot instance and check if it actually works with real Bitbucket
 - you submit a PR with this change
 - I review and merge the PR
 - I replace the current implementation with httpclientservice with corresponding tests
 - you test whether the httpclientservice version still works with real Bitbucket
 - we look into how to add proxy support into httpclientservice so it can be used for all HTTP requests across Buildbot.

Does that sound right?

**Comment by sjalloq** [comment]
@p12tic 

That all sounds amazing, thanks.  I'll test what I have first thing on Monday.  As a side note, we're already using the GitPoller which seem to work with our proxy so however that is implemented could be copied I guess.

**Comment by sjalloq** [comment]
@p12tic Finally got there.  PR created.  It seems to be working on my local dev machine.  I'll try it in our cluster with the proxy next.  I did notice that client.getPage already calls httpclientservice.
