### ISSUE TITLE
Obsolete BuildRequestControl

### ISSUE THREAD

**Issue by chrwen-omicron** [buildbot/buildbot#4167]
I was looking through the code and found the [IBuildRequestControl](https://github.com/buildbot/buildbot/blob/master/master/buildbot/interfaces.py#L1060) interface. So the [BuilderControl.getPendingBuildRequestControls](https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/builder.py#L477) method returns a list of IBuildRequestControl objects, but [buildrequest.BuildRequestControl](https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/builder.py#L492) doesn't seem to exist anymore. Is this something which was forgotten as part of a refactoring or did I miss something?

**Comment by tardyp** [comment]
There are a whole bunch of old stuff that remains within the codebase mainly the status module. It is harmless but messy, and we need to eventually remove it (some tests are depending on it so it is a bit cumbersome)

**Comment by tardyp** [comment]
yes, BuilderControl is dead and data API should be use for that (so that it works in multimaster mode)

**Comment by chrwen-omicron** [comment]
Got it, thanks for clarifying!
