### ISSUE TITLE
ShellCommand doesn't work well with string containing escaple characters

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#4171]
Below is a simple example on Windows 7, Python 2.7.13 and BB 1.1.0:
```
Test_Step = steps.ShellCommand(
    command=["python", "-c",
             r"import sys;open('output.log', 'wb').write(sys.argv[1])",
             "aaa\nbbb"],
    logEnviron=False)
```
It turns out like below:
![image](https://user-images.githubusercontent.com/19603852/41913897-2a0d0bf8-7984-11e8-8424-c638973c6cdf.png)

It seems bb doesn't deal with this properly.

**Comment by tardyp** [comment]
Do you mean that the UI is not handling it properly? or is there another functional issue?

**Comment by lancelodliu** [comment]
No. My purpose is to write multiple lines to a file by Python. It seems that windows command line could not accept a multiple lines argument.

**Comment by tardyp** [comment]
If it is a windows command line issue, then I am not sure what we can do.

**Comment by lancelodliu** [comment]
Yes. I solve it using a workaround.
