### ISSUE TITLE
Logviewer text illegible on ubuntu if ttf-mscorefonts-installer installed?

### ISSUE THREAD

**Issue by dankegel** [buildbot/buildbot#4186]
The colorized log in the 2nd screenshot in the slideshow on the front page of http://buildbot.net/ is perfectly legible, but in real life, buildbot 1.2 colorized logs are illegible because they lack sufficient brightness contrast.  In this screenshot
![illegible-log](https://user-images.githubusercontent.com/170976/42226721-89db0f52-7e94-11e8-9288-5764846a54bd.png)
the word 'stdio' in the title bar is clearly legible, and the line numbers in the window on the left are somewhat visible, but the red text to the right is nearly completely illegible.  Squinting at logs like that makes me want to throw buildbot 1.2 right into the bin and go back to 0.8, but I can't, as I don't want to waste any more time keeping 0.8 alive, and gitlab v4 has broken my old 0.8 setup.

I'm happy to hack on source to temporarily get higher contrast, but it's hard to locate the code involved.
Changing e.g.
```
--- a/www/base/src/styles/colors.less
+++ b/www/base/src/styles/colors.less
@@ -14,7 +14,7 @@ pre.log {
         color: #c7c7c7;
     }
     .log_e, .ansi_red, .ansi31 {
-        color: #c91b00;
+        color: #00ff00;
     }
     .ansi_green, .ansi32 {
         color: #00c200;
```
didn't change anything I could see.

**Comment by tardyp** [comment]
I am not colorblind afaik, and can hardly read this as well.

Looks like your stdio is not ansicode 31 (which is the code from red), it might be encoded in ansi 256 color mode. In that case, buildbot can't do much, because it just applies the color as specified.
What you can do is to use the chrom developer mode, click the selector tool:
![image](https://user-images.githubusercontent.com/109859/42229619-2790b524-7ee7-11e8-9d5f-cf29f4f28fb1.png)

and then show me the html code around the line
![image](https://user-images.githubusercontent.com/109859/42229590-18c0de8e-7ee7-11e8-9413-e628cc6beeef.png)

I am mostly interrested in the class of the span embedding the line of log.

**Comment by dankegel** [comment]
All my steps' output have the problem, but for instance, this step
```
    f.addStep(steps.GitLab(repourl=repourl, mode='full', submodules=True, method='copy', branch=branch, getDescription=True))
```
outputs a first line like this:
```
<div style="height:18px;"><span class="no-wrap log_h ng-binding" data-linenumber-content="0"><span class="">git --version</span></span></div>
```

Since that step is part of buildbot, any colorization is buildbot's own doing...

**Comment by tardyp** [comment]
At this point, I think we have a font issue. not color, the font looks too slim. are you sure you are 100% scale?

**Comment by dankegel** [comment]
Bingo. It's not zoom -- both browsers report 100% when I look at the zoom menu item -- but it may be specific to this one cursed system; it doesn't happen on other systems (mac, linux, win) I just tested.

This system is using Intel graphics and a fairly standard ubuntu 18.04.
Maybe the fonts installed are different; the 18.04 where it looked better was a very fresh minimal install.

Yup, the problem seems to occur when the package ttf-mscorefonts-installer is installed.

Grr.

**Comment by dankegel** [comment]
Fun fact: if you uninstall  ttf-mscorefonts-installer while chrome is running, it gets very confused until you restart it.  Or at least it did for me.  After restarting, the logviewer text looked fine.

That package is in multiverse, so it's not enabled by default, but https://popcon.ubuntu.com/multiverse/x11/by_inst shows it's fairly popular,
possibly out of inertia (it used to be more important back in the days of bad fonts?).

Anyway, this is probably a bug for... uh... not sure who.  I'll try reporting it to chrome.

**Comment by tardyp** [comment]
you can look at the dev console, and try to change the list of font selected:
![image](https://user-images.githubusercontent.com/109859/42233117-dc4b8242-7ef0-11e8-8a2d-c139aad28250.png)

on my system menlo is selected:
![image](https://user-images.githubusercontent.com/109859/42233179-0d9f8550-7ef1-11e8-99d7-2c92e4f9afff.png)

maybe with the mscorefonts, another one is selected, that we should remove.

**Comment by seankelly** [comment]
Checking that package and here's the included font faces (plus some different weights):

> Andale_Mono.ttf
> Arial_Black.ttf
> Arial.ttf
> Comic_Sans_MS.ttf
> Courier_New.ttf
> Georgia.ttf
> Impact.ttf
> Times_New_Roman.ttf
> Trebuchet_MS.ttf
> Verdana.ttf
> Webdings.ttf

Courier New is in the package and `font-family` list.

**Comment by Alexthunder974** [comment]
Could it be possible to just remove "Courier New" font or replace it for the future releases?
That's what the bootstrap community did : [https://github.com/twbs/bootstrap/pull/18814/commits/cf7795da9399a72289fd0f9175b32668e9548a9b](https://github.com/twbs/bootstrap/pull/18814)

**Comment by DarkDefender** [comment]
Seems like github also removed "Courier New" and replaced it on their end with "Liberation Mono".

I think that makes sense because all non EOL Windows installs should now have the Consolas font.
