### ISSUE TITLE
Missing owner in buildrequest table on builder page

### ISSUE THREAD

**Issue by pmisik** [buildbot/buildbot#4207]
![image](https://user-images.githubusercontent.com/14224662/42470626-59aaf0aa-83bb-11e8-8945-fb505d990b42.png)

It seems problem is here 
https://github.com/buildbot/buildbot/blob/master/www/base/src/app/builders/builder/builder.tpl.jade#L24
but adding `` span | {{ br.owner}} `` is not enough as it seems ``.owner`` neither ``.properties`` are not set.

**Comment by tardyp** [comment]
indeed, we would need to do an additional rest request for each buildrequest
