### ISSUE TITLE
Git poller errors out with bad object message

### ISSUE THREAD

**Issue by tecywiz121** [buildbot/buildbot#4211]
So this is an error that's been happening to us for a while now, since Buildbot 1.0, and continues into version 1.1.2. If it's been fixed since then, I apologize for the duplicate issue.

```
2018-07-11 14:29:44+0000 [-] trying to poll branch refs/heads/testing of ssh://git@git.example.com:7999/SOURCES/red_connector.git
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1442, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 198, in poll
        yield self._process_changes(revs[branch], branch)
      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 295, in _process_changes
        results = yield self._dovccmd('log', revListArgs, path=self.workdir)
      File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/usr/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 356, in _convert_nonzero_to_failure
        command, args, path, self.repourl, code, stderr))
    buildbot.changes.gitpoller.GitError: command log ['--format=%H', '2a435aefce8ba79df1df19f5223dbe094a815ce5', u'^04e9ef90096c54d2ea518962762637e805a45194', u'^21718e4c56fe46adcc104119a115f8902d92be83', u'^293645b8ea73efbedc1cb58a9e9ffe3adbaf38bc', u'^2a435aefce8ba79df1df19f5223dbe094a815ce5', u'^45bf5a901013cf3307dc712b3e5e0ed506a0954c', u'^8293280165d718dbd2f0d2a7bf96affc88bd4d47', u'^8a593024f3d2e8fc39ae40b9549970d5446b7197', u'^a9cf6b6b61efceb386bfa63a40637ec89adf860d', u'^c40d80f03282efa8c7bea7ab88456400894c20ca', u'^d3de8e5ee1dc97bbafbb5e8e6d27ee12b0fdd96d', '--'] in /var/lib/buildbot/gitpoller-work on repourl ssh://git@git.example.com:7999/SOURCES/red_connector.git failed with exit code 128: fatal: bad object 04e9ef90096c54d2ea518962762637e805a45194
```

I normally fix this by dropping everything in the buildbot database that references that bad object. It doesn't happen often, and I have no idea how to reproduce it. I'm using git version 2.15.2 on the master.

**Comment by aunsbjerg** [comment]
I had an issue similar to this a while back. It turned out to be something wrong in the actual git database and nothing to do with buildbot. Maybe you have a similar issue.

If I recall correctly, my bad object came from having cherry-picked a commit to master from a local branch. I pushed the master to origin, but not the local branch with the original commit. I didn't notice any issues locally, because I had the branch, but doing a clean clone of the repo showed the error, as well as the buildbot gitpoller.

I fixed the issue by pushing the local branch with the original commit to origin.

**Comment by tecywiz121** [comment]
I don't believe cherry-picked commits have any reference to the original branch. It just re-applies the same diff on top of a different branch.

Regardless of how the commit arrived in buildbot's database, I believe it's still a bug for buildbot to fail when the object is removed from the repository.

**Comment by aunsbjerg** [comment]
Well, fair enough. It's either an issue with buildbot or with your git repository.

* Does the bad object actually exist in your local git repo? (git show <hash>)
* Does the bad object exist if you do a fresh clone of the repo?
* Is the error permanent or intermittent in buildbot?
* Are you doing full or incremental builds in buildbot?
* If you are doing incremental builds, does the error re-appear if you delete the repo clone in your buildbot worker folder?

In my case, I actually had a bad object in my remote repo, I could see that when doing a clean clone of the repo. This is the issue I needed to fix, it wasn't an issue with buildbot.

**Comment by tecywiz121** [comment]
Before I answer your questions, I just want to point out that git returns the same error ("bad object") if the commit is bad, or more importantly, if the commit doesn't exist.

> * Does the bad object actually exist in your local git repo? (git show )

I can't verify it right now, but I do believe the object existed at one time. It may have appeared in a branch that was force-pushed over.

> * Does the bad object exist if you do a fresh clone of the repo?

The bad object error only appears on buildbot.

> * Is the error permanent or intermittent in buildbot?

Once the bad object error appears in the logs, the GitPoller stops working until I remove all traces of that commit in the buildbot database.

That said, the error really doesn't come up that often. Maybe once a month with 10 developers over a dozen repositories.

> * Are you doing full or incremental builds in buildbot?

This is happening in the GitPoller.

I'm doing `mode=full` with `method=fresh` in most of my builds though.

> * If you are doing incremental builds, does the error re-appear if you delete the repo clone in your buildbot worker folder?

Next time it comes up, I'll try deleting the git poller work directory.

**Comment by tecywiz121** [comment]
Huh, so it seems to have happened again!

I can't seem to find the offending commit any where in our web UI, but if I navigate directly to it by crafting the URL, it does exist!

It has a full diff and everything seems in order, but the commit itself doesn't exist on any branches.

If I clone the repository fresh, the commit doesn't appear in `git show`.

**Comment by seankelly** [comment]
> It has a full diff and everything seems in order, but the commit itself doesn't exist on any branches.

git itself will keep unreachable commits until it runs a GC to clean up. I guess the web UI is similar, perhaps using git itself in the backend, so it can find a commit still but the commit is unreachable from any branch.

You can see this behavior when rebasing. The old revision is still viewable but can't be found from any branch. Some internal refs will include it but I don't believe that's strictly necessary for the revision to exist.

**Comment by tecywiz121** [comment]
The error happens because of the command buildbot is issuing, not because of anything wrong with the git repository itself:

## Contrived Example

### Setting up the Repository

```bash
$ git init banana
$ cd banana
$ touch afile
$ git add afile
$ git commit -m "Initial Commit"
$ echo "hello world" > afile
$ git commit -a -m "Second Commit"
```

### Git Log

```
commit dc37645252b86a4488563c4f821ad43fae3b690b (HEAD -> master)
Author: Sam Wilson <tecywiz121@example.com>
Date:   Mon Jul 16 10:27:15 2018 -0400

    Second Commit

commit 58a18ba1ac93b1e877ce17c7d42b568005f47305
Author: Sam Wilson <tecywiz121@example.com>
Date:   Mon Jul 16 10:26:17 2018 -0400

    Initial Commit
```

### Removing a Commit

```bash
$ git reset --hard HEAD^
$ git reflog expire --expire-unreachable=now --all
$ git gc --prune=now
```

### Running Buildbot's Command

```bash
$ git show dc37645252b86a4488563c4f821ad43fae3b690b
fatal: bad object dc37645252b86a4488563c4f821ad43fae3b690b
```

## Summary

In the above example, I create a git repository, add two commits, remove one of the commits, then run `git show`. At no point is the git repository broken, but we end up with exactly the same error as the one that buildbot is running into.

My theory is that buildbot's list of commit objects in the `object_state` table gets out of date with respect to the actual repository when someone does something equivalent to a `git push -f origin HEAD^:master`. Does that make sense?

**Comment by azhogov** [comment]
We faced the same problem with Buildbot 1.4.0. I agree that "this still qualifies as a buildbot bug, since commits can disappear for a ton of reasons, and none of them should break the GitPoller". The "git push -f origin..." is typical scenario for reproducing this issue.

**Comment by brkindar** [comment]
I also hit this on an existing repo. "Fixing" the repo is not an option, and this makes the GitPoller useless (after a while it just shuts down).

Is there an update on this ? Any place to start looking to fix it ?

**Comment by tardyp** [comment]
@brkindar are you sure this is the same error, please copy paster your twisted.log exception.

poller code is located here https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/gitpoller.py#L1

an improvement would be to detect this kind of corruption error, and clobber the working directory (in buildbot parlance, erase working directory and clone again from scratch)

**Comment by brkindar** [comment]
Here is the error log :
2018-10-10 13:56:22+0200 [-] trying to poll branch refs/heads/test27458148 of git@github.ENTERPRISE.com:bad/PROJECTNAME.git
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
	    _inlineCallbacks(r, g, status)
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 227, in poll
	    yield self._process_changes(revs[branch], branch)
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 324, in _process_changes
	    results = yield self._dovccmd('log', revListArgs, path=self.workdir)
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 410, in _dovccmd
	    stdout = yield self._dovccmdImpl(command, args, path)
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/lib/python3.7/site-packages/buildbot/changes/gitpoller.py", line 441, in _dovccmdImpl
	    full_args, path, self.repourl, code, stderr))
	buildbot.changes.gitpoller.GitError: command ['log', '--format=%H', '336d50b979a012541d2b36b06ed21094c27809d6', '^09b4fbaf772f9c258575fd31ea65315f70c3d988', '^0d159d9f48c3dff6a61277e7207881202428ac0b', '^0e168bed8451f1e2e2cd48a0a70113b7a885111d', '^14eeef3394cc3f3086d82557170e889120d5d50e', '^17646895b446515eceebf132aa6631fccf1ba031', '^186d3ba78a1b283967811efdab5f1c819ac2b8c1', '^18fa8a236b324d0db0920e35852b8f0dca27cc9d', '^19e9c54ba442e9ad568f6fc5fc73f53115ec4780', '^1ac9323417966cb4ef882b70f301bae71cd29b29', '^208e2d4fd5d81384743828828518c2558a1b669d', '^21afc2e7defda2005f192a7ffafc2c5a3578b1b5', '^230636cf03856500ebdd47dedf330d5c3e7a9b85', '^248844f1e51df55ff232af4fc1913d85e2bca026', '^27beb538ea5cee3718a0b5706dd55a3514a5b9a7', '^2d8976a6e61e82d9f83f479ab7d4c1c6e609de81', '^2dfbe298ac1ec3f19201e97ad5a58aa4d3efacbc', '^2ea29869530ed7fd261ca2ffe2ea9bf1985c9897', '^336d50b979a012541d2b36b06ed21094c27809d6', '^33ee1fd89c049631405947cb0185cff6d528439e', '^35692b7247d674f2697997e164c594d68e080b22', '^35f4b61de4524bad6fb77c4f96618382ba1cea1c', '^3c1fc4d9331955f2cd3964b363f3faa83b52bf9c', '^4177e8d7a66aa725138b4e6d84ba414fbddb553b', '^42d0de1b9e4733df36a7cfec5d195d064d58435a', '^4a43184a199a24b39924a5afe6434f851b117315', '^4a8c2a97383a9c8a7351cf4ecce223cacd8b7703', '^4d2fe458155d41b8e0c5f4b65250915049a20ef3', '^4d691b9163b7713b4af518a0fc6c30cb89629be4', '^5dfb8486d37050882695a605d307c2adb65865d3', '^5f62f3843971359bc349286fc85bc1d1a43636d5', '^6c22beeb352c356f617bb5e309f079c1d0dec208', '^709d13b9e665d513cc06bd78ce46e9d725d8d300', '^77b7922e566177503cc09cfa75df96d856653c79', '^7c45e8cf0c3ff807409acae0aec0d4c8562ce27c', '^7d2fe9d98d0ff0b04f9fa74bc0d4f6ef256133ae', '^7db23527fa616f03e9a55a00e7696c6244451441', '^84754c847ccf657fc4befb9164b63e34a9aa4856', '^8515d033ad6d3a192508fe32631928bf23e8c965', '^864db7bc92a58e6613ced07573757e339942ade7', '^8b8043e5deeadf2e28ada2b0e33a275478392e28', '^8c60a2bcf4449d04a03485a453da3d4aee9b0da7', '^8c90df2634a0cb837c350249d67ea2570e7e7ee5', '^8e9bed98b028146d26a84e5175dd204deecaef60', '^90f0815988befb2e942fe3b5e457669648c80a1a', '^9aaee9ac18acdf8aaacbaf56a8ff92520a9a9869', '^9dd90c3270abb702e1c8960abc294be9414a688c', '^9e29c0f0924c141989b878e1b8d9e9bd15845798', '^a5734bc8a72c8fd2b1e2d754159c7ccab4c0812e', '^adb0d9e719c7ce91614e589150fabf3edb9aa817', '^af265ec1210b0c1d782d05b83b259ce2d691fedf', '^b2225871425d598f1594ca2f588bb6a5b24317b4', '^b41039be0d1deccd9726e525743415aa40d14f88', '^b869a41a9a1af7353814a92ed9ca31d91170430d', '^b97a147ccba4b787d3f30bd42f69df65ccf75795', '^bde6823a2836e4b5de0876e09d208122d3f763a1', '^bdf9a7d53b339d40f81dec3443caa4a216ab0afc', '^bf4a813316e74688d87550711016be15f4bc1ee6', '^bf50a0ebf883b0bcc4662bf780fbb898c74067b6', '^c1c575acbfaac439a62696a6c44dd954f9c4a256', '^c629da5fd96f71c9e0cb3d82399681117580468b', '^d33f7ad757b85fc0bee6a2bd0b775081a6d9d86a', '^dbb37528aa8484f052529f4a2c534c92a78e21ec', '^dc97a0c1288f7696d931c02790071ddff1c5a664', '^dc9a01980255c8b67ece79c25ca84af83a18ddd7', '^e0893b66a69c655b97abb196819c9c4fcb54bf42', '^e0e5d1a66876f8f7ef037976320586e72e346cc7', '^e67e2887a1c33b20f13aaf20a83b784dd68e1a21', '^e855c2a180f1a7ab8893c870d6106c7ed1ab9376', '^efcbfc4624e2c9b0c5dbc95be0c190a79c83b74b', '^f121ed84a220c4f2c7344da8da20b71116efe43e', '^f1f30c68a25f1d0084cc97a2dd3719912d9b0102', '^f34b556ffb80207c43835239023207b1466234aa', '^f5cfd4c912c23c98b24688606510a38f157c0c1f', '^f8b5ef4b4410a8fa9f8a3db8e682e17f9c2d4162', '^ffab10cf70440f4d8b7a020174f08536cd57674f', '--'] in /Users/USERNAME/buildbot/PROJECTNAME/gitpoller-workdir-PROJECTNAME on repourl git@github.ENTERPRISE.com:bad/PROJECTNAME.git failed with exit code 128: fatal: bad object 7d2fe9d98d0ff0b04f9fa74bc0d4f6ef256133ae

**Comment by brkindar** [comment]
How would the working directory impact it ? It looks like it is the git repo which behaves strangely but still we have to accomodate it...

**Comment by tardyp** [comment]
did you try to remove the working directory? My first idea would be a corruption. Another idea would be an hidden ref. Not sure why he try to log so much sha1..

**Comment by brkindar** [comment]
Yes, even after removing the gitpoller-workdir, the messages reappear directly.

**Comment by tardyp** [comment]
Ah. So this is because of a force push? 
Could mean the poller can't find how many new commit has been sent.

**Comment by tardyp** [comment]
BTW, I see you are using github. I would recommend you to use the github hook mechanism, this is much more reliable way of detecting change and support force push.

**Comment by brkindar** [comment]
As much as I'd like that, I would need to "own" the project to set that hook, wouldn't I ? Presently that is not the case.

**Comment by tardyp** [comment]
or ask nicely to your colleagues to setup the hook :)

**Comment by azhogov** [comment]
> an improvement would be to detect this kind of corruption error, and clobber the working directory (in buildbot parlance, erase working directory and clone again from scratch)

Erasing the working directory doesn't resolve the issue. It is required modifying Buildbot data base as described above.

**Comment by tecywiz121** [comment]
Would a simple fix be to un-batch the arguments to `git` and do one commit at a time? At least that way buildbot would still be able to get some new commits, instead of dying right away.

**Comment by tardyp** [comment]
I think we should detect the case where self.lastRev does not exist anymore, and then change self.lastRev to be the head of the branch, and create a new change with some flag telling this is a force push.

**Comment by pc-tradelab** [comment]
Hello any news ont this issue ? It may related to my problem (using docker BB 1.4.0) : 
> 
2018-11-19 03:48:56+0000 [-] trying to poll branch master of https://XXX@github.com/tr/audience.git
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
            _inlineCallbacks(r, g, status)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 225, in poll
            'rev-parse', [self._trackerBranch(branch)], path=self.workdir)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/lib/python2.7/site-packages/buildbot/changes/gitpoller.py", line 410, in _dovccmd
            stdout = yield self._dovccmdImpl(command, args, path)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
            result = result.throwExceptionIntoGenerator(g)
          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
        exceptions.TypeError: exceptions must be classes, or instances, not type
> 

I think Gitpoller is a central feature for many builbot users. Issues related to this component should be treated with a high importance. 


Regards,

Pc

**Comment by shoelzer** [comment]
Wow am I glad to find this issue. I've been having this problem since April! I was finally able to get polling working again by hacking GitPoller with a list of "bad" hashes to ignore. The problem seemed to be that GitPoller was trying to "git log" some old hashes that no longer exist in the repo. Simply dropping those hashes from the command got things working again.

I realize that this is not a good way to fix things. Gitpoller should really handle this case gracefully and it sounds like there are ideas about how to do that. @tecywiz121 mentioned [un-batching arguments to git](https://github.com/buildbot/buildbot/issues/4211#issuecomment-428627408) and based on my hacky workaround, I think his idea would work.

But until then, a better fix for me would be to edit Buildbot's database like @tecywiz121 said in the initial bug report. Can anyone give me guidance on what needs to be changed? What tables need to be edited? Thanks.

**Comment by tecywiz121** [comment]
This is usually what I go through, but I can't state that it leaves the DB in a consistent state:

```
buildbot=# delete from sourcestamps where revision = 'e32c2ee8eaa2f67d4323f83b48fda4818fa53c56'; # Replace the commit with the one you noted earlier
buildbot=# delete from changes where revision = 'e32c2ee8eaa2f67d4323f83b48fda4818fa53c56'; # Replace the commit with the one you noted earlier
buildbot=# delete from object_state where value_json like '%e32c2ee8eaa2f67d4323f83b48fda4818fa53c56%'; # Replace the commit with the one you noted earlier, but keep the percent signs
buildbot=# delete from build_properties where value like '%e32c2ee8eaa2f67d4323f83b48fda4818fa53c56%';
```

**Comment by sandywang1982** [comment]
After cleaning up db, buildbot master has to be killed and restart, otherwise it keeps putting the bad commit back into object_state table, i think buildbot master caches data for lastRev.

**Comment by tehmoon** [comment]
Had the same exact issue (still running on 0.8.12 :/).
Solved it using the `gitbin` option in the `GitPoller` scheduler which points to a simple bash scripts:
```
#!/bin/bash

[ "${1}" = "log" ] && { shift && git log --ignore-missing "${@}"; } || git "${@}"
```

Basically, it adds the `--ignore-missing` flags if buildbot does `git log`.

**Comment by sandywang1982** [comment]
@tehmoon good to know that, I will try on my end to see if it works. Thank you

**Comment by EndrII** [comment]
@tehmoon please tell me in more detail how to add --ignore-missing for gitpoller?

**Comment by tehmoon** [comment]
@EndrII The idea is to add `gitbin` as an option to the `gitPoller` when you configure it.
Then it should point to a script you control, in this script you basically inject extra parameters like the `--ignore-missing`.

**Comment by EndrII** [comment]
@tehmoon thanks

**Comment by tardyp** [comment]
@tehmoon did you try to add --ignore-missing in gitpoller.py?

**Comment by tehmoon** [comment]
@tardyp I did not, not that I did not think about it, but because I did not want to have to change the source code, because it's always a pain to have to port the patch from updates to updates.
I think buildbot provided a really nice way to fix this this issue with the gitPoller's flag.

One last note: I don't really understand all buildbot's internals, what I did only fixed my issue. I did not see any side-effect since I put it in production. But it does not mean that I might have broken some part of the internals without realizing it 😄

**Comment by tardyp** [comment]
Well, if you don't want to port your patch updates after updates, just upstream it. We gladly accept them.
The gitpoller code is not that complicated. you will also have the benefit to help other users of buildbot.

**Comment by tehmoon** [comment]
@tardyp I could have taken a look at it, but it looked like from that thread, that the problem was not from buildbot. Which is totally legitimate, don't get me wrong.
I just wanted to find a way to make it work in a more sustainable (to my point of view) because our workflow was broken.

Now, I'm pretty sure that adding the option would work. I can try to find the relevant line of code though.

**Comment by bjb** [comment]
I tried adding --ignore-missing in gitpoller.py and ran the tests - more tests failed than before I made the change.  https://github.com/bjb/buildbot/commits/gitpoller-log-ignore.  So there is more to do than just add --ignore-missing.  I will have to learn more about buildbot before I can do any more, but I wanted to report the results of the suggestion here.

Without the change:
FAILED (skips=32, failures=2, errors=4, successes=5649)

With the change:
FAILED (skips=32, failures=10, errors=19, successes=5638)

A little more detail:
Without the change:

F buildbot.test.unit.test_worker_ec2.TestEC2LatentWorker.test_start_instance
F buildbot.test.unit.test_worker_ec2.TestEC2LatentWorker.test_start_spot_instance
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait

With the change:
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_allBranches_multiple
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_allBranches_single
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_branchFilter
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_callableCategory
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_callableFilteredBranches
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_true
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_true_fast_forward
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_true_not_tip
F buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_old

E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.integration.test_try_client.Schedulers.test_userpass_wait
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_allBranches_multiple
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_callableFilteredBranches
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_allBranches_multiple
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_allBranches_single
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_callableCategory
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_old
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_branchFilter
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_default
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_true
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_noChanges
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_nothingNew
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_true_fast_forward
E buildbot.test.unit.test_changes_gitpoller.TestGitPoller.test_poll_multipleBranches_buildPushesWithNoCommits_true_not_tip

**Comment by felixfontein** [comment]
I'm experiencing the same problem; adding `--ignore-missing` helped. I've looked up the problematic commits in the DB, these belong to branches that no longer exist. When creating a new clone of the repo, these commits aren't there; I can still find them in GitLab though.

**Comment by felixfontein** [comment]
@bjb what you were missing was adjusting the unit tests. They check which precise `git` command was executed, and since you updated the command without updating the expected commands in the tests, the tests fail.
