### ISSUE TITLE
passing security options to docker latent worker

### ISSUE THREAD

**Issue by rgerhards** [buildbot/buildbot#4215]
I would like to run tests involving clang ASAN inside a docker latent worker. Unfortunately, this requires elevated privileges (see for example https://github.com/google/sanitizers/issues/764).

As far as I could see from the doc, this currently seems not to be supported. Even though my python is pretty weak, I had a look at the latent worker source. I see that create_host_config is called, but I do not see how the config options go to there. The docker API supports setting security parameter: http://docker-py.readthedocs.io/en/stable/api.html

Question: where are the hostconfig params created and how could I try to make buildbot accept security related ones?

**Comment by tardyp** [comment]
Hi, the hostconfig is passed when initializing the LatentWorker:

http://docs.buildbot.net/current/manual/cfg-workers-docker.html?highlight=hostconfig

**Comment by rgerhards** [comment]
Doh! I went to the doc and searched for capabilities and security, then went to the code and did not make the connection back to the doc... Thanks for pointing this out. Works well!

**Comment by rgerhards** [comment]
Just for those that may find this thread via search engines. This made clang ASAN work for me:
```
  worker.DockerLatentWorker('....', None,
                                docker_host='tcp://...',
                                image="...",
                                build_wait_timeout=0,
                                hostconfig= { 'cap_add': 'SYS_PTRACE'},
                                followStartupLogs=True)
```
Depending on the Distro and security hardening in place (AppArmor, SELinux) this may not be sufficient. To test if the problem is privilege-related, you can do this:
```
                                hostconfig= { 'privileged': True },
```
That's obviously not very secure, so I would limit it to testing, only.

@tardyp thanks again for pointing me at the right spot and special thx for making buildbot so flexible! It is helping us making rsyslog even more reliable.
