### ISSUE TITLE
Specify a branch for a Git step

### ISSUE THREAD

**Issue by wrosecrans** [buildbot/buildbot#4221]
The Git buildstep allows you to pass a default branch, and if a user does a force-build, it will override the default branch.  Is there any way to prevent this?

I often want to use jobs with multiple Git steps where there is one repo for the source that should use the branch specified in the force build, but then other stuff should just use whatever branch I specify when I set up the builder, no matter what.  How can I set a specific branch for the Git step, rather than merely a default branch if nothing else is specified?

**Comment by mv740** [comment]
I use step.git for the main git and then use shell step ( git clone **.git) 

So whenever i pass a value through the force builder it doesnt overwrite my other "git steps"

**Comment by p12tic** [comment]
@wrosecrans: Could you please check whether `alwaysUseLatest=True` and `branch='your_branch'` works for your use case? This comes from my reading of https://github.com/buildbot/buildbot/blob/master/master/buildbot/steps/source/base.py#L263. That behavior should probably be documented.

**Comment by wrosecrans** [comment]
That's...  a little counterintuitive, since my branch isn't guaranteed to be the latest, but I just did a test with that in my config and it seems to work.

I can check out a main repo, get a JSON file and parse it, and then use the contents to optionally  step.build.addStepsAfterCurrentStep() a step to get something from another repo specified in the JSON.  In my case, I am using it to grab a Dockerfile that will be used to build the source in the first repo.  If I run into problems with it, I'll fall back to mv740's suggestion of just ignoring the Git step and doing it as a shell command instead.

**Comment by p12tic** [comment]
> since my branch isn't guaranteed to be the latest

`alwaysUseLatest=True` just guarantees that the latest commit in that particular branch is used, at least that's what's currently coded.

**Comment by lpetraglio** [comment]
`steps.git( ... , alwaysUseLatest=True,  branch=<branch-name>)`  works correctly using buildbot 1.2.0 and Python  2.7.13

**Comment by p12tic** [comment]
@tardyp I think this issue can be closed.
