### ISSUE TITLE
Can a github PR build be auto-cancelled on update?

### ISSUE THREAD

**Issue by rgerhards** [buildbot/buildbot#4231]
Hi, we have pretty lengthy runtime on our rsyslog buildbot installation (https://build.rsyslog.com/). Sometimes, a problem is deteced by a "quick slave" (e.g. clang static analyzer) while the slow ones (e.g. "make distcheck") continue to run and do so for quite some while. The problem then is fixed quickly and the commit ammended, PR rewritten. Is it possible to have buildbot auto-cancel the previous runs? I haven't found it in the doc (sry if I overlooked) and this capability would be very helpful, not only to avoid waste of resources. Any hint is appreciated.

**Comment by tardyp** [comment]
This is a common request. Some have hacked it in their bot AFAIR, but not shared the code, or upstreamed it. It is a matter of using the data api to find and cancel build with appropriate properties.

**Comment by rgerhards** [comment]
thx for the answer. If you don't mind, I'd like to keep the issue open, maybe someone comes along and contributes his solution. I'll also see if I can help with something, but my python... ;-)

**Comment by p12tic** [comment]
This feature request has been addressed in #6075.
