### ISSUE TITLE
Broken links to and unsuccessful docs building at Read the Docs

### ISSUE THREAD

**Issue by bugrfeaturer** [buildbot/buildbot#4238]
PDFs unavailable.

http://media.readthedocs.org/pdf/buildbot/v1.3.0/buildbot.pdf
https://docs.buildbot.net/
https://readthedocs.org/projects/buildbot/
https://readthedocs.org/projects/buildbot/downloads/
https://readthedocs.org/projects/buildbot/builds/

**Comment by tardyp** [comment]
@bugrfeaturer thanks for report
