### ISSUE TITLE
`buildbot/buildbot-master:latest` is out of date

### ISSUE THREAD

**Issue by terencehonles** [buildbot/buildbot#4247]
I looked into automated builds on docker hub and it appears this setting wouldn't be something I could create a PR for (it's not like the "official images"), but can we add an additional build hook which is the same as the `v.*` tags, but updates the `latest` tag.

I'd like to pull from the most recent released version rather than master, (My current setup is `FROM buildbot/buildbot-master:master`) and I don't really want to have to be updating the Dockerfile.

This would also help with confusion when initially I had `FROM buildbot/buildbot-master` and docker defaulted to the `latest` tag which was not actually what I wanted.

**Comment by p12tic** [comment]
tardyp: Would it make sense to alter the release scripts to point `latest` to the latest release tag, e.g. `1.7.0` currently?

**Comment by jared-hardy** [comment]
@tardyp shouldn't this :latest tag always keep up with the *latest stable* version of the docker container, currently tagged `v2.3.0`, which I believe is standard practice with all docker containers?

**Comment by terencehonles** [comment]
I think it varies from package to package. Since we already have a `master` tag, it would probably make sense to have `latest` point to the most recent stable version as you both are suggesting.

I mainly wanted to point out that if you were to run `docker run buildbot/buildbot-master` it will default to `latest` which is very out of date rather than `master` which also would probably work, but obviously isn't a stable release.

**Comment by terencehonles** [comment]
@p12tic was there any more thoughts on this? It's been awhile, and I would like to use a `latest` tag so I can auto-build and verify a new buildbot setup rather than manually check for a new stable tag or manually verify I'm ok with `master`.

Not sure how much work this would be on your end, but I would hope it would just be that when a new release is pushed you also push to `latest` (so wherever that change would belong).

cc: @tardyp since both of you pinged them on your messages.

**Comment by terencehonles** [comment]
Looking at the buildbot/buildbot-worker tag list it seems like that might be unmaintained. I'm not sure what latest is pointing to and the more recent versioned tag I see is v2.1.0. I was kinda expecting to see [v2.4.0](https://github.com/buildbot/buildbot/releases/tag/v2.4.0) which calls out bumping the worker to a new Ubuntu version.

Do you guys want help getting this configured? I can try to help, but I don't know where to look.

For the worker images I would expect there to be both a `latest` tag, but also some tags that allow you to pin the base OS image you are building from (so you could potentially have xenial and bionic living side by side for awhile). The reason I was looking was that I build off your image adding some things that are distro specific (or might be), and if the OS was changing I needed to make some updates to my Dockerfile.

**Comment by tardyp** [comment]
@terencehonles we could certainly use help at maintaining docker images. If you want to start working on linking docker hub do your buildbot own fork, and demonstrate better integration, I think we can give you then access to the official docker hub repository.

**Comment by p12tic** [comment]
I believe the problem was that the dockerhub configuration was wrong and attempted to build the worker using wrong context. I've updated the images and they should now work.
