### ISSUE TITLE
how to change name of build directory

### ISSUE THREAD

**Issue by tfzxyinhao** [buildbot/buildbot#4256]
golang project has some special requild for directory struct
like this: **$GOPATH/src/$project**

worker name goproj
GOPATH=/usr/local/goproj

`c['change_source'].append(changes.GitPoller(
        'git@git.xxx.com:go/project.git',
        workdir='src', branch='master', project='monitor',
        pollInterval=300))`

part of log
`.....`  
`OLDPWD=/usr/local/goproj/src`  
`PWD=/usr/local/goproj/src/build` 
`.....`

can configure it to  
`
PWD=/usr/local/goproj/src/$project 
`

**Comment by lancelodliu** [comment]
You can set workdir parameter of the BuildStep.
