### ISSUE TITLE
Undocumented required property

### ISSUE THREAD

**Issue by jugglinmike** [buildbot/buildbot#4281]
[The documentation for the Trigger build step](http://docs.buildbot.net/current/manual/cfg-buildsteps.html#buildbot.steps.source.buildbot.steps.trigger.Trigger) describes the `sourceStamps` parameter with the following text:

> Accepts a list of dictionaries containing the keys `branch`, `revision`, `repository`, `project`, and optionally `patch_level`, `patch_body`, `patch_subdir`, `patch_author` and `patch_comment` and creates the corresponding SourceStamps.

However, if a property named `codebase` is not defined, the step fails with an exception:

>     Traceback (most recent call last):
>     Failure: exceptions.KeyError: 'codebase'

Defining the `codebase` property as an empty string seems to satisfy the internals.

Should this requirement be documented? Should the internals be refactored to support values which omit the property?

- Python version: 2.7.12
- Buildbot version: 1.1.0
- Twisted version: 18.7.0

**Comment by sa2ajj** [comment]
Could you please provide a bit fuller trace back, so the particular line of code could be examined?

Side note: I've been using multiple code bases quite actively, but the things are at work and I do not have access to our Buildbot configuration right now.  (I'll try to check it tomorrow, if I do not forget.)

**Comment by p12tic** [comment]
Closing the bug report as several codebase-related problems have been fixed in the past year. Please re-open if that's not the case.
