### ISSUE TITLE
Doc: bad umask syntax

### ISSUE THREAD

**Issue by kraiskil** [buildbot/buildbot#4287]
In http://docs.buildbot.net/current/manual/installation/worker.html#worker-options
it says I can set e.g. `umask=022`, but this causes the worker not to start with a "Failed to load application: invalid token".
Is this a Python 3 issue? Octal numbers need to be prefixed with `0o`: https://www.python.org/dev/peps/pep-3127/ . This could be mentioned in the Buildbot docs.

**Comment by sa2ajj** [comment]
Thanks for the report, I hope this change fixes the issue.
