### ISSUE TITLE
#4268 breaks Buildbot on Git step workers with different filesystem layout than the master

### ISSUE THREAD

**Issue by terencehonles** [buildbot/buildbot#4316]
Resolving `abspath` in 33682e89057349fed6b72ca7613944b2687633f9 on the Buildbot master does not work in scenarios that the Buildbot worker is using a different working directory than the master.

[Master WORKDIR: /var/lib/buildbot](https://github.com/buildbot/buildbot/blob/master/master/Dockerfile#L93)
[Worker WORKDIR: /buildbot](https://github.com/buildbot/buildbot/blob/master/worker/Dockerfile#L51)

This was rather tricky to track down and I'm going to revert this commit locally and look at fixing it in a subsequent PR.

**Comment by p12tic** [comment]
Indeed, this totally fell out of my mind when developing the prior PR.

**Comment by terencehonles** [comment]
@p12tic I was trying to submit patch, but `tox` in the `master` directory didn't seem to work and I wasn't really able to easily get a local testing environment together. Is there docs/how do you test things locally?

**Comment by tardyp** [comment]
@terencehonles we don't use tox for testing, please have a look at ur development quickstart: http://docs.buildbot.net/current/developer/quickstart.html

**Comment by tardyp** [comment]
do we have a patch for this?

**Comment by p12tic** [comment]
@terencehonles If you lack time, could you just push whatever you had in development and I could polish the code and finish the PR. Thanks!

**Comment by chanphil** [comment]
I'm seeing what may be another manifestation of this issue, although it's possible it's something different.  I'm running a CENTOS docker latent worker from a build master running on Ubuntu, and get the following error during the git --version part of a Git step:

```
Upon execvpe b'git' [b'git', b'--version'] in environment id 139797679318504
:Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/twisted/internet/process.py", line 445, in _fork
    environment)
  File "/anaconda/lib/python3.6/site-packages/twisted/internet/process.py", line 523, in _execChild
    os.execvpe(executable, args, environment)
  File "/anaconda/lib/python3.6/os.py", line 568, in execvpe
    _execvpe(file, args, env)
  File "/anaconda/lib/python3.6/os.py", line 604, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/anaconda/lib/python3.6/os.py", line 594, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory: b'/bin/git'
```

The part that doesn't quite make sense to me is that yum install in CENTOS (the worker) put git in both /usr/bin and /bin, both of which are in the PATH printed in the environment during the Git step.  The buildmaster only has /usr/bin/git, but presumably /bin/git existing on the worker is what's important.  Creating a symbolic link from /bin/git to /usr/bin/git on the master also didn't help.

**Comment by p12tic** [comment]
Will look into this bug next week. As we didn't receive any patch, it's unlikely I'll duplicate anyone's work.

**Comment by tardyp** [comment]
what should I do for the release? should I revert #4278?

**Comment by p12tic** [comment]
Turns out this bug only affects git operations when the recent ssh options are set.

**Comment by terencehonles** [comment]
@p12tic thanks for getting this, I sadly did not have enough time to dig into this. I had barely started looking into it and was just fiddling with things and wanted to test if I was breaking anything else. For our CI I pinned us to the version before the change and was trying to carve out time to look at this. Once again thanks for the help!
