### ISSUE TITLE
Unable to send emails to devel@buildbot.net

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4322]
The emails sent to devel@buildbot.net seems to be getting lost. They do not appear on the devel Archives. For example I sent an email day before yesterday to devel@buildbot.net, but it doesn't show up on  https://lists.buildbot.net/pipermail/devel/2018-September/subject.html

Similarly, I sent two emails last month (Aug 2 and Aug 14), but they did not show up on https://lists.buildbot.net/pipermail/devel/2018-August/subject.html

I did not get any delivery failure notification. However, I did not get any response to any of these emails.

As these emails don't show up on devel archive, it seems like there is something wrong with mail server.

**Comment by tardyp** [comment]
@verm can you look at this?

**Comment by djmitche** [comment]
I see some emails from me at https://lists.buildbot.net/pipermail/devel/2018-September/date.html

**Comment by verm** [comment]
Huh weird I'll look into it tonight.

**Comment by djmitche** [comment]
I've seen some devel@ posts recently, both mine and others'.

@aj062 can you check if this is still the case?
