### ISSUE TITLE
How to list all properties available during build?

### ISSUE THREAD

**Issue by rgerhards** [buildbot/buildbot#4336]
This probably is a pretty dumb question for folks with decent Python know-how ... which I lack.

I have read the properties description http://docs.buildbot.net/latest/manual/cfg-properties.html#common-build-properties but somehow think I miss to find some properties (e.g. those within (?) `kw`, as given in the URL sample on the bottom of the page). 

I also see properties in the builder web UI, as e.g. here https://build.rsyslog.com/#/builders/181/builds/12. nevertheless, it looks like those are even fewer than actually available.

So I wonder if it is possible to somehow output **all** available properties and their actual values. 

The root reason for my question is that I need to integrate our buildbot infrastructure with other services, both (to-be-)home-grown as well as well-known (e.g. CodeCov --> I know about https://github.com/codecov/codecov-python/issues/68 and https://github.com/buildbot/buildbot/pull/1671). I just have a hard time chasing all the property names for all things that I need plus what their actual value is.

Any suggestions are highly appreciated.

**Comment by lancelodliu** [comment]
You can get all the properties in any of your `BuildStep.run` method by calling `self.getProperties()` which returns a `dict`(or sth like) containing all the properties build has got. But note that [properties set by one step will not be seen until next step](http://docs.buildbot.net/current/manual/configuration/properties.html):
> Some build properties come from external sources and are set before the build begins; others are set during the build, and available for later steps.
