### ISSUE TITLE
Provide mechanism to skip a build

### ISSUE THREAD

**Issue by tcarmet** [buildbot/buildbot#4341]
Buildbot already provide a proper mechanism to properly skip build steps with the `doStepIf` parameter, which can be quite useful sometimes.

Would it be interesting to provide the same mechanism for builds/buildrequests? Easily skipping a build with the proper condition set by the user **before** the builds has started and so, in some cases, before the resource has been created.

I see that there are some close functions with the [nextBuild](http://docs.buildbot.net/latest/manual/customization.html#id16) and [canStartBuild](http://docs.buildbot.net/latest/manual/customization.html#id17) but nothing that directly provide an "easy" way to skip a build.

Is it something that we would look into implementing in buildbot itself? Or is it up to the user to make his proper implementation?

**Comment by mrstanwell** [comment]
I've got a related itch to scratch at #4223.  In that case, what I'm thinking about doing is putting an "isBuildRequested" param on the scheduler that only schedules a build if it evaluates to true.

**Comment by tcarmet** [comment]
Thanks for the response @mrstanwell !

Took a look into the description of #4223 sounds like we're looking for the same feature :)

Although it seems that @seankelly was talking about overriding `startBuild`, this could work, but `startBuild` is only defined on `Timed` schedulers, and IMHO I think adding this feature into the `BaseScheduler` would be more useful. But don't I know if that's what we're supposed to do.

Anyway, should we close this issue as a dup of #4223?

**Comment by tcarmet** [comment]
closed as dupe of #4223
