### ISSUE TITLE
REST api does not parse newer python request's get()'s data parameter.

### ISSUE THREAD

**Issue by ewongbb** [buildbot/buildbot#4357]
I only just started trying out the api and apparently the following code doesn't work:

rs = requests.Session()
rs.auth = (user, password)
resp = rs.get('http://localhost:5550/api/v2/auth/login', data={"username": "tester"})

I get a JSONRPC error: JSON parse error: No JSON object could be decoded.

while this is mostly a change in request's _encode_params() https://github.com/requests/requests/blob/master/requests/models.py#L105,  I think this can be fixed by checking for the
type of request.content information.

from https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/rest.py#L186,
it assumes that the incoming request content is a json object.  Should the code be changed
such that it can also convert any urlencoded info to a json object?

**Comment by tardyp** [comment]
did you try

```
resp = rs.get('http://localhost:5550/api/v2/auth/login', json={"username": "tester"})
```

**Comment by ewongbb** [comment]
Oh right.  Thanks.   Yes, that works.
but should that line check whether or not it is a valid json string before loading it?

**Comment by tardyp** [comment]
Well, the try except block is exactly meant to check for bad json.

checking for correct json is equivalent to loading it, so that is why we usually do the try except pattern for loading and detecting error at the same time.

We could also check content-type header, but this does not change much
