### ISSUE TITLE
RFC: Support suspend and wake machines running workers on demand

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#4434]
Hey,

I have several local build servers that are rather rarely used but have non-insignificant power usage on idle. To reduce waste of power I currently suspend and resume them manually. Ideally I'd like buildbot to do this: suspend machine when there have been no builds for a specified time and resume it on demand using a wake-on-lan packet, probably from another machine than the master is running.

Does anyone have any ideas and suggestions on how this could be best implemented?

My current plan is as follows:

- There's new `SuspendableWorker` class that overrides `AbstractLatentWorker`.

- There's a new class `SuspendableWorkerGroupManager` (naming is WIP :-) ) that coordinates when to shutdown or wake up a specific machine that hosts multiple `SuspendableWorker`s.

- Multiple `SuspendableWorker` are linked to `SuspendableWorkerGroupManager`. `SuspendableWorker`s and `SuspendableWorkerGroupManager` communicate about what everyone is doing. Once `SuspendableWorkerGroupManager` notices that workers have been idle for specified time, it insubstantiates them to prevent further incoming builds. Once that completes, it puts the machine to sleep. Any substantiations of `SuspendableWorker`s after that will result in `SuspendableWorkerGroupManager` resuming the machine.

- `SuspendableWorkerGroupManager` is extensible by two actions: `suspend` and `wake`.

- `wake` and `suspend` are implemented via two different class hierarchies. The actions are almost completely independent, for example, suspend will run from different host than wake. Thus we can't just extend `SuspendableWorkerGroupManager` as we`d like to mix and match different implementations of `wake` and `suspend`.

- The implementations of `wake` and `suspend` are implemented by talking to hosts directly without reusing any existing worker infrastructure. At least `suspend` will need elevated privileges and using workers will increase the chance of credential leakage.

Does the above architecture make sense? In particular, I'm interested in complications that might potentially arise in multimaster setups. Do I need add a new table for `SuspendableWorkerGroupManager` to the DB? @tardyp, @seankelly ? :-)

**Comment by seankelly** [comment]
This feels like a latent worker, except with terrible startup time compared to a VM or container. But, the flow feels similar:

1. Need to do builds so start the worker (machine).
2. Do builds.
3. Wait some amount of time (`build_wait_timeout`) for additional builds.
4. Stop the worker (and machine).

But, latent workers are started on-demand while I can imagine people wanting to batch this better. NightlyScheduler does have the ability to batch changes together to only run on regular intervals. That could suffice but also easy to see people want additional flexibility.

**Comment by tardyp** [comment]
I think this is fairly complex and specific usecase. Your design looks okay, but I am not sure it would be useful for many buildbot users.
Typically I doubt multimaster will have such usecase, so I think this is better to keep it simple and to have the limitation that SuspendableWorkerGroupManager must only control a group of worker which is connected on one master.
Also there is a nice key value store infrastructure in the buildbot db, for such usecase where it is not worth to add a db migration.
http://docs.buildbot.net/current/developer/database.html#module-buildbot.db.state

I think this would make sense for a separate plugin python module (like buildbot travis)

**Comment by p12tic** [comment]
First PR implementing this landed as #4691.
