### ISSUE TITLE
Drop Python 2.7 support for master.

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#4439]
## Reasonings:

- Python 2 is going unmaintained as soon as 2020: https://pythonclock.org/

- Maintaining compatibility for both python2 and python3 is expensive resource wise

- Will allow to use python3 features like async/await, which adds a big performance boost for asynchronous apps like Buildbot

## Timeline

Buildbot 2.0 is planned to be released on February 2019.
This version will drop support for 2.7 in the master.

Buildbot 1.7 and 1.8 will contain loud warning for python2 users at Buildbot start to invite them to upgrade.

Original issue:
```
There have been some talks about no longer supporting running master under python 2.x 
some time in the future.
 As 2.0 version will be released soon, maybe it would make sense to mark python 2.x support 
deprecated so that it can be removed in the next major release - 3.0?
```

**Comment by tardyp** [comment]
I would rather drop python 2.x for 2.0. This would allow us to switch to async/await and improve a lot readability debugability and efficiency.

What should be feasible imho is to have a installer script which would automatically convert async/await code to inlinecallbacks for compat with 3.5.

**Comment by p12tic** [comment]
Oh, even better. The async/await conversion is a great idea!

**Comment by tardyp** [comment]
Let's keep it open for discussion. I created an email to users@buildbot.net

**Comment by p12tic** [comment]
Thinking about it more, if we decided to have an LTS, wouldn't be dropping older python 3.x versions that don't support async/await a good idea from maintainability perspective too? Python 3.5.0 is already 3 years old and all LTS releases of major Linux distributions have at least that version.

Ubuntu 18.04 LTS: python 3.6.5
Debian stretch: python 3.5.3
Red Hat Enterprise Linux 7: python 3.6.6 via EPEL

Any users who can't upgrade could just use 1.7.x.

**Comment by seankelly** [comment]
RHEL 8 had a beta release with:

>  Python 3.6 is the default Python implementation in RHEL 8; limited support for Python 2.7 is provided. No version of Python is installed by default.

**Comment by rodrigc** [comment]
We had some discussion for ideas on dropping Python 2.7 support here:

https://supybot.buildbot.net/meetings/buildbot/2018/buildbot.2018-09-04-16.00.log.html#l-100

**Comment by rodrigc** [comment]
I suggested a timeline for dropping Python 2.7 support: https://lists.buildbot.net/pipermail/users/2018-November/001756.html

I also recommended updating the https://buildbot.net web site to put a warning deprecating Python 2.7 support

**Comment by tardyp** [comment]
Looking at the telemetry, we still have 70% of the significant installs (> 1 builder) which is python 2.7, seen over the last 90 days.

I am adding a warning at Buildbot start
https://github.com/buildbot/buildbot/pull/4469

Some suggested also on the documentation, which is the most looked at content, probably more than 
the marketing site.

**Comment by rodrigc** [comment]
Not surprising, if `pip install buildbot` is what people do, that will install buildbot with Python 2.7.

**Comment by tardyp** [comment]
edited original issue to reflect what was decided in meeting

**Comment by Conan-Kudo** [comment]
Python 3 is being requested for inclusion into RHEL/CentOS 7 base: https://bugzilla.redhat.com/show_bug.cgi?id=1639030

**Comment by sirisak1985** [comment]
open

**Comment by SHAGO7932** [comment]
Heeello

**Comment by CAM-Gerlach** [comment]
Random passerby here, but maybe time to retire or at least update the webpage banner, given this issue is well over 4 years old and 2.0.0 was released just over 4 years ago now?

![image](https://user-images.githubusercontent.com/17051931/230390449-875e33fc-cc64-4e8d-8532-6478b2601131.png)

**Comment by terencehonles** [comment]
I assume the trove classifiers haven't been updated to mention newer Python versions (we also use it for newer versions, but aren't on Python 3.12 yet), but for 2.7 that might be left there because the build workers I believe still support Python 2? I'm not sure when that is planned to be dropped, but it seems 2.7 is starting to be slowly pulled from things and it may make sense to drop 2.7 on the worker in addition to the master.

I agree though, that the banner can probably be dropped or changed to reflect that this is in the past i.e. "Buildbot dropped support for Python 2.7 for the master [More Info]"
