### ISSUE TITLE
Buildbot Docker v1.6

### ISSUE THREAD

**Issue by pc-tradelab** [buildbot/buildbot#4449]
Hi,

I am using the docker images of buildbot and I would like to use the version 1.6 : 
* as for buildbot-worker, v1.6.0 exists (https://hub.docker.com/r/buildbot/buildbot-worker/tags/)
* i don't see the v1.6.0 for buildbot-master (https://hub.docker.com/r/buildbot/buildbot-master/tags/ ). However the master was created 2 days ago and may point to the v1.6.0.

Can you update the repo with the latest tags ?

Thanks in advance,

Pc

**Comment by tardyp** [comment]
Thanks for pointing that out. docker tags must be created manually after release due to build scripts limitations. It is now being built
