### ISSUE TITLE
Builder build times graph approximate time Y labels not useful

### ISSUE THREAD

**Issue by hdznrrd** [buildbot/buildbot#4453]
The approximate time used for labeling the Y axis on the builder pages used for displaying historic build times is pretty useless if times are relatively consistent but an approximate time is used.

Take this example:

![](https://chaos.social/system/media_attachments/files/002/058/892/original/b1896dd676dd243e.png?1542983547)

I'm using a docker-based buildbot setup and it shows its version as "2018.11.22"

**Comment by tardyp** [comment]
Thanks for report! this is indeed unfortunate!
