### ISSUE TITLE
Wrong worker version in workers page

### ISSUE THREAD

**Issue by BishopGIS** [buildbot/buildbot#4464]
Workers with version **1.6** report start date instead version. In screenshot Windows worker with version 1.3 reports correct version and fresh workers - start date.

<img width="201" alt="2018-12-04 22 00 29" src="https://user-images.githubusercontent.com/1708122/49466164-61df7600-f810-11e8-8e74-d127cf7d4823.png">

**Comment by seankelly** [comment]
Nitpick, it reports the modified time of the `__init__.py` file. This only happens if all other version detection methods fail.

**Comment by seankelly** [comment]
The `VERSION` file was present in 1.5.0 and is missing in 1.6.0.

**Comment by vibbo** [comment]
Yes, this can be quite annoying.
The culprit commit is this one: https://github.com/buildbot/buildbot/commit/b339c0ede7876d301415b7b875e33cfc496448c1
There is no longer a "VERSION" file in *.whl package in https://pypi.org/project/buildbot-worker/1.6.0/#files and it was present in version 1.5.0. (Note: It is still present in *.tar.gz though).

As I am unfamiliar with the release process, would someone from maintainers fix this problem? Reverting the deleted code was enough to fix this problem, but I am not entirely sure what was the purpose of deleting it in the first place...

**Comment by p12tic** [comment]
Fixed in #5977, will be released as v3.1.1.
