### ISSUE TITLE
drmaa support

### ISSUE THREAD

**Issue by rymaj** [buildbot/buildbot#4487]
Hi There,

I noticed that there were some discussions about DRMAA support in slave/worker long time ago, 
http://trac.buildbot.net/ticket/624

The last action in that ticket was "Milestone changed from 0.8.+ to 0.9.+ Ticket retargeted after milestone closed". Not sure if we are still looking into this feature?  

I tried to search with DRMAA in the current buildbot github web, but didn't find anything meaningful.  Or is there any existing solution to use LSF/SGE as workers that I've missed? Thanks.

**Comment by p12tic** [comment]
AFAIK there's no work being done in this area, but maybe @tardyp knows more?

**Comment by tardyp** [comment]
I wasn't even aware of what DRMAA was. if there is a usable python API, you can try creating a latent worker.
