### ISSUE TITLE
SIGTERM first, then SIGKILL

### ISSUE THREAD

**Issue by rymaj** [buildbot/buildbot#4492]
Hi There,

My builder needs to do some cleanup when it was "Stop", however, it got SIGKILL directly instead of receiving SIGTERM first.

I noticed that there was a defect ticket (http://trac.buildbot.net/ticket/751) saying "
I think that the correct approach is what a lot of initscripts do: send SIGTERM, poll for process exit for some mid-length time, and if it doesn't exit, send SIGKILL. In other words, "please quit", wait, "die". We'll probably also need this to be configurable from the master side - both the inter-signal timeout, and whether to try SIGTERM at all.

I will make a release 0.8.10 this week; it will include the fix for this problem."

But seems this "defect" is still existing in 1.6.0 release. Not sure if someone is still working on it? I can try to work out a patch if not recreating the wheel.

Thanks.

**Comment by rymaj** [comment]
Just realized that sigtermTime was already there. 👍

**Comment by p12tic** [comment]
sigtermTime is documented, looks like there's nothing to fix for us.
