### ISSUE TITLE
secrets.SecretInVault doesn't exist

### ISSUE THREAD

**Issue by seankelly** [buildbot/buildbot#4510]
From IRC:

> I'm trying to get Vault integration up and running with Buildbot  1.7.0. Following the docs I've got `secrets.SecretInVault(...)` being added to `c["secretsProviders"]`. When I start the master server I'm given a config parsing error which reads `error while parsing config file: Unknown component name: SecretInVault (traceback in logfile)`. Anyone have Vault integration up and running with Buildbot or knows what's missing here?

Checking `setup.py` and there's `HashiCorpVaultSecretProvider`. The docs mention `secrets.SecretInVault` however.

**Comment by phillxnet** [comment]
I have replicated this on buildbot version 2.3.1 installed via pip.
```
error while parsing config file:
        Traceback (most recent call last):
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/config.py", line 170, in loadConfig
            self.basedir, self.configFileName)
        --- <exception caught here> ---
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/config.py", line 128, in loadConfigDict
            execfile(filename, localDict)
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/twisted/python/compat.py", line 247, in execfile
            exec(code, globals, locals)
          File "/home/philip/tmp/bb-master/master/master.cfg", line 34, in <module>
            c['secretsProviders'] = [secrets.SecretInVault(
          File "/home/philip/tmp/bb-master/sandbox/lib64/python3.6/site-packages/buildbot/plugins/db.py", line 275, in __getattr__
            raise AttributeError(str(err))
        builtins.AttributeError: Unknown component name: SecretInVault
```

The prior mentioned docs links:
> The docs mention `secrets.SecretInVault` however.

can be found is here: https://docs.buildbot.net/latest/manual/secretsmanagement.html#secretinvault

If instead the following is used:
```
c['secretsProviders'] = [secrets.HashiCorpVaultSecretProvider(
                        vaultToken=open('VAULT_TOKEN').read(),
...
```
Then the vault secrets provider seems to be added successfully.

**Comment by dvaston** [comment]
@phillxnet I am also trying to setup Secret with Hashicorp Vault. I am using Buildbot version 1.7.0

In my master.cfg I have tried:
`c['secretsProviders'] = [secrets.HashiCorpVaultSecretProvider(...`

but when I run "buildbot checkconfig" then I get the error:
`Configuration Errors:`
`error while parsing config file: Unknown component name: HashiCorpVaultSecretProvide (traceback in logfile)`

Is there an extra import statement required in the master.cfg?
Or does this require upgrading to a later version of BuildBot to fix this?

**Comment by phillxnet** [comment]
> Is there an extra import statement required in the master.cfg?

@dvaston I'm very new to buildbot myself but as per the docs and my limited experience, yes you do require an additional import:
```
from buildbot.plugins import steps, util, worker, schedulers, secrets
```
With 'secrets' and 'util' being the most pertinent. See the docs here:
https://docs.buildbot.net/latest/manual/secretsmanagement.html

> Or does this require upgrading to a later version of BuildBot to fix this?

My experience is only with Buildbot version 2.3.1 currently but from my very limited understanding the sercrets management element of Buildbot is an 'in development' system that may well benefit in your case from using the newest version that you can. Note though that more recent versions of Buildbot are python3 only for the master so that might limit your choices.

**Comment by tardyp** [comment]
At some point in buildbot history, HashiCorpVaultSecretProvider was not properly registered as a plugin.
With recent version, this should now be fixed.
