### ISSUE TITLE
Badge for specific branch

### ISSUE THREAD

**Issue by estan** [buildbot/buildbot#4511]
It would be good if you could get a badge showing the status of the latest build of a specific branch. Typically in your README you want to see the status of the main branch (e.g. `master` or `dev`).

**Comment by tardyp** [comment]
usually, people assign builders to branch.
This helps for seeing the evolution of status, and for badges

**Comment by estan** [comment]
Hm, you're right. Perhaps our setup is a little unorthodox, and it would actually be a good idea for us to make separate builders for our long-lived branches, even if the steps would be the same as for the non-long-lived.

Feel free to close this issue :)

**Comment by angeloudy** [comment]
@tardyp Is there a way to dynamically creates builders as branches are added and removed in version control? We tried playing with virtual builders but they don't seem to solve this problem.

**Comment by tardyp** [comment]
Virtual builders are made for the problem you are referring to.
Why do you think they do not solve it?

**Comment by angeloudy** [comment]
@tardyp 
Can you give an example?
My understanding is that virtual builders can dynamically trigger which builder to run, but cannot dynamically add new builders.

**Comment by angeloudy** [comment]
@tardyp 
When you specify a property `virtual_builder_name: builderxxxx`, will it automaticall create a new virtual builder?

**Comment by angeloudy** [comment]
To be clearer, what I'm doing is this:

```
c['schedulers'].append(schedulers.SingleBranchScheduler(
    name='myproject-epics',
    change_filter=util.ChangeFilter(branch_re='epics/.*'),
    builderNames=['myproject-epics'],
    properties={
        'virtual_builder_name': util.Interpolate("myproject-%(prop:branch)s")
    }
))
```

However, we can't use Interpolate here. So I still want to create a virtual builder with a name of the branch in the changeset.

The documentation doesn't give any example, so we are a bit lost on how to implement this.

**Comment by tardyp** [comment]
Indeed, virtual_builder_name is designed to be used with dynamic trigger.
I think your use case make sense, and we should make virtual_builder_name renderable in other schedulers than Triggereable.

I have created #4811 for that matter. note that prop:branch won't work, but ss::branch will.

**Comment by estan** [comment]
Cool Pierre 👍
