### ISSUE TITLE
Docs §1.1.4 not valid behind certain proxies/firewalls

### ISSUE THREAD

**Issue by 0cjs** [buildbot/buildbot#4521]
In the "First Run" documentation at the end of [§1.1.4](https://docs.buildbot.net/1.7.0/tutorial/firstrun.html#creating-a-worker) (after the instructions to start the worker) it says you should see something under the waterfall view and "Your master is now quietly waiting for new commits to hello-world."

My waterfall view shows a blank panel, rather than a line with "runtests" as in the documentation image, and poking around does not provide any indication that anything is configured for `hello-world` at all.

The reason for this is likely that I tried this in a heavily firewalled environment where access to `git://github.com/buildbot/hello-world.git` is blocked:

    2019-01-10 17:01:22+0900 [-] command ['fetch', 'git://github.com/buildbot/hello-world.git', '+master:refs/buildbot/git%3A%2F%2Fgithub.com%2Fbuildbot%2Fhello-world.git/master'] in /home/cjs/co/py-virtualenv/buildbot/buildbot/master/gitpoller-workdir on repourl git://github.com/buildbot/hello-world.git failed with exit code 128: fatal: unable to connect to github.com:
            github.com[0: 192.30.255.113]: errno=Connection timed out                   
            github.com[1: 192.30.255.112]: errno=Connection timed out

Changing the URL to use `https:` instead of `git:` and running `buildbot reconfig` doesn't fix the problem even though both the master and the worker were started with working `http_proxy` etc. environment variables. (`git clone https://github.com/buildbot/hello-world.git` does work fine with these set.) Searching the web for how to configure the master and builder to use a proxy is difficult because of the enormous number of hits on pages describing how to use a reverse proxy in front of the buildbot server.

### Suggested Actions

1. Where you have the user check the buildbot master web server for the `hello-world` app, add a note that network access to `github.com` port TCP/9418 (Git protocol) is required for this to be working.
2. Consider using `https:` instead of `git:` as the default protocol for that repo if that would work ok. This will fix the problem for people with port 443 available but 9418 blocked to `github.com`.
3. From the same place, link to documentation on how to get the master and builder to use a proxy, if that can be done, for people who don't have port 443 access to `github.com`.

**Comment by tardyp** [comment]
Hy @0cjs I think those are good recommendations. Can you send a PR so you can get credits for your findings?

**Comment by 0cjs** [comment]
I've submitted PR #4522 to deal with suggestion action 1 above. (This alone is at least helpful to save debugging time for people following the tutorial and affected by the problem.) However, I'm _very_ new to buildbot so I'm not sure if suggestion 2 has ramifications not obvious to me and I have no idea how to do suggestion 3. If and when I learn enough to deal with those suggestions, I'll come back and handle them if nobody else has already done so.

It's just occurred to me that I can get around the network access problem by cloning `hello-world.git` to somewhere more local and changing the config to point to that. (If I'm particularly lucky, I may be able to use a `file:///` URL to a copy on my local disk.) If that works out for me, do you think it would be worth adding a small section to the documentation on how to do this? I'm thinking a §1.1.5 that's clearly marked optional.

**Comment by tardyp** [comment]
If you are behind http proxy, using https:// url would do the trick, no?
buildbot and git can just use the https_proxy environment variables.

**Comment by 0cjs** [comment]
That works fine for me with `git`, but did not seem to work for the buildbot master process. I'm happy to accept hints on debugging this.

**Comment by tardyp** [comment]
what do you mean by this does not work with buildbot master process?

buildbot uses the standard git binary for its poller and it should forward the environment variable inherited by the buildbot start command.

**Comment by p12tic** [comment]
If I understood correctly, #4522 fixes this issue completely.

**Comment by 0cjs** [comment]
No, there's still the image problem ("There does appear to be a problem with the last image in tutorial §1.1.4;" above). Do we want to re-open this (though the title is misleading) or should I open a new issue for the documentation/image problem?

**Comment by p12tic** [comment]
Let's reopen.

**Comment by 0cjs** [comment]
Since I was re-running the tutorial from scratch because of the 1.1.8 release, I grabbed a couple of screenshots demonstrating what I'm proposing above add put them in a commit in PR #4548.

**Comment by 0cjs** [comment]
I'm closing this as superseded by #4548 for the remaining parts of this issue.
