### ISSUE TITLE
worker stop

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#4533]
When I press 'STOP' on a build, the process running on the worker is terminated. However, our worker process spools up some services that persist after the process ends. The next build then has to wait for those services to complete before it can begin, causing artificially long builds for those subsequent builds. Is there any mechanism to catch the STOP operation so we can terminate those spooled up processes? We are running workers under Windows.

**Comment by p12tic** [comment]
You can set nonzero `sigtermTime` to allow your process to shutdown the services. See http://docs.buildbot.net/2.0.1/manual/configuration/buildsteps.html#shellcommand.
