### ISSUE TITLE
Cannot delete old changes without wiping all of them

### ISSUE THREAD

**Issue by rjarry** [buildbot/buildbot#4539]
I tried to setup the cleanup using the cascade deletes and I noticed that when removing old sourcestamps, all changes are systematically deleted.

Here is how I experienced the problem:

```sql
SELECT count(*) FROM sourcestamps;
-- 737
SELECT count(*) FROM changes;
-- 737

-- Delete soucestamps older than 30 days.
-- The starting point is not "now" but the most recent sourcestamp.
DELETE FROM sourcestamps
WHERE created_at < (SELECT max(created_at) - (30 * 24 * 60 * 60) FROM sourcestamps);
-- DELETE 577

SELECT count(*) FROM sourcestamps;
-- 160
SELECT count(*) FROM changes;
-- 2
```

**Comment by rjarry** [comment]
@tardyp: damn, I forgot to reference this issue in the news fragment. Do you want me to do another pull request for this? Or should I push it directly to the master branch?

**Comment by tardyp** [comment]
please just create a news fragment in new PR. so that we are sure of the spelling
