### ISSUE TITLE
The branch property contains the tag on tag push events

### ISSUE THREAD

**Issue by estan** [buildbot/buildbot#4541]
Hi,

In our build steps, we would like to obtain the Git branch name, even when the build was due to a tag push events, but currently the `branch` property contains the Git tag name on such builds, e.g:

![build](https://user-images.githubusercontent.com/86675/51425340-00fed800-1bdb-11e9-8237-6f8e0450ed4a.png)

(1.0.1 here is the tag name)

How can I get the branch name even for tag builds? Is there some other property which always contains the branch name?

**Comment by seankelly** [comment]
There isn't a branch for tags.

**Comment by estan** [comment]
Fair enough, closing :)
