### ISSUE TITLE
Master can't shutdown when worker gets missing without TCP connection being severed

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#4575]
Reproduction steps:

 - Create sample master config with a single worker.
 - `buildbot start path/master`
 - `buildbot-worker start path/worker`
 - `kill -SIGSTOP $(cat path/worker/twistd.pid)`
 - start build
 - `buildbot stop path/master`

The last step will say: `never saw process go away`

**Comment by seankelly** [comment]
Sounds similar to #2914.
