### ISSUE TITLE
buildbot-worker PATH may change if run as systemd service

### ISSUE THREAD

**Issue by ciarancourtney** [buildbot/buildbot#4590]
I had a build failure on 2019-02-01 because `/usr/local/bin` was missing from `PATH`, it was set to:  `PATH=/sbin:/usr/sbin:/bin:/usr/bin:/snap/bin`

The previous build on 2019-01-31 passed when env had `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

I think this may be caused by a apt upgrade in Ubuntu (also note snap added to my path). My buildbot version didn't change from 1.8.0 during the above.

I couldn't find any existing issues related to this, so adding it here in case anyone else sees it.

I saw your note in docs [here](http://docs.buildbot.net/current/manual/installation/misc.html#launching-the-daemons), so the question is how this should be handled? Perhaps add to the [systemd sample](https://github.com/buildbot/buildbot-contrib/blob/master/master/contrib/systemd/worker.service) ?

    [Service]
    Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

FYI I don't think you can extend PATH in the Environment directive

**Comment by rjarry** [comment]
Hi,

Are you using the Ubuntu Deb package or did you install from pip ?

**Comment by ciarancourtney** [comment]
> Hi,
> 
> Are you using the Ubuntu Deb package or did you install from pip ?

pip

**Comment by rjarry** [comment]
Is it possible that the PATH was modified by something in `/etc/profile.d`?

In any case, if you want to force a PATH environment variable in the systemd service, your example will work.

**Comment by ciarancourtney** [comment]
> Is it possible that the PATH was modified by something in `/etc/profile.d`?

No, nothing changed in `/etc/profile.d`, or `.bashrc` or `/etc/environment` for that matter. Something else I cannot attest to (wouldn't be the first time on ubuntu/systemd)

> In any case, if you want to force a PATH environment variable in the systemd service, your example will work.

Yep, it does work.

So to close this issue I think it would be good to document it, perhaps commented out in the service file sample? I can do this if you want?

**Comment by rjarry** [comment]
> So to close this issue I think it would be good to document it, perhaps commented out in the service file sample? I can do this if you want?

Sure, feel free to submit a pull request :+1:
