### ISSUE TITLE
v2.0.0 disappeared from pypi

### ISSUE THREAD

**Issue by ciarancourtney** [buildbot/buildbot#4611]
https://pypi.org/project/buildbot/#history

Assuming this is not a mistake, It would have been better to push a 2.0.0.post1 release to pypi if something was seriously wrong in 2.0.0

**Comment by rodrigc** [comment]
This was done on purpose.

See:

* https://supybot.buildbot.net/meetings/buildbot/2019/buildbot.2019-02-12-17.00.log.html#l-24
* https://github.com/buildbot/buildbot/issues/4593

This code have been done differently with a 2.0.0.post1 release, but at this point, I guess what is done is done.

**Comment by tardyp** [comment]
we released 2.0.1.
2.0.0 had python2 compatible wheels, if we had kept it, then even if we release 2.0.1, without python2 wheels, then ``pip install -U buildbot`` would pickup 2.0.0.

**Comment by ciarancourtney** [comment]
> we released 2.0.1.
> 2.0.0 had python2 compatible wheels, if we had kept it, then even if we release 2.0.1, without python2 wheels, then `pip install -U buildbot` would pickup 2.0.0.

OK, gotcha
