### ISSUE TITLE
ForceScheduler buttons are not ordered

### ISSUE THREAD

**Issue by atomikin** [buildbot/buildbot#4619]
Steps to reproduce the issue:
1. Create a new buildbot head using buildbot v.2.0.1 or older and python 3.6
1. Create master.cfg using the provided example file
1. Add one more forcescheduler into master.cfg
1. Start the master and check order of buttons
1. Restart the master several times and check the order of the buttons after each restart
* **Actual result**: buttons may change position from start to start, i.e. after master.cfg reload.

I failed to properly trace the error through the code. It may have something to with the fact that the schedulers are stored in the unordered dict. Anyway it makes sense to sort the list of actions in the guanlecoja-ui controller (by caption for example).

**Comment by tardyp** [comment]
Thanks for your report. I have sent a simple patche for this issue
