### ISSUE TITLE
Buildbot raises error if Docker image not on Docker worker host

### ISSUE THREAD

**Issue by vdsbenoit** [buildbot/buildbot#4622]
If we run a build on a Docker latent worker and the image is not yet pulled on the Docker host, the job will fail. 
````
buildbot.interfaces.LatentWorkerCannotSubstantiate: Image "buildbot/buildbot-worker" not found on docker host.
````
With this example, you could tell me to manually pull the image on the Docker host. It will indeed do the trick.
However, in an infrastructure with a local Docker registry, where there are several docker latent worker hosts and several kind of custom images, it can get bothering. Once an image is pushed on the Docker registry, you then have to manually pull it from on every Docker latent worker host. And I guess it is the same for updating images with the `:latest` tag.

**Comment by tardyp** [comment]
You can use autopull=True, or alwaysPull=True options.

**Comment by tardyp** [comment]
http://docs.buildbot.net/latest/manual/configuration/workers-docker.html

**Comment by vdsbenoit** [comment]
My bad... Thank you and sorry for the inconvenience!
