### ISSUE TITLE
buildbot uninstallable due to no satisfactory version of Twisted

### ISSUE THREAD

**Issue by andrewspiers** [buildbot/buildbot#4630]
Hi, I've had exactly the same happen under python 3.7.0 (shown below) and 3.6.3

`andrew@nuc:~/src/sandbox/buildbot-tutorial/bb-master$ python3.7 -m venv sandbox
andrew@nuc:~/src/sandbox/buildbot-tutorial/bb-master$ . sandbox/bin/activate
(sandbox) andrew@nuc:~/src/sandbox/buildbot-tutorial/bb-master$ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.0.3
(sandbox) andrew@nuc:~/src/sandbox/buildbot-tutorial/bb-master$ pip install 'buildbot[bundle]'
Collecting buildbot[bundle]
  Downloading https://files.pythonhosted.org/packages/80/41/ee63aee7ed465b1e65e69fb656ee6a8c90f19573ce3315890491fb78e6a1/buildbot-2.0.1-py3-none-any.whl (779kB)
    100% |████████████████████████████████| 788kB 9.5MB/s
Collecting python-dateutil>=1.5 (from buildbot[bundle])
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting txaio>=2.2.2 (from buildbot[bundle])
  Downloading https://files.pythonhosted.org/packages/e9/6d/e1a6f7835cde86728e5bb1f577be9b2d7d273fdb33c286e70b087d418ded/txaio-18.8.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=8.0 in ./sandbox/lib/python3.7/site-packages (from buildbot[bundle]) (39.0.1)
Collecting autobahn>=0.16.0 (from buildbot[bundle])
  Downloading https://files.pythonhosted.org/packages/d5/5d/49152a3ce88ad8f985a4f82ff9633a29f3ef2da050ae8aba8075142f5a61/autobahn-19.2.1-py2.py3-none-any.whl (302kB)
    100% |████████████████████████████████| 307kB 7.8MB/s
Collecting Twisted>=17.9.0 (from buildbot[bundle])
  Could not find a version that satisfies the requirement Twisted>=17.9.0 (from buildbot[bundle]) (from versions: )
No matching distribution found for Twisted>=17.9.0 (from buildbot[bundle])
`

**Comment by seankelly** [comment]
No versions listed implies that the install failed because nothing from Twisted was found.

**Comment by p12tic** [comment]
It's unlikely that something within buildbot has broken pip downloading. There's no indication that incorrect version has been requested. It's probably an intermittent network failure or something like that.
