### ISSUE TITLE
Polish support for multi-master mode - GSOC 2019

### ISSUE THREAD

**Issue by arvand** [buildbot/buildbot#4651]
I'm applying for GSOC 2019, I wanted to work on this issue. I couldn't find the previous documents and works about this issue. I'm not also sure how can I simulate and test the final outcome?

**Comment by tardyp** [comment]
Hi,

You can start by looking at the multimaster docker setup

There is an official docker compose here:
https://github.com/buildbot/buildbot-docker-example-config/tree/master/multimaster

There is also a kubernetes version
https://github.com/Zempashi/buildbot_kubernetes_deployment/tree/master/kubernetes
which needs to be version updated, but the theory did not change.
@Zempashi I though you have a helm version? can't find it.

Concepts doc are here:
http://docs.buildbot.net/latest/manual/concepts.html#multimaster

I am purposedly not going into details to let you figure it out as a welcome challenge! good luck!

**Comment by Zempashi** [comment]
that's here: https://github.com/buildbot-kubernetes/buildbot-kubernetes

**Comment by arvand** [comment]
@tardyp 
Challenge accepted!

**Comment by tardyp** [comment]
hi @arvand any issue with your challenge? Don't hesitate to get support here or on IRC!

**Comment by arvand** [comment]
Unfortunately I can't apply for GOSC due to visa issues. Sorry
