### ISSUE TITLE
'FakeBuild' object has no attribute 'addStepsAfterCurrentStep'

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4669]
If a build-step uses addStepsAfterCurrentStep() method. Corresponding unit-tests fail will following error:

> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/buildbot/process/buildstep.py", line 577, in startStep
>     self.results = yield self.run()
>   File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
>     result = g.send(result)
>   File "/Library/Python/2.7/site-packages/buildbot/process/buildstep.py", line 707, in run
>     results = yield self._start_deferred
> AttributeError: 'FakeBuild' object has no attribute 'addStepsAfterCurrentStep'
> 

It seems like FakeBuild class doesn't have addStepsAfterCurrentStep method (https://github.com/buildbot/buildbot/blob/master/master/buildbot/test/fake/fakebuild.py#L69)

For Build class this method is at https://github.com/buildbot/buildbot/blob/master/master/buildbot/process/build.py#L482

Seems like addStepsAfterCurrentStep method should be added to FakeBuild.

**Comment by p12tic** [comment]
FakeBuild is not part of public API provided by Buildbot. As a workaround, you could implement your own copy of the class, or upstream the functionality that you use FakeBuild to write tests for.
