### ISSUE TITLE
worker name can not start with a digit?!

### ISSUE THREAD

**Issue by kevbroch** [buildbot/buildbot#4679]
I have a worker machine name that starts with a digit. I am unable to configure the master.cfg to use that worker.

Instead I get the following error:

```
2019-03-25 15:19:13-0700 [-] Configuration Errors:
2019-03-25 15:19:13-0700 [-]   worker name '1example-worker' is not an identifier
2019-03-25 15:19:13-0700 [-]   no workers are configured
2019-03-25 15:19:13-0700 [-]   builder 'runtests' uses unknown workers '1example-worker'
2019-03-25 15:19:13-0700 [-] Halting master.
2019-03-25 15:19:13-0700 [-] BuildMaster startup failed
2019-03-25 15:19:13-0700 [-] BuildMaster is stopped
2019-03-25 15:19:13-0700 [-] Main loop terminated.
2019-03-25 15:19:13-0700 [-] Server Shut Down.
```

I'm able to duplicate this problem for default master.cfg by making the following changes:

```
kbroch@barolo:/home/kbroch/bb_mst_debug $ diff master.cfg.sample master.cfg                                                                                                                   
18c18
< c['workers'] = [worker.Worker("example-worker", "pass")]
---
> c['workers'] = [worker.Worker("1example-worker", "pass")]
69c69
<       workernames=["example-worker"],
---
>       workernames=["1example-worker"],

```

Here's versions:

```
kbroch@barolo:/home/kbroch/bb_mst_debug $ buildbot --version
Buildbot version: 2.1.0
Twisted version: 18.9.0
kbroch@barolo:/home/kbroch/bb_mst_debug $ python3 --version
Python 3.6.7
```

**Comment by tardyp** [comment]
Indeed, most names in Buildbot must be identifier and cannot start with number.
I am not sure how this can be a huge issue.

**Comment by kevbroch** [comment]
I appreciate the response.  Not a huge issue.  I should have read error msg better.  I had dictionary key on the brain instead of identifier. 

My current use case was just to use the environment var $HOSTNAME to set the worker name so I have a buildbot.tac file that's the same for all workers.  I can easily modify this to account for hostnames that start with a digit.

Thanks again for quick response and more importantly all the work on buildbot!
