### ISSUE TITLE
sshHostKey does not support known_hosts file format

### ISSUE THREAD

**Issue by fradeve** [buildbot/buildbot#4681]
Hi all,

thanks a lot for giving us such an amazing project! I have been struggling with this for 2 days, and I decided to open an issue because I can't find my way out.

In order to avoid any trouble, I am using the official worker provided by Docker Hub: `buildbot/buildbot-worker:2.1.0`. Both master and worker are run using Docker Compose.

Secrets configuration:
```
c['secretsProviders'] = [
    secrets.SecretInAFile(dirname="/var/lib/buildbot/secrets", strip=True),
]
```

In the `secrets` folder I have two files, named `id_rsa` and `bitbucket_host_key`, each one with the right permissions.

I have done a manual test, copying both it in the worker container and running
* `ssh -i id_rsa -T git@bitbucket.org` (it works)
* `GIT_SSH_COMMAND=ssh -i "id_rsa" -o "UserKnownHostsFile=bitbucket_host_key" git clone --branch dev git@bitbucket.org:ubiquitypress/zipper.git test` (it works)

```
    steps.Git(
        repourl='git@bitbucket.org:ubiquitypress/zipper.git',
        mode='incremental',
        useProgress=True,
        sshPrivateKey=util.Secret('id_rsa'),
        sshHostKey=util.Secret('bitbucket_host_key'),
    ),
```

During the build I see the following command being triggered:

```
git clone --branch dev git@bitbucket.org:ubiquitypress/zipper.git .
 in dir /buildbot/zipper/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['git', 'clone', '--branch', 'dev', 'git@bitbucket.org:ubiquitypress/zipper.git', '.']
 environment:
  BUILDMASTER=buildbot
  BUILDMASTER_PORT=9989
  GIT_SSH_COMMAND=ssh -i "/buildbot/.build.buildbot/ssh-key" -o "UserKnownHostsFile=/buildbot/.build.buildbot/ssh-known-hosts"
  HOME=/home/buildbot
  HOSTNAME=b388d4351b42
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PWD=/buildbot/zipper/build
  WORKERNAME=worker1
  WORKERPASS=pass
  WORKER_ENVIRONMENT_BLACKLIST="DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST"
  security_updates_as_of=2018-06-15
 using PTY: False
Cloning into '.'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
program finished with exit code 128
```

Any idea? @p12tic I am tagging you here since I went through the code in #4160 in order to understand how the SSH key works, before opening this :D

**Comment by fradeve** [comment]
Hi all,
just to add that I have been able to reproduce the same issue on Gitlab as well. I am not sure if I am missing something, but it seems like the worker is not picking up the SSH key I have specified.

I don't believe the SSH agent is needed in the worker to get it to use the right key (at least, I haven't found this mentioned anywhere in the docs).

**Comment by sinofool** [comment]
I have the same issue using private key.
Buildbot expect the secret file contains host key only, not in "known_hosts" file format.
https://github.com/buildbot/buildbot/blob/master/master/buildbot/util/git.py#L107-L109

The secret file should looks like

> ssh-rsa AAAA<...>WsHQ==

not 

> |1|xx2342k3= ssh-rsa AAAA.....


I need two ssh host keys in my setup, my workaround is add a new line to the top of known_hosts file.

**Comment by p12tic** [comment]
@fradeve: Could you confirm that the workaround by @sinofool works? We indeed currently support only the bare key being passed, but ideally known_hosts file format could also be supported.

**Comment by fradeve** [comment]
Hi all, just want to say thanks @tardyp for your hard work!

Unfortunately I am unable to confirm that this fixes my issue, since we didn't have resources to look into this and we had to switch to a different self-hosted solution.

Hopefully other users in the community will benefit from this :)
