### ISSUE TITLE
Data API inconsistency: buildset times are returned as integers instead of date

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#4682]
Looks like the `submitted_at` and `complete_at` properties of buildsets are integers instead of date like for the rest of date and time properties within the REST API.

**Comment by tardyp** [comment]
So this would only affect the dat api, not the REST api, as in rest, all the dates are automatically converted to integers anyway.
This is done here:

https://github.com/buildbot/buildbot/blob/9043e016101cf0b04b67396ed7f298b9e2b2c4c4/master/buildbot/www/rest.py#L438

https://github.com/buildbot/buildbot/blob/9043e016101cf0b04b67396ed7f298b9e2b2c4c4/master/buildbot/util/__init__.py#L237

We don't have API versioning for data anyway. I am not sure if this is worth it to fix this coherency issue. buildset api is quite specific, so I am not sure if this is really used.
This is clearly API break, so this would in theory mandate a major version bump..
