### ISSUE TITLE
Schedulers does not trigger build if a different scheduler of same type triggered for the same commit

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#4686]
Configuration: v2.0.1
* a GitPoller for the repo URL, and the list of branches
* Each scheduler is initialized with the name of the scheduler, a list of builders, and a ChangeFilter for the branch.
* The schedulers in this case is either a SingleBranchScheduler or a schedulers.Nightly

We have a configuration, among other configurations, with two branches that follow the same commits, with one usually being ahead of the other, or they are on the same commit. The branch names are used to differentiate compile time customization.  Each of these branches have two schedulers,   a SingleBranchScheduler and a schedulers.Nightly.

Expected behavior is that when one of the branches is move to a new commit, new builds are triggered for the relevant branch's new commit.

Actual behavior is that if one of the schedulers of a type have triggered a build for that commit, the other scheduler of the same type, for the other branch, will NOT trigger a build until the branch contains at least one commit that is not yet  part of the first scheduler's branch.

It seems like buildbot is triggering builds based of unique groups of (repository, scheduler_kind, commit) rather than the expected (repository, scheduler_name, branch, commit) group.

This seems to be a regression compared to the previous Chromium-developed 0.8.4-based buildbot we used before.

One possibility that might be useful to investigate is to check which name is used when associating the triggered commits with the scheduler. Is it the master.cfg configured name, or the default name member of the class? Note that the correct name is used in the properties for the triggered build.

**Comment by YngveNPettersen** [comment]
Added a zipped testcase demonstrating the problem

* Unzip the file
* cd into the test directory
* Run setup.sh; this will check out the test upstream repo (buildbot), configure the sandbox and install python modules.
* Run runtests.sh . This will reset the buildbot master, and start it, then update branches in the upstream repo.

Expected result: 4 builds

Actual results: 2 builds

[scheduler_test.zip](https://github.com/buildbot/buildbot/files/3025695/scheduler_test.zip)

**Comment by p12tic** [comment]
Thanks for the bug report and taking time to send a testcase. Indeed this looks like a bug, but I can't promise when the dev team will have time to fix it.

**Comment by YngveNPettersen** [comment]
Did a bit of testing and look around. It seems the problem may be that GitPoller argument buildPushesWithNoCommits defaults to false.

Forcing that argument to True seems to solve the issue.

From my point of view, as mentioned earlier, when I have two branches with a scheduler for each, it should not matter whether those branches and one time or another points to the same commit, both schedulers should trigger for that commit. IMO having only one of the schedulers trigger for a commit as a default is unexpected behavior.

I would suggest that this behavior and the argument's default value should be reconsidered.

**Comment by seankelly** [comment]
Seems somewhat similar to #4642.

**Comment by YngveNPettersen** [comment]
Could be the same issue; possibly same workaround (or solution, depending on whether one thinks current behavior is correct, or not)

**Comment by kallisti5** [comment]
After upgrading from 1.2.0 -> 2.0.0, several of our triggers around repositories stopped working.
https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg


https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg#L1933 to be specific.

**Comment by YngveNPettersen** [comment]
kallisti5: The single scheduler configs for master look similar to the ones I have had trouble with.

As mentioned above, using buildPushesWithNoCommits=true when configuring the GitPoller seems to fix the issue (although, I have recently seen that there is still a problem when first configuring such overlapping schedulers for the first build, triggered just after the scheduler has been added)

**Comment by kallisti5** [comment]
> As mentioned above, using buildPushesWithNoCommits=true when configuring the GitPoller seems to fix the issue

No luck.  I  tried that option without any success.

**Comment by hmoffatt** [comment]
I see something similar; not sure if it's the same; I have two SingleBranchSchedulers triggering the same builder but with different properties.

- one is for any branch with treeStableTimer=15
- the other is for a specific branch with treeStableTimer=60 with extra properties

Normally a push triggers both as expected, but if two pushes come in close together then the second one gets triggered but the first one doesn't.
