### ISSUE TITLE
Started At format on builder page

### ISSUE THREAD

**Issue by erkansari** [buildbot/buildbot#4703]
In buildbot 0.8's builder page we can see exact time of build start(Feb 07 10:27). On buildbot 0.9.15 it shows "2 days ago".  Is it possible to print started at in exact time? Is it possible to see revision number on same page? And owner column is empty. Do I have to do configuration to fill owner column?

**Comment by p12tic** [comment]
Thanks for filing the issue.

> Is it possible to print started at in exact time? 

You can hover on the "2 days ago" text and exact time will be shown.

> Is it possible to see revision number on same page?

Currently no. It's a compromise as showing too much information will make the page inconvenient. In multi-project builds the build has more than one revision associated to it for example, so it's not simple.

> And owner column is empty.

Looks like a bug.

**Comment by p12tic** [comment]
Opened #4735 for the owner column issue.
