### ISSUE TITLE
Add committer field to changes

### ISSUE THREAD

**Issue by rajdeepbharati** [buildbot/buildbot#4709]
Currently, buildbot only has `author` field for a `change`. A `committer` field would be helpful for certain projects.

**Comment by p12tic** [comment]
Hey, thanks for the bug report. Could you shed some light on how these projects would find this feature useful?

**Comment by rajdeepbharati** [comment]
This would be particularly useful for the [Macports](https://github.com/macports) project, where the author doesn't have commit rights to be able to fix a potentially broken commit (only the committer is able to do that), however, buildbot isn't able to send the notification about a failed build to the committer.

**Comment by tardyp** [comment]
First step is to add the committer column to change

Here is an example commit which adds a column to a table.
https://github.com/buildbot/buildbot/commit/b24f0e6479c356c8d4dc86f0fd18a5edc61b9620

Then we will need to add the column to data API

Then add the support in git poller, and git webhooks

**Comment by rajdeepbharati** [comment]
Don't I also have to modify the https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/changes.py
and https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/changes.py files?
