### ISSUE TITLE
Maximum buildstep time

### ISSUE THREAD

**Issue by staticfloat** [buildbot/buildbot#4721]
Sometimes, our build jobs are extremely poorly behaved.  Running the full Julia test suite on an armv7l board typically takes an hour or two, but occasionally something goes terribly wrong in the multithreaded runtime and the process can get stuck in a loop printing out warnings for 17 hours until I notice, login, and `kill -9` the errant process.

The `timeout` parameter works for many of these hiccups, but it would be nice to be able to set an absolute maximum time at which point we _know_ something has gone horribly wrong, and that the entire test should be forcibly destroyed.  In particular, it's important that `buildbot` be able to send very forceful commands (e.g. `kill -9`) as sometimes Julia gets caught in a state where it ignores gentle suggestions to quit, and must be persuaded with more authority.

**Comment by seankelly** [comment]
Do you have the `maxTime` option set? It defaults to disabled.

**Comment by staticfloat** [comment]
Ah, excellent; I did not find that when I searched the documentation, but there it is, clear as day.  I'll try that out, thanks!  Sorry for the noise.
