### ISSUE TITLE
Svn update takes extremely long time

### ISSUE THREAD

**Issue by angeloudy** [buildbot/buildbot#4722]
I found recently that the SVN step takes extremely long.
But if I run the svn command by hand, it takes less than one second.

My gut feeling was that it has something to do with python `subprocess` module.
So tried to run 
```
python3 -c "import subprocess;subprocess.Popen(['svn', 'update', '--non-interactive', '--no-auth-cache', '--username', 'buildbot', '--password', 'xxxxxxx'])"
```
And, as expected this command hangs forever

My buildbot-worker is 1.5.0 running on MacOSX 10.14.4, subversion 1.11.1

**Comment by p12tic** [comment]
I think subprocess in certain cases will deadlock if the command returns a lot of output, even though the documentation says otherwise. We need to check whether this is the case here and maybe have a wrapper that buffers the output correctly.

**Comment by p12tic** [comment]
Looking again, we use `twisted.internet.utils.getProcessOutput` which should be immune to the problem I mentioned. Could you perhaps check what `subprocess.Popen` does in your case if you pass `stdin=subprocess.DEVNULL`?

**Comment by angeloudy** [comment]
Yes, even with `stdin=subprocess.DEVNULL`, it still stucks.
I found that the problems goes away if I restart buildbot master; then after running for a few days, it will happen again.

**Comment by angeloudy** [comment]
It does not stuck with `stdout=subprocess.DEVNULL`
