### ISSUE TITLE
IRC Channel History

### ISSUE THREAD

**Issue by uglycoyote** [buildbot/buildbot#4731]
The website lists the IRC channel as one of the primary places to go to "Get Involved".   I'm not involved enough to be present on the IRC channel very frequently, but I would like to search it for things that might be being discussed, either particular issues, or just general terms (e.g. I'm interested in the buildbot frontend, so I might search "javascript" or something)
There should be an easy way to browse the IRC log history.

I used to do searches every once in a while on the IRC logs at https://irclogs.jackgrigg.com/, but it seems like that server has stopped archiving stuff recently, so I was wondering if there is anywhere else where the IRC chats are archived?  see [this search](https://irclogs.jackgrigg.com/search.pl?server=irc.freenode.net&channel=buildbot&nick=&q=coffee) for an example, it says the last mention of coffee was May 2018

I think I originally got the idea of using this jackgrigg log from the Buildbot community. e.g. it is mentioned in this buildbot [trac issue](http://trac.buildbot.net/ticket/2853) where about 3-4 years ago it sounded like people were looking for a more stable alternative to jackgrigg.    It seems like jackgrigg may not be maintaining his IRC bot that diligently, e.g. it has a link in the footer that says "powered by Snailbot" which links to http://snailbot.jackgrigg.com/, which at the moment is redirecting to the website for "Eliza Grigg,  NZ Alpine Ski Team".

If there is currently a stable logging solution somewhere else, it would be good to link to that off the main page.  

Incidentally, a way to search the mailing list archives would be nice too, but that is a separate issue I guess.

**Comment by tardyp** [comment]
Hi,

Indeed jackgrigg has been down for a while. There has been discussion to
move our chat to other place, but this has not yet been finished.

For irclogs a lot of us use irccloud, so this is not as much of an issue to
not have the archives.
It is basically a BNC SaaS, which we find very practical. It is 4 EUR per
month.
We do not have affiliation or anything, it is just a cool service that has
made the job for years without any issues.

We would love if somebody step up to create a bot with logging. maybe we
can use our good old supybot to generate and serve those logs.


Regards,
Pierre


Le jeu. 25 avr. 2019 à 00:49, uglycoyote <notifications@github.com> a
écrit :

**Comment by tardyp** [comment]
Here is an irccloud export of buildbot channel:

https://www.irccloud.com/log-export/82323/irccloud-export-45259-2019-04-25-11-16-30.zip
I can generate that for you every once in a while if you want.

Regards
Pierre

**Comment by uglycoyote** [comment]
the link you posted gives me a 401 unauthorized error, so I guess it's accessible to you because you are logged in there but not to me.

**Comment by tardyp** [comment]
[irccloud-export-45259-2019-04-25-11-16-30 (1).zip](https://github.com/buildbot/buildbot/files/3118559/irccloud-export-45259-2019-04-25-11-16-30.1.zip)

**Comment by uglycoyote** [comment]
that link works. thanks!

**Comment by p12tic** [comment]
I think that @tardyp uploading IRC logs somewhere on request is good enough solution. It solves the problem for the few people that have it without large investment of time.

**Comment by p12tic** [comment]
@uglycoyote  Thanks for bringing this up. My IRC logs have holes, so it's good to have a log with definite history.
