### ISSUE TITLE
Don't timeout during clone / checkout

### ISSUE THREAD

**Issue by mojca** [buildbot/buildbot#4745]
During `git clone` buildbot (2.2) seems to supress all output. A big disadvantage is that it can no longer differentiate between situation when git (or another VCS) is still happily doing its job and situations when something actually hanged. If the command kept outputting something, buildbot wouldn't need to time out.

In my case I wanted to fetch https://github.com/tex-live/luatex.git which is apparently more than 1 GB during checkout.

Note that also #3281 is true for me, but it's orthogonal and I'm actually glad that this other ticket was not addressed at this very moment. I figured out that I had 16 instances of `git` running, all started by buildbot in the last two hours. The internet connection where I'm now is horrible, so I was glad that those thousand megabytes kept being fetched after the timeout occured :) :) :) Of course, it would be nice to fix both.

**Comment by mojca** [comment]
Oh, wait. I now noticed the option

> progress (optional)
>     Passes the (--progress) flag to (git fetch). This solves issues of long fetches being killed due to lack of output, but requires Git 1.7.2 or later.

which presumably solves just that. This makes me wonder: doesn't buildbot immediately check for git version at the beginning? It could automatically turn this on when git is new enough.

**Comment by rajdeepbharati** [comment]
git version can be checked and then the value of progress can be set accordingly here:
https://github.com/buildbot/buildbot/blob/master/master/buildbot/steps/source/git.py#L84

**Comment by rajdeepbharati** [comment]
@p12tic do you want me to send a PR?

**Comment by p12tic** [comment]
@rajdeepbharati : That would be great! We already have some version parsing in buildbot/master/buildbot/util/git.py.

**Comment by rajdeepbharati** [comment]
@p12tic I probably can't use that method since progress needs to be set inside `__init__` constructor of `class Git`

**Comment by p12tic** [comment]
> @p12tic I probably can't use that method since progress needs to be set inside `__init__` constructor of `class Git`

You don't need to. You just need to call it before you make a decision on whether to add `--progress` flag. If you check the code flow you'll see that it's already done for you.
