### ISSUE TITLE
Allow hiding of inactive builders in Waterfall view

### ISSUE THREAD

**Issue by rajdeepbharati** [buildbot/buildbot#4761]
Add an option to hide old builders from waterfall view.

**Comment by rajdeepbharati** [comment]
@tardyp Virtual builders don't have any master (hence no active master). Should I make them have some `builder.masterids`?

**Comment by rajdeepbharati** [comment]
Or we can simply do:
```
if (builder.tags.includes('virtual')) {
  active = true;
}
```
in `hasActiveMaster` function (this wouldn't work unless 'virtual' tag has been assigned to virtual builders.

**Comment by tardyp** [comment]
I like the virtual tag idea
