### ISSUE TITLE
Logical operator like && is quoted in ShellCommand command at runtime

### ISSUE THREAD

**Issue by ciarancourtney** [buildbot/buildbot#4768]
I parse YAML config files for each project to create a simple build steps using shell commands e.g.

    steps:
        build:
            cmd: make && make install

Example is only illustrative, I know its better to split it up or use sub-shell commands.

If I pass `command` as a string to `ShellCommand` it works fine, but if I split the string into a list and pass that in, the && operator will be single quoted, and break.

**Comment by tardyp** [comment]
what do you mean single quoted?

Are you aware that the command parameter as a list in ShellCommand is interpreted as raw argv process arguments (without shell processing)

I think this can be your source of confusion.

**Comment by ciarancourtney** [comment]
> what do you mean single quoted?

In the log output it will appear to be run as `make '&&' make install` and fail, as expected. If I instead pass `command` as a str it runs `make && make install` and works fine.

> Are you aware that the command parameter as a list in ShellCommand is interpreted as raw argv process arguments (without shell processing)

Does that mean you just can't use logical shell operators (is that what their are called?) like `&&` `|| ` or `;` when using a list type command?

**Comment by tardyp** [comment]
> Does that mean you just can't use logical shell operators (is that what they are called?) like && || or ; when using a list type command? 

No you can't. This also mean you don't have to quote stuff that can be interpreted by shell in filename.
We usually recommand using this type of argument as this is less error prone especially combined with property interpolation.
Why do you insist in using the list type?
Do you know that yaml has several way of doing multiple line strings?
It is pretty confusing, there is even a website dedicated to that https://yaml-multiline.info/

**Comment by ciarancourtney** [comment]
> Why do you insist in using the list type?

Do only reason is so I can use interpolation, I have build steps migrating from jenkins that I can't change e.g.

    . ./jenkinVersion.sh && ./build.sh ${JENKINS_VERSION}_${BUILD_NUMBER}

In the above I want `$JENKINS_VERSION` to be substituted with the var sourced from `jenkinVersion.sh`
and I want to substitute $BUILD_NUMBER for the buildbot `buildnumber` property. To do this I am replacing occurrences of `${BUILD_NUMBER}` in cmd with the property, this works fine.

**Comment by tardyp** [comment]
You can use Interpolate in order to do that.
```python
ShellCommand(command=Interpolate("""
. ./jenkinVersion.sh && ./build.sh ${JENKINS_VERSION}_%(prop:buildnumber}s
""")```

So in your yaml parsing, you can pass you cmd attribute through Interpolate before sending to ShellCommand, and then add interplate syntax inside your yaml.

Note that buildbot_travis is doing all that already:

https://github.com/buildbot/buildbot_travis#interpolate

**Comment by ciarancourtney** [comment]
@tardyp Great, thats much better than what I had, don't know why I didn't think of that!

FYI you have a typo in sample above, the last bracket, maybe fix it to save someone else their sanity :)

On a different note, I did look at the Travis wrapper before, is it easy to migrate an existing db to this and does it upstream buildbot cleanly? I was mainly looking at it before for easy github PR builds, but gave up as the setup looked pretty complex compared to buildbot.

**Comment by tardyp** [comment]
>  I was mainly looking at it before for easy github PR builds, but gave up as the setup looked pretty complex compared to buildbot.

It is supposed to actually be simpler, as a lot of the boilerplate config is already implemented.

>  is it easy to migrate an existing db

buildbot_travis will create additional builders along side your existing builders.

>  does it upstream buildbot cleanly ?

not sure I understand the question

**Comment by ciarancourtney** [comment]
> > I was mainly looking at it before for easy github PR builds, but gave up as the setup looked pretty complex compared to buildbot.
> 
> It is supposed to actually be simpler, as a lot of the boilerplate config is already implemented.
> 
> > is it easy to migrate an existing db
> 
> buildbot_travis will create additional builders along side your existing builders.
> 

In that case I might give it another go.

> > does it upstream buildbot cleanly ?
> 
> not sure I understand the question

I mean is buildbot a dependency of buildbot_travis, its not pinned to a specific version and comparability is maintained both ways?

**Comment by tardyp** [comment]
> I mean is buildbot a dependency of buildbot_travis, its not pinned to a specific version and comparability is maintained both ways?

buildbot_travis is what we use for running our own buildbot CI. So we make sure we follow the buildbot changes. There are not too much actually, as Buildbot API is pretty stable, and buildbot_travis is not using private API.
