### ISSUE TITLE
shellCommand fails when passed a lists. 

### ISSUE THREAD

**Issue by Fenn-CS** [buildbot/buildbot#4812]
`builder.addStep(steps.ShellCommand(command=["cd", "folder"]))` would fail throwing the follow error:
```
Upon execvpe b'cd' [b'cd', b'folder'] in environment id 139697078579272
:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/process.py", line 445, in _fork
    environment)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/process.py", line 523, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python3.6/os.py", line 568, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python3.6/os.py", line 604, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.6/os.py", line 594, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory: b'/bin/cd'
```

While `builder.addStep(steps.ShellCommand(command="cd folder"))` works fine. 

_I am guessing this is a problem with twisted?_

**Comment by Fenn-CS** [comment]
**Follow up**
I additionally noticed that, though "cd folder" run's without throwing an error the builder remains in the same directory meaning the command does not take effect.

**Comment by yhager** [comment]
You can't run `cd` in a shell command, it's not a binary. Instead, put the command you want and use `workdir` property.

**Comment by Fenn-CS** [comment]
@yhager figured that out later but had no idea of the buildbot workdir property, thank you!
