### ISSUE TITLE
SVN quiet checkout failed

### ISSUE THREAD

**Issue by christophercylai** [buildbot/buildbot#4851]
steps.SVN( … extra_args=['quiet'])

command timed out: 1200 seconds without output running [b'svn', b'checkout', b'<branch name>', b'.', b'--non-interactive', b'--no-auth-cache', b'--quiet'], attempting to kill

I think steps.SVN is looking for some output from SVN - probably looking for revision number and other SVN info. I am trying to find a way to conduct a quiet SVN checkout, because currently all the checkout output is written to hard drive, and making the build master slow.

**Comment by p12tic** [comment]
Buildbot waits for any output for `timeout` seconds, after that time it assumes the command hung and kills it. Maybe you could increase the `timeout` parameter of the SVN command?

**Comment by christophercylai** [comment]
Thank you p12tic, you are right.
Closing this issue.
