### ISSUE TITLE
Fully support committer field

### ISSUE THREAD

**Issue by rajdeepbharati** [buildbot/buildbot#4860]
changes.commiter is `null` on 

- [ ] github pull requests
- [ ] hooks

**Comment by aliceinwire** [comment]
this is actually a bug.
 sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: changes.committer

**Comment by rajdeepbharati** [comment]
@aliceinwire have you run `buildbot upgrade-master`?

**Comment by aliceinwire** [comment]
I'm rebuilding the environment but the error persist.
I'm using docker 
image:buildbot/buildbot-master:master
and
```
sources.append(GitHubPullrequestPoller(
   owner='aliceinwire',
   branches=None,
   category='mycategory'
   repo='my-repo'))
)
```

**Comment by aliceinwire** [comment]
i'm trying to use buildbot-master:v2.3.1 and see if something change

**Comment by rajdeepbharati** [comment]
committer field is still a WIP. It has only been added to the db layer and data api. Does this happen when you don't use GitHubPullrequestPoller?

**Comment by aliceinwire** [comment]
buildbot-master:v2.3.1 worked but I'm starting to think that it could actually be a problem with docker.
docker-compose down and docker-compose up was probably still keeping the same instance.
I will check again with buildbot-master:master and report

**Comment by aliceinwire** [comment]
Work also with buildbot-master:master after I pulled the image again.

**Comment by rajdeepbharati** [comment]
with the pullrequestpoller?

**Comment by aliceinwire** [comment]
yes

**Comment by nakyong** [comment]
@rajdeepbharati  Hello, if i'd like to use directly with Docker and files in github (buildbot),  Which version should I use?
I'm getting same issue and i'm trying to handle pull request.
buildbot_1  |   sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "committer" violates not-null constraint

In advance, thank you for help:)

**Comment by rajdeepbharati** [comment]
@nakyong You should use the one on the master branch which is available on docker hub: https://hub.docker.com/r/buildbot/buildbot-master
Maybe you have to pull the image again.
I tested it using docker but I don't seem to get any issue. Could you provide some more context?

**Comment by nakyong** [comment]
@rajdeepbharati Thank you for reply. I tried again and I solved issue. It looks not pulled well at first time!
