### ISSUE TITLE
HttpStatusPush docs are not clear

### ISSUE THREAD

**Issue by Extravert-ir** [buildbot/buildbot#4867]
In HttpStatusPush documentation:
https://docs.buildbot.net/current/manual/configuration/reporters.html#httpstatuspush
it is not clear, what's the format of the `build` parameter of `format_fn` function.

Would be nice to have a link to the format description, or the format itself put into that paragraph

**Comment by p12tic** [comment]
Seems to be addressed as of now (see https://docs.buildbot.net/3.3.0/manual/configuration/reporters/http_status.html). Closing the bug.
