### ISSUE TITLE
REST API endpoints return data with wrong HTTP Content-Type

### ISSUE THREAD

**Issue by Extravert-ir** [buildbot/buildbot#4870]
REST API endpoints return json data with `Content-Type: text/plain; charset=utf-8`, while it should be `application/json`

**Comment by tardyp** [comment]
application/json content is sent only if accepts json header is set.

see code and comments:
https://github.com/buildbot/buildbot/blob/master/master%2Fbuildbot%2Fwww%2Frest.py#L414
