### ISSUE TITLE
     error: package directory 'buildbot' does not exist

### ISSUE THREAD

**Issue by nakyong** [buildbot/buildbot#4883]
Hello,

I'm trying to test master based on ubuntu16.04.
I copied  latest setup.py and then run same 'Dockerfile' (except linux-alpine, I'm trying to change ubuntu 16.04)

When i build Dockerfile, it gave error like below.
Processing /usr/src/buildbot
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/buildbot.egg-info
    writing top-level names to pip-egg-info/buildbot.egg-info/top_level.txt
    writing requirements to pip-egg-info/buildbot.egg-info/requires.txt
    writing dependency_links to pip-egg-info/buildbot.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/buildbot.egg-info/entry_points.txt
    writing pip-egg-info/buildbot.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/buildbot.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'buildbot' does not exist

Could somebody help me?
I did based on this github, so It's hard to figure out the issue.

**Comment by tardyp** [comment]
That dockerfile is mean to be built from within the full source code.

Did you copy only the dockerfile?

Pierre

**Comment by nakyong** [comment]
@tardyp Thank you for reply.

Could you explain "full source code" means?
I copied dockerfile & setup.py & README.rst.

I thought, 'pip3 install buildbot' installing buildbot
 : Installing collected packages: buildbot

 Should I copy 'buildbot/master/buildbot/'?

**Comment by p12tic** [comment]
You should checkout Buildbot source using git and execute Dockerfile from there. The packages downloaded via e.g. pip miss a bunch of things referenced by the Dockerfile.

**Comment by nakyong** [comment]
@tardyp @p12tic  Thank you for reply!
 After checkout it, it solved issue. I thought pip could download things needed.

**Comment by tardyp** [comment]
Note that the Dockerfile in our repo is too complicated for normal use.

You can just use a much simpler version:

https://github.com/buildbot/buildbot-docker-example-config/tree/master/pypy/master

Here this is with pypy, but you can just use

```
from python:3-onbuild
```

**Comment by nakyong** [comment]
@tardyp  could you explain main difference between simple one and this one?
I'd like to check what should I use, but it's difficult to find details. 
Thanks!

**Comment by tardyp** [comment]
The one I just pointed is 2 lines of dockerfile. The one that we use in CI
is more complex, as it builds buildbot from source.
Pierre
