### ISSUE TITLE
Ubuntu comes with Python 3 but Buildbot can't find it on install

### ISSUE THREAD

**Issue by garhbod** [buildbot/buildbot#4889]
Running `pip install buildbot` produces `RuntimeError: Buildbot master requires at least Python-3.5`

But `python3 --version` returns `Python 3.6.8`

Not sure how to sort the issue

**Comment by rajdeepbharati** [comment]
try doing `pip install -U pip`

**Comment by seankelly** [comment]
`/usr/bin/pip` corresponds to Python 2, you need to use `pip3` for Python 3.

**Comment by p12tic** [comment]
I think the question has been answered, closing the bug.
