### ISSUE TITLE
Performance of stopping jobs on Yocto Project buildbot instance is problematic

### ISSUE THREAD

**Issue by rpurdie** [buildbot/buildbot#4894]
The Yocto Project has a buildbot installation at: https://autobuilder.yoctoproject.org/typhoon/#/console which includes a custom console view plugin (http://git.yoctoproject.org/cgit.cgi/yocto-autobuilder2).

A characteristic of this is there are a couple of trigger jobs (a-full and a-quick) which trigger 40-50 sub jobs. If we notice a build failing and want to stop it, we can hit the "stop" button in the buildbot UI. The problem is that the server then goes completely non-responsive for 3-4 minutes. Builds that are running will keep running and the UI does come back but nginx will timeout and we lose the UI for that time.

We shared profiling data with tardyp who said it looked like some kind of unindexed database query problem. We switched our database backend from sqlite to mysql and whilst the UI is responsive in some other ways, the original problem remains. The database is around 8GB in size, mostly with logfiles. We're looking at timing those out but I instinct says that probably also won't help this timeout problem much. Any pointers on how to improve things, or help debug this are welcome. We can reproduce the problem at will by starting a build, letting it get going then stopping it.

**Comment by tardyp** [comment]
Need to repro with a unit test if you can give me the sqlite db file on an S3 or something. that can help

**Comment by p12tic** [comment]
@tardyp: Do we have any way to check for long running queries from Buildbot side? I think it would be a valuable too to directly pin point the issues like this without the need to acquire full database from the user.

**Comment by tardyp** [comment]
Here, it looks like there are several long running queries, at the same time, which fills all the thread of the db thread queue.
I think long running queries are inevitable, probably we could split the queue into two, one for long queries, and another for short queries.
For that particular case, I think there is an unindexed query that we should fix.

**Comment by tardyp** [comment]
I've tried to reproduce the issue with your sqlite db  and wasn't able to reproduce any slowness.

Here is the test I wrote:
```python
# This file is part of Buildbot.  Buildbot is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Copyright Buildbot Team Members


import locale
import os
import shutil
import sqlite3
import tarfile
import time

import migrate
import migrate.versioning.api
from sqlalchemy.engine import reflection
from sqlalchemy.exc import DatabaseError

from twisted.internet import defer
from twisted.python import util
from twisted.trial import unittest
from buildbot import util

from buildbot.db import connector
from buildbot.db.model import EightUpgradeError
from buildbot.test.fake import fakemaster
from buildbot.test.util import db
from buildbot.test.util import querylog
from buildbot.test.util.integration import getMaster
from buildbot.data.resultspec import ResultSpec, Filter

class SlowStopBuildTestMixin( unittest.TestCase):

    # db URL to use, if not using a real db
    db_url = os.environ.get("YOCTO_SQLITE_DB")

    @defer.inlineCallbacks
    def setUp(self):
        self.basedir = self.mktemp()
        os.mkdir(self.basedir)
        print(self.basedir)
        self.master = master = yield getMaster(self, None, {'db_url': self.db_url, 'multiMaster': True,})
        self._sql_log_handler = querylog.start_log_queries()

    def tearDown(self):
        querylog.stop_log_queries(self._sql_log_handler)

    @defer.inlineCallbacks
    def test_basic(self):

        # take one of the parent builds, and build any associated buildrequests
        res = self.master.db._engine.execute("select buildrequests.id from buildsets left join buildrequests on buildrequests.buildsetid=buildsets.id where parent_buildid=43729;")
        dl = []
        brids = [row[0] for row in res.fetchall()]
        for brid in brids:
            # mark those builds as pending
            res = self.master.db._engine.execute("update builds set complete_at=null, results=null where buildrequestid={};".format(brid))
            res.close()

        stopped_builds = []
        @defer.inlineCallbacks
        def controlStopBuild(path, args):
            # fake a build stop (finishBuild, and compressLogs)
            buildid = path[-2]
            for step in (yield self.master.data.get(('builds', buildid, 'steps'))):
                for log in (yield self.master.data.get(('steps', step['stepid'], 'logs'))):
                    yield self.master.data.updates.compressLog(log['logid'])
            print("stop build", buildid)
            yield self.master.data.updates.finishBuild(path[-2], 0)
            stopped_builds.append((path[-2]))

        yield self.master.mq.startConsuming(controlStopBuild,
                                                ("control", "builds",
                                                None,
                                                "stop"))

        # simulate trigger step cancelling requests in parallel
        for brid in brids:
            print("cancel", brid)
            dl.append(self.master.data.control('cancel', {}, ('buildrequests', brid)))
        yield defer.gatherResults(dl)

        # wait that all builds have been stopped
        while(len(stopped_builds)<len(brids)):
            t1 = time.time()
            yield self.master.data.get(('builders',))
            # make sure there is no stall of reactor
            print(time.time()-t1, len(stopped_builds),len(brids))
            yield util.asyncSleep(1)
```

This test case do not reproduce any stall of reactor, and no slow db query

I use following patch to see if there are slow requests, but there are none.
```
@@ -211,6 +211,9 @@ class DBThreadPool(object):
                         log.err(e, 'Got fatal Exception on DB')
                     raise
             finally:
+                elapsed = time.time() - start
+                if elapsed > .1:
+                    print("slow db request!", elapsed, callable, args, kwargs)
                 if not with_engine:
                     arg.close()
             break
```
 
Then I wondered if there could be anything in the master config which could freeze the master thread.
I can see this supspicious code:
https://git.yoctoproject.org/cgit/cgit.cgi/yocto-autobuilder2/tree/steps/observer.py#n45

```
        self.addCompleteLog('warnings', '\n'.join(self.warningLines))
        self.addCompleteLog('errors', '\n'.join(self.errorLines))
```
Depending on number of warnings, or errors. The join could be fairly long.
If this is the culprit, it would be best to stream those warnings as soone as they arrive, instead of gathering them in the end.

As a next step, you can try to apply the long running query warnings patch and see if this triggers (you may need to tweak the threshold)

**Comment by rpurdie** [comment]
Thanks for looking, its puzzling you couldn't reproduce. FWIW the errors and warnings lists we have should be short, mostly zero, a maximum of maybe a hundred very rarely. Whilst bad practice, I'm therefore not convinced that join would cause this. I'll try the slow query patch and see if we can see anything.

**Comment by tardyp** [comment]
Other thoughts:
There have been a few  db optimization that entered the mainline since 1.6 version that you are using. 
Those db optimization come with a migration script which is pretty long to run on your db. took 10min for me on my macbookpro
I did try my test with both master branch and  1.6 tag, but couldn't reproduce as well.

Also another test to try is to increase the pool_size using 
c['db_url'] = "mysql://username:password@example.com/database_name?pool_size=40"

this to check if the problem comes from a saturation of the db thread pool or if this is coming from a stall of the reactor thread.

You can also check if http request which does not use db is served while you have a stall situation.
if the reactor thread is stalled, then the page won't be served if you have db pool saturation, then the image should be served.
ex:
https://autobuilder.yoctoproject.org/typhoon/img/icon.svg

**Comment by rpurdie** [comment]
I just tried doing two things, one was adding the slow query logging and at the same time, I tried loading icon.svg. I coulnd't load icon.svg which suggests the reactor thread is stalled. I also noticed that the build itself seemed to have stopped in the logs but we were seeing "wkl" updates which is our plugin that updates a wiki page. I'm now deeply suspicious of our wiki plugin. I did previously check and this wasn't the bottleneck however that was before the switch to mysql so it could be there were multiple problems.

**Comment by rpurdie** [comment]
I disabled that code and can confirm that whilst the UI is laggy when we stop the build, it doesn't hang. The code in question is the Buildfinished call to updateBuild: http://git.yoctoproject.org/cgit.cgi/yocto-autobuilder2/tree/reporters/wikilog.py#n65. We are seeing a few slow queries in the logs so I'll post those logs here next in case that also shows anything interesting/of use from a performance perspective.

**Comment by rpurdie** [comment]
Having rewritten the way our wiki log plugin works, the system is now much more repsonsive when stopping builds so this was our broken plugin. Sorry for the confusion.
