### ISSUE TITLE
How to use Secrets?

### ISSUE THREAD

**Issue by EndrII** [buildbot/buildbot#4908]
From the documentation, I realized that I need to create a folder with secrets, and each file in it will be a key, and the contents of the file will be a value.

How can I get the value of a secret file?

An example I have a file folder:
``` bash
(sandbox) andrei@quasarapp:~/buildBotSecret$ ll
total 28
drwxrwxr-x  2 andrei andrei 4096 Jul 22 06:52 ./
drwxr-xr-x 29 andrei andrei 4096 Jul 21 19:50 ../
-rw-------  1 andrei andrei   12 Jul 22 06:49 ENDRII
-rw-------  1 andrei andrei   41 Jul 19 19:28 gitHub
-rw-------  1 andrei andrei   15 Jul 22 06:52 SIGPASS
-rw-------  1 andrei andrei   37 Jul 22 06:52 SIGPATH
```

Service Initialization:
``` python
        self.masterConf['secretsProviders'] = [
            secrets.SecretInAFile(dirname="/home/andrei/buildBotSecret")
        ]
```

Attempt to get value:

``` python
@util.renderer
def androidQmake(props):

    command = [
        'qmake-android',
        '-spec', 'android-clang',
        "-r",
        "CONFIG+=qtquickcompiler",
        util.Interpolate('SIGN_PATH="%(secret:SIGPATH)s"'),
        'SIGN_ALIES="quasarapp"',
        util.Interpolate('SIGN_STORE_PASSWORD="%(secret:SIGPATH)s"')
    ]

    return command

```

But qmake gets the invalid value \<SIGPATH\> in place of the file contents.

same behavior with authz

``` python
        # minimalistic config to activate new web UI
        self.masterConf['www'] = dict(port=8010,
                        plugins=dict(waterfall_view={}, console_view={}, grid_view={}))

        self.masterConf['www']['authz'] = util.Authz(
                allowRules = [
                    util.AnyEndpointMatcher(role="admins")
                ],
                roleMatchers = [
                    util.RolesFromUsername(roles=['admins'], usernames=['EndrII'])
                ]
        )

        self.masterConf['www']['auth'] = util.UserPasswordAuth([
            ('EndrII', util.Interpolate('%(secret:ENDRII)s')),
            ])

```

Apparently util.Interpolate ('% (secret: ENDRII) s') did not work correctly and now I can’t get rid of by the user EndrII

Maybe I'm doing something wrong, tell me what could be the problem?

**Comment by EndrII** [comment]
full code of the [project](https://github.com/QuasarApp/QuasarAppCI/tree/master/BuildBotLib)

**Comment by p12tic** [comment]
@EndrII: Could you check the master logs? It may contain a clue to why the error is happening.

**Comment by EndrII** [comment]
yes 
[twstdlog.log](https://github.com/buildbot/buildbot/files/3434424/twstdlog.log)

**Comment by EndrII** [comment]
Note that keys were transferred to qmake

``` python
@util.renderer
def androidQmake(props):

    command = [
        'qmake-android',
        '-spec', 'android-clang',
        "-r",
        "CONFIG+=qtquickcompiler",
        util.Interpolate('SIGN_PATH="%(secret:SIGPATH)s"'),
        'SIGN_ALIES="quasarapp"',
        util.Interpolate('SIGN_STORE_PASSWORD="%(secret:SIGPATH)s"')
    ]

    return command
``` 
[stdio.log](https://github.com/buildbot/buildbot/files/3434451/stdio.log)

**Proof** :
```
/home/andrei/Qt/Qt-v5.13.0/Android/bin/androiddeployqt --input /home/andrei/worker/githubworker/github-worker/build/installer/../Snake/android-libsnake.so-deployment-settings.json --output /home/andrei/worker/githubworker/github-worker/build/installer/../android-build --jdk /usr --gradle --sign <SIGPATH> quasarapp --storepass <SIGPATH> --release
```

**--sign <SIGPATH> quasarapp --storepass <SIGPATH> --release**

[stdiodeploy.log](https://github.com/buildbot/buildbot/files/3434456/stdiodeploy.log)

**Comment by EndrII** [comment]
Your documentation says that only the secret key is printed in the logs.
But:
  1. 2nd it is qmake output.
  2. If the secrets has been transferred correctly, then I would have received a correctly assembled project, but I received an error in the place of it.
  3. Some problem with login in buildbot,  If the secrets has been transferred correctly, then I could log in

**Comment by phillxnet** [comment]
Not sure if this is relevant or helpful but I've recently had success with SecretInAFile:
```
c["secretsProviders"] = [secrets.SecretInAFile(dirname="/home/philip/secrets")]
...
steps.Git(
...
repourl=util.Interpolate(
        "https://buildbot:%(secret:buildbot)s@gitlab.com/...git")
```
But note that unlike almost all the problem examples here, this was not within a command list.
buildbot 2.3.1 via pypi install.

Re secrets use in www auth I think I remember something about it not yet working there anyway. Sorry I'm new to buildbot so may have this all wrong.

**Comment by phillxnet** [comment]
OK, just found the reference that I think led me to doubt that secrets were supported in ['www']['auth']:
But that was an older version of buildbot (1.5.0):
See @p12tic comment in: #4725 
Again I'm new to buildbot so apologies if I'm muddying the waters here.

**Comment by dvaston** [comment]
Just adding a note on this ticket. I have now upgraded BuildBot on my local pc to v2.3.1

c['secretsProviders'] = [secrets.SecretInAFile(dirname="C:\\TestSecretFolder\\")]
...
f_test.addStep(steps.ShellCommand(command=["my_app.exe", util.Interpolate("%(secret:TestSecretFile.txt)s")]))
...
In the logs I get: my_app.exe <TestSecretFile.txt> 
But in my application I still see the obfuscated parameter "<TestSecretFile.txt>"

**Comment by EndrII** [comment]
I have a temporary [solution](https://github.com/QuasarApp/QuasarAppCI/blob/b02b2229cfbd49082f0322b39f6338d74f0ebd1f/BuildBotLib/buildBotServices.py#L17) until the secret service is fixed.

I use own [SecretManager](https://github.com/QuasarApp/QuasarAppCI/blob/master/BuildBotLib/secretManager.py)

**Comment by tardyp** [comment]
This is not clear at all to me why @EndrII solution will fix the problem, as it is very similar to secretInAFile. 
It looks like there is a lot of confusion in this thread.

> But in my application I still see the obfuscated parameter "<TestSecretFile.txt>"

Where do you look at to find out the parameter is obfuscated. If it is in Buildbot logs, then it is normal. Buildbot will remove all instances of the secret from its log for obivous security reason. You can workaround that by transforming the secret. for example

f_test.addStep(steps.ShellCommand(command=util.Interpolate("echo %(secret:TestSecretFile.txt)s | base64"))

you will probably need to adapt to windows shell

**Comment by dvaston** [comment]
Hi @tardyp, Buildbot calls my F# application my_app.exe and passes in the password parameter. Below is a snippet from my application code

`open System`
`[<EntryPoint>]`
`let main args =`
`    let myPwd = args.[0]   // This has the obfuscated text "<TestSecretFile.txt>" instead of the actual password "ThisIsSecretText" from my Secrets file`
`...`

**Comment by tardyp** [comment]
>let myPwd = args.[0] // This has the obfuscated text "<TestSecretFile.txt>" instead of the actual password "ThisIsSecretText" from my Secrets file

How do you know that?
Do you debug the code?

If you just print myPwd to stdout, then buildbot will obfuscate it *after* print

**Comment by dvaston** [comment]
> How do you know that?
> Do you debug the code?
> How do you know that?
> Do you debug the code?

Hi @tardyp, I have tested it a couple of ways, e.g. doing a string comparison of the args parameter from within my F# program:

`open System`
`[<EntryPoint>]`
`let main args =`
`    let myPwd = args.[0]`
`    if myPwd = "<TestSecretFile.txt>" then Console.WriteLine "args has obfuscated text"`
`    elif myPwd = "ThisIsSecretText" then Console.WriteLine "args has password text"`
`    else Console.WriteLine "args has some other text"`

**Comment by dvaston** [comment]
Ok, I tested it another way, just doing a string comparison from within my F# code (and not outputting the contents of the args to the BuildBot console) and it seems to work ok, for example:

`open System`
`[<EntryPoint>]`
`let main args =`
`    if args.[0] = "<TestSecretFile.txt>" then Console.WriteLine "args has obfuscated text"`
`    elif args.[0] = "ThisIsSecretText" then Console.WriteLine "args has password text"  // Getting this so all good now :)`
`    else Console.WriteLine "args has some other text"`
`...`

Thanks :)

**Comment by sananand007** [comment]
I am not convinced that this is a closed discussion ? 

I am also Trying to debug this exact problem with buildbot to expose `secrets` but unable to figure out how to just print out the `values` stored . 


```
self.secrets['secretsProviders'] = [secrets.SecretInAFile(dirname=self.secrets_dir_local)]
```

My `dirname` is a `Path` which contains `text` files whose names are the `keys` that I would like to access and the values are the `content` of the text file . 


In `pycharm` debugger, I do not see anything related to the files in the directory within the `self.secrets` dictionary.

**Comment by sananand007** [comment]
> I am not convinced that this is a closed discussion ?
> 
> I am also Trying to debug this exact problem with buildbot to expose `secrets` but unable to figure out how to just print out the `values` stored .
> 
> ```
> self.secrets['secretsProviders'] = [secrets.SecretInAFile(dirname=self.secrets_dir_local)]
> ```
> 
> My `dirname` is a `Path` which contains `text` files whose names are the `keys` that I would like to access and the values are the `content` of the text file .
> 
> In `pycharm` debugger, I do not see anything related to the files in the directory within the `self.secrets` dictionary.

![image](https://github.com/buildbot/buildbot/assets/13934022/b82be544-aaf5-49c9-a41d-4db5b96e426f)

**Comment by sananand007** [comment]
Also the secrets need to be accessed and then passed as `strings` to another application as `arg` values, how can we do that, there is no specific examples to do that in the docs ?

**Comment by sananand007** [comment]
Also something we cannot just use `Interpolate` since we have to use something as below where we need to use `bash` because we have to set some `export` before running a `script` . Why cannot we have a easier way to expose just strings ?

```
util.ShellArg(
                        command=[
                            "bash",
                            "-c",
                            f"export PYTHONHTTPSVERIFY=0 && cd <path> && python3 scripts/file.py --jenkins-user {util.Interpolate('JENKINS_USER="%(secret:jenkins_user)s"')} --jenkins-password {util.Interpolate('JENKINS_PASSWORD="%(secret:jenkins_password)s"')} ",
                        ],
                        logname="running_sanity_check"
                    )
                    ```
