### ISSUE TITLE
deleteOldLogChunks too slow

### ISSUE THREAD

**Issue by angeloudy** [buildbot/buildbot#4926]
I am using `LogChunksJanitor` to delete old logs.
The job runs once a week.
But every time it took over 3 hours to run, during which period, all the other builder cannot run because the SQL `delete` query locks the database.
The problem is that there are just two many rows in `logs` table. 
Can we delete the logs by chunks, like 1000 rows a time? It will be much faster.

**Comment by tardyp** [comment]
Hello,

Can you tell which database you are using?
How many log per week to you have?

I am not sure how deleting rows by chunk will make it faster.

On the other hand, If you run the janitor everyday, it will obviously be 7 times faster.

**Comment by angeloudy** [comment]
I am using mariadb 10.3.16.

This link explains why it's slow to delete from large tables.

https://dba.stackexchange.com/questions/147103/mysql-delete-becomes-exceptionaly-slow-with-a-large-number-of-rows

I will change it to daily see how fast it can get.

**Comment by angeloudy** [comment]
I just ran my janitor again(4hours since last run) and it took the same amount of time.
So changing it to daily wouldn't help.
I think the problem is I am only deleting logs that are one months old. 
The `logs` table is still huge even with one month's data.
The snowiness could be in the queries to find logs to delete.
It was 3 times slow before I made this change #4893

**Comment by angeloudy** [comment]
The SQL that does the job is
```
DELETE FROM logchunks WHERE logchunks.logid IN (SELECT logs.id  FROM logs  WHERE logs.type = 'd'
```
This query is extremely slow even the `SELECT` subquery returns empty.

There are known issues with sql `DELETE`  with subqueries.
It is recommended to use `JOIN`

If I change the above query to 
```
DELETE t1 FROM logchunks t1 JOIN (SELECT logs.id  FROM logs  WHERE logs.type = 'd'
logs.type = 'd') t2 ON t1.logid = t2.id
```
, it returns immediately.

**Comment by tardyp** [comment]
Hi.
Your thinking makes sense

The code is here"

https://github.com/buildbot/buildbot/blob/7658c965b3bedb3e5532446e1352f62fe7c102ab/master/buildbot/db/logs.py#L395
Would you like to expirement and change the ``in`` into a ``join``, and report your findings?

**Comment by angeloudy** [comment]
I don't know how to write the `join` query. But I did the following changes and now my builder only takes 30 seconds to run, which is more than 100 times faster.
```
diff --git a/master/buildbot/db/logs.py b/master/buildbot/db/logs.py
index 3baef22bf..ca59bc20d 100644
--- a/master/buildbot/db/logs.py
+++ b/master/buildbot/db/logs.py
@@ -384,15 +384,11 @@ class LogsConnectorComponent(base.DBConnectorComponent):
                 )
                 res.close()

-            # query all logs with type 'd' and delete their chunks.
-            q = sa.select([model.logs.c.id])
-            q = q.select_from(model.logs)
-            q = q.where(model.logs.c.type == 'd')

             # delete their logchunks
             res = conn.execute(
                 model.logchunks.delete()
-                .where(model.logchunks.c.logid.in_(q))
+                    .where(model.logs.c.id == model.logchunks.c.logid).where(model.logs.c.type == 'd')
             )
             res.close()
             res = conn.execute(sa.select([sa.func.count(model.logchunks.c.logid)]))
```
