### ISSUE TITLE
Question about Secrets - password text is still obfuscated in the destination application

### ISSUE THREAD

**Issue by dvaston** [buildbot/buildbot#4944]
I have a question on using Secrets. I want a password parameter to be obfuscated in my BuildBot config files and log files. However, I want the actual (non-obfuscated) password to be accessible from within my destination application which is being executed from BuildBot. Is this possible?

I am using this in my master.cfg:
`c['secretsProviders'] = [secrets.SecretInAFile(dirname="C:\\TestSecretFolder\\")]`

Then in my factory I am using this:
`f_myFactory = util.BuildFactory()`
`f_myFactory.addStep(steps.ShellCommand(command=["my_app.exe", util.Interpolate("%(secret:TestSecretFile.txt)s")]))`

When I run this through BuildBot I am seeing the password parameter obfuscated in the BuildBot log file, so far so good. :)
`my_app.exe <TestSecretFile.txt>`

However, within the destination application my_app.exe (this is an F# program) I am seeing the parameter being passed through as the literal text _**"<TestSecretFile.txt>"**_. How do I get the actual (non-obfuscated) password text (that is meant to be inside my file C:\\TestSecretFolder\\TestSecretFile.txt ?

I am referring to the documentation on http://docs.buildbot.net/current/manual/secretsmanagement.html

Just want to check if I am missing something, or is this a limitation of BuildBot?
Note: I am currently on BuildBot v1.7.0

**Comment by dvaston** [comment]
Note: this may be similar to #4908

**Comment by EndrII** [comment]
This is the same problem as #4908 
I think this is an error, because the interpolation function should return the actual password but not it's key

**Comment by dvaston** [comment]
Closing this as a duplicate of #4908
