### ISSUE TITLE
hgpoller fails with "null value in column committer"

### ISSUE THREAD

**Issue by komaeda** [buildbot/buildbot#4987]
I'm running a Buildbot master inside a Docker container, and I have an HgPoller set up to poll a Kallithea repository. When the poller detects changes, it fails with the following:

```
buildbot_1  | 2019-08-23 19:58:52+0000 [-] hgpoller: repo poll failed
{... unneeded stack trace ...}
buildbot_1  |   sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "committer" violates not-null constraint
buildbot_1  |   DETAIL:  Failing row contains (9, marisa <marisa@mokou.zone>, null, Add lint script for CI execution, default, 8c43f72068449130372da25f6583531c9e4f88a8, , 1566588893, null, https://callie.marisa.cloud/tometo/tometo, , tometo, 1, null).
```

Reading through the hgpoller source, this seems to stem from here:

https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/hgpoller.py#L285

Am I correct in assuming that `committer=None` is directly opposed to `committer` being a non-null constraint in the database? If so, wouldn't that be a clear bug?

**Comment by rajdeepbharati** [comment]
@komaeda Yes I think you're right. Since there's no concept of `committer` in mercurial, we can either set it to an empty string in hgpoller or set it as nullable in the db layer.

**Comment by tardyp** [comment]
committer and author should be identical, if there is no notion of committer

**Comment by eev** [comment]
@tardyp So just set `committer` to `author` unconditionally? Mind if I create a pull request for that?

**Comment by tardyp** [comment]
pull requests are always very much welcomed
Pierre

**Comment by mojca** [comment]
> @tardyp So just set `committer` to `author` unconditionally? Mind if I create a pull request for that?

Yes, but only for the version control systems which don't support the committer. Subversion and mercurial come to mind, and you should not do it for git. I'm not familiar with the rest.

**Comment by rajdeepbharati** [comment]
I had accidentally set all of them except git (svn, hg, etc.) to none. Bitbucket needs to be fixed as well https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/bitbucket.py#L144

**Comment by tardyp** [comment]
are we saying that all changesources but git are broken in buildbot 2.4?

**Comment by mojca** [comment]
@tardyp: after a second thought: is it really necessary that the committer field is not null / equal to the author?

From my point of view it could be handled both ways (either being null or equal to the author for the systems that don't support this). Unless the committer would be actually used in some ways where it's always needed, I find it perfectly OK (actually better) if we have some values set to null when the underlying version control system doesn't support that particular variable, and just change the database entry to allow nulls.

As an extreme example, I was thinking of potentially writing `RsyncPoller` which would check whether anything changed on the rsync server. This could work perfectly well to trigger the builds only when changes are seen, but the only reasonable value for the author (and committer) would in fact be null.

So in a way I would be more in favour of properly supporting null values, but it's of course up to you to decide.

**Comment by rajdeepbharati** [comment]
> are we saying that all changesources but git are broken in buildbot 2.4?

Yes, I guess (I hadn't manually tested on other vcs)

**Comment by rajdeepbharati** [comment]
@mojca the reason I set it to not null was because it would otherwise become difficult to handle situations where committer can't be null (say in git).
But your argument is also perfectly valid. So it's up to @tardyp

**Comment by tardyp** [comment]
I think committer == author for vcs not supporting committer is a good thing, but I also think they should be able to be null (both)

Actually the committer patch was incoherent regarding model.py and the migration script.
Which means that this bug is only about new setups, and not about upgrading setups, which explain why we don't have that much complains.

I've send a simple fix for model.py
@p12tic I think that one deserves patch release. :-/
