### ISSUE TITLE
`__contains` filter doesn't allow `.` (dot) character

### ISSUE THREAD

**Issue by rajdeepbharati** [buildbot/buildbot#4994]
For example, I want to query something like:
`http://localhost:8010/api/v2/builders?name__contains=llvm-6.0`
It shows error:
```
{"error": "invalid filter value for name__contains"}
```

**Comment by rajdeepbharati** [comment]
@tardyp @p12tic Is it possible?
I guess it is coming from here https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/rest.py#L325

**Comment by rajdeepbharati** [comment]
I changed [this line](https://github.com/buildbot/buildbot/blob/82e70bc62598fad0737c0b814013be79ee1247b9/master/buildbot/www/rest.py#L321) to `values = [bytes2unicode(v)`
It worked, but a few tests are failing

**Comment by tardyp** [comment]
It is because BuilderName is identifier in the data api.

The regular expression there do not contain dot
https://github.com/buildbot/buildbot/blob/747279acfbfde3a9d3b9b3b78c72329f39cefa29/master/buildbot/data/types.py#L159

Can you fix it?

**Comment by rajdeepbharati** [comment]
OK thanks, I will try to fix this.

**Comment by mojca** [comment]
I started with #4861, but had no time to finish it, so I closed it until I would find time to fix all the unit tests etc. Having this fixed would be awesome also from the perspective of regular builder names, not just the virtual ones.

**Comment by rajdeepbharati** [comment]
@tardyp This one seems to be a really simple fix (just by changing the regex) and surprisingly the CI isn't breaking. But in the one by @mojca (dots in workernames) I do get a ton of failed tests.
