### ISSUE TITLE
Cannot use haproxy in PB port connection string

### ISSUE THREAD

**Issue by AndrewCooper** [buildbot/buildbot#5001]
In fact it seems like PB port can only use these:
```python
_serverParsers = {"tcp": _parseTCP,
                  "unix": _parseUNIX,
                  "ssl": _parseSSL,
                  }
```

Because of the way buildbot listens for PB connections, twisted cannot handle a connection string for anything except tcp,unix, or ssl. If a parser besides these three is requested, endpoints._parseServer() returns a different structure and strports.listen() raises a TypeError trying to find a reactor listenX function. It appears to be mostly a twisted bug, but perhaps buildbot could use the strports.service() like it does for www.

```python
#buildbot/pbmanager.py:135
def startService(self):
    assert not self.port
    self.port = strports.listen(self.portstr, self.serverFactory)
    return super().startService()
```

```python
#twisted/application/strports.py:46
def listen(description, factory):
    from twisted.internet import reactor
    name, args, kw = endpoints._parseServer(description, factory)
    return getattr(reactor, 'listen' + name)(*args, **kw)
```

```python
#twisted/internet/endpoints.py:1532
_serverParsers = {"tcp": _parseTCP,
                  "unix": _parseUNIX,
                  "ssl": _parseSSL,
                  }

#twisted/internet/endpoints.py:1627
def _parseServer(description, factory):
    args, kw = _parse(description)
    endpointType = args[0]
    parser = _serverParsers.get(endpointType)
    if parser is None:
        # If the required parser is not found in _server, check if
        # a plugin exists for the endpointType
        plugin = _matchPluginToPrefix(
            getPlugins(IStreamServerEndpointStringParser), endpointType
        )
        return (plugin, args[1:], kw)
    return (endpointType.upper(),) + parser(factory, *args[1:], **kw)
```

**Comment by tardyp** [comment]
I am not sure what you are trying to do. How do you want to configure buildbot?

**Comment by AndrewCooper** [comment]
I wanted to use haproxy as a TLS terminator between workers and master. So a configuration like `haproxy:tcp:9989` on the master

**Comment by tardyp** [comment]
In that case, from the point of view of the master, it sees a tcp connection, so just configure it tcp:9989

**Comment by AndrewCooper** [comment]
Ok, I'll try that. I was under the impression that the master would need original worker information via PROXY protocol.
