### ISSUE TITLE
Mercurial/HG broken. Only the GitPoller manages to trigger the AnyBranchScheduler (or SingleBranchScheduler)

### ISSUE THREAD

**Issue by datgame** [buildbot/buildbot#5004]
Same exact setup for git and hg, but only git version works.
ForceScheduler and Periodic however work fine for hg too.
So my guess is that HgPoller is broken? I see in the log that it detects a change, but then it won't kick off the Single/AnyBranchScheduler anyway.
This is after I manually had to apply this fix to the 2.4.0 release
https://github.com/buildbot/buildbot/pull/4989/files

OS: Arch Linux, and buildbot installed via Arch's official package repo.

**Comment by smelc** [comment]
@datgame > If you're using an instance of HgPoller per branch you watch, try making HgPoller's name unique, see the discussion here : https://github.com/buildbot/buildbot/issues/4876#issuecomment-510084971. If this fixes the issue, this confirms the discussion on https://github.com/buildbot/buildbot/issues/4876. In addition, if this fixes the issue, you may use HgPoller new capability (buildbot 2.2.0) of tracking multiple branches with a single instance; until this fix is integrated.

**Comment by datgame** [comment]
Adding name="randomstring" to the HgPoller fixes it! GitPoller didn't need this.
I only have 1 branch and 1 poller. So it's not related to multiple branches.
I just set up a minimal builder from scratch. no special extras or anything.
However, regarding the repourl, you must end it with a / or buildbot will just append "default" to the string during build and not find it. It should add "/default" instead I presume. (I had branch=None)

**Comment by tardyp** [comment]
fixed in https://github.com/buildbot/buildbot/releases/tag/v2.4.1
