### ISSUE TITLE
Log viewer is low contrast, and is illegible to colorblind users

### ISSUE THREAD

**Issue by dankegel** [buildbot/buildbot#5021]
The log viewer for some reason uses dim red text on a black background for most of its output.  Here's a screenshot:

![Bildschirmfoto von 2019-09-26 11-52-30](https://user-images.githubusercontent.com/170976/65716585-4f128800-e054-11e9-8062-89c38812beba.png)

And here it is zoomed in so you can see individual pixels, and how dim they are:

![Bildschirmfoto von 2019-09-26 11-56-22](https://user-images.githubusercontent.com/170976/65716860-ccd69380-e054-11e9-891a-023801e39970.png)

The resulting contrast is low, especially for red colorblind users.

There are a *lot* of users with some degree of red colorblindness.

You could fix this by increasing the contrast of the current colorized output.
Alternately, you could add a button to turn off colorization (and use full contrast), but that'd be annoying to have to click every time you looked at a log file.

See also https://contrastrebellion.com/

**Comment by tardyp** [comment]
This looks like a font issue. Here's how it looks on my mac:

![image](https://user-images.githubusercontent.com/109859/65720547-7bf08a80-e0a8-11e9-9215-654313f8ddca.png)

You can look in developer console, and tell me what font looks good on your setup
![image](https://user-images.githubusercontent.com/109859/65720799-033dfe00-e0a9-11e9-897d-cef3749b2ad8.png)

Font selection is currently:
```
    font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
```

**Comment by dankegel** [comment]
Dammit. Probably a dup of https://github.com/buildbot/buildbot/issues/4186

**Comment by tardyp** [comment]
> Dammit. Probably a dup of #4186


Indeed..
