### ISSUE TITLE
Custom templates still not working

### ISSUE THREAD

**Issue by vibbo** [buildbot/buildbot#5035]
Hi, this is the original issue with broken custom templates #4980

But it doesn't work even after the fix (2.4.1).
The web part of Buildbot is far to complicated for me. But I was able to find lines like this in scripts.js?_1568233606304
```
    , function(e, t) {
        e.exports = window.T["undefined/properties.html"] || '<table class="table table-hover...
    }
```
And I presume there is something wrong if there is "**undefined**/properties.html".

**Comment by marrak** [comment]
@tardyp when we can expect new release containing this fix?
