### ISSUE TITLE
p4 issues

### ISSUE THREAD

**Issue by bschatt** [buildbot/buildbot#5042]
We had a lot of issues with p4poller recently. Most of them appeared after we enabled ticket-based auth on our p4 server.

1. (moved to #5148)

2. We are currently running in a random issue. Sometimes we get a weird error forever. I think this is due to the password parameter but not sure. I will let you know if I find anything.

> 2019-10-17 17:49:41+0200 [-] P4 poll failed on XXX.XXX.XXX.XXX:1666, //XXXXXXXXX/
> 	Traceback (most recent call last):
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
> 	    result = f(*args, **kw)
> 	  File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/changes/p4poller.py", line 175, in poll
> 	    d = self._poll()
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
> 	    return _cancellableInlineCallbacks(gen)
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
> 	    _inlineCallbacks(None, g, status)
> 	--- <exception caught here> ---
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
> 	    result = g.send(result)
> 	  File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/changes/p4poller.py", line 245, in _poll
> 	    result = yield self._get_process_output(args)
> 	  File "/home/buildbot/.local/lib/python3.7/site-packages/buildbot/changes/p4poller.py", line 183, in _get_process_output
> 	    d = utils.getProcessOutput(self.p4bin, args, env)
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/utils.py", line 128, in getProcessOutput
> 	    reactor)
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/utils.py", line 28, in _callProtocolWithDeferred
> 	    reactor.spawnProcess(p, executable, (executable,)+tuple(args), env, path)
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 331, in spawnProcess
> 	    args, env = self._checkProcessArgs(args, env)
> 	  File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 981, in _checkProcessArgs
> 	    raise TypeError("Arguments contain a non-string value")
> 	builtins.TypeError: Arguments contain a non-string value

3. Buildbot seems to create normal workspaces even when the depot is a stream depot. I added the support for streams. I can submit a PR for this feature if you want.

Useful informations :
Buildbot version: 2.4.1
Twisted version: 18.9.0
Python 3.7.3

**Comment by tardyp** [comment]
I don't have any knowledge on p4
@aisoard @lancelodliu are the two last contributors on p4 ticket parsing

fdd2e40ba6959c85a020eacf4fa054721c96fca2 and 0707d290f741bcc8e2a7c0ebe12d946c76d6b448

Is this a problem of compatibility with different p4 versions?

**Comment by bschatt** [comment]
Ticket parsing is working fine as far as I know.

The first error is probably more related to Python than perforce. My guess is that it was caused by the end of the Python 2 support.

I'm not sure why the second issue is happening but I finally managed to fix it by simplifying the code. I will fill a PR.

**Comment by bschatt** [comment]
I submitted PR #5045 to fix my first issue but I feel like I'm missing something. I will run more tests.

In the mean time is there a reason why the ticket is read from stdout rather than stored in ~/.p4tickets which is the default behaviour ?

**Comment by magestik** [comment]
Any news on this ?

**Comment by bschatt** [comment]
Any news on this ?

**Comment by p12tic** [comment]
@bschatt: I fixed the #5045 PR.

Regarding your questions:

> In the mean time is there a reason why the ticket is read from stdout rather than stored in ~/.p4tickets which is the default behaviour ? 

I don't know much about P4 myself, but according to the cursory reading of the documentation, the ticket expires in 12 hours. So maybe the developer of the P4PollingStep just decided to query for the ticket every time instead of using cached value, which may be stale?

> Buildbot seems to create normal workspaces even when the depot is a stream depot. I added the support for streams. I can submit a PR for this feature if you want.

That would be great! I can review that in timely manner, you won't need to wait as much as for your first PR.

**Comment by bschatt** [comment]
Thanks for fixing/merging #5045 !

I will try to submit the PR to support Stream depots soon.

**Comment by bschatt** [comment]
Please see #5149 (streams support) and #5150 (ticket issue).

**Comment by p12tic** [comment]
I think this issue has been fixed  #5045, #5149 and #5150.
