### ISSUE TITLE
Set Server header to buildbot

### ISSUE THREAD

**Issue by oxr463** [buildbot/buildbot#5081]
The response headers currently return the following,

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Server: TwistedWeb/19.2.1
Date: Fri, 22 Nov 2019 01:08:35 GMT
Content-Type: text/html
Cache-Control: public;max-age=0
```

I would like to both A) be able set this value from the `master.cfg`, and B) set it to `Server: buildbot` by default.

**Comment by tardyp** [comment]
I think this make sense.
https://stackoverflow.com/questions/20304287/remove-rewrite-http-header-server-twistedweb

I Would remove the header completely as I don't see any use case of keeping it.

https://github.com/buildbot/buildbot/blob/master/master/buildbot/www/service.py#L137

Would you like to take the work and make a PR?
