### ISSUE TITLE
SSLError on events.buildbot.net - certificate verify failed

### ISSUE THREAD

**Issue by phillxnet** [buildbot/buildbot#5106]
I'm receiving the following requests.exceptions.SSLError:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='events.buildbot.net', port=443): Max retries exceeded with url: /events/phone_home (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

This looks to me to be an SSL expiration issue. Noting here in case this is of use. Apologies if this is in the throws of being sorted.

**Comment by tardyp** [comment]
We hav an issue with our certbot config, and our certs ar all expiring one by one. sorry for incovenience.

**Comment by phillxnet** [comment]
@tardyp Thanks for the confirmation.

No worries or inconvenience on my end, Just wanted to flag this in case it was back-end certs and nothing I'd overlooked. I can turn usage data back on when certs are sorted again.

Well chuffed with Buildbot by the way. Thanks. Will try to contribute where/when I can.

**Comment by p12tic** [comment]
This bug seems to have been fixed.
