### ISSUE TITLE
Home Dir "~/" of workers

### ISSUE THREAD

**Issue by EndrII** [buildbot/buildbot#5111]
Recently, I needed a worker to deploy an assembled project in his home directory. I set the path to 
```
“~/app”
``` 
and expected it to be 
```
“/home/user/app”
```
 but got 
```
“/home/user/worker/build/~/app/”
```

It seems to me that this is not correct behavior.

Versions of master and build workers: 2.5.1

**Comment by tardyp** [comment]
~/app shall be processed using os.path.expanduserpath.

This is not the default in python (as it is not portable e.g in windows), so it is preferable not to use it.

**Comment by EndrII** [comment]
@tardyp  thanks
