### ISSUE TITLE
Feature request: Import /etc/os-release into worker properties on startup

### ISSUE THREAD

**Issue by cmouse** [buildbot/buildbot#5114]
When buildbot worker starts up, it should see if /etc/os-release exists and import the key-values specified there into build properties. These can be used to make OS-agnostic workflows that can leverage from knowing what OS is running in the worker.

**Comment by tardyp** [comment]
Hi @cmouse , we don't really take feature request, as we wouldn't have ressources to work on it anyway.
We do accept patches though. I think this feature makes sense.

We already are parsing all the files present in worker/info
https://docs.buildbot.net/latest/manual/installation/worker.html#creating-a-worker

then it is available in the data/rest API (not as a build property)
https://docs.buildbot.net/latest/developer/rest.html?highlight=workerinfo#worker

**Comment by tardyp** [comment]
Parsing of the info files is done here

https://github.com/buildbot/buildbot/blob/b0875d0d017d25665511ad14f5d64887d4865cd8/worker/buildbot_worker/base.py#L317

You can safely add the parsing of /etc/os-release there

**Comment by cmouse** [comment]
Thanks for the information, I'll see what I can do.
