### ISSUE TITLE
latent: Can't stop build when it's preparing worker

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#5136]
I've seen this on buildbot.buildbot.net and didn't debug it so I'm not sure if it's caused by Kubernetes or by a general bug in latent worker implementation.

**Comment by tardyp** [comment]
Indeed, the way of stopping is to interrupt the current step. This is not supported by all the steps. 
For such steps, we will just wait until the step is finished, and stop before starting the next.
Basically, only ShellCommand and TriggerStep's interrupt are implemented AFAIR, the others are so quick it is not worth to implement.

For preparation, the is a fake step.
https://github.com/tardyp/buildbot/blob/6cf74f2b1876222fa585b79669f969b958ab9929/master/buildbot/process/build.py#L315

We could hack and change the interrupt callback at each intermediate step of the preparation phase, but I think that would be a bit dangerous.

**Comment by benzcash** [comment]
I'm seeing this too on a kubernetes install. How I I reset a `preparing worker` job?

**Comment by iusyk** [comment]
> I'm seeing this too on a kubernetes install. How I I reset a `preparing worker` job?

Looks like no way, I have a test without the steps at all - preparing is going ........

**Comment by p12tic** [comment]
FYI @benzcash @lusyk: I believe this bug has been fixed in #5599.

**Comment by p12tic** [comment]
Please reopen the bug if you still see any issues like this.

**Comment by jpflori** [comment]
Hi all,

I have as slightly related issue with libvirt latent workers.

The connection got lost but the build went on, or rather kept waiting for worker feedback.
I tried to stop the build by clicking the stop button but it does not work and stays in yellow/building.
It only adds new lines with:
`no reason`
or
`[Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
]`

I'm using 2.10.0 from pip which must not include  #5599 
I'll report once this gets released.

If there is any way to kill the build without restarting the master that would be nice to know.

**Comment by p12tic** [comment]
@jpflori: Could you please file a separate bug with more information? A fuller traceback would help a lot. #5599 is included into 2.10.0, so this is a different issue, maybe related to our libvirt implementation of latent workers.
