### ISSUE TITLE
Build fails with process killed by signal 13

### ISSUE THREAD

**Issue by vladbogo** [buildbot/buildbot#5152]
Hi, 

I have found a problem where the build is stopped by signal 13 and no other error occurs. Full log can be found here: https://buildbot.mariadb.org/#/builders/21/builds/2494

The buildbot uses DockerLatentWorkers and there are no errors reported in the logs related to this. Any ideas?

Thanks!

**Comment by tardyp** [comment]
Signal 13 is SIGPIPE. It is usually raised when a process tries to write to a socket which has already been closed. 
Could this be generated by your test setup (a race condition in the tear down phase)

**Comment by vladbogo** [comment]
Thanks for your suggestion. As far as I am aware this shouldn’t be the case, but I will look into it.
