### ISSUE TITLE
treq/ txrequests dependency message on buildbot version 0.9.15.post1

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#5153]
We are on buildbot 0.9.15.post1 and we enabled github hooks.
For enabling GitHubStatusPush, we are getting this message on buildbot reconfig. We have txrequests and treq both packages installed already in our venv. But still seeing this message and reconfig is not happening successfully.
we tried testing on 1.8.0 as well, but still see this message. Is there a way I can disable this message?
```
	txrequests is based on requests and is probably a bit more mature, but it requires threads to run,
	so has more overhead.
	treq is better integrated in twisted and is more and more feature equivalent
	
	txrequests is 2.8x slower than treq due to the use of threads.
	
	http://treq.readthedocs.io/en/latest/#feature-parity-w-requests
	pip install txrequests
	    or
	pip install treq
```

**Comment by vvscloud** [comment]
Resolved.

**Comment by p12tic** [comment]
@vvscloud Was it an issue in Buildbot or in your environment?

**Comment by vvscloud** [comment]
@p12tic , I have to stop my buildbot and start it to resolve this. reconfig does not load these modules.
