### ISSUE TITLE
does buildbot supports build trigger on pull requests in github?

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#5158]
I am trying to trigger a build when a user creates a pull request on github repo. I am getting the payload for this in twistd.log, but scheduler is not triggering the build for pull requests/ events.

Only Push requests (upon merging), I am able to trigger the build. we are using enterprise github.

We are on buildbot 0.9.15.post1

Log we get. It throws a key error on github.py

**Comment by tardyp** [comment]
Why using such an old version of Buildbot?

We do support your use case. You can see our own CI as a proof.

**Comment by vvscloud** [comment]
Yes it is working; Closing this now.
Thanks for your prompt support as always @tardyp ! Buildbot Team rocks! :)

**Comment by UnsafePointer** [comment]
@vvscloud can you elaborate on what was wrong in your case? I am seeing the same behavior.
