### ISSUE TITLE
Github oauth2 now requires use of http-header for authentication

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#5188]
Got email from github when logging with metabuildbot:

> On February 4th, 2020 at 09:12 (UTC) your application (metabuildbot) used an access token (with the User-Agent python-requests/2.21.0) as part of a query parameter to access an endpoint through the GitHub API.
> 
> https://api.github.com/user
> 
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
> 
> Thanks,
> The GitHub Team
> 

Need to fix the code as required.

**Comment by p12tic** [comment]
Fixed in #5189.
