### ISSUE TITLE
Possibility to use gitlab-ci.yml directly in buildbot

### ISSUE THREAD

**Issue by micheelengronne** [buildbot/buildbot#5210]
[Buildbot_travis](https://github.com/buildbot/buildbot_travis) can consume `.travis.yml` file.

Is there a possibility to have the same for `.gitlab-ci.yml` files ?

It would greatly facilitate migrations from gitlab-ci.

Thanks.

**Comment by tardyp** [comment]
gitlab-ci.yml is a bit more complex than travis. There are several features that are present in gitlab-ci, and not in buildbot_travis.yml

- Stages. This can be mapped in buildbot with several trigger steps
- docker images: this can be mapped with dockerworker image renderable configuration
- artifacts: you can map this with a custom step using DownloadFile and some kind of zipping
- caches: basically similar to artifacts.
- yml includes and extends. This can be implemented by the yml parser.

So this is not impossible at all, provided you don't need all the features at once, this can be implemented in a few days, by looking at how buildbot_travis is working.

**Comment by micheelengronne** [comment]
Ok, thanks.
