### ISSUE TITLE
Add option to builder to stop a buildset on failure

### ISSUE THREAD

**Issue by 0x8000-0000** [buildbot/buildbot#5225]
In our configuration we have a mix of different builders. Some are cheap and can run on virtual machines, some are expensive and need real test hardware to run on.

We see many situations where a cheap check has failed (like clang-format or clang-tidy) but the buildset still proceeds to use up a test station for a while, for a revision that will need .. revised.

Is there a way to indicate that if a Builder has failed, just don't start any more builds requests for that buildset and report the failure though the regular mechanism?

**Comment by p12tic** [comment]
I think you could implement this as two trigger steps. One triggers the the cheap checks and the second one launches the expensive ones. The second trigger step can be marked as `haltOnFailure=True` which would prevent the second trigger step from executing.

**Comment by p12tic** [comment]
I think you could implement this as two trigger steps. One triggers the the cheap checks and the second one launches the expensive ones. The second trigger step can be marked as `haltOnFailure=True` which would prevent the second trigger step from executing.

**Comment by 0x8000-0000** [comment]
> I think you could implement this as two trigger steps. One triggers the the cheap checks and the second one launches the expensive ones. The second trigger step can be marked as `haltOnFailure=True` which would prevent the second trigger step from executing.

I was considering that... but felt it was clunky. There is already support for bailing out early from a buildset, for instance when a new revision of a patchset is observed.

**Comment by 0x8000-0000** [comment]
> I think you could implement this as two trigger steps. One triggers the the cheap checks and the second one launches the expensive ones. The second trigger step can be marked as `haltOnFailure=True` which would prevent the second trigger step from executing.

The result callback would only be called with the top-level schedulers and not with the triggered. So it is harder to figure out the failure point.

**Comment by p12tic** [comment]
@0x8000-0000 This has been implemented as FailingBuildsetCanceller service in Buildbot 3.3.0.

**Comment by 0x8000-0000** [comment]
Thank you @p12tic !
