### ISSUE TITLE
"YOUR BROWSER IS OUT OF DATE" error in web interface.

### ISSUE THREAD

**Issue by vext01** [buildbot/buildbot#5237]
Hi,

When visiting a buildbot instance in the [DuckDuckGo Privacy Browser for Android](https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&hl=en_GB) you are greeted with a rather obnoxious error message:

![buildbot](https://user-images.githubusercontent.com/604955/76618437-7ab0fe00-6520-11ea-9e7d-822777a54eeb.png)

Since it's recommending Chrome, I guess it's generated by a dependency from Google somewhere?

Can it be killed?

Thanks

**Comment by rajdeepbharati** [comment]
See https://github.com/buildbot/buildbot/pull/4864.
Can you test it on duckduckgo, then open a pull request to add support if it works?
These are the browsers currently supported: https://github.com/buildbot/buildbot/pull/4864/commits/05788b90045b6778c741add42a55289c71c9239f#diff-1b4f766c346703882a0a3ed7d01e8162R1

**Comment by rajdeepbharati** [comment]
Note that buildbot doesn't really work well on mobile browsers

**Comment by vext01** [comment]
Hi,

Can you tell me what usually doesn't work and I'll give it a go.

Thanks

**Comment by rajdeepbharati** [comment]
Buildbot uses [outdated-browser-rework](https://github.com/mikemaccana/outdated-browser-rework/blob/master/index.js#L5) but it doesn't have an option for duckduckgo android.

On the other hand, duckduckgo is being recognized as chrome on browser-update.org:

![WhatsApp Image 2020-03-19 at 8 00 26 PM](https://user-images.githubusercontent.com/30660439/77147087-849fa780-6ab2-11ea-9fbc-ae935d4ffa0d.jpeg)

So I think it probably uses chromium behind the scenes. We'll need to fix this in upstream.
