### ISSUE TITLE
Question: How to add new build or scheduler to buildbot without restarting

### ISSUE THREAD

**Issue by sri-codefresh** [buildbot/buildbot#5248]
I am new to buildbot, and we have installed buildbot to our regression setup.
Now, the question is how to add new builds or schedulers.

If I restart, I am able to do it.

But, with out restart, I want to add new builds

**Comment by p12tic** [comment]
You could look into https://github.com/buildbot/buildbot_travis, that's what Buildbot test suite is using. See e.g. https://github.com/buildbot/buildbot/blob/master/.bbtravis.yml.

**Comment by sri-codefresh** [comment]
Hi, I am actually using master.cfg file, and I am adding builds to c['builds']. every time I add new builds I am executing "buildbot checkconfig test-master" to check the changes. But to add them to buildbot I have to use "buildbot restart test-master". Till now everything I have coded in python and I nerver came across these .yml files.

Here I don't want to use "buildbot restart test-master", as this command will kill current running builds.

So I am wondering, Is there any other way to add builds to Master build config.

**Comment by marrak** [comment]
I guess you are looking for: buildbot reconfig test-master.

**Comment by sri-codefresh** [comment]
Yes, I tried buildbot reconfig test-master, but it is not able to add my new builds, instead it is complaining saying "duplicate builders, duplicate schedulers".

If I execute buildbot reconfig test-master twice, the complaint lines becoming double.

So, not sure why it is behaving like that

**Comment by sri-codefresh** [comment]
Hint : It seems to be the way we are importing files. If I have entire code in one file,then reconfig is working fine. Is there way I can make import to pass in this case

**Comment by macdems** [comment]
This is my code that reloads the builders configuration, which are in separate files (in the `builders` subdirectory):

```python
from importlib import import_module, reload

for importer, modname, ispkg in pkgutil.iter_modules(['builders'], 'builders.'):
    if modname.startswith('_'): continue
    must_reload = modname in sys.modules
    mod = import_module(modname)
    if must_reload: reload(mod)
    try:
        bconf = mod.config
    except AttributeError:
        continue
    if not isinstance(bconf, (list, tuple)):
        bconf = bconf,
    for bc in bconf:
        C['builders'].append(bc)
```

With this code `buildbot reconfig` does the job. The important part is the `reload(mod)` if `mod` is already in `sys.modules`.

**Comment by sri-codefresh** [comment]
Thanks mac.
I tried with your fix and it is worked for me.
