### ISSUE TITLE
Add owner/repo_name args to BitbucketStatusPush

### ISSUE THREAD

**Issue by dunderpate** [buildbot/buildbot#5271]
Allow users to specify a custom owner and repo_name for a BitbucketStatusPush
instance. This is useful when we want to push status to a bitbucket instance
even though we are pulling from a different repository. In cases like this,
extracting the owner and/or repo_name from the sourcestamp may not be possible.

I've already taken a stab at implementing this. Feel free to let me know if I missed anything 😄

https://github.com/buildbot/buildbot/pull/5270

Thanks everyone!

Dunderpate

**Comment by tardyp** [comment]
as per discussion on #5270 we think this option is not very scalable, and we prefer to let use use git insteadOf in order to implement CI via a mirror.
