### ISSUE TITLE
update buildbot master dockerfile to use Alpine 3.11

### ISSUE THREAD

**Issue by doudou** [buildbot/buildbot#5278]
We've had a lot of segmentation faults in a tar process on the master. It seems that the problem lies in musl, and upgrading to Alpine 3.11 made these errors go away.

At least for our rather stock buildbot master container, we've had no bad experience switching to 3.11.

**Comment by tardyp** [comment]
hello. good finding. can you submit a PR?

**Comment by doudou** [comment]
Done ... #5279
