### ISSUE TITLE
Proposal: Improving flexibility of status reporting

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#5285]
The current design of all BuildBot reporters is centered on reporting the pass/fail status of a build to different data sinks. This unfortunately is not flexible enough if we want to add additional data formats, such as those allowed by the test results PR (#5254).

For example, we may want to support the following use cases:

 - there is a PyLint step. It submits test results to the database after run. A reporter detects when the build has been run as a result of a PR on Github, in which case it would gather the test results on master branch, test results on PR branch and create a comment for each new issue as a comment on the github PR near specific code lines.

 - there is a performance testing step. It submits test results to the database after run. A reporter that detects when the build has been run as a result of a PR on Github, in which case it would gather test results on master branch, test results on PR branch, compare them and create a github comment on the PR listing all significant differences.

 - there is a performance testing step. It submits test results to the database after run. A reporter that detects when the build has been run on a master branch on Github in which case it would gather test results, compare them to last 10 test results on the master branch, create a nice HTML report and send it via email to some developer list.

As can be seen, the data processing requirements for the test results are completely different compared to the current status reporters, where pretty much the only information to be reported is the status of the build and information related to it.

However, it's very likely that it will be possible to send a certain type of report via multiple medium types. Thus it makes sense to separate the concepts of content generation and sending of the report via some medium. The content is not unrelated to the medium as the capabilities of the medium vary wildly. For example, there's a night and day difference between formatting possibilities allowed by a Github comment and what is supported by a HTML page that is uploaded somewhere.

I propose that we extract the content part out of the reporters into a separate concept, called `ReportGenerator` (better suggestions are welcome). This would be responsible for generating a report of a particular format. The report would be communicated to the reporter as a `dict` that can potentially be converted to json and back without information loss. The structure of that dictionary would define what data would be available to the reporters.

The reporters would be responsible for merging the reports and converting the result to a format that is appropriate for presentation.

What report generators are enabled on a reporter would be controlled by a new parameter. The existing way to control a reporter would be deprecated, but preserved for backwards compatibility until BuildBot 3.0.

I've created a test PR at #5286 to prove feasibility of this proposal. I looked into the `NotifierBase` class that powers several of our status reporters. Turns out that there are actually three different report generators buried within it: one to generate reports on build results, one to generate reports on buildset results and one to generate reports on missing workers. Splitting the reporter generators out of `NotifierBase` made the responsibilities much more clearer, so I think it's a good demonstration that the proposal has good potential to improve the design of Buildbot.

**Comment by tardyp** [comment]
About your use cases. I think it make sense at some point for the 3 of your use cases to make the build fail if there is new pylint errors, or if there is meaning full performance regression.

This is another argument why we should make this analysis in a step rather than in the reporter.

**Comment by p12tic** [comment]
I was thinking about that more the past week and I agree that eventually we should have a special step to generate various reports out of the build and pass/fail the build.

**Comment by thinwu** [comment]
Hi , 
I want to know if the feature of sending customized log through email,  on this page, is still available, https://docs.buildbot.net/0.8.3/MailNotifier.html
`_The last 80 lines of the log are provided as well as the changes_`

from the latest doc I can't find an example of this use.
http://docs.buildbot.net/latest/manual/configuration/reporters.html?highlight=mailnotifier#mailnotifier

**Comment by p12tic** [comment]
@thinwu I think you can still do this via `messageFormatter` argument to the notifier.

**Comment by p12tic** [comment]
This has been implemented in Buildbot 2.9 and 2.10.
