### ISSUE TITLE
Views should show build results as "generated warnings" instead of "success"

### ISSUE THREAD

**Issue by rcgordon** [buildbot/buildbot#5305]
Currently the grid view (etc) show you the results of a given build with a badge, green for success and red for failure, but it would be useful if they changed orange for "successful but warnings were generated," as the waterfall did in 0.8.9.

The master has this information, as it can be shown in the waterfall when mousing over a build, but it appears to be data about specific steps (it shows a proper warning badge in the build summary view for the appropriate steps) and not recorded with the final build result.

It seems like doing what the waterfall does on mouseover is the wrong approach for what we'd need here (build.loadSteps() and iterate, because it needs to render for each step and appears to grab that data on demand, whereas we would want this information once upfront).

It feels like maybe there should be a flag _somewhere_ that could be set to say "this build saw a warning" instead of iterating all the steps in the grid UI, but I don't know if that's a protocol change or whatnot. Theoretically we just need that one state to change and leave the existing UI code alone.

I'm out of my league in tracking this down further, though.

**Comment by tardyp** [comment]
I think what you need is the warnOnWarnings flag on your step.

http://docs.buildbot.net/latest/developer/cls-buildsteps.html?highlight=warnonwarnings#buildbot.process.buildstep.BuildStep.warnOnWarnings

**Comment by rcgordon** [comment]
Oh wow, this totally solves the problem. Sorry to waste your time on this!
