### ISSUE TITLE
Interpolate is no longer hashable in Buildbot 2.8.0

### ISSUE THREAD

**Issue by kfriedberger** [buildbot/buildbot#5312]
We have a Buildbot instance where we have several pairs of build jobs.
The first job of a pair triggers the second job if some requirements are satisfied.
This is implemented in a generic way, i.e., the first job applies `steps.Trigger(..., schedulerNames = [util.Interpolate("%(prop:buildername)s-secondJob")],...)`.
With the newest Buildbot 2.8.0, this causes an error `builtins.TypeError: unhashable type: 'Interpolate'` from the following line:
https://github.com/buildbot/buildbot/blob/144eb7e82dc261e6506f1f68493446bcb24d77a0/master/buildbot/steps/trigger.py#L68

I assume that with the latest changes to `Interpolate` some things might have changed, e.g., comparable `Interpolate` and such stuff.
Is it in general supported to use `Interpolate` for `schedulerNames` in `Trigger`? It worked until now.
Can you or can we fix that?

**Comment by tardyp** [comment]
Thanks for the quick report!

Indeed, this change of Interpolate has lead to the finding of a number of bugs, where the contructors of steps, where not taking in account the possibility that values are computed in dynamic. 

This actual check at config time does make much sense if the schedulerNames are interpolated.
I'll send a patch this afternoon to fix this one.
A shame it wasn't catched by the unit tests.

I imagine we will have some other reports soon, we will wait a bit, and try to release a 0.8.1 with as much of those issues fixed

sorry for inconvenience :bow:

**Comment by kfriedberger** [comment]
Thanks for the fix. The new release `2.8.1` works for us.
