### ISSUE TITLE
First build determination after a lot of change requests

### ISSUE THREAD

**Issue by Lind971** [buildbot/buildbot#5315]
Hello all,

I am trying to make a custom change poller implementing the class `PollingChangeSource`. When I submit a lot of changes at once using the ` self.master.data.updates.addChange`, a build is started. But I can not understand how it is choosen!

I have even added a function in the parameter `nextBuild` of the `BuilderConfig`. It is working well for every builds after the first one! Could you help me understand more?

**Comment by p12tic** [comment]
Have you looked into `treeStableTimer` parameter of the schedulers?

**Comment by Lind971** [comment]
Yes, actually I set it to None. I wanted to have a separate build started immediately for each Change.

**Comment by tardyp** [comment]
I think in you case, you need to configure collapseRequests https://docs.buildbot.net/latest/manual/configuration/builders.html#collapsing-build-requests
which is a mechanism which avoid to have a long queue for branch based CI.
If the build time is longer than the change rate, then the collapser will then gather changes in a single build.

**Comment by Lind971** [comment]
Actually, I already looked into it. But gather changes into a single build does not match my needs. I find it easier to detect the origin of failed builds when an unique build for each change is triggered.

For example, when 4 changes are detected at once, I don't know which one will be the first to trigger a build. I can control the order of the 3 last builds with the parameter `nextBuild` of the `BuilderConfig`. But the first one does not seem to be taken into account in this process.

**Comment by tardyp** [comment]
Sorry, I actually suggested to disable the request collapser. It is enabled by default.

**Comment by Lind971** [comment]
Yes, I should have say it, but I did that already :-)

**Comment by p12tic** [comment]
Okay, seems that I understood the problem. There are multiple changes incoming and you want to start builds in the order they come.

I think this is currently not supported.

**Comment by Lind971** [comment]
Yes, that's it. Too bad, but thank for the confirmation. I will try to look more into it.

**Comment by tardyp** [comment]
@p12tic I am not sure what in the engine will drop the order of the changes. Do you have something in mind?
