### ISSUE TITLE
Windows service fails after upgrade from 2.7.0 to 2.8.1

### ISSUE THREAD

**Issue by BeagleJoe** [buildbot/buildbot#5344]
Hello,
Windows 7
Buildbot 2.8.1
Twisted 20.3.0
pywin32 227

I upgraded my Buildbot master from version 2.7.0 to version 2.8.1.
Buildbot is configured to run as a Windows service. After the upgrade, the service starts then quickly stops. 
The twistd.log does not get written to.
The Windows Event log(Application) shows:
```
The instance's SvcRun() method failed 
<Error getting traceback - traceback.print_exception() failed 
%2: %3
```
The Windows Event log(System) shows:
```
The BuildBot service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

buildbot/master/buildbot/scripts/windows_service.py (line 233)
`cmd = '{} --spawn {} start --nodaemon {}'.format(self.runner_prefix, hstop, bbdir)`
needs to be changed to:
`cmd = '{} --spawn {} start --nodaemon {}'.format(self.runner_prefix, int(hstop), bbdir)`

Notice the call to int(hstop)
The first version produces something like:
`python.exe --spawn <PyHANDLE:456> start --nodaemon c:/master`
instead of:
`python.exe" --spawn 456 start --nodaemon c:/master`
Thanks,
Joe

**Comment by p12tic** [comment]
Most likely caused by 6bafe09d93fcb40389ff4a1d736347032ad98d96. Thanks a lot!
