### ISSUE TITLE
`owner` vs `owners`

### ISSUE THREAD

**Issue by buck-E** [buildbot/buildbot#5384]
Trying to set the "owners" for a scheduler to control who gets e-mail sent to them when `sendToInterestedUsers = True`.  There are docs that talk about "owners":

https://docs.buildbot.net/current/manual/configuration/reporters.html?highlight=owners

```
You can add additional, statically-configured, recipients with the extraRecipients argument. You can also add interested users by setting the owners build property to a list of users in the scheduler constructor (Configuring Schedulers).

Each MailNotifier sends mail to a single set of recipient
```

But if you follow that link to  https://docs.buildbot.net/current/manual/configuration/schedulers.html#configuring-schedulers, the information is to set "owner" not "owners" and there is no other information.

Please explain the difference, and what the correct way is to set "owners".

**Comment by tardyp** [comment]
owners is a property computed at the start of a build, which concatenate the 'owner' or 'author' property of the buildrequests and changes.
See the actual code: https://github.com/buildbot/buildbot/blob/5c86cb3bf2c716800f4d6f738c5aa9c0e6583dea/master/buildbot/process/build.py#L477

**Comment by buck-E** [comment]
Okay that is what I was already working on but it does not work.  I get this error and the buildbot-worker does not complete:

https://github.com/buildbot/buildbot/issues/5380

**Comment by buck-E** [comment]
@tardyp

The goal is to set this to send an e-mail only to the most recent committer.  Not sure if that information helps, although technically this issue is resolved and the next question continues in https://github.com/buildbot/buildbot/issues/5380
