### ISSUE TITLE
Remove Google+ link?

### ISSUE THREAD

**Issue by vext01** [buildbot/buildbot#5390]
On the buildbot website, under "getting involved" there's a dead link to Google+

![image](https://user-images.githubusercontent.com/604955/86347504-e80ea900-bc4d-11ea-9023-ea1827ddee86.png)

**Comment by p12tic** [comment]
Fixed in https://github.com/buildbot/buildbot-website/commit/a353180aa3d9f46b4ed358ae34aca4ae3615c467.
