### ISSUE TITLE
How to pass custom headers to reporters.HttpStatusPush?

### ISSUE THREAD

**Issue by stillru** [buildbot/buildbot#5398]
Now i done job with editing buildbot src (/usr/lib/python3.6/site-packages/buildbot/util/httpclientservice.py) myself. It's integration with Rocket.Chat.
Now i add some headers to reporter code:

```
if isinstance(json, (dict, list)):
            jsonStr = jsonmodule.dumps(json, default=toJson)
            kwargs['headers']['Content-Type'] = 'application/json'
        +   kwargs['headers']['X-Auth-Token'] = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        +   kwargs['headers']['X-User-Id'] = 'XXXXXXXXXXXXX'
```

How to do this without this dirty hack?

**Comment by p12tic** [comment]
This has been fixed in #5721.
