### ISSUE TITLE
Http Request Based secrets

### ISSUE THREAD

**Issue by xeniorac** [buildbot/buildbot#5403]
Hi I wanted to see how much value we will have http based secrets
I am working on a project and I want to make a rest api call and get the value and put it in a secret... 
So wanted to add that as a provider.
If it does make sense, I can take the issue

**Comment by xeniorac** [comment]
@anish

**Comment by tardyp** [comment]
Hello,
There is already a vault backend for secrets.
https://docs.buildbot.net/latest/manual/secretsmanagement.html#secretinvault

**Comment by p12tic** [comment]
Closing issue as inactive. If Pierre's response did not resolve this issue, please reopen.
