### ISSUE TITLE
Show GitHub Avatar in Buildbot

### ISSUE THREAD

**Issue by ryandesign** [buildbot/buildbot#5416]
When I log into my Buildbot with GitHub, I see an avatar in the upper right of the Buildbot screen and when I click it I see my name and email address from my GitHub account. But the avatar image is unfamiliar to me. Presumably it is from Gravatar, which I understand is your default avatar provider. How do I change this to show my GitHub user icon?

I found [documentation](https://docs.buildbot.net/latest/manual/configuration/www.html?highlight=avatar_methods#web-server) which says

> `avatar_methods`
>
> List of methods that can be used to get avatar pictures to use for the web server. By default, buildbot uses Gravatar to get images associated with each users

but it does not say what other values of that option are possible.

I see that something called AvatarGitHub was submitted over 4 years ago in #1894, and @tardyp provided an improved implementation of it in a code review, but the PR was closed without being merged. I don't find any occurrences of "AvatarGitHub" in the Buildbot 2.8.2 source code. Did this feature simply never get included? Or did it get included a different way?

**Comment by tardyp** [comment]
hi #1894 was awesome, but unfortunately nobody stepped up to finish it.
Anybody interrested can pick up stalled request and rebase them to continue work, no problem..

**Comment by ryandesign** [comment]
For anyone else wanting to look into this, I updated your code as follows. (This diff is against buildbot-2.8.2.tar.gz from pypi.)
```
--- buildbot/www/avatar.py.orig	2020-06-14 09:25:22.000000000 -0500
+++ buildbot/www/avatar.py	2020-07-23 05:46:53.000000000 -0500
@@ -14,6 +14,7 @@
 # Copyright Buildbot Team Members
 
 import hashlib
+import txrequests
 from urllib.parse import urlencode
 from urllib.parse import urljoin
 
@@ -31,6 +32,37 @@
         raise NotImplementedError()
 
 
+class AvatarGitHub(AvatarBase):
+    name = "github"
+    cache = {}
+    BASE_URL = 'https://api.github.com'  # can be overridden for GHE
+    SEARCH_PATH = '/search/users'
+
+    def getSession(self):
+        return txrequests.Session()
+
+    @defer.inlineCallbacks
+    def getUserAvatar(self, email, size, defaultAvatarUrl):
+        if not email in self.cache:
+            return None
+        url = self.cache.get(email)
+        if not url:
+            search_url = self.BASE_URL + self.SEARCH_PATH
+            with self.getSession() as session:
+                res = yield session.get(search_url,
+                                        params={'q': email + b' in:email', 'type': 'user', 'per_page': 1})
+                if res.status_code != 200:
+                    return None
+                json = res.json()
+                if not json['total_count']:
+                    self.cache[email] = None
+                    return None
+                url = str(json['items'][0]['avatar_url'])
+                self.cache[email] = url
+        url += '&' + urlencode({'s': str(size)})
+        raise resource.Redirect(url)
+
+
 class AvatarGravatar(AvatarBase):
     name = "gravatar"
     # gravatar does not want intranet URL, which is most of where the bots are
--- setup.py.orig	2020-06-14 09:25:23.000000000 -0500
+++ setup.py	2020-07-22 18:28:57.000000000 -0500
@@ -397,7 +397,7 @@
             ('buildbot.util.kubeclientservice', [
                 'KubeHardcodedConfig', 'KubeCtlProxyConfigLoader', 'KubeInClusterConfigLoader'
             ]),
-            ('buildbot.www.avatar', ['AvatarGravatar']),
+            ('buildbot.www.avatar', ['AvatarGravatar', 'AvatarGitHub']),
             ('buildbot.www.auth', [
                 'UserPasswordAuth', 'HTPasswdAuth', 'RemoteUserAuth', 'CustomAuth']),
             ('buildbot.www.ldapuserinfo', ['LdapUserInfo']),
```

The above works... as long as the email address being looked up is the one the user is displaying on their GitHub profile. If they're displaying a different address, or no address at all, the lookup fails.

What's getting in the way here is Buildbot's notion that an email address can be turned into an avatar, which doesn't generally hold for GitHub. You can look up an avatar from a GitHub username, but you can't necessarily look up a username from an email address. But when you receive a change_hook notification from GitHub, it tells you the user's name, email address and username. I'll bet the GitHub authentication system will also tell you the authenticated user's username. So in the case of GitHub login and/or repositories, maybe Buildbot should store the GitHub username and use that as the basis for avatar lookups. Maybe other services like GitLab or BitBucket work in similar ways.

P.S.: I'm often seeing this error in the log when an avatar is looked up:
```
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```
Maybe it will be easy for someone who knows Python to understand how to fix this.

**Comment by tardyp** [comment]
you should start a PR so that we can discuss the code more easily.
Like for the first PR, the problem here is that requests is a synchronous API, so you should take the method I suggested in the previous PR.

As per email vs username I agree this is unfortunate.
For login avatar, this could be worked around [here](https://github.com/buildbot/buildbot/blob/f0b3f1ef84bb6559f800d4f0001ef2cc35bd002f/www/base/src/app/common/directives/loginbar/loginbar.tpl.jade#L18) I guess the user id shall be available, and we could have a userid query param for the avatar api.

But most of the avatars are for owner of builds in the CI, and there I think we only store the email address to identify users, and never a github userid, as this wouldn't be very generic.

The problem is that avatar is used

**Comment by ryandesign** [comment]
> you should start a PR so that we can discuss the code more easily.

Maybe if I have any further changes to propose.

> Like for the first PR, the problem here is that requests is a synchronous API, so you should take the method I suggested in the previous PR.

I am using your method. My code is based on yours.

> As per email vs username I agree this is unfortunate.
> For login avatar, this could be worked around [here](https://github.com/buildbot/buildbot/blob/f0b3f1ef84bb6559f800d4f0001ef2cc35bd002f/www/base/src/app/common/directives/loginbar/loginbar.tpl.jade#L18) I guess the user id shall be available, and we could have a userid query param for the avatar api.

I noticed on the Buildbot About page that my logged in username is listed. So I agree it's available.

> But most of the avatars are for owner of builds in the CI, and there I think we only store the email address to identify users, and never a github userid, as this wouldn't be very generic.

I'm not sure what you mean by "owner of builds in the CI".

I agree that storing a github user ID is not very generic, and yet given GitHub's popularity it seems reasonable to make some special accommodations for it. And I suspect some other services like GitLab or BitBucket might copy how GitHub does things.

**Comment by mojca** [comment]
> > But most of the avatars are for owner of builds in the CI, and there I think we only store the email address to identify users, and never a github userid, as this wouldn't be very generic.
> 
> I'm not sure what you mean by "owner of builds in the CI".

I suspect he meant the avatars shown next to the "responsible user(s)". Those might be either developers committing the code (maybe also developers merging the code, even though that's probably not yet shown) or those who "force build".

Unrelated, but I still didn't figure it out how to potentially show just the name and the avatar of the user, while hiding the email. I find public listing of all emails (which is turned on by default in any case) quite a bit problematic.

**Comment by tardyp** [comment]
The avatar is indeed use in the changes pages, and one some other pages (perhaps not enough)

![image](https://user-images.githubusercontent.com/109859/88325357-48f94080-cd25-11ea-9532-3271d6754719.png)

You can see in this image that in github PR changes, there is no email, but only github id.
So it would make sense to change the avatar api to accept email or userid (by looking for an @ in the argument)

**Comment by rajdeepbharati** [comment]
@ryandesign I'm not sure why but the patch you sent didn't work in my case, although I have my email listed on github.

Here's a hacky patch that worked (this checks for username parameter). (this is definitely not a good way of doing it, we should create another class, as you mentioned):

```diff
diff --git a/master/buildbot/www/avatar.py b/master/buildbot/www/avatar.py
index 6550eedec..5b94a2733 100644
--- a/master/buildbot/www/avatar.py
+++ b/master/buildbot/www/avatar.py
@@ -37,18 +37,24 @@ class AvatarGravatar(AvatarBase):
     # just use same default as github (retro)
     default = "retro"
 
-    def getUserAvatar(self, email, size, defaultAvatarUrl):
-        # construct the url
-        emailBytes = unicode2bytes(email.lower())
-        emailHash = hashlib.md5(emailBytes)
-        gravatar_url = "//www.gravatar.com/avatar/"
-        gravatar_url += emailHash.hexdigest() + "?"
-        if self.default != "url":
-            defaultAvatarUrl = self.default
-        url = {'d': defaultAvatarUrl, 's': str(size)}
-        sorted_url = sorted(url.items(), key=lambda x: x[0])
-        gravatar_url += urlencode(sorted_url)
-        raise resource.Redirect(gravatar_url)
+    def getUserAvatar(self, email, username, size, defaultAvatarUrl):
+        if username is not None:
+            # construct the github avatar url
+            if username != "":
+                github_avatar_url = "https://github.com/"+ username.decode("utf-8") + ".png"
+                raise resource.Redirect(github_avatar_url)
+        else:
+            # construct the gravatar url
+            emailBytes = unicode2bytes(email.lower())
+            emailHash = hashlib.md5(emailBytes)
+            gravatar_url = "//www.gravatar.com/avatar/"
+            gravatar_url += emailHash.hexdigest() + "?"
+            if self.default != "url":
+                defaultAvatarUrl = self.default
+            url = {'d': defaultAvatarUrl, 's': str(size)}
+            sorted_url = sorted(url.items(), key=lambda x: x[0])
+            gravatar_url += urlencode(sorted_url)
+            raise resource.Redirect(gravatar_url)
 
 
 class AvatarResource(resource.Resource):
@@ -70,14 +76,17 @@ class AvatarResource(resource.Resource):
 
     @defer.inlineCallbacks
     def renderAvatar(self, request):
+        username = request.args.get(b"username")
         email = request.args.get(b"email", [b""])[0]
+        if username is not None:
+            username = username[0]
         size = request.args.get(b"size", 32)
         r = None
         if self.cache.get(email):
             r = self.cache[email]
         for method in self.avatarMethods:
             try:
-                res = yield method.getUserAvatar(email, size, self.defaultAvatarFullUrl)
+                res = yield method.getUserAvatar(email, username, size, self.defaultAvatarFullUrl)
             except resource.Redirect:
                 if r is not None:
                     self.cache[email] = r
diff --git a/www/base/src/app/common/directives/loginbar/loginbar.tpl.jade b/www/base/src/app/common/directives/loginbar/loginbar.tpl.jade
index 2c6ce8dc5..696d68874 100644
--- a/www/base/src/app/common/directives/loginbar/loginbar.tpl.jade
+++ b/www/base/src/app/common/directives/loginbar/loginbar.tpl.jade
@@ -15,7 +15,9 @@ ul.nav.navbar-nav.navbar-right(ng-show="config.auth.name != 'NoAuth'")
 
     li.dropdown(uib-dropdown, ng-hide="anonymous")
         a.dropdown-toggle(uib-dropdown-toggle)
-            .avatar(ng-if="email")
+            .avatar(ng-if="username")
+                img(ng-src="avatar?username={{username}}")
+            .avatar(ng-if="!username")
                 img(ng-src="avatar?email={{email}}")
             span(ng-if="!email")
                 | {{full_name || username}}
```
