### ISSUE TITLE
Why git step uses `git checkout -B <branch>`? Can it be made configurable? 

### ISSUE THREAD

**Issue by Beatris** [buildbot/buildbot#5417]
Hi,

We use git step with mode='full' and method='fresh'.
When the user misspells the branch name when starting a build, we expect the step to fail but instead it creates new local branch by using `git checkout -B <branch>`.

Can the `-B` option be configurable?

Also, out of curiosity, why someone would need new local branch?

Thanks in advance!

**Comment by Beatris** [comment]
Also, after some initial testing, I've discovered that if a new branch is created on the remote and passed as an argument to the builder, using `git checkout -B` creates new local branch but it does NOT track the remote branch.. as no `--track <remote>/<branch>` is passed.

So, basically no way to run a build in a new branch (revision=HEAD) without cloning the repo every time?

**Comment by tardyp** [comment]
Hello,
You might be looking at a corner case of the code. It is defined here:
https://github.com/buildbot/buildbot/blob/f0b3f1ef84bb6559f800d4f0001ef2cc35bd002f/master/buildbot/steps/source/git.py#L345

and shall be relatively easy to follow.

In order for us to better understand your usecase and the associated code path, this would be nice to have the full log of you git step (you can remove the private stuff of course)

in case of not existing branch, the code should not do the checkout -B as it is protected, and shall run only if previous reset succeed.

**Comment by Beatris** [comment]
Okay, to summarize:

1. New branch, let's call it `new-branch`, is created on the remote.
2. A build is triggered with branch=`new-branch` and revision=HEAD.
3. Git step with mode='full' and method='fresh' is used.

**Expected result:** the build is run with the latest revision of the branch, let's say **9ad294147e8**.
**Actual result:** new local branch is created from the currently checked-out branch. If the previous build has used branch master for example, new local branch `new-branch` is created from master. It's not using the remote branch.

Git step log:

(the last revision from the checked-out master branch is **c754e8f69a35235717caa0e2ac2cef4ad6134b7d** whereas from `new-branch` is **9ad294147e8** but as you can see it's not checked-out)

```
git --version
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'--version']
 environment: <ENV>
git version 2.14.1
program finished with exit code 0
elapsedTime=0.009847
stat: No such file or directory: <worker_dir>/.buildbot-patched program finished with exit code 2
program finished with exit code 0
git clean -f -f -d -x
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'clean', b'-f', b'-f', b'-d', b'-x']
 environment: <ENV>
Removing <unstaged files>
program finished with exit code 0
elapsedTime=0.216438
git cat-file -e HEAD
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'cat-file', b'-e', b'HEAD']
 environment: <ENV>
program finished with exit code 0
elapsedTime=0.013814
git reset --hard HEAD --
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'reset', b'--hard', b'HEAD', b'--']
 environment: <ENV>
HEAD is now at c754e8f69a <commit message>
program finished with exit code 0
elapsedTime=0.292628
git checkout -B new-branch
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'checkout', b'-B', b'AUT-5165']
 environment: <ENV>
Switched to and reset branch 'AUT-5165'
program finished with exit code 0
elapsedTime=0.237674
git rev-parse HEAD
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'rev-parse', b'HEAD']
 environment: <ENV>
c754e8f69a35235717caa0e2ac2cef4ad6134b7d
program finished with exit code 0
elapsedTime=0.013587
```
And of course, in the properties:

```
got_revision: {"<our_repo>": "c754e8f69a35235717caa0e2ac2cef4ad6134b7d"}
```

**Comment by terencehonles** [comment]
@Beatris not sure if you figured this out by now, but what seems to be missing for me is a `git fetch` step, and I'm not 100% what you're trying to accomplish. During the phase you shared:

```
git cat-file -e HEAD
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'cat-file', b'-e', b'HEAD']
 environment: <ENV>
program finished with exit code 0
elapsedTime=0.013814

git reset --hard HEAD --
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'reset', b'--hard', b'HEAD', b'--']
 environment: <ENV>
HEAD is now at c754e8f69a <commit message>
program finished with exit code 0
elapsedTime=0.292628

git checkout -B new-branch
 in dir <worker_dir> (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'checkout', b'-B', b'new-branch']
 environment: <ENV>
Switched to and reset branch 'new-branch'
program finished with exit code 0
elapsedTime=0.237674
```

I **normally** have (running a force build with a GitHub source and providing *nothing* (the branch will come from the builder config)):

```
git -c 'core.sshCommand=ssh -i "/var/lib/buildbot/.lint.build.buildbot/ssh-key"' fetch -t git@github.com:org/repo.git HEAD --progress
 in dir /var/lib/buildbot/lint/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'-c', b'core.sshCommand=ssh -i "/var/lib/buildbot/.lint.build.buildbot/ssh-key"', b'fetch', b'-t', b'git@github.com:org/repo.git', b'HEAD', b'--progress']
 environment: <ENV>
From github.com:org/repo
 * branch                HEAD       -> FETCH_HEAD
program finished with exit code 0
elapsedTime=0.764534

git reset --hard FETCH_HEAD --
 in dir /var/lib/buildbot/lint/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'reset', b'--hard', b'FETCH_HEAD', b'--']
 environment: <ENV>
HEAD is now at 71058274b Merge comment
program finished with exit code 0
elapsedTime=0.022680
```

If instead I specify `HEAD` as the revision I see what you see (`master` is the default branch name because of the builder config as specified above):

```
git reset --hard HEAD --
 in dir /var/lib/buildbot/lint/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'reset', b'--hard', b'HEAD', b'--']
 environment: <ENV>
HEAD is now at 48f5a3362 Merge comment
program finished with exit code 0
elapsedTime=0.154641

git checkout -B master
 in dir /var/lib/buildbot/lint/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'git', b'checkout', b'-B', b'master']
 environment: <ENV>
Switched to and reset branch 'master'
program finished with exit code 0
elapsedTime=0.015276
```

It's very likely that you just want to remove `HEAD` from the revision field, as by *default* buildbot should be resetting the branch as  you expect. By specifying both you are stating what commit you want and since HEAD is a valid refname it doesn't complain but it treats it literally as the HEAD where the git repo is operating on is, which means whatever was last built on the machine :sweat_smile: 

---------------

@tardyp looking at the code in question https://github.com/buildbot/buildbot/blob/4856238ba9eb6294d0e4226f05dd636028a12dec/master/buildbot/steps/source/git.py#L307-L312

It may make sense to either warn or error if `cat-file` is checking `FETCH_HEAD` or `HEAD` since it's very likely not what you want. I was looking at the source because I was surprised there was no fetch and how it could "assume" the ref exists in the repo. Well looking at the code there's no assumption, it's just checking if it can, and it can, but causes unexpected behavior!

**Comment by Beatris** [comment]
Hi,

Oooh, yeah.. of course! Thanks for the research! It appears that is the issue indeed.
The thing is HEAD is default in the revision field of our builder. I just didn't think of the early check if the revision already exists.. because when cloning, it will first clone with `git clone --branch <my_branch>` and then checkout the revision and HEAD will be the correct one..

Thanks again and sorry to bother you!
