### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: b'./setup_build_environment.sh'

### ISSUE THREAD

**Issue by blake1029384756** [buildbot/buildbot#5422]
The first step in my job is to pull a GitHub repo. This repo has a few scripts that need to be ran but whenever I call them in subsequent steps I get the permission denied error. 

<img width="892" alt="Screen Shot 2020-07-27 at 2 27 03 PM" src="https://user-images.githubusercontent.com/6282185/88583023-48a6c100-d015-11ea-92f8-27102b1ce903.png">

**Comment by tardyp** [comment]
Hi,
You probably want to specify that you want to use bash
[b'/bin/bash', b'./setup_build_environment.sh']

**Comment by siko1056** [comment]
@tardyp I am facing a similar error, and indeed using bash solves the permission error, but why does it occur and what permissions are denied?  Is there a global switch to make bash the default interpreter for Buildbot Workers?  Thank you for your help.

**Comment by tardyp** [comment]
When using [], buildbot just tries to [execve](https://docs.python.org/2/library/os.html#os.execve) the content of the list.
The first argument is supposed to be executable. If its not, you get a permission error.

http://docs.buildbot.net/latest/manual/configuration/steps/shell_command.html#using-shellcommands
