### ISSUE TITLE
Configured not to show information when I'm not logged in, but it still does

### ISSUE THREAD

**Issue by ryandesign** [buildbot/buildbot#5433]
I've configured buildbot to show no information unless I'm logged in with my GitHub account:

```
    authz=util.Authz(
        allowRules=[
            util.AnyEndpointMatcher(role='admin'),
            util.AnyControlEndpointMatcher(role='admin')],
        roleMatchers=[
            util.RolesFromUsername(roles=['admin'], usernames=users)]),
```

But I've now logged out while builds are in progress, and to my surprise information about the builds that are in progress is being shown on the waterfall, and in builds>builders and builds>pending buildrequests. How is this possible?

**Comment by tardyp** [comment]
The message queue through websocket is not enforcing authorizations. 
So you actually get the live events, and buildbot UI is able to reconstruct some view from that.

**Comment by ryandesign** [comment]
Is there a plan for fixing that? Sounds like a security flaw.

**Comment by tardyp** [comment]
this is by design. It is indeed not properly documented.

**Comment by ryandesign** [comment]
You wrote in #5437:

> The only resources that are only available for read in REST API are the log data (a.k.a `logchunks`).

So just to make sure: Does this mean that Buildbot authz is sufficient to prevent unauthorized users from reading build logs?
