### ISSUE TITLE
Github integration not successful for user in a team

### ISSUE THREAD

**Issue by xeniorac** [buildbot/buildbot#5451]
```
from buildbot.plugins import util
c['www'] = {
    # ...
    'auth': util.GitHubAuth("clientid", "clientsecret", apiVersion=4,
                            getTeamsMembership=True),
    'authz': util.Authz(
        allowRules=[
          util.AnyControlEndpointMatcher(role="checkers"),
        ],
        roleMatchers=[
          util.RolesFromGroups(groupPrefix='buildbotvb/')
        ]
      )
}
```

I have the above added to my buildbot to allow users from buildbotvb org belonging to the team checkers... 
As per the documentation...

Any members inside the team checkers under buildbotvb must be able to run rebuilds and stuffs... 
I can login successfully via Github but when I click rebuild it get's me an error saying 

*Cannot rebuild: you need to have role 'checker'*

Can I know what am I missing here?

This works great for basic user:pass auth though

**Comment by p12tic** [comment]
@xeniorac: Thanks for the bug report.

Could you set `debug=True` for `GitHubAuth` and check twisted.log? We should see `GitHubAuth GraphQL Response: ` lines there. It would be great if these could be sanitized and posted here as it would contain all the information necessary.

By the way, reading the code I found this comment:

```
# Organizations can have OAuth App access restrictions enabled,
# disallowing team data access to third-parties.
```

Could it be the same for `buildbotvb` team?

**Comment by xeniorac** [comment]
Actually, this worked... 
OAuth Github app restriction was enabled...
