### ISSUE TITLE
Timeline for deleting support for old style steps

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#5459]
Old style steps have been deprecated since BuildBot 0.9.0 which has been released on October 2016. Supporting both old style and new style steps alongside is a significant maintenance burden as its hard to change Buildbot internals that are affected by the old style emulation code. In particular, I have been looking into logs handling which is much more complex now than it needs to be.

I think that support for old style steps needs to be removed. Almost 4 years have passed since this was deprecated and so much time should have been enough for the users to move to new style steps and submit bugs for found issues.

It seems that the most significant hurdle for the completion of the migration was that the Buildbot itself uses old style steps a lot and no one bothered to actually do the time consuming work of migrating these. This no longer applies as I already have completed most of the work migrating steps off old style ShellCommand and related base step classes. This work will be submitted over the next few days.

I propose the following migration plan:

We need at least one release that contains the following features:

 - All old style steps within BuildBot have been migrated to new style steps

 - The old style step emulation code emits deprecation warnings

 - Support for any other related APIs (such as the old Status API) emit deprecation warnings

 - The internal steps that have been converted to new style must work. This is important, because a lot of steps provided by Buildbot seem to lack sufficient unit tests.

This way we will have at least one release that could be used as a solid base for migration. Users will be able to split their migration work into two parts - migrating the steps that depended on private APIs exposed by the steps provided by Buildbot itself.

Depending on what other work we want to include into Buildbot I think we would be around 2 minor releases away from a release that match the above criteria. That would mean Buildbot v2.10.0 would be the last 2.x release.

I think it makes sense to backport any bugs arising from my old style -> new style conversion work to 2.x. Also, I think we should release as many v2.10.y releases as needed to mark all API removed in v3.0.0 as deprecated.

**Comment by p12tic** [comment]
Related issues #5365, #5364

**Comment by p12tic** [comment]
@tardyp 

I was thinking about what to do with the steps that are commonly derived from, such as WarningCountingShellCommand, Test and others. The current master will break user code once we release it as v2.9.0.

What do you think if I renamed all such steps to <StepName>NewStyle and added back old implementations as <StepName>?

We can then ask users to upgrade to <StepName>NewStyle in v2.9.0 and add deprecation warnings to <StepName>.

Once v3.0.0 is released, we can rename <StepName>NewStyle back to <StepName> and make <StepName>NewStyle a deprecated alias. This would be removed on v3.1.

This way users would not be forced to fix all their steps immediately after upgrading to v2.9.0, but to migrate step by step whenever they want. Also, we would hold our promise that no API is removed without warnings in at least one previous release.

What do you think about this amendment to the migration plan?

**Comment by tardyp** [comment]
Hello,

I have two issues with NewStyle postfix.

- the default will still be old style, which means that new user will keep using the old code without knowing. The deprecation warning is a mitigation to that, but still this means that all our doc suggest to use the deprecated thing which is not ideal.

- it needs to change all your code if you want to opt-in, which is potentially a big barrier, so people will effectively delay it.

I wonder if we can take advantage of the plugin interface so that user can opt-out new style steps via that.

at the beginning of the master.cfg, they would do

from buildbot.plugin import useOldStyleSteps

```
useOldStyleSteps('Compile', 'WarningCountingShellCommand', etc)
```

So we make NewStyle the new default, and provide very little upgrade task to do (we could even suggest the line to add at upgrade by parsing the BuilderFactories)

If ppl don't use old style steps, or already migrated, then they don't have to bother changing anything for 3.0

**Comment by phillxnet** [comment]
Is there yet a canonical doc reference for what an old style or new style step actually is? I don't know if we are using old or new style. Apologies if this is an inappropriate question/setting for question.

**Comment by tardyp** [comment]
@phillxnet http://docs.buildbot.net/current/manual/upgrading/0.9-new-style-steps.html

You can see for example this PR to see how much simpler the steps are eventually looking

https://github.com/buildbot/buildbot/pull/5479/files

This only is relevent if you are actually writing custom steps

**Comment by p12tic** [comment]
@tardyp I've looked into the plugin DB approach during the past month and in the end I arrived into conclusion that it's worse option than the NewStyle postfix approach.

I think that the need to change code to migrate to NewStyle postfix is a minor problem. The majority of cases are when the users only instantiate the steps directly, in which case it does not matter whether new or old style step is used. The only cases when the rename is necessary is when the users derive the step classes to override functions. In this case, renaming will be the least of their problems, as there will be a lot of code to migrate anyway.

We will be able to add notices about the migration to the documentation, so that the users know what's happening. Since the only thing that changes is functions exposed for overriding, only small part of the documentation will be affected.

Plugin DB also has a serious issue in that it's a singleton. This would force the users to select new/old style steps for their whole Buildbot configuration. This would make migration much much harder in certain cases when users have a lot of custom steps because they won't be able to migrate them one by one.

Finally, the need to add an opt-out of new-style steps via e.g. `useOldStyleSteps` breaks our upgrade promise that no code breaks upon minor version upgrades.

Given the above, I suggest that we stick to the NewStyle postfix proposal.

What do you think about that?

**Comment by tardyp** [comment]
Sorry for taking so long to give feedback. I agree with your arguments. 
I think like always with such migration there is no perfect solution, there will always be some work for our users.

My point was to try and have a way to encourage people to migrate early. I this current solution, people who migrate early will have to migrate twice (second when we release 3.0, to migrate back to simple names)
But the second migration is just a simple sed, so that is fine.

**Comment by p12tic** [comment]
Resolved in https://github.com/buildbot/buildbot/pull/5804.
