### ISSUE TITLE
Missing tags for versions 2.8.0+ on Docker Hub

### ISSUE THREAD

**Issue by heytred** [buildbot/buildbot#5469]
I was recently chasing down a bug related to the GitPoller where missing commits would throw an error - I found the fix using issue https://github.com/buildbot/buildbot/issues/4211 and saw that a fix was merged into v2.8.0 with this PR (https://github.com/buildbot/buildbot/pull/5302/commits/3763d17a7faf22b7268123c46d07d50bb9efc850) however the lastest non-master tag on Docker Hub is v2.7.0. I resolved the issue in my situation, but adding tags for 2.8.0/2.8.1/2.8.2 to Docker Hub would be great.

**Comment by p12tic** [comment]
Looks like docker build process was broken in v2.8.0 and no one noticed. #5472 should fix this bug, but unfortunately we won't be able to release the existing 2.8.x tags.

I've updated the release check list so that similar issues never happen again.
