### ISSUE TITLE
Cannot filter on started_at in REST API

### ISSUE THREAD

**Issue by rossburton** [buildbot/buildbot#5529]
I wanted to list all builds in the last week using the REST API.  `.../api/v2/builds?order=-started` gets the list of all builds ever sorted in date order, but adding for example `started_at__ge=1598375285` to filter to just builds started after a specific timestamp results in an `invalid filter value for started_at__ge`.

**Comment by smrnmakhija** [comment]
Can you give some guidelines to reproduce?

**Comment by senyai** [comment]
Would you like `started_at__ge=2010-10-25` to also work?

**Comment by rossburton** [comment]
That would be nice, but a first step of a machine-readable integer (unix timestamp, presumably) would work.

**Comment by tardyp** [comment]
I think that it makes sense to also allow 2010-10-25 like strings. If there are dash in the string, then try to parse a date with iso8601 derivatives

maybe something like this:

YYYY-MM-dd
YYYY-MM-ddTHH:mm
YYYY-MM-ddTHH:mm:ss
YYYY-MM-ddTHH:mm:ss.ss
YYYY-MM-ddTHH:mm:ss.ss±hh:mm

I'll leave it to you to create a new issue on this topic.
