### ISSUE TITLE
Documentation: firstrun tells you to install buildbot in ~/tmp/bb-master

### ISSUE THREAD

**Issue by JulianGro** [buildbot/buildbot#5543]
http://docs.buildbot.net/current/tutorial/firstrun.html tells you to install buildbot in `~/tmp/bb-master`
A path with `tmp` in its name is probably the worst choice. Someone on IRC suggested using `/opt/buildbot` instead.
It probably doesn't *really* matter what path as long as it is not `tmp`.

**Comment by p12tic** [comment]
Fixed in #5720, thanks for raising the bug.
