### ISSUE TITLE
Feature Request: Add Podman support for Buildbot latent workers

### ISSUE THREAD

**Issue by FilBot3** [buildbot/buildbot#5555]
# Feature Request: Podman support for Buildbot Latent Workers

* [Buildbot Meting 2020-09-08 Notes](https://supybot.buildbot.net/meetings/buildbot/2020/buildbot.2020-09-08-16.05.log.html)

I wanted to ask if there would be the possibility of Buildbot getting the ability to work with Podman container runtime? It does not need to be ran as root as the Docker service does so there are less vulnerabilities, but the user would need to do a little networking setup.

Kubernetes could use Podman as it's container runtime when it launches pods, but not everyone has a Kubernetes instance to run. I'm not sure about `k3s` or `minikube` or `kind`. 

## References

* [Podman Homepage](https://podman.io/), [Github: Podman](https://github.com/containers/podman)
* [Buildah Homepage](https://buildah.io/), [Github: Buildah](https://github.com/containers/buildah)

**Comment by grooverdan** [comment]
If buildbot uses https://github.com/docker/docker-py for a docker client, and podman advertised a docker compatible API - http://docs.podman.io/en/latest/_static/api.html , does that mean the feature is already there?

**Comment by FilBot3** [comment]
You are correct.

* https://podman.io/blogs/2020/06/29/podman-v2-announce.html#restful-api
* https://github.com/containers/podman/blob/master/docs/tutorials/remote_client.md#creating-the-first-connection
* https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/

I wasn't aware of this capability, or it wasn't there when originally asked for. Seems I need to enable the podman service for either the root user or for a root-less user. Then using the `podman-docker` package, provide similar sockets. I remember having to define the socket for BuildBot to take advantage of it, so this wouldn't be much more different than doing that.

I suppose we could close this. I'll make further posts as I get tests in and figure out some results.

**Comment by p12tic** [comment]
Sounds good, please reopen the issue if you find that Podman does not work and there's something simple missing in Buildbot to make it compotible with Podman docker compatibility layer.
