### ISSUE TITLE
Some integer fields should be explicitly converted into integer before being written into DB

### ISSUE THREAD

**Issue by jpflori** [buildbot/buildbot#5612]
When filling integer fields in the database, self.master.reactor.seconds() should be explicitly casted into an integer: int(self.master.reactor.seconds())
This might be a sqlalchemy/sqlite3 issue, but when migrating from sqlite3 to postgresql, conversion failed because sqlite3 stored the float returned by self.master.reactor.seconds() as a float and I add to modify the sqlite3 database by hand to migrate.
Explicitely casting to int should not hurt and is already done for other fields (see below).

The complete_at field here:
https://github.com/buildbot/buildbot/blob/38dbae5bad193653a77d1db16222ea3a5be6f38f/master/buildbot/db/builds.py#L203
and here:
https://github.com/buildbot/buildbot/blob/38dbae5bad193653a77d1db16222ea3a5be6f38f/master/buildbot/db/steps.py#L172
(Note this is already done for the started_at field)

And the created_at field her:
https://github.com/buildbot/buildbot/blob/38dbae5bad193653a77d1db16222ea3a5be6f38f/master/buildbot/db/sourcestamps.py#L96

**Comment by p12tic** [comment]
Fixed in #5613.
