### ISSUE TITLE
GitHubStatusPush failures in 2.9.0

### ISSUE THREAD

**Issue by steven-johnson** [buildbot/buildbot#5664]
Our build has been creating a GitHubStatusPush instance like so:

```
gs = reporters.GitHubStatusPush(token,
                                startDescription='Build started.',
                                endDescription='Build done.',
                                context=Interpolate("buildbot/%(prop:buildername)s"),
                                verbose=True,
                                builders=my_builder_list)
```

Under 2.8.4, this works fine; under 2.9.0, this now fails at parse time with

```
builtins.TypeError: checkConfig() got multiple values for argument 'startDescription'
```

... from eyeballing the docs (and also a cursory look at the code), I don't see what's wrong with the way our code has been calling this. Is it possible there's a glitch in the 2.9 release for this? (Or has our code just been getting lucky up to now?)

**Comment by p12tic** [comment]
Thanks a lot for the bug report. There were some changes in the github reporter and underlying functionality and one of them turned out to create a release-critical bug. This should be fixed in #5666 which will be released as BuildBot 2.9.1 shortly.
