### ISSUE TITLE
`MasterShellCommandNewStyle` and `MasterShellCommand` are the same

### ISSUE THREAD

**Issue by jsonar-cpapke** [buildbot/buildbot#5674]
I noticed that the classes `MasterShellCommandNewStyle` and `MasterShellCommand` (as of buildbot version 2.9.1 at least) have the exact same code inside them, except for one single line of `self.warn_deprecated_if_oldstyle_subclass('MasterShellCommand')` inside `MasterShellCommand`.

I suspect that `MasterShellCommand` was intended to keep the previous code, but it looks like it was updated to contain new-style code.

**Comment by p12tic** [comment]
Thanks for the bug report. Indeed, somehow I picked wrong revision for reverting the old-style steps to. Or maybe git noticed the file copy and got a bit confused with all the rebasing that was happening at the time.

In any case, this will be released as 2.9.2 today or tomorrow.
