### ISSUE TITLE
change_hook/poller not working for ReconfigurablePollingChangeSource

### ISSUE THREAD

**Issue by stoklund** [buildbot/buildbot#5727]
In [poller.py](https://github.com/buildbot/buildbot/blob/a0e1d8840e8856ead136a1ad6e2021931355af15/master/buildbot/www/hooks/poller.py#L40), the change sources are filtered like this:

```python
        for source in change_svc:
            if not isinstance(source, PollingChangeSource):
                continue
```

This means that any pollers derived from the super-class `ReconfigurablePollingChangeSource` will not be found. Since [new code is supposed to use `ReconfigurablePollingChangeSource`](https://docs.buildbot.net/current/developer/cls-changesources.html?highlight=reconfigurablepollingchangesource#pollingchangesource), the code should probably read:

```python
        for source in change_svc:
            if not isinstance(source, ReconfigurablePollingChangeSource):
                continue
```

**Comment by p12tic** [comment]
@stoklund Thanks a lot for the bug report. It seems that your observation is correct. Could you maybe submit a pull request with a correction? Tests are in `master/buildbot/test/unit/www/test_hooks_poller.py`, there we would need maybe just a single additional test to check whether ReconfigurablePollingChangeSource behaves correctly.

**Comment by stoklund** [comment]
Sure! Let me check if I'm able to run buildbot tests. Then I can make a PR.

**Comment by p12tic** [comment]
@stoklund [This part of the documentation](http://docs.buildbot.net/latest/developer/quickstart.html) should get you started for unit tests quickly. You only need to create a Python environment, ignore the section on Javascript.
