### ISSUE TITLE
Use MD5 instead of md5 to create auth credentials

### ISSUE THREAD

**Issue by markus-sus** [buildbot/buildbot#5743]
I ran into a problem in which using urllib request in python3 fails to connect to the buildbot api using basic authentication. The reason is simply that the built in python library cannot handle 'md5' hash algorithm but it can handle 'MD5'.

I think the relevant code is in www/auth.py when calling DigestCredentialFactory in functions HTPasswdAuth and UserPasswordAuth.

Looking at this header in the browser the data seems to be reported as 'MD5' but when python urllib.request library connects it will get the header as md5.

I did a local test in which I changed the lines to use MD5 instead of md5 in the auth.py and it seems to solve the problem and still works in the browser.

Is there any specific reason why md5 is used? If not then I could go through the process of supplying a patch.

I will file a bug report about making python urllib.request library handle different cases just to see what they think.

**Comment by markus-sus** [comment]
Ok. I found some kind of specification for the www-authenticate header and it seems like 'md5' is not listed as an alternative and it should be MD5 so I think this should change in the buildbot code.

**Comment by tardyp** [comment]
Hello,

As per twisted doc, it is supposed to be case insensitive, and the default is lowercase:
https://github.com/twisted/twisted/blob/trunk/src/twisted/cred/credentials.py#L200

In the RFC, is is also mentionned that this is case insensitive.
https://tools.ietf.org/html/rfc3230#section-4.1.1

So I would say this is a problem in python library.

https://github.com/python/cpython/blob/3.9/Lib/urllib/request.py#L1206
these checks should be case insensitive.

**Comment by tardyp** [comment]
https://github.com/python/cpython/pull/24122

**Comment by markus-sus** [comment]
Oooh, thank you. Then I do not have to do file a bug report.

**Comment by p12tic** [comment]
I think we still need to work around this in Buildbot code as the feature does not work as intended right now. There will be many people during the next following years that will use Python versions without fix for python/cpython#24122, most of them will not know the bug exists and it will appear as if it is Buildbot which is broken, not Python.

@markus-sus: It would be great if you could do a PR to fix this problem.

I think we don't need a test here, but please add a comment with a link to the bug report in cpython explaining why we have the algorithm as uppercase.

**Comment by markus-sus** [comment]
I will schedule a task for making a PR sometime in the next two weeks.
Not very used to git and github so bear with me as I need to closely follow some guide :/

**Comment by tardyp** [comment]
you can see the documentation on how to make PR
http://docs.buildbot.net/current/developer/pull-request.html

don't hesitate to come back to us if you need help. Looking forward to this contributino, and the next ones!

**Comment by markus-sus** [comment]
Hello. I am having trouble running the End-to-End Tests described here:
http://docs.buildbot.net/current/developer/pull-request.html

```
15:36:54] I/launcher - Running 1 instances of WebDriver
[15:36:54] I/local - Starting selenium standalone server...
[15:36:54] E/launcher - spawn java ENOENT
[15:36:54] E/launcher - Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[15:36:54] E/launcher - Process exited with error code 199
```
I tried using chronium browser, the open source one for this on ubuntu 20.04.
are you normally using the chrome browser itself for this one or something else?
The reason I want to test this is that a quick grep seems to indicate that a user/password is setup for the master used by this test.

apart from this it seems like all the tests are passing with the small modification I did.
I also wrote a smaller variant of the original python script that exhibited the behaviour to test that the problem was there, and that it is fixed after the small change I did. For that I modified the test-master config file (locally, not something that git will track). Should I supply those two files as part of this ticket or somewhere else to make it easy for someone to test if they ever feel like it.

**Comment by p12tic** [comment]
I think in this case don't bother running end to end tests locally as they're the hardest to setup. We'll see if tests work on CI here after you create a PR.

> For that I modified the test-master config file (locally, not something that git will track). Should I supply those two files as part of this ticket or somewhere else to make it easy for someone to test if they ever feel like it.

Maybe you could attach the files to a comment at this issue? I think this issue will be one of first things people will find when searching for related problems.

**Comment by markus-sus** [comment]
Here are some files for testing the problem and the solution.

[test-setup-files.zip](https://github.com/buildbot/buildbot/files/5796492/test-setup-files.zip)

**Comment by markus-sus** [comment]
One more thing. Is this ticket worthy of a notice in newsfragment or can I omit that?
Feels like it is a too small change.

**Comment by p12tic** [comment]
I think it's worth a newsfragment, because the problem could be very annoying to some end users.

Something like: ```Worked around a bug in Python's urllib which caused Python clients not to accept basic authentication headers (:issue:`5743` ```

**Comment by markus-sus** [comment]
Crappit. I should have waited with doing a pull request.
Back to linux then.

**Comment by markus-sus** [comment]
To be fair. I think if there were more users that was using urrlib and python then this should have been discovered a long time ago.
I think a lot of people simply uses the requests python library (or as a workaround if this kind of thing happens). Or they simply use a different authentication scheme (like we did for years, external authentication to the pages) which don't exhibit this problem.

**Comment by p12tic** [comment]
I agree that if a lot of people were using this authentication scheme with urllib this would have discovered earlier. However, I'm looking more into benefit/cost in a larger scale. Someone who needs this authentication scheme and for some reason uses urllib will waste hours trying to get this to work. For us, it's just a couple of minutes to document what has changed which would allow such user to see that e.g. he needs to upgrade Buildbot. So even if one person avoids having to spend time figuring out the issue, our time is well spent.
