### ISSUE TITLE
GitHub hook does not work without token

### ISSUE THREAD

**Issue by umar456** [buildbot/buildbot#5760]
GitHub accepts requests for its API without requiring a token for public repositories. Commit  f1d01ecac8beea3766d7e101b2afd281e396346e seems to break this by requiring a token to get the files from the GitHub API. Because of this (and maybe other commits) my instance of buildbot is not creating change sets for the incoming hooks.

**Comment by terencehonles** [comment]
It looks like this code path may need to just try to hit the github API or maybe the repo needs to be checked for public access. I do not have a token setup and my repository is private and a previous change broke buildbot for me. The change referenced was me disabling the seemingly broken functionality and I did not realize that it would work without a token in certain settings.

**Comment by p12tic** [comment]
@terencehonles If I create a fix for the public repository case, would you be able to test it in your setup?

**Comment by terencehonles** [comment]
@p12tic yeah I think I can do that, not sure my turnaround but I'll try to be prompt now that I'm aware it's needed :slightly_smiling_face:

**Comment by terencehonles** [comment]
@p12tic that ^^^ should fix the issue. I've not tested it in my deployment, but the previous code did not do an HTTP check and now that it's in there it's probably safe to make the HTTP request. It's always going to fail for me which will result in some extra logging, but it won't crash like it was before.
