### ISSUE TITLE
Question: Is there any way to use sudo or execute only one command as root

### ISSUE THREAD

**Issue by orensbruli** [buildbot/buildbot#5785]
Hello,

I have just deployed my first buildbot and worker. I'm loving it.
I have found a problem integrating our usual testing workflow which involves a "sudo make install" command.
I have seen sudo cant be executed as shellCommand step. 
Is there any other way to execute only one command in the worker as root?

Thank you in advance.

**Comment by p12tic** [comment]
You can execute sudo as a shellCommand step. The only question is how to pass the password.

I think this could help: https://superuser.com/questions/67765/sudo-with-password-in-one-command-line

You would need to send the password to the worker into a file (see http://docs.buildbot.net/2.10.0/manual/secretsmanagement.html#how-to-populate-secrets-in-a-build). Then you would need a script that does `cat password_file | sudo -S <command>`. This way you run arbitrary commands as root user in somewhat secure way.

If you want a simplier setup you can omit the secrets part and just hardcode the passwords in master.cfg and send them e.g. as part of the shellCommand. But this would be less secure as anyone who can read the shell history or running processes may read the password as well.

**Comment by tardyp** [comment]
Another preferred way of running sudo command is to have the buildbot user
in the /etc/sudoers file and specifying the exact command the bot may run
without password.
See NOPASSWD option in man sudoers.

Regards

**Comment by orensbruli** [comment]
Thank you both. I'm gonna try with your suggestion first @tardyp

**Comment by orensbruli** [comment]
> NOPASSWD

I confirm this works. Thank you again.
