### ISSUE TITLE
High-profile open-source projects listed on the landing page

### ISSUE THREAD

**Issue by dandv** [buildbot/buildbot#5845]
https://www.buildbot.net states

> This flexibility has led to its use in a number of high-profile open-source projects, including Chromium, WebKit, Firefox, Python, and Twisted.

https://github.com/buildbot/buildbot/wiki/SuccessStories no longer lists Firefox and Chromium.

**Comment by p12tic** [comment]
Thanks for the bug report.

This has been fixed in https://github.com/buildbot/buildbot-website/pull/57.
