### ISSUE TITLE
Web-based assignment of new workers and builders

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#5868]
In our build environment we have a master for each project. Workers are assigned to builders using each project's master.cfg. However, there comes a time in the project when we want to bother another project's workers to improve throughput of testing and building. A week later, we want to move those workers back. Sometimes we want to distribute the workers within the project differently. Finally, we are discussing making every single computer in our office a worker in the nighttime for broad scope testing.

Is the only way to reconfigure workers and their builder assignments via master.cfg reboot? Or are there hooks in there that we could experiment with? Ideally we could do this via a web interface.

**Comment by tardyp** [comment]
Hi,

Actually the workers are choosing which master they are connecting to.

You can just configure all workers in all masters, and use another mean
(ansible?) to connect/disconnect worker from whichever master.

Regards
Pierre

**Comment by sphet** [comment]
Tardy,

That solution is appropriate for master allocation, but not builder allocation. We have to restart the master to re-allocate workers. Do you think there would be a way where we could re-assign the worker-to-builder mechanism on the fly? I guess I could dig through the source and see where the builder assignment code is as I kind of remember (five years ago) that the code asks for valid workers in there.

Any direction hints would be great.

**Comment by p12tic** [comment]
You can reconfig master to let the builders take new workers or lose old workers.

Another option would be to use https://github.com/buildbot/buildbot_travis and just put everything to a single master. This may or may not work for you use case though.

Long term buildbot will get some understanding of "projects" with a separate per-project UI to group builders. This would solve the problem you're seeing at least partially.

**Comment by sphet** [comment]
@p12tic Does the reconfig re-instantiate all of the steps, pollers, status reporters?

**Comment by p12tic** [comment]
@sphet Steps are reinstantiated completely and old versions in the Builder configuration are replaced by them. The builders on the other hand only change their internals, the instance stays the same (see `Builder.reconfigServiceWithBuildbotConfig()`). Pollers and status reporters are essentially handled the same way by the `BuildbotServiceManager` class and thus they also keep their instances and are just reconfigured.

**Comment by sphet** [comment]
I'll look at the reconfig option again. Our master.cfg is very involved with the import of custom steps, so I have been weary over the years given that reconfig has not always worked *quite right*. We are behind a fair bit on versions so I will try to get us to the head and try again.

**Comment by tardyp** [comment]
Back when I was maintaining a very large buildbot, we had the same issue with lots of custom steps.
I advice to not try and reload modules in the reconfig we tried for months to get this right but this leaves too much of the old config in memory and becames very instable so we had to retart anyway.

Rather, you should have your 'reconfigable' configuration described in yaml, .toml, .json, whatever you prefer, so that the code does not get reloaded, but you still have the possibility to change what's needed to change often.

**Comment by sphet** [comment]
@tardyp  can you explain more this 'reconfigurable' configuration in yaml (or whatever) and explain how this is reloaded for worker assignment? We already use virtual_builders a lot overtop of generic "test atoms" but the builder assignment is the downside.
