### ISSUE TITLE
flawed HashiCorpVaultSecretProvider implementation

### ISSUE THREAD

**Issue by mixicz** [buildbot/buildbot#5903]
After unsuccessfuly trying to get vault working with buildbot I realized, that current naive implementation has several major flaws preventing it to be usable in real world scenarios. To give more context, we are using hashicorp vault in production at my work for about 5 years now, having several thousand secrets stored in generic kv store. We use typically 5 level deep paths allowing us for fine grained access control to secrets.

### Current issues:
1. separating optional key with `/` is ambiguos, as vault path components are separated by `/` as well,
2. only flat (single component) path can be used now, which is not viable real world use (it would severely hinder management of access control in vault),
3. only token authentication is supported, but even when I write some python code in config to obtain it, tokens are short lived with forced TTL. So in real world scenarios buildbot uptime will typically exceed token TTL, breaking pipelines after some time after config/restart,
4. vault paths in general may contain any characters so it is good practice to URL escape path components.

### To resolve this I suggest following changes:
1. use [HVAC](https://github.com/hvac/hvac) module for vault communication (it will help with points 3. and 4.),
2. use colon `:` for separating path from key (this convention is used in [Ansible hashi_vault lookup plugin](https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html)), ideally with escaping extra colons in path or key name using `\`,
3. support additional login methods, at least *approle* which is probably most typical for CI/CD pipelines,
4. drop support for default `value` key, it's only confusing with no real world benefit; mentioned Ansible plugin returns dictionary with all keys when no key is specified, but I'm not sure if buildbot could handle this (if not, we can throw exception to enforce key specification).

I would welcome any comments or objections regarding this topic. I'll make PR with new HashiCorpVaultSecretProvider once we agree on this.

**Comment by p12tic** [comment]
@mixicz Thanks for filing this bug report. I agree on all of your points.

Regarding (2), escaping sounds good, `Interpolate` should handle the subsequent colons and just pass it as part of string for the secret to interpret.

Regarding (4), let's just remove implicit `value` key support altogether.

Since the code of the current `HashiCorpVaultSecretProvider` is rather simple, would it be possible to implement your changes within that class? The only backwards incompatible changes are the path/key separator and getting rid of the implicit key support. I think we can handle both by adding e.g. `path_key_sep` argument that is equal to `/` by default and throws a deprecation warning. Users would need to pass `path_key_sep=':'` to get rid of the warning. No other values are supported. `path_key_sep=':'` would also turn off the default `value` key logic.

What do you think about the above?

Looking forward to your PR.

**Comment by mixicz** [comment]
> Regarding (4), let's just remove implicit `value` key support altogether.
> 
> Since the code of the current `HashiCorpVaultSecretProvider` is rather simple, would it be possible to implement your changes within that class? The only backwards incompatible changes are the path/key separator and getting rid of the implicit key support. I think we can handle both by adding e.g. `path_key_sep` argument that is equal to `/` by default and throws a deprecation warning. Users would need to pass `path_key_sep=':'` to get rid of the warning. No other values are supported. `path_key_sep=':'` would also turn off the default `value` key logic.

While I think it is generally good practice to do such changes in backwards compatible way as you suggest, I have moral problem forcing users to specify extra parameter to switch from broken to correct behavior.

Use `path_key_sep` parameter is good idea, but I would rather set default it to new `path_key_sep=':'`. Instead I'd evaluate if path contains unescaped separator, and if not, use *last* slash as path-key separator with deprecation warning (and in case no slash is present in the path, use default `value` key). I would also allow to specify any separator character, not just `:` or `/`, it might be handy feature in case someone often uses colon in vault paths.

This way it would remain backwards compatible and would not require any extra parameters for new users.

**Comment by p12tic** [comment]
@mixicz The problem I want to avoid is to break users' configurations in a way that's difficult to understand. At least when they are explicitly fixing a deprecation warning they'll are more likely to notice issues with their secret paths. When one is upgrading from Buildbot 2.2.0 to 2.10.1 backwards incompatible changes just lead to non-working configuration and it's hard to know what exactly is wrong.

If we immediately default to `path_key_sep=':'` then we would break all configuration that use `':'` in key paths.

The requirement to have `path_key_sep` for new users will be temporary - until we remove the deprecated previous default and switch to the colon. This will happen with a new major version of Buildbot.

**Comment by mixicz** [comment]
@p12tic I do understand your concern and while I think it's unlikely anyone has such configuration, there is no way to be sure.

I'm still not inclined to force users specifying extra parameter though. What if I create new class instead (`HashiCorpVaultHvacSecretProvider` or `HvacSecretProvider`) and old class would show deprecation message to migrate to new class? Old configuration would remain bug-to-bug compatible, new secret provider would be way cleaner not having to support old buggy implementation and easier to use without need to specify extra parameters.

**Comment by p12tic** [comment]
@mixicz I agree that having a different class would address my concerns. It would be easier for you to implement it this way too.

**Comment by mixicz** [comment]
@p12tic OK, I'll create new class named `HashiCorpVaultHvacSecretProvider`. I can't promise any specific timeline as this is part of my free time hobby project, but I expect 2-3 weeks to have PR tested and ready.
