### ISSUE TITLE
FileUpload umask issues

### ISSUE THREAD

**Issue by lfdmn** [buildbot/buildbot#5946]
Hi,

I'm trying to set the umask for buildbot master.

```python
m = BuildMaster(basedir, configfile, umask=0o013)
```

I have buildbot master running in Docker container and nginx into another. They are on the same host and share the nginx html folder via folder mapping.

I added a group with same id on host, buildbot master and nginx, as well as set the sticky permission bit.

At the end of my builder I have a `Fileupload` step uploading the build artifact into the nginx folder.

Everything works, except that no mater what `umask` setting I use, the uploaded file permissions are `600`
```shell
-rw-------. 1 root    buildsystem    68989 Mar 25 13:33 blabla.zip
```

So I can list files and directories from we browser, but get 403 Forbidden error due to the lack of read permission.

I could of course change permissions after each upload but would like to avoid extra steps is possible.

**Comment by senyai** [comment]
The `Fileupload` docs say: _The copied file will have the same permissions on the master as on the worker, look at the mode= parameter to set it differently._ So, maybe you should try that `mode` parameter?

**Comment by p12tic** [comment]
@senyai Thanks for explaining. I'll close this issue as it's likely the problem the user had is solved by the suggestion and there was no response anyway.

If the suggested solution does not solve the issue, please reopen the bug. Thanks.
