### ISSUE TITLE
Unmodified builder name used in ssh path

### ISSUE THREAD

**Issue by levitte** [buildbot/buildbot#5949]
Buildbot version: 2.6.0

I recently discovered that while a Unix worker will work very well with builder names having almost all sorts of characters, such as `:`, a Windows worker has issues.

The documentation for builder builddirs does specify that ["this parameter defaults to the builder name, with some characters escaped"](http://docs.buildbot.net/latest/manual/configuration/builders.html) (in practiced, that seems to mean that certain characters are changed to underscores).  However, it doesn't like the same type of munging doesn't happen for the SSH path, and this function seems to confirm that:

https://github.com/buildbot/buildbot/blob/9f185536ff1138e125a51fe8c028334fb9b4356d/master/buildbot/util/git.py#L147-L170

(I checked, this function hasn't changed between v2.6.0 and now)

What happens on Windows is that the git setup step fails, like this (`mkdir` is the problem...  the `stat` line is to show the builder name munging I was expecting to happen in *any* path):

```
stat: The system cannot find the file specified: C:\Users\buildworker\vc-win32\builder_name_with_colons\build\.buildbot-patchedprogram finished with exit code 2
mkdir: The filename, directory name, or volume label syntax is incorrect: C:\Users\buildworker\vc-win32\.builder:name:with:colons.build.buildbotprogram finished with exit code 22
```

**Comment by tardyp** [comment]
Good finding! I think you are only a few steps away to fixing this issue..

Would you like to submit a patch?

**Comment by levitte** [comment]
I can give it a shot, given my weak python-fu (I'm pretty much a beginning learner)

**Comment by levitte** [comment]
Wait, hold on....   naaaaahhhhh, can't be *that* simple, can it?
Well, ok, if that was it, PR comming up!

**Comment by levitte** [comment]
Looks like I got it, see #5960.
