### ISSUE TITLE
lazylogfiles broken on 3.0.2

### ISSUE THREAD

**Issue by tonyhutter** [buildbot/buildbot#5957]
I'm upgrading from 0.8.x to 3.0.2, and have this:
```python
test_factory = util.BuildFactory()

test_factory.addStep(ShellCommand(
    env={'PATH' : bin_path},
    command=["runurl", bb_url + "bb-dependencies.sh"],
    decodeRC={0 : SUCCESS, 1 : FAILURE, 2 : WARNINGS, 3 : SKIPPED },
    haltOnFailure=True, logEnviron=False,
    lazylogfiles=True,
    description=["installing dependencies"],
    descriptionDone=["installed dependencies"]))
```
Which gives me:
```
2021-03-26 18:38:03+0000 [-]   Invalid argument(s) passed to ShellCommand: lazylogfiles
```
According to the 3.0.2 documentation, `lazylogfiles` is a valid parameter for `ShellCommand`
http://docs.buildbot.net/3.0.2/manual/configuration/steps/shell_command.html

I originally opened a question for this (https://github.com/buildbot/buildbot/discussions/5954) but was told to open a bug instead.

**Comment by p12tic** [comment]
@tonyhutter FYI the only thing what was broken was an argument allowlist. See https://github.com/buildbot/buildbot/pull/5970/commits/78fae50f54e6ed14d34bed364f0e940637fd60dd.

**Comment by tonyhutter** [comment]
Thank you! :smile: :+1:
