### ISSUE TITLE
Going to invalid builder URL in the web frontent throws errors in the backend logs

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#5981]
Going to e.g. `https://my-buildbot-host/#/builders/1234%20%20` (note the extra spaces) will throw an exception to the logs:

```
autobahn.wamp.exception.InvalidUriError: 
MasterService.subscribe(): 
invalid value "<redacted>   ." for URI (did not match pattern "^(([^\s\.#]+\.)|\.)*([^\s\.#]+)?$" 
with options strict=False, allow_empty_components=True, allow_last_empty=False, allow_none=False)
```

We should not throw errors in such cases as that's an easy way to spam logs in the master. These should be caught, ignored and only enabled in a debug mode.

**Comment by mokibit** [comment]
Hi @p12tic,
I could not reproduce this bug in my Buildbot. This is my web window:
1)  URL http://localhost:8010/#/builders/7%20%20 (note the extra spaces)
<img width="478" alt="image" src="https://github.com/buildbot/buildbot/assets/37383410/b9f60f82-9c07-499e-ae79-f45b1abe3a93">

2) URL http://localhost:8010/#/builders/1234aoeui (note the extra letters)
<img width="475" alt="image" src="https://github.com/buildbot/buildbot/assets/37383410/42910883-2ee3-4582-a01f-6f671b3cc1b5">

These two URLs do not throw any errors in the back-end logs.
Could you check once again if you have this bug in your system? If so, could you provide more information about how to reproduce it.
