### ISSUE TITLE
Lock on step not waiting until the lock is free

### ISSUE THREAD

**Issue by jsonar-cpapke** [buildbot/buildbot#5987]
While I was doing some testing around locks, I noticed a situation where the lock seems to release early. I have put what I believe is a minimal `master.cfg` below that reproduces the problem for me.

The issue I found can be replicated by triggering the builder 3 times. The one triggered first will run and the other two will wait for the lock. But if one of the other two builds is cancelled while they are still waiting for the lock, the third build will run, even though the first build should still have the lock.

I had a quick look at the code for the locks, and I think what is happening is that the `releaseLocks()` function (and more specifically, the `lock.isOwner()` function) only uses the step config to check if it is the owner, not which build the step is running on, and so the lock is released regardless of which build releases it.

pip freeze snippet:
```
buildbot==3.1.0
buildbot-worker==3.1.0
buildbot-www==3.1.0
```

`master.cfg`:
```
from buildbot.plugins import *

c = BuildmasterConfig = {}

c['workers'] = [
    worker.LocalWorker('worker1'),
    worker.LocalWorker('worker2'),
    worker.LocalWorker('worker3'),
]

c['protocols'] = {'pb': {'port': 9989}}

c['schedulers'] = [
    schedulers.ForceScheduler(
        name='scheduler',
        builderNames=['builder'],
    )
]

locks = [util.MasterLock(f'lock').access('exclusive')]

factory = util.BuildFactory()
factory.addStep(steps.ShellCommand(
    command=['sleep', 3600],
    locks=locks,
))

c['builders'] = [
    util.BuilderConfig(
        name="builder",
        workernames=['worker1', 'worker2', 'worker3'],
        factory=factory,
    )
]

c['buildbotURL'] = "http://localhost:8010/"
c['www'] = dict(port=8010)
c['db'] = {'db_url': "sqlite:///state.sqlite"}
```

**Comment by p12tic** [comment]
The steps are cloned when the build starts, so it shouldn't be that a step of one build could release a lock owned by a step of another build as these steps are different instances. Though maybe there are surprises in this part of the code.

Thanks for investigation and clear reproduction steps.

**Comment by rvanlaar** [comment]
I have a comparable problem.
We're running multi-master and only want one build, with triggerable substeps, to run at a given time.

This config works when running single master:
    ```build_lock = util.MasterLock("Build")

    c["builders"] = []
    c["builders"].append(
        util.BuilderConfig(
            name="build",
            workernames=WORKER_NAMES,
            factory=build_factory,
            locks=[build_lock.access("exclusive")],
        )
    )```
Let me know if this is the same problem, or if I should create a new ticket.
