### ISSUE TITLE
build_wait_timeout option in Latent worker not working as expected

### ISSUE THREAD

**Issue by BishopGIS** [buildbot/buildbot#5988]
Buildbot version 3.1.0 both master and latent worker (worker.LibVirtWorker).

After upgrade from 2.4 to 3.1 the builds using latent worker begin to stop in about 10 minutes.
It seems to me that build_wait_timeout now starts timer not after the build task finished but from the moment from start of latent worker.
Changing build_wait_timeout to several hours fix the problem (quick fix).

Also in documentation there is no mention to set build_wait_timeout in seconds (http://docs.buildbot.net/current/manual/configuration/workers.html?highlight=build_wait_timeout#common-options).

First I tried to set 20 min (build_wait_timeout=20) and I got restarting latent worker every 20s.

**Comment by BishopGIS** [comment]
The problem with builds was because daylight saving on LibVirtWorker. There was 1 hour difference leads such behaviour.
Disabling this in worker OS fixed problem. 
So bug label can be removed.

**Comment by p12tic** [comment]
Thanks for the bug report, this issue has been fixed in #6344.
