### ISSUE TITLE
ws_ping_interval is not added in the set of allowed keys for ww

### ISSUE THREAD

**Issue by pablogsal** [buildbot/buildbot#5991]
Checking the configuration after adding this parameter throws:

```
Configuration Errors:
  unknown www configuration parameter(s) ws_ping_interval
make: *** [Makefile:34: check] Error 1
```

The parameter should be updated in https://github.com/buildbot/buildbot/blob/c1c4812cc67265798dd597b06f113943dc154112/master/buildbot/config.py#L717

**Comment by vstinner** [comment]
ws_ping_interval parameter was added to Buildbot 3.0.0 ( 2021-03-08 ) in the issue #4078.

**Comment by vstinner** [comment]
The buildbot server of the Python project has timeout issues: https://bugs.python.org/issue41701 Using ws_ping_interval is an attempt to workaround this issue.

**Comment by pablogsal** [comment]
@p12tic Would it be possible to make a bugfix release or similar so we can leverage the fix in the CPython buildbot server?

**Comment by p12tic** [comment]
@pablogsal Yes, there will a bugfix release, maybe today.

**Comment by p12tic** [comment]
@pablogsal 3.1.1 has been just released.

**Comment by pablogsal** [comment]
> @pablogsal 3.1.1 has been just released.

Fantastic, thanks a lot! ❤️
