### ISSUE TITLE
compatibility with sqlalchemy 1.4

### ISSUE THREAD

**Issue by anthraxx** [buildbot/buildbot#5992]
Hi,

It would be great if buildbot gets compatibility with 1.4. In PR #5912 the constraints has simply been set to <1.4 but this is unfortunately not a solution for distro packaging of buildbot.

Is there an estimated timeline for compatibility with 1.4 as this issue is blocking distro efforts?

**Comment by yan12125** [comment]
I attempted to create a patch for sqlalchemy 1.4 compatibility but gave up at a very early stage. Needed changes seem non-trivial.

The 'buildbot' strategy is passed to sqlalchemy's `create_engine()` [1], and
the latter no longer accepts a strategy other than 'mock' in version 1.4 [2][3]. The commit message for a related change [4] may shed some light:

> The system of "engine strategies" has been removed.   Extensibility for the :func:`.create_engine` process has been available since the 1.x series using the :class:`.CreateEnginePlugin` extension.

[1] https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/enginestrategy.py
[2] https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine
[3] https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_10/lib/sqlalchemy/engine/create.py#L513
[4] https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/1190, file doc/build/changelog/migration_20.rst

**Comment by p12tic** [comment]
Currently there is no timeline but we will do this ASAP as time allows.

**Comment by Conan-Kudo** [comment]
Has there been any progress on this?

**Comment by p12tic** [comment]
@Conan-Kudo @yan12125 @anthraxx This should be fixed in #6156.

**Comment by yan12125** [comment]
Thanks! I updated buildbot to the latest commit and running it with [sqlalchemy 1.4.15](https://archlinux.org/packages/community-staging/x86_64/python-sqlalchemy/) and postgresql 13.3 seems fine.
