### ISSUE TITLE
CustomAuth logout, followed by login, does not request user and password

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#6003]
We are trying to use CustomAuth to validate against our corporate password. We are not using reverse proxy web server. I have hooked up CustomAuth, and can login, but when I press "Logout", and get back an anonymous user, subsequent "Login" will simply log me in with the same user and password. There appears to be no way to logout and login as a DIFFERENT user. Is there something I need to do in my CustomAuth to handle this case?

I did experiment with authenticating myself on Buildbot metabuildbot using my github authentication and it seems to suffer the same problem. Once I have logged in, even if I log out, I don't get directed to GitHub to enter a new username and password. Is this perhaps a bug, or is there something I can do to force the login window to come up again?

**Comment by sphet** [comment]
If someone can point me to the right place in code to explore the caching of this data, I will look into it. Or is it not solvable?

**Comment by p12tic** [comment]
@sphet Could it be that the caching is on the backend to which CustomAuth communicates? In the case of metabuildbot I can see that logout successfully clears the Twisted session cookie, but when authenticating again Github does not offer to change users and just reuses whoever is already signed in on Github side. If I sign out on Github, subsequent login on Buildbot will no longer automatically login. Github does no longer have a signed in user, so it requests a sign in.

Maybe there needs to be an explicit way to tell the authentication backend that this user has logged out and any cached login autherization needs to be cleared.

**Comment by p12tic** [comment]
Closing the issue as there was no response and it seemed the problem is not really on Buildbot side.
