### ISSUE TITLE
DOCS: Buildbot worker as windows service has a broken link

### ISSUE THREAD

**Issue by levitte** [buildbot/buildbot#6048]
https://docs.buildbot.net/latest/manual/installation/misc.html#launching-worker-as-windows-service has a link to [the TRAC wiki page "RunningBuildbotOnWindows"](http://trac.buildbot.net/wiki/RunningBuildbotOnWindows), but that doesn't seem to be available any more.

It would be nice if this was updated

**Comment by p12tic** [comment]
Fixed now.
