### ISSUE TITLE
MailNotifier aggregate multiple builder results

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#6053]
After a build is complete for a specific revision, we trigger a suite of builders for testing. Currently each test haas a notifier, so in the case of a cross-test failure we get a spam of emails.

Is there a method to aggregate builder results somehow into one email? 

We do collapse build requests for some long-running tests, so I recognize this might be a hard problem to solve, but I'm looking for any ideas to get started with.

**Comment by yan12125** [comment]
[`BuildSetStatusGenerator`](https://docs.buildbot.net/latest/manual/configuration/report_generators/buildset.html) may be useful. I have a similar issue and all failure mails for the same git commit are merged after I switched to `BuildSetStatusGenerator`. Here are my changes: https://gitlab.com/yan12125/buildbot/-/commit/c75952433e6421bb9b286ff6f41d3d8d1dea7afe

**Comment by p12tic** [comment]
I think yan12125 has answered the question, so I will close the issue.
