### ISSUE TITLE
Protractor being sunsetted, end of 2022

### ISSUE THREAD

**Issue by rodrigc** [buildbot/buildbot#6060]
Related to https://github.com/buildbot/buildbot/issues/5875

According to https://github.com/angular/protractor/issues/5502 , Protractor is being sunsetted at the end of 2022.

Buildbot may wish to change its e2e tests from Protractor to one of the suggested alternatives.

**Comment by p12tic** [comment]
I think we'll change to cypress when converting from AngularJS to React.

**Comment by p12tic** [comment]
Fixed in https://github.com/buildbot/buildbot/pull/7045.
