### ISSUE TITLE
Git poller state exceeds database field size after some time

### ISSUE THREAD

**Issue by felixfontein** [buildbot/buildbot#6100]
When the Git poller covers all branches, it can happen that eventually the `lastRev` state gets too large so that it cannot be stored in the DB anymore (resulting in `Data too long for column 'value_json' at row 1` exceptions). This is because it never forgets branches that used to exist in the past (https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/gitpoller.py#L239), so its `lastRev` state never shrinks.

I'm wondering whether the `lastRev` state really needs to be updated (and not replaced) by the current set of references. The only reason why update is used (instead of replacing) I can think of is that if a branch is deleted and then restored (with the same HEAD), it will not trigger a change.

I'd like to create a PR which removes the updating, or at least makes it configurable. What is the preferred solution here?

**Comment by p12tic** [comment]
@felixfontein I think replacing makes sense here. It can be argued that removing a branch will remove all state related to it in the repository and subsequent push is unrelated even if the commit SHA is the same.
