### ISSUE TITLE
HgPoller is not updated anymore

### ISSUE THREAD

**Issue by LuluDavid** [buildbot/buildbot#6116]
Hi. I am using buildbot with Mercurial, and it seems that lots of improvements I am seeking are implemented on GitPoller but not on HgPoller. For instance : 

- An option **branches=True** to listen to all alive branches
- An option **branches=filter** to filter all alive branches to listen
- Building commits on previously unknown branches using the direct parent on the origin branch to record the change
- ...

So I am reimplementing these functionalities myself extending HgPoller and overriding some class methods, but wanted to know why HgPoller is not updated like GitPoller. My guess : GitPoller is used WAY more by users. But possibly : Git and Mercurial do not offer exactly the same features, so some functionalities are not doable for Mercurial.  

By the way, thanks for reading, and thanks for buildbot which is very useful.

**Comment by p12tic** [comment]
@LuluDavid It would be great if you submitted your improvements as PRs, so they would benefit all users and be maintained by the project long-term.
