### ISSUE TITLE
WorkerLock's maxCountForWorker ineffective when acquiring lock for a buildstep

### ISSUE THREAD

**Issue by slawek-es** [buildbot/buildbot#6132]
I have been trying to define a `WorkerLock` with the number of maximum concurrent builds specifically set for one of my workers, and add it to a single build step, like this:

```
MY_LOCK = util.WorkerLock("mylock",
                          maxCount=10,
                          maxCountForWorker={"myworker": 1})
```
```
class MyCustomBuild(Compile):
    def __init__(
        self,
        **kwargs: Any,
    ) -> None:
        kwargs.setdefault("locks", [MY_LOCK.access("counting")])
		super().__init__(**kwargs)
        ...
```

It looks like there is an issue which prevents the worker-specific maximum count from being used, as I can see that the `MyCustomBuild` step can be executed twice concurrently on the same worker.

After I added instrumentation to Buildbot's code, it seemed to me that a `Worker` object gets passed to `RealWorkerLock.getLockForWorker()`: the value passed as `workername` was stringified as `<Worker 'myworker'>` rather than just `myworker`.

**Comment by p12tic** [comment]
Fixed in #6133.
