### ISSUE TITLE
Should add the exit code '128' of TASKKILL as a Successful Return Code

### ISSUE THREAD

**Issue by yinyangsx** [buildbot/buildbot#6140]
Hello, my Windows Server 2019 worker failed to run TASKKILL command when timeout happen.  TASKKILL failed with exit status 128. 
_2021-07-14 10:29:25+0300 [-] using TASKKILL PID /F /T to kill pid 213464
2021-07-14 10:29:25+0300 [-] Unhandled Error
Traceback (most recent call last):
File "d:\buildbot\sandbox\lib\site-packages\twisted\application\app.py", line 399, in startReactor
self.config, oldstdout, oldstderr, self.profiler, reactor)
File "d:\buildbot\sandbox\lib\site-packages\twisted\application\app.py", line 312, in runReactorWithLogging
reactor.run()
File "d:\buildbot\sandbox\lib\site-packages\twisted\internet\base.py", line 1272, in run
self.mainLoop()
File "d:\buildbot\sandbox\lib\site-packages\twisted\internet\base.py", line 1281, in mainLoop
self.runUntilCurrent()
File "d:\buildbot\sandbox\lib\site-packages\twisted\internet\base.py", line 902, in runUntilCurrent
call.func(*call.args, **call.kw)
File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 822, in doTimeout
self.kill(msg)
File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 946, in kill
hit = self.sendSig(self.interruptSignal)
File "d:\buildbot\sandbox\lib\site-packages\buildbot_worker\runprocess.py", line 905, in sendSig
"TASKKILL /F /PID {0} /T".format(self.process.pid))
File "C:\Program Files\Python37\lib\subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'TASKKILL /F /PID 213464 /T' returned non-zero exit status 128._

I've manually invoked the failing TASKKILL command, and it does fail with error code 128. From the output, we can see the failure reason is that there is no running instance of the task when killing some child process. 
As well as I found that the process tree was successfully killed, but the job is not terminated, it is still in yellow, the yellow job blocks new jobs to be assigned to my my windows worker. 
**I think Buildbot should add the exit code '128' of TASKKILL as a Successful Return Code because code 128 means that the process you attempted to kill wasn't actually running on the target system.** 

_ERROR: The process with PID 214484 (child process of PID 213096) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 213976 (child process of PID 212212) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 215376 (child process of PID 215556) could not be terminated.
Reason: There is no running instance of the task.
SUCCESS: The process with PID 215556 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 212212 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 215492 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213196 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 207940 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 207084 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 214124 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 211980 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213620 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 215100 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213096 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 210924 (child process of PID 213264) has been terminated.
SUCCESS: The process with PID 213264 (child process of PID 214776) has been terminated.
SUCCESS: The process with PID 214776 (child process of PID 208396) has been terminated.
SUCCESS: The process with PID 208396 (child process of PID 213760) has been terminated.
SUCCESS: The process with PID 213760 (child process of PID 212780) has been terminated.
SUCCESS: The process with PID 212780 (child process of PID 211996) has been terminated.
SUCCESS: The process with PID 215312 (child process of PID 213256) has been terminated.
SUCCESS: The process with PID 211996 (child process of PID 213256) has been terminated.
SUCCESS: The process with PID 213256 (child process of PID 28064) has been terminated._

**Comment by p12tic** [comment]
@yinyangsx Would you be willing to contribute a bugfix?

**Comment by yinyangsx** [comment]
> @yinyangsx Would you be willing to contribute a bugfix?

Ok, I will try to do it.
