### ISSUE TITLE
DOCS: Why a virtual environment in Launching worker as Windows service?

### ISSUE THREAD

**Issue by levitte** [buildbot/buildbot#6170]
I finally got some peace of mind and could try following the steps described in [Launching worker as Windows service](https://github.com/buildbot/buildbot/blob/master/master/docs/manual/installation/misc.rst#launching-worker-as-windows-service), and I wonder, why is it necessary to make a virtualenv at all?

**Comment by levitte** [comment]
I did try out following the steps, but without setting up a virtualenv, i.e. installing all python modules system wide.  It works like a charm.  That makes me wonder what I'm missing...

**Comment by p12tic** [comment]
Fixed now.
