### ISSUE TITLE
buildbot.net website is down

### ISSUE THREAD

**Issue by p2shree** [buildbot/buildbot#6176]
Hi,

The buildbot.net website is down. Due to this I don't have access to documentation, including how to install buildbot.
I need to install buildbot server on CentOS. I also need to install buildbot slave on Windows, CentOS, and FreeBSD. Where can I find installers for buildbot

~ shree

**Comment by kordex0** [comment]
You can find the documentation at https://buildbot.readthedocs.io/en/latest/ while buildbot.net is down.

**Comment by p12tic** [comment]
This has now been fixed.
