### ISSUE TITLE
Windows: Worker service regression in 3.4.0

### ISSUE THREAD

**Issue by pmisik** [buildbot/buildbot#6294]
Hi,

I just tried to upgrade quite old worker running on 2.3 to latest one 3.4.0.
Upgrade were done on Python 3.7 x86

Observed problem:
After installation of buildbot-worker there is missing `buildbot_worker_windows_service.exe` in `sandbox\Scripts` folder.
Tried to downgrade to previous version and it 3.3.0 works well.

It looks like some issue introduced in 3.4.0 release (or some dependent package)

**Comment by pmisik** [comment]
It looks like given changes does not work with wheel packaging as
there is missing filed `buildbot_worker_windows_service = buildbot_worker.scripts.windows_service:HandleCommandLine`
in `[console_scripts]` section.

**Comment by p12tic** [comment]
Seems that the issue has been fixed. Closing.
