### ISSUE TITLE
buildbot checkconfig should fail for old style steps in buildbot 3

### ISSUE THREAD

**Issue by jain-aakash** [buildbot/buildbot#6315]
buildbot 3 doesn't seems to support old style build steps. However 'buildbot checkconfig' doesn't warn/fail for old style steps. It happily says: "Config file is good!" even with completely broken configuration containing old style steps.

This fails the basic purpose of checkconfig. checkconfig should tell about such issues.

**Comment by tardyp** [comment]
Hi,

old style steps where deprecated in buildbot 2, and not supported in buildbot 3.
As even the detection of such steps incur some non trivial maintainance of code and tests, we removed all support in buildbot 3.
Some kind of old style step may work on buildbot 3. we don't know as it is not tested anymore.
