### ISSUE TITLE
CodebaseParameter multichoice bug

### ISSUE THREAD

**Issue by dimavs** [buildbot/buildbot#6402]
My codebase parameter looks like:

```
util.CodebaseParameter(
    "src-tree",
    label="SrcTree",
    project     = util.ChoiceStringParameter(name = "project", choices = projects, multiple = True, default = "common"),
    repository  = util.FixedParameter(name = "repository", default = vcs.GIT_SRC),
    branch      = util.FixedParameter(name = "branch", default = branch),
    revision    = util.FixedParameter(name = "revision", default = "HEAD"),
)
```

There is an SQL exception with multiple projects selected:
```
       [SQL: INSERT INTO sourcestamps (ss_hash, branch, revision, patchid, repository, codebase, project, created_at) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
        [parameters: ('dc2d60278c18383338dbeb997157e83216003d32', 'master', 'HEAD', None, '<repo>', 'src-tree', ['foo', 'bar'], 1644
743192)]
        (Background on this error at: https://sqlalche.me/e/14/e3q8)

2022-02-13 20:06:32+1100 [-] while handling API request
        Traceback (most recent call last):
          File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
            result = current_context.run(
          File "/usr/lib/python3.10/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
            return g.throw(self.type, self.value, self.tb)
          File "/usr/lib/python3.10/site-packages/buildbot/www/rest.py", line 221, in renderJsonRpc
            with self.handleErrors(writeError):
          File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
            self.gen.throw(typ, value, traceback)
        --- <exception caught here> ---
          File "/usr/lib/python3.10/site-packages/buildbot/www/rest.py", line 130, in handleErrors
            yield
          File "/usr/lib/python3.10/site-packages/buildbot/www/rest.py", line 235, in renderJsonRpc
            result = yield ep.control(method, params, kwargs)
        twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'sqlalchemy.exc.OperationalError'>: (MySQLdb._exceptions.Operationa
lError) (1241, 'Operand should contain 1 column(s)')
```

**Comment by tardyp** [comment]
Well, it is not a bug if it is not documented that you can provide a list of projects in a sourcestamp...
It is just a feature that is yet to be implemented. ;)

In order to make that a feature, probably we need a bit more information about your actual usecase.

What do you want buildbot to do when several projects are selected?

Maybe you want to create multiple sourcestamps?

**Comment by dimavs** [comment]
That's a good question :-). From my point of view sourcestamp it's just a repository and revision. It doesn't matter which project we are building (but I may be wrong). I haven't looked at the buildbot source code and full architecture yet (python is not my first language :-) ).
My use case is quite simple: one repository; you can build multiple projects from it; forced or nightly schedulers. So, I can't see why would I need multiple sourcestamps. One sourcestamp with a list of projects should be fine.

Thanks!

**Comment by tardyp** [comment]
So you have a monorepo.

The sourcestamp is the triplet project/repository/revision. So you indeed need several sourcestamps if you want to have a buildset with several project

I would personally create one builder per project if possible this makes it easier to see the trend per projects.
again it really depends on the details of your project

**Comment by dimavs** [comment]
Yes, you are right. One builder per project is a better solution. Thanks!
