### ISSUE TITLE
Expired CA certificate on https://buildbot.pypy.org

### ISSUE THREAD

**Issue by IvanZosimov** [buildbot/buildbot#6562]
Hi, 👋! It looks like the CA certificate for https://buildbot.pypy.org has expired. Could you please take a look at that issue? We have some issues with CI because of that.

**Comment by IvanZosimov** [comment]
Just a ping @p12tic 💌

**Comment by tardyp** [comment]
This is not in a buildbot infra, but rather a pypy project infra.

**Comment by pmisik** [comment]
@IvanZosimov tardyp is right and it looks like there is already bug in pypy https://foss.heptapod.net/pypy/pypy/-/issues/3773

You are incorrect in statement **CA certificate** has expired. CA stands for **C**ertificate **A**uthority in terms of Public Key Infrastructure (PKI). In this particular case [end-entity certificate](https://crt.sh/?id=6474597191) (for site `buildbot.pypy.org`) has expired not CA certificate. Both CA certificates (issuing/intermediate CA and root CA) are valid.

**Comment by IvanZosimov** [comment]
@tardyp, @pmisik, thanks for your comments and for correcting my mistake in the name of the certificate 🤟
