### ISSUE TITLE
Fittering builds of a builder by started_at doesn't work: invalid filter value for started_at__gt

### ISSUE THREAD

**Issue by kwk** [buildbot/buildbot#6607]
I want to continuously fetch build information from the LLVM buildbot server but I cannot [filter](https://docs.buildbot.net/current/developer/rest.html#filtering) by the `started_at` attribute.

What I'm doing:

```
$ curl -sL https://lab.llvm.org/staging/api/v2/builders/224/builds?started_at__gt=1604843464
``` 

The error I get:

```yaml
{"error": "invalid filter value for started_at__gt"}
```

It seems that #5529 was also discussing this and there was a commit that claims to fix this issue but I don't know if

a) the commit is in the version deployed on the server that I'm talking to (see https://lab.llvm.org/staging/#/about)
   * Python version: 3.6.9
   * Buildbot version: 2021.10.08
   * Twisted version: 22.4.0

b) I'm using the API correctly.

Any feedback on this would be helpful.

**Comment by p12tic** [comment]
@kwk Thanks for bug report. I tried querying buildbot.buildbot.net using `curl -sL https://buildbot.buildbot.net/api/v2/builders/1/builds?started_at__gt=1604843464` and it seems to work. buildbot.buildbot.net runs the current master branch, so the bug seems to be fixed.
