### ISSUE TITLE
apply patch not working

### ISSUE THREAD

**Issue by Aaron-Chan** [buildbot/buildbot#6801]
@defer.inlineCallbacks
    def applyPatch(self, patch):
        patch_command = ['patch', f'-p{patch[0]}', '--remove-empty-files',
                         '--force', '--forward', '-i', '.buildbot-diff']

which windows has no patch command

**Comment by pmisik** [comment]
You are right that `patch` is not native Windows command.
You can try to install Cygwin (or mingw-64 / msys2) and ensure tool is available through PATH environment.
https://buildbot.readthedocs.io/en/latest/manual/installation/requirements.html#windows-support

**Comment by Aaron-Chan** [comment]
> You are right that `patch` is not native Windows command. You can try to install Cygwin (or mingw-64 / msys2) and ensure tool is available through PATH environment. https://docs.buildbot.net/latest/manual/installation/requirements.html#windows-support (https://buildbot.readthedocs.io/en/latest/manual/installation/requirements.html#windows-support)

Thank you

**Comment by mokibit** [comment]
@p12tic, 
I think this problem could be closed for the time being.
