### ISSUE TITLE
ShellCommand does not recognize finished command sometimes

### ISSUE THREAD

**Issue by zilti** [buildbot/buildbot#6827]
Sometimes, ShellCommand does not recognize that a command has finished. I don't know what exactly it looks for to determine this, because this is undocumented behaviour. I tried to circumvent this by putting my command through `time`, so I ended up with something like `steps.ShellCommand(command=['time', 'mycommand', 'argument'])`.

The buildbot logs even show the output of the `time` command as expected, but still the step keeps running until it times out.

**Comment by mokibit** [comment]
Hi, @zilti.
What Buildbot version do you use?
If it is not a secret, which exact shell commands cause unacceptable behavior?
The more details about the problem I have, the easier it will be to reproduce and to solve it.

**Comment by p12tic** [comment]
I will close this issue for now, please reopen once you have more information.
