### ISSUE TITLE
test_worker_proxy tests fail due to DeprecationWarning

### ISSUE THREAD

**Issue by YngveNPettersen** [buildbot/buildbot#6887]
In test_worker_proxy.py the run_proxy function makes a call to asyncio.get_event_loop() which throws a DeprecationWarning in Python 3.10 on Windows (the tests passes on Linux) when there is no event loop. The result is that the log file name is included as the "port" in the proxy configuration string.

See https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop for more information.

AFAICT the except step of the try block needs to catch both the RuntimeError and the DeprecationWarning.

I don't see any changes in the file that seem to fix this in 3.8

Update; tested on master (31952a86), and these tests fail for that as well.

**Comment by mokibit** [comment]
Hi, @YngveNPettersen,
I could not reproduce this problem on Windows10 Pro machine with Python3.8.10, Python3.9.7 and Python3.10.11 on latest Buildbot master (431375fe58663).
