### ISSUE TITLE
Reloading buildbot plugins?

### ISSUE THREAD

**Issue by ArthurPKFX** [buildbot/buildbot#6892]
I've recently created a private buildbot plugin to extend the API. I based it off [badges](https://github.com/buildbot/buildbot/tree/master/www/badges) (thanks for that "example", helped a lot) and it's been working great

However I'm facing a major issue that I haven't been able to resolve. When changing the code inside my routes, the changes don't affect my plugin when I reconfig Buildbot. It only works after doing a restart. I've tried debugging, trying to find a solution, to no avail
From what I understand this is basically caused by the fact a buildbot www plugin has to be a package (I installed it with `pip install -e .`), which somehow doesn't reload the reference to my plugin that it holds

Is this something I could avoid? It's a pretty big issue both for development (restarting takes a bit) and deploying (restarting cuts builds)
Hopefully there's a simple fix I'm missing! 🙂

**Comment by p12tic** [comment]
Unfortunately for Python code changes a `buildbot restart` is currently required.

For web frontend code this is not required though. You can run Buildbot web frontend as a devserver wich automatically reloads the web page whenever code changes. At least this was like this when I worked on the new React-based plugin infrastructure recently. For plugins a manual `vite build` step and a browser refresh was required, but this is still much faster than full `buildbot restart`.

**Comment by ArthurPKFX** [comment]
Thanks for the quick answer 🙂 
Sadly my plugin is python-only, for the web API

Could you explain why buildbot requires the plugin to be an installed package? Is this something I could modify?

**Comment by p12tic** [comment]
> Could you explain why buildbot requires the plugin to be an installed package? Is this something I could modify?

I think there's no hard reason for this. Plugins are distributed as packages so this needed to be supported. Perhaps no one looked into how to improve this to improve development turnaround time.

**Comment by ArthurPKFX** [comment]
I might be able to look into this then. Do you have some pointers on what buildbot requires for a plugin? Where is the entry point set?

**Comment by ArthurPKFX** [comment]
Alternatively, is there a way to expose an API through buildbot (on the same port basically) but without a plugin?

**Comment by p12tic** [comment]
@ArthurPKFX Sorry for taking a long time to reply, I didn't have an appropriate answer.

An easy solution that would work for you would be to use Buildbot multimaster mode with two instances - one for running builds and another for serving web frontend. Then you could restart the web frontend without interrupting the builds.

**Comment by p12tic** [comment]
Proper code reload is impossible unfortunately, as even `importlib.reload` has a lot of problems, such as any dependent modules being not reloaded automatically and so on.

**Comment by ArthurPKFX** [comment]
Thanks for the answer 🙂 Glad to know there's a partial solution if we need it
