### ISSUE TITLE
Buildbot master hangs on initLock during reconfig

### ISSUE THREAD

**Issue by slydiman** [buildbot/buildbot#6908]
Ubuntu 18.04.6 LTS
python 3.6.9
twisted 22.4.0

We have a highly loaded buildbot with 200+ workers.
We are using reconfig often and we have faced that buildbot master hangs every 5-10 reconfigs on the line 
`yield self.initLock.acquire()` https://github.com/buildbot/buildbot/blob/master/master/buildbot/master.py#L420
The object `initLock` in master.py is used directly.
The same object `initLock` is present in 
https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/bitbucket.py#L92
and
https://github.com/buildbot/buildbot/blob/master/master/buildbot/changes/hgpoller.py#L142
and used via the decorator `@deferredLocked('initLock')`.
It seems getattr(args[0], 'initLock') in the line https://github.com/buildbot/buildbot/blob/master/master/buildbot/util/misc.py#L30
returns `master.initLock` instead of a local object `initLock`.
We were able to workaround this issue by renaming `initLock` in bitbucket.py and hgpoller.py to `initLock2` and `initLock3` respectively.
We can prepare a pull request.
Thanks.

**Comment by p12tic** [comment]
Thanks for the bug report.

It would be very weird if `@deferredLocked('initLock')` in `bitbucket.py` and `hgpoller.py` returned master init lock. Seems like this could be unrelated concurrency-related race condition.

Which version of Buildbot are you using?

**Comment by slydiman** [comment]
We have faced this issue on v2.8.5. But nothing changed in the decorator `deferredLocked`, bitbucket.py and hgpoller.py around initLock since 2.8.5. We plan to upgrade to the current version soon. But we would like to minimize local patches.

> Seems like this could be unrelated concurrency-related race condition.

Note we did not change anything around `master.initLock` in our workaround. So it does not look like a race condition. Apparently a wrong object is being used.

**Comment by p12tic** [comment]
@slydiman There have been a number of race condition fixes in 2.10.x. I suggest to upgrade to 2.10.5 first. This would be much smaller step compared to upgrading to the latest version. Then you would see if the bug is still there.

**Comment by slydiman** [comment]
Thanks. We will try to upgrade the buildbot.

**Comment by p12tic** [comment]
I will close the bug report for the time being, but if you discover that the bug is still present on a newer Buildbot, please reopen it.
