### ISSUE TITLE
buildbot worker and Python 2 (dependency on future)

### ISSUE THREAD

**Issue by frenzymadness** [buildbot/buildbot#6980]
I have one simple question – Do you still need to support Python 2 for buildbot worker? I'm asking because this project uses future. future will no longer work with Python 3.12 because imp module has been removed from stdlib and the situation will be even worse with 3.13 because the lib2to3 which is the core of the future will be removed from stdlib as well.

It should be simple to remove the dependency on future, it's a good idea to do it, and I can help you with that if you want to.

**Comment by p12tic** [comment]
Thanks for the heads up. Yes, I agree that it's time to remove Python 2.7 support for the worker. Even after this the old workers will be able to connect to new master so whoever still needs to run tests on ancient operating systems can take this option.

> I can help you with that if you want to.

That would be great contribution.
