### ISSUE TITLE
Let's keep it open for discussion. I created an email to users@buildbot.net

### ISSUE THREAD

**Issue by poiuowrioi** [buildbot/buildbot#7046]
Let's keep it open for discussion. I created an email to users@buildbot.net

_Originally posted by @tardyp in https://github.com/buildbot/buildbot/issues/4439#issuecomment-439705837_

**Comment by pmisik** [comment]
Could you please explain why it is important to support Python 2.7? (3 years after official EOL of Python 2)

**Comment by p12tic** [comment]
@poiuowrioi Python 2.7 support is going to be removed completely from Buildbot in a couple of months. If you need Python 2.7 support, your best bet is to hire someone to keep porting new features and bug fixes to Python 2.7.

**Comment by p12tic** [comment]
Closing as answered. Please reopen if my answer is unclear or you don't agree with it.
