### ISSUE TITLE
How does it take effect after changing the files in the www folder

### ISSUE THREAD

**Issue by wqn521** [buildbot/buildbot#7088]
I have made changes to the front-end files in the www folder. How can I see the effect of the changes

**Comment by p12tic** [comment]
@wqn521 I know that the answer is too late. This page documents how to setup environment for frontend development http://docs.buildbot.net/current/developer/quickstart.html#create-a-javascript-frontend-environment.

**Comment by p12tic** [comment]
Please reopen if there are further questions (e.g. if documentation is unclear).
