### ISSUE TITLE
Worker status reason visualization in web UI

### ISSUE THREAD

**Issue by pmisik** [buildbot/buildbot#7104]
Worker action dialog allow specify reason when doing action with worker.
Like:
![image](https://github.com/buildbot/buildbot/assets/14224662/cc43bde9-7371-443d-aa43-8a4b0fa28453)

At the moment `reason` is visible just in `twisted.log`.
It would be useful to see entered `Reason` in web UI (e.g. on worker status page).

**Comment by tdesveaux** [comment]
Hi,

This is of interest to us as well.
I might be able to take some time to implement this, but I'd need to evaluate the time it would take to get it approved first.

If someone could give me some pointers were to look to implement this, that'd be great.

**Comment by p12tic** [comment]
This has been addressed in https://github.com/buildbot/buildbot/pull/7199.
