### ISSUE TITLE
react_www: login/logout button link does not work on same page

### ISSUE THREAD

**Issue by Mic92** [buildbot/buildbot#7107]
After enabling the react_www plugin, I can no longer press the login button here:

![Login button](https://github.com/buildbot/buildbot/assets/96200/0598fec6-a893-4e5b-acd9-a3bceb5db263)

Instead I have do a right click on the link and open it in a new tab.
This happens with both firefox and chromium on 3.9.2. You can check it out live by visiting https://buildbot.thalheim.io/ and trying to login (you should be able to get at least to the github login page)

**Comment by p12tic** [comment]
Thank you for the bug report. This has been addressed in https://github.com/buildbot/buildbot/pull/7085 and https://github.com/buildbot/buildbot/pull/7111 and will be released in Buildbot 3.10.0 in the next few weeks.

**Comment by Mic92** [comment]
Ok. If you need testers, I am happy to also test a release candidate of buildbot.
