### ISSUE TITLE
React UI: Add builder's workers to BuilderView

### ISSUE THREAD

**Issue by tdesveaux** [buildbot/buildbot#7162]
When there is a large number of workers and builders and all worker are not assigned to all builders, it's useful to be able to see which workers are assigned to a given builder.
The information is already there on the BuildersView, but it's annoying to find one builder when the list is large.

I managed to add it roughly in the react-ui with this code: https://github.com/tdesveaux/buildbot/commit/ec6d2967fd4505315e536616e65b4e756bee6b15
![image](https://github.com/buildbot/buildbot/assets/7926549/47ba179f-b9da-4a98-aa60-12d93ca3d74b)

But, IMHO, it would clutter the view a bit for an information that is not useful to everyone.

One solution that came to mind would be to add the information in a tab beside the 'Build requests' tab.
However, the tab container is part of the `BuildRequestsTable` component.

Would it be fine to extract the tabs part from `BuildRequestsTable` and move it to `BuilderView`?
This would result in a tab with Build requests and Builds information as it is now (with renaming of the tab title) and another tab with the workers list.

I'm prepared to submit a PR with proposed changes or to discuss another solution to this.

**Comment by p12tic** [comment]
@tdesveaux 

> Would it be fine to extract the tabs part from BuildRequestsTable and move it to BuilderView?
This would result in a tab with Build requests and Builds information as it is now (with renaming of the tab title) and another tab with the workers list.

This would be great I think.
