### ISSUE TITLE
Migrate away from distutils

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7203]
Buildbot build scripts still use distutils module, which is deprecated.

**Comment by Mic92** [comment]
It looks quite complicated to generate those VERSION files with setuptools. Maybe it's better to have the generated ahead of time?

**Comment by Mic92** [comment]
Ok. This Command class could be used: https://github.com/buildbot/buildbot/pull/7216/files

**Comment by p12tic** [comment]
Seems to be fixed in https://github.com/buildbot/buildbot/pull/7343.
