### ISSUE TITLE
Which Python version should be used to compile the buildbot source code

### ISSUE THREAD

**Issue by wqn521** [buildbot/buildbot#7218]
I can compile buildbot using Python 3.11, but compiling buildbot www cannot start the master

**Comment by tdesveaux** [comment]
I built it with py3.11 without issues.
Did you use `make tarballs` to build the tar/wheels? www packages need to be `yarn run build` to build the frontend files, which make takes care of.

**Comment by p12tic** [comment]
I think the question was answered. Please reopen if it isn't.
