### ISSUE TITLE
React UI: reverse proxy doesn't work with relative URLs (3.10, 3.9.2)

### ISSUE THREAD

**Issue by oron-peled** [buildbot/buildbot#7260]
I have few working instances of buildbot-3.8 behind `nginx` reverse proxy:
* However, the React based UI in 3.10 (and 3.9.2) doesn't work.
* I hacked my settings to make it work, but it still use absolute urls, not relative to the provided endpoints.
* As a result, even with the hack, I cannot host **multiple** instances behind one reverse proxy.

Details below...

The following is included into an `nginx` "`server {...}`" block and work with buildbot-3.8 (and 3.7 before):
```
location /my-endpoint-1/ {
        proxy_http_version 1.1;
        include proxy_params;
        proxy_pass http://127.0.0.1:8051/;
        proxy_set_header   Host               $http_host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;

        proxy_connect_timeout 150;
        proxy_send_timeout 100;
        proxy_read_timeout 100;
}

# Server sent event (sse) settings
location /my-endpoint-1/sse/ {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_pass http://127.0.0.1:8051/sse/;
}

# Websocket settings
location /my-endpoint-1/ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:8051/ws;
        proxy_read_timeout 6000s;
}
```
In my operational setup, each instance has it's own:
* Endpoint (in the example `/my-endpoint-1`)
* Port (in the example `8051`)

When using React based ui the initial result is empty page.
By looking into `/var/log/nginx/access.log` I found the endpoints this UI tries to access:
* `/assets`
* `/api`
* `/src`
So I added 3 extra proxy settings similar to this:
```
location /assets {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8051/assets;
        proxy_read_timeout 6000s;    
}
```

With these modifications, the React based UI seem to be functional.
**BUT:** the endpoints are absolute, so I cannot host multiple buildbots behind the same reverse proxy.

**Comment by oron-peled** [comment]
Clarification:
* The traditional web-UI (Angular based) is working in all buildbot versions
* It's the React UI that pose the issue described above
* But as UI development happens now only in React -- this issue becomes more serious (and will block future upgrading)

**Comment by oron-peled** [comment]
Thanks for the fix, I'll test it later this week when I'm at the office and will report results here.

**Comment by jpflori** [comment]
Not sure how to configure my apache2 proxy, with 3.11.2, I now get some UI, but data does not load, e.g. on the builders page I see "Loading..."

**Comment by jpflori** [comment]
Looks like some URL are not relative, the browser is trying to fetch bla.com/api/... instead of bla.com/buildbot/api/...
Might it be related to https://github.com/vitejs/vite/issues/11142#issuecomment-1501689795 ?

**Comment by oron-peled** [comment]
I just tested with the new version 3.11.2 and the problem remained the same.
The tries to access 3 endpoints with absolute path: `/api`, `/src` and `/assets`

This allows hosting a **single instance** only, by adding explicit reverse proxy of these endpoints.

For example:
* Running single `buildbot` on 127.0.0.1 port 8091 behind Nginx reverse proxy
* I added the following configuration to Nginx to make the web-ui function:
```
location /src {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8091/src;
        proxy_read_timeout 6000s;
}

location /api {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8091/api;
        proxy_read_timeout 6000s;
}


location /assets {
        proxy_http_version 1.1;
        proxy_pass http://127.0.0.1:8091/assets;
        proxy_read_timeout 6000s;
}
``` 

So we are still with the same issue as before -- we cannot have multiple `buildbot` instances running on the same host

**Comment by oron-peled** [comment]
Tested now buildbot [v4.0.1](https://github.com/buildbot/buildbot/releases/tag/v4.0.1)
I can confirm that with this version, reverse proxy operation is now supported on React UI.

Thanks a lot, this issue was an upgrade blocker for my setup (multiple buildbots behind single reverse proxy)
