### ISSUE TITLE
Remove AngularJS frontend

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7262]
We now have React web frontend and it no longer makes sense to maintain AngularJS frontend past v4.0.

**Comment by oron-peled** [comment]
Note that issue #7260 blocks using React web frontend.
It does not handle correctly reverse-proxy.

**Comment by p12tic** [comment]
@oron-peled I agree that #7260 is blocker.

**Comment by mokibit** [comment]
This issue is fixed in https://github.com/buildbot/buildbot/pull/7287.
