### ISSUE TITLE
Improve code completion

### ISSUE THREAD

**Issue by cathaysia** [buildbot/buildbot#7385]
Python currently supports using tools such as typing to prompt variable types. But buildbot currently does not support this part. The experience with complete code is still not very good.
On the other hand, modules exported from buildbot.plugin also have no type information.

To improve the code completion experience, on the one hand, type information needs to be added to existing code, and on the other hand, the modules in the plugin need to be exported using reexport instead of loading them using functions.

Do you have any plans to change this, and if I submit a PR, will this kind PR be accepted?

**Comment by p12tic** [comment]
I'm closing this issue as https://github.com/buildbot/buildbot/pull/7390 has been closed.

Improvements to typing support are welcome in Buildbot.
