### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by vstinner** [buildbot/buildbot#7429]
https://www.buildbot.net/ > Get Started > Read The Docs > http://docs.buildbot.net/current/index.html

This documentation says "Buildbot 3.9.0".

http://docs.buildbot.net/current/index.html > Release Notes

This doc only shows Buildbot 3.9.0 release notes.

I'm looking for Buildbot 3.11.0 release notes.

**Comment by vstinner** [comment]
Ah, I found 3.11 release notes at: https://github.com/buildbot/buildbot/blob/master/master/docs/relnotes/index.rst

**Comment by p12tic** [comment]
This has been fixed in https://github.com/buildbot/buildbot-infra/pull/270. Updated website will be visible once DNS TTL expires.

**Comment by vstinner** [comment]
Thanks for the fix!
