### ISSUE TITLE
what's the current communication channel?

### ISSUE THREAD

**Issue by sa2ajj** [buildbot/buildbot#7448]
I don't think i saw explicit information about it

**Comment by sa2ajj** [comment]
> I don't think i saw explicit information about it

irc, discord, etc?

**Comment by p12tic** [comment]
I personally monitor github issues the most.

**Comment by sa2ajj** [comment]
particular links?

**Comment by sa2ajj** [comment]
what used to work doesn't seem to any more

**Comment by sa2ajj** [comment]
ack

**Comment by sa2ajj** [comment]
i used to be an owner 🤔

**Comment by sa2ajj** [comment]
i aim to see if i could contribute a couple of things

**Comment by p12tic** [comment]
Seems like the question has been answered. In case it hasn't been please reopen.
