### ISSUE TITLE
Stop all build steps from dynamic build factories

### ISSUE THREAD

**Issue by JulienMalka** [buildbot/buildbot#7467]
I have a `BuildStep` that dynamically add a number of steps to my pipeline using `addStepsAfterCurrentStep`. 
Whenever I hit the `stop` button on the web interface, instead of killing all the queue of steps like I expect it too, it cancel the current step and goes on to the next one.

**Comment by tdesveaux** [comment]
@JulienMalka  I failed to reproduce with the following test:
```python
class CustomStep(BuildStep):
    def run(self):
        self.build.addStepsAfterCurrentStep([
            shell.ShellCommand(name=f"step-{idx:02d}", command=['sleep', idx])
            for idx in range(10)
        ])

        return defer.succeed(SUCCESS)

factory = BuildFactory(
    steps=[
        CustomStep(name='custom'),
    ]
)
```

Any chance the steps you add dynamically have `alwaysRun=True`?

**Comment by JulienMalka** [comment]
@tdesveaux You are right, I was adding steps with `alwaysRun=True`. Sorry for the misleading bug report and thank you for experimenting!
