### ISSUE TITLE
Waterfall tooltips broken after upgrade to Firefox 124

### ISSUE THREAD

**Issue by marrak** [buildbot/buildbot#7489]
**To reporoduce:**
Go to
https://buildbot.buildbot.net/#/waterfall
and try to display step info. (v. 3.10.1.dev426)
**Actual result:**
Tooltips are broken - can't see anything.
**More info:**
Works well on latest Chrome, Edge and FF earlier than v.124.
Reproduced on our private Buildbot too (v.3.5.0)

**Comment by pmisik** [comment]
Could you please attach images from FF 123 vs 124/5?
I've never seen correctly rendered Watherfall in FF.
![image](https://github.com/buildbot/buildbot/assets/14224662/11d84c98-486a-40b2-a491-505d6dd22246)

**Comment by marrak** [comment]
FF 123 - win64
![obraz](https://github.com/buildbot/buildbot/assets/2847500/0f9cafcc-45ac-470b-89af-29d60189165c)

**Comment by marrak** [comment]
FF 124 - win64
![obraz](https://github.com/buildbot/buildbot/assets/2847500/fb4bb80b-5b8b-4c5f-85ec-d499f6d4b34b)

**Comment by yan12125** [comment]
It's reported as a Firefox bug and fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1886012. I can confirm with Firefox beta (126.0b9), the waterfall view works fine again.

**Comment by pmisik** [comment]
I think this can be closed as it is fixed in Firefox 126 released today.

**Comment by p12tic** [comment]
Indeed, thanks!
