### ISSUE TITLE
GitPoller misses changes when buildbot reconfigured

### ISSUE THREAD

**Issue by doliver-pulsemining** [buildbot/buildbot#7527]
Our buildbot configuration builds every git commit on select branches using the SingleBranchScheduler. We regularly add or remove branches to be built and reload the config with `buildbot reconfig`.

I've been investigating a few commits that did not trigger a build in our setup. I found that when buildbot is reconfigured to pick up config changes it ignores any commit between the last poll before the reconfig and the first poll after the reconfig. 
The commit does trigger a build if buildbot is restarted.

It appears this is caused by the line [self.lastRev = {}](https://github.com/buildbot/buildbot/blob/b6a7d098471020aa4c89ebc2e4b55788a36a8392/master/buildbot/changes/gitpoller.py#L175). 
When buildbot is restarted the `activate` method loads `lastRev` from the database [self.lastRev = yield self.getState('lastRev', {})](https://github.com/buildbot/buildbot/blob/b6a7d098471020aa4c89ebc2e4b55788a36a8392/master/buildbot/changes/gitpoller.py#L215)
I think that the `reconfigService` method should also call `getState` to load the correct `lastRev` from the database.

Buildbot Version: 3.11.1
Operating System: RHEL9

**Comment by mokibit** [comment]
I am looking into this.
