### ISSUE TITLE
Webhooks not working with latest buildbot version

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#7575]
https://github.com/buildbot/buildbot/discussions/7556#discussion-6603463

Can someone please help on this.
It says POST is not allowed.

**Comment by p12tic** [comment]
Which exact Buildbot version are you using?

**Comment by vvscloud** [comment]
3.11.1

**Comment by p12tic** [comment]
Closing, since solution has been found in https://github.com/buildbot/buildbot/discussions/7556.
