### ISSUE TITLE
After upgrading to version 3.11.3, Gitpoller no longer fetches new changes

### ISSUE THREAD

**Issue by ah-1047games** [buildbot/buildbot#7687]
As the title says, my Buildbot configuration no longer fetches new changes since upgrading to 3.11.3.

I haven't made any recent changes to the Buildbot configuration. I can manually clone git@github.com-my-repo:MyCompany/my-repo.git without issues.

Here are the relevant logs from twisted.log related to Gitpoller:

`2024-06-05 11:51:34+0200 [-] gitpoller: processing changes from "git@github.com-my-repo:MyCompany/my-repo.git"`

Relevant config:

```
c['change_source'] = []
from buildbot.plugins import changes

c['change_source'].append(changes.GitPoller(
        repourl='git@github.com-my-repo:MyCompany/my-repo.git',
        branches=True,
        pollAtLaunch=True,
        pollInterval=60))


c['logCompressionMethod'] = 'gz'
c['logMaxSize'] = 1024*1024 # 1M
c['logMaxTailSize'] = 32768
c['logEncoding'] = 'utf-8'

c['caches'] = {
    'Changes' : 100,
    'Builds' : 500,
    'chdicts' : 100,
    'BuildRequests' : 10,
    'SourceStamps' : 20,
    'ssdicts' : 20,
    'objectids' : 10,
    'usdicts' : 100,
}

c['configurators'] = [util.JanitorConfigurator(
    logHorizon=timedelta(weeks=5),
    hour=12,
    dayOfWeek=6
)]
```

**Comment by tdesveaux** [comment]
duplicates of #7663

I introduced a bug that was included in the 3.11.3 release.
You can safely rollback to 3.11.2. I apologies for the inconvenience.
