### ISSUE TITLE
Improve backport tracking and process

### ISSUE THREAD

**Issue by tdesveaux** [buildbot/buildbot#7692]
Currently, backport are tracked in issues for each version (#7668, #7615, #7614).

A small improvement could be to use labels on PRs that need backports (like backport/3.11.3, backport/4.0.0).
This way, a simple search on Github filtering on the label allow to see which PRs need to be backported, and make for an easy check at release time.

In a second time, backporting could be automated with tools like https://github.com/GiteaBot/gitea-backporter (this is the only one I know off the top of my head, might incompatible with Buildbot's workflow, or there might be other better suited).
I can look into that to provide a documented steps on deploying this for Buildbot.

**Comment by p12tic** [comment]
I use bug approach because it's easier to give instructions to @mokibit on what needs to be backported and there's paper trail on what happened.
