### ISSUE TITLE
4.0.0 missing on PyPI

### ISSUE THREAD

**Issue by yan12125** [buildbot/buildbot#7743]
Hi, I noticed [4.0.0](https://github.com/buildbot/buildbot/releases/tag/v4.0.0) is tagged in git, while on PyPI the latest version is still [3.11.5](https://pypi.org/project/buildbot/#history). Is 4.0.0 considered generally available?

**Comment by elbehery95** [comment]
https://docs.buildbot.net/latest/manual/upgrading/4.0-upgrade.htm

Mentioned that it is a non released version

**Comment by yan12125** [comment]
(There seems a typo in your link. I assume you meant https://docs.buildbot.net/latest/manual/upgrading/4.0-upgrade.html)

Did you refer to this statement?

> This page documents the latest, unreleased version of Buildbot.

That sentence appears on every page under https://docs.buildbot.net/latest/ (ex: https://docs.buildbot.net/latest/manual/upgrading/3.0-upgrade.html). I wonder if that is an evidence that 4.0 is a non-released version.

On the other hand, version 4.0 is also mentioned on "current" documentation: https://docs.buildbot.net/current/manual/upgrading/4.0-upgrade.html

**Comment by yan12125** [comment]
4.0.0 is up on PyPI, thank you!

**Comment by p12tic** [comment]
Sorry, I wasn't able to upload to Pypi at the time (Pypi infrastructure issues?) and later forgot about it.
