### ISSUE TITLE
4.0.0 reverse proxy problem

### ISSUE THREAD

**Issue by limburgher** [buildbot/buildbot#7746]
I've been running 3.11.5 with no issues, on Fedora 40 reverse proxied behind Apache, both http and ws.

I'm the Fedora package maintainer, and in the process of testing 4.0.0 to upgrade, I ran into a problem where the javascript UI elements failed to load. 

The browser debugging console revealed that several urls were incorrect.

Example: If my buildbot instance is at https://example.com/buildbot, the UI is trying to load https://example.com/plugins/waterfall_view/scripts.js, which should actually be https://example.com/buildbot/plugins/waterfall_view/scripts.js

When I create a ssh tunnel to the server and connect via http://localhost:port, the UI works as expected.

I haven't made any changes to where files are placed with the RPMs in 4.0.0 vs 3.11.5. I did use the github source tarballs since they're not on pypi, but between that and the new react ui, that's the only change.

**Comment by limburgher** [comment]
There are no base or data-module directories in www for 4.0.0; should this apply to 4.0.0?

**Comment by limburgher** [comment]
#7780 doesn't apply to 4.0.0 either.

**Comment by p12tic** [comment]
> There are no base or data-module directories in www for 4.0.0; should this apply to 4.0.0?

The code has that: https://github.com/buildbot/buildbot/tree/fdf421a62888a9e9fb358e3a537ccfb0556cc2c8/www

Could you be using something else than v4.0.0 or trying to apply a patch to Buildbot that is installed? On installed Buildbot a lot of web-related files are missing because they are built into a javascript bundle (much like a compiled C application). Applying the patch is impossible in that case.

You can simply install 4.0.1 which will include the fixes. Please let me know if that works.

**Comment by limburgher** [comment]
4.0.1 works, thank you!

**Comment by limburgher** [comment]
4.0.1 is better, but at least src/browser-warning-list.js is missing.

**Comment by yan12125** [comment]
> 4.0.1 is better, but at least src/browser-warning-list.js is missing.

That sounds like a different problem: https://github.com/buildbot/buildbot/issues/7439

**Comment by oron-peled** [comment]
Tested now buildbot [v4.0.1](https://github.com/buildbot/buildbot/releases/tag/v4.0.1)
I can confirm that with this version, reverse proxy operation is now supported on React UI.

Thanks a lot, this issue was an upgrade blocker for my setup (multiple buildbots behind single reverse proxy)

**Comment by tdesveaux** [comment]
@oron-peled note #7814 if this was a blocker for you and you use authentication. It's fixed but not yet released.

**Comment by oron-peled** [comment]
@tdesveaux thanks, just tested latest release (4.0.2) and added a note in #7814 that it's closed before the fix is released.
Waiting for next release to re-test.
