### ISSUE TITLE
Fail fast if yarn or yarnpkg is not present.

### ISSUE THREAD

**Issue by gl-yziquel** [buildbot/buildbot#7751]
I tried to build buildbot on a "blank slate" machine with not much installed. In particular, with no yarn install. I noticed a failure with an "install" instruction. The YARN makefile variable was in fact set to an empty string and what should have been "yarn install" became interpolated into "install". This PR adds a check to make if "fail fast" with an error message that is more palatable that a badly interpolated "install" instruction in some shell scripting.

https://github.com/buildbot/buildbot/pull/7749

**Comment by mokibit** [comment]
@gl-yziquel , thanks for opening an issue and offering solution.
It was fixed by https://github.com/buildbot/buildbot/pull/8065.

**Comment by gl-yziquel** [comment]
> @gl-yziquel , thanks for opening an issue and offering solution. It was fixed by #8065.

@mokibit you're welcome.
