### ISSUE TITLE
Need help to upgrade a WSGI dashboard from buildbot 3.11 to buildbot 4.0

### ISSUE THREAD

**Issue by vstinner** [buildbot/buildbot#7775]
Hi,

I upgraded buildbot from 3.11.3 to 4.0.0 and a plugin using `wsgi_dashboards` is gone: it seems to be ignored! I don't know how to debug that.

I tried to follow the [upgrade guide](https://docs.buildbot.net/4.0.0/manual/upgrading/4.0-upgrade.html#custom-plugins).

I replaced `buildbot-wsgi-dashboards==4.0.0` dependency with `buildbot-react-wsgi-dashboards==4.0.0`, but buildbot failed to start:

```
builtins.RuntimeError: could not find plugin wsgi_dashboards; is it installed?
```

The upgrade guide asks to uninstall: `pip uninstall (...) buildbot-react-wsgi-dashboards` and then install `pip install (...) buildbot-react-wsgi-dashboards`. It is the same package, no?

Our plugin config: https://github.com/python/buildmaster-config/blob/5dca1bcee7e809777ca390e151e9188fafa5cb9f/master/master.cfg#L536-L544 

Our Flash dashboard: https://github.com/python/buildmaster-config/blob/main/master/custom/release_dashboard.py 

I also tried to downgrade, but then the Alembic "migration" went bad :-(

My issue: https://github.com/python/buildmaster-config/issues/498

**Comment by tdesveaux** [comment]
Hi,

I think you just need to replace `wsgi_dashboard` [here](https://github.com/python/buildmaster-config/blob/5dca1bcee7e809777ca390e151e9188fafa5cb9f/master/master.cfg#L536) with `react_wsgi_dashboard`.

Although the `react` plugins were for the latest v3 to prepare upgrade, so if you install `buildbot-wsgi-dashboard==4.0.0`, it should use the react version of the plugin.

**Comment by vstinner** [comment]
wsgi_dashboards in https://buildbot.python.org/all/?#/about says:

[{"name":"release_status","caption":"Release Status","app":"'flask.app.Flask' not yet IConfigured","order":2,"icon":"rocket"}]

Oh, there is a Flask error.

**Comment by vstinner** [comment]
> It seems like I have a major URL issue which might cause this issue: https://github.com/buildbot/buildbot/issues/7776

We worked around the issue and it seems like buildbot is now mostly fully functional. Only our dashboard plugin is broken, maybe because of the migration to React?

**Comment by vstinner** [comment]
I close the issue. I may open more specific issue if I need more help.
