### ISSUE TITLE
Buildbot 4.0 strips "all/" suffix from "https://buildbot.python.org/all/" buildbotURL

### ISSUE THREAD

**Issue by vstinner** [buildbot/buildbot#7776]
Hi,

I just upgraded buildbot from 3.11 to 4.0 (see issue #7775) and I noticed in Firefox web tools that many requests are failing with HTTP 404.

The configure file `master/master.cfg` contains:

```
c["buildbotURL"] = "https://buildbot.python.org/all/"
```

The problem is that Firefox opens URLs without `all/`. For example, it tries to load `https://buildbot.python.org/all/api/v2/builders` instead of `https://buildbot.python.org/all/api/v2/builders`. The `all/` is gone in the URL.

Multiple pages are broken by this issue:

* About page
* Login with GitHub
* Builders
* etc.

Can it be a buildbot 4.0 regression? Or a configuration issue?

Thanks in advance.

**Comment by vstinner** [comment]
I'm very confused. If I switch to a different web browser (Chromium), it seems like everything is fine when I browse: https://buildbot.python.org/all/

Maybe Firefox has outdated caches?

**Comment by tdesveaux** [comment]
Probably fixed by #7747

Not yet release though (and not in planned backports, but maybe it's a miss)

**Comment by p12tic** [comment]
Added https://github.com/buildbot/buildbot/pull/7747 to backports list.

**Comment by p12tic** [comment]
@mokibit Would it be possible to apply the backports tomorrow?

**Comment by mokibit** [comment]
Yes, by tomorrow it will be done.

**Comment by p12tic** [comment]
Thanks a lot.

**Comment by p12tic** [comment]
@vstinner I recommend against major Buildbot version upgrades without any additional testing. There exists a document on upgrade procedure - it is quite long. https://docs.buildbot.net/latest/manual/upgrading/4.0-upgrade.html#upgrading-to-buildbot-4-0-not-released

Tomorrow I will release 4.0.1 with https://github.com/buildbot/buildbot/pull/7747 and we will see if that helps.

**Comment by vstinner** [comment]
We worked around the issue by changing the URL to "https://buildbot.python.org/".

**Comment by p12tic** [comment]
> We worked around the issue by changing the URL to "https://buildbot.python.org/".

https://github.com/buildbot/buildbot/pull/7747 should fix this issue. I expect you will probably just keep the current URL and not bother spend time testing.

I will thus close this issue. Please reopen if you notice that #7747 does not fix the bug.

Thanks for the bug report, which caused us to prioritize releasing the bugfix.

**Comment by vstinner** [comment]
I don't plan to change the URL back to /all/ for testing, since it's a non-trivial change which requires to change also our Nginx rules. It was stressful for me to fix the issue in production. And we didn't solve all issues yet.

Anyway, thanks for the quickfix!
