### ISSUE TITLE
Buildbot 3.11.5 Missing / after # in URLs of items triggered by the builder

### ISSUE THREAD

**Issue by StefanBeOs** [buildbot/buildbot#7789]
Been playing around with buildbot 3.11.5 and one thing I had noticed that is under a Builder's build steps if there are a list of triggers the URLs for each triggered item (builders/buildrequests) are missing a / after the # symbol in the URL.
Such as 'https://buildbot.local/#buildrequests/20' which should actually be 'https://buildbot.local/#/buildrequests/20'

```
trigger
[Example builders #1](https://buildbot.local/#buildrequests/20)
[success: testexample #1](https://buildbot.local/#builders/1/builds/1)

```

**Comment by mokibit** [comment]
Hi, @StefanBeOs,
thanks for opening an issue!
I tried reproducing it on master branch and on v3.11.5 (with and without React). Unfortunately, to no avail.
Could you please provide more details on how to reproduce this issue, what is the exact master.cfg configuration, and I will try to fix it.

**Comment by p12tic** [comment]
Seems like the bug can be closed. In case the issue is still present, please reopen the bug report.
