### ISSUE TITLE
Buildbot does not work in web subdirectory

### ISSUE THREAD

**Issue by vit9696** [buildbot/buildbot#7814]
Even after the latest backports to 4.0.1 login link still points to website root: `href="/auth/login?redirect=/"` effectively preventing authorisation to work.

**Comment by vit9696** [comment]
Original report which is not fully fixed was reported in #7746.

**Comment by p12tic** [comment]
Thanks for the bug report. Indeed, it's likely that people who fixed the bug were using local installation where login is not needed.

**Comment by tdesveaux** [comment]
That's ... exactly what happen. I'll look into it.

I also created #7819 to implement tests to prevent future issues on this. But as mentioned, I'm no sure how to tackle this.

**Comment by vit9696** [comment]
I have just updated to 4.0.2. This issue is NOT fixed in 4.0.2. Please reopen the ticket.

CC @p12tic, @tdesveaux.

**Comment by tdesveaux** [comment]
Looks like https://github.com/buildbot/buildbot/pull/7824 was not backported to 4.0

**Comment by oron-peled** [comment]
Just tested today version 4.0.2 and the issue is still there (http requests of absolute "`/auth/...`" urls)
It seems this issue should be reopened.

**Comment by vit9696** [comment]
Tested 4.0.3, works fine.
