### ISSUE TITLE
Test and release scripts should pin dependencies to specific version instead of upgrading

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#7834]
There are multiple places in Buildbot codebase where we do `pip install -U <packages>` where <packages> are most often a combination of pip, setuptools and wheel. This makes the process non-reproducible and dependent on upgrades to these packages not breaking the rest of the code. The latter happens time to time, e.g https://github.com/pypa/setuptools/issues/4477.

We should have requirements-pip with these dependencies.

**Comment by mokibit** [comment]
@p12tic fixed in https://github.com/buildbot/buildbot/pull/7835.
