### ISSUE TITLE
react_waterfall view in 4.0.1 no longer allows to click on an individual build to see the build steps

### ISSUE THREAD

**Issue by doberkofler** [buildbot/buildbot#7854]
The react_waterfall view in 4.0.1 no longer allows to click on an individual build to see the build steps.
In other views this is still possible but not in the react_waterfall view.
There is also a small visual problem with the step names not being contained in the hoover popup as visible in this screenshot.

![image](https://github.com/user-attachments/assets/2a93ba9d-4339-4d44-8b9e-47366b93d55d)

**Comment by yan12125** [comment]
The main issue seems the same as an issue that is recently fixed. The fix will be in 4.0.2: https://github.com/buildbot/buildbot/pull/7831

> There is also a small visual problem with the step names not being contained in the hoover popup as visible in this screenshot.

I can see something similar in buildbod 3.x (ex: https://lab.llvm.org/buildbot/#/waterfall). Probably that's an old issue.

**Comment by p12tic** [comment]
Closing as 3.11.7 and 4.0.2 have been released.

**Comment by doberkofler** [comment]
@p12tic I just upgraded to 4.0.2 but it does not yet seem to work as expected
