### ISSUE TITLE
ui_default_config not respected

### ISSUE THREAD

**Issue by classabbyamp** [buildbot/buildbot#7894]
on buildbot 4.0.2, these settings are not respected (the default value `False` is used) on buildmaster startup:

```py
c['www']['ui_default_config'] = {
        'Waterfall.number_background_waterfall': True,
        'Waterfall.show_builders_without_builds': True,
        'Grid.fullChanges': True,
}
```

`'Builders.show_workers_name': True` is respected.

These values I copied from the settings page's "override defaults for all users" section and pasted in my buildbot config.

**Comment by jvivenot** [comment]
I believe this is what I fixed in #7790
