### ISSUE TITLE
Downgrade evalidate to an extra dependency

### ISSUE THREAD

**Issue by yan12125** [buildbot/buildbot#7933]
Currently, the new dependency `evalidate` (74767e81cbe53e28d16e453fd66065da07878409) is only used by "experimental and not documented" steps in buildbot.steps.configurable (5a21eb4b28756a76902bb9b17251860c29e9ea03). How about moving it from `install_requires` to `extras_require` in https://github.com/buildbot/buildbot/blob/master/master/setup.py?

**Comment by mokibit** [comment]
@yan12125 thanks for suggestion. Implemented by https://github.com/buildbot/buildbot/pull/8034.
