### ISSUE TITLE
Web UI generates broken project URLs

### ISSUE THREAD

**Issue by mathrick** [buildbot/buildbot#7954]
I'm following the official tutorial's [Quick Tour](https://docs.buildbot.net/current/tutorial/tour.html). The project identity in `master.cfg` is set as follows, the URL is unchanged from the auto-generated sample:

```python
####### PROJECT IDENTITY

# the 'title' string will appear at the top of this buildbot installation's
# home pages (linked to the 'titleURL').

c['title'] = "Hello World Tutorial"
c['titleURL'] = "https://buildbot.github.io/hello-world/"
```

There are two immediate issues here that are visible:

1. The `title` string is not actually linked anywhere on the homepage, it's rendered as just a string.
2. The URL *is* linked in the About page, but the link generated is broken by being made relative to the web UI's own URL (ie. `http://localhost:8010/?#/about/https://buildbot.github.io/hello-world/`). This is also true for the "buildbot" link which should link to the buildbot project's homepage.

![image](https://github.com/user-attachments/assets/ff758720-b2e8-4661-bfb5-ef68df3ce018)

**Comment by yan12125** [comment]
The URL issue should have been fixed in https://github.com/buildbot/buildbot/pull/7895

**Comment by p12tic** [comment]
Fixed in https://github.com/buildbot/buildbot/pull/7895 and backported to 4.0.3.
