### ISSUE TITLE
Master docker build fails due to vite package version incompatibility with node 16 

### ISSUE THREAD

**Issue by mallow123** [buildbot/buildbot#8009]
master docker image build fails due to version incompatibility.

`error vite@5.4.3: The engine "node" is incompatible with this module. Expected version "^18.0.0 || >=20.0.0". Got "16.20.2"
error Found incompatible module.
`

**Comment by p12tic** [comment]
This has been addressed in https://github.com/buildbot/buildbot/pull/8021.
