### ISSUE TITLE
No worker Actions buttons in 4.0.3

### ISSUE THREAD

**Issue by fraca7** [buildbot/buildbot#8063]
As said in https://github.com/buildbot/buildbot/discussions/8010 the worker actions button seems to be missing from the workers page and the specific worker pages; see attached screenshots and configuration.

Tested on:

Ubuntu 22.04 (Python 3.10.12)
buildbot 4.0.3
Vivaldi 6.9.3447.44-1
Firefox 130.0

[packages.txt](https://github.com/user-attachments/files/17186952/packages.txt)
![cap1](https://github.com/user-attachments/assets/e63c4ed3-14c5-49f1-af02-2a3c6c3fe352)
![cap2](https://github.com/user-attachments/assets/2609fe4d-71f1-4ab8-9477-7792e2fd3ad0)

**Comment by fraca7** [comment]
Forgot to mention: the buildbot configuration itself is the basic master.cfg.example generated by create-master

**Comment by tdesveaux** [comment]
https://github.com/buildbot/buildbot/pull/7984 add the Action button to the Workers page.

Still missing from the specific Worker page.

In the mean time, note that the emote in the "State" column is clickable and open the dialog that would be open with the Action button.
