### ISSUE TITLE
buildbot 4.x: Waterfall is truncated on Firefox

### ISSUE THREAD

**Issue by vstinner** [buildbot/buildbot#8139]
Page, buildbot 4.1: https://buildbot.python.org/#/waterfall

Chromium 129.0.6668.100:

![Capture d’écran du 2024-10-17 11-46-59](https://github.com/user-attachments/assets/dfdbeda3-c00f-47b4-9832-f30be2008307)

Firefox 131.0.2:

![Capture d’écran du 2024-10-17 11-47-26](https://github.com/user-attachments/assets/cd7d3bd5-e699-42a4-b7a8-68bfda619f2e)

**Comment by pmisik** [comment]
I use Firefox Developer Edition - 132.0b9 (64-bit) on Windows 11 and it looks similiar to latest MS Edge.
Maybe Mozilla fixed issue.
Can you check if this is still relevant on Your environment?

**Comment by vstinner** [comment]
I still have the issue with Firefox 131.0.3 (on Fedora 40).

**Comment by vstinner** [comment]
FYI I still have the issue on Firefox on Firefox 132.0.1 (64 bits) on Fedora 41.

**Comment by p12tic** [comment]
Interestingly it works on Firefox 128.4.0esr

**Comment by p12tic** [comment]
@vstinner I couldn't reproduce with Firefox 133. However, could it be that the view is just zoomed out a lot in your case? Zoom buttons are hidden behind the three bar button (usability bug).

**Comment by vstinner** [comment]
> @vstinner I couldn't reproduce with Firefox 133. However, could it be that the view is just zoomed out a lot in your case?
> Zoom buttons are hidden behind the three bar button (usability bug).

The Zoom buttons have no effect.

**Comment by p12tic** [comment]
If you go to Settings, what does "Waterfall related settings -> Scaling factor" say?

**Comment by vstinner** [comment]
> If you go to Settings, what does "Waterfall related settings -> Scaling factor" say?

It's equal to zero.

![Screenshot 2024-12-04 at 11-07-30 Buildbot](https://github.com/user-attachments/assets/45999bb3-a51e-4e1a-99f4-9d2afe02cb44)

If I set it to one... The bug is solved! Oh!

I have no idea how this setting became zero. I didn't touch it. This buildbot migrated from Buildbot 3.x to Buildbot 4.x, I don't know if it's related?

**Comment by p12tic** [comment]
> I have no idea how this setting became zero. I didn't touch it. This buildbot migrated from Buildbot 3.x to Buildbot 4.x, I don't know if it's related?

It could be. The migration path may have bugs unfortunately.

**Comment by vstinner** [comment]
What might be done on the buildbot side is to replace automatically `zoom <= 0` setting with `zoom=1`.

**Comment by vstinner** [comment]
I close the issue since I found a workaround.
