### ISSUE TITLE
doStepIf is ignored in ShellSequence

### ISSUE THREAD

**Issue by cmouse** [buildbot/buildbot#8241]
- Buildbot version: 4.1.0
- Twisted version: 22.10.0
- Python 3.11.2

I have following ShellSequence

```py
    def imaptest_step(self, factory, *extra):
        factory.addStep(
            steps.ShellSequence(
                commands=[

                    util.ShellArg(
                        command=DetermineImaptestDownload(),
                        logname="download",
                    ),
                    util.ShellArg(
                        command=["sudo", "install", "/tmp/imaptest", "/usr/bin/imaptest"],
                        logname="install"
                     )
                ],
                workdir="build",
                name="Install imaptest",
                haltOnFailure=True,
                doStepIf=canDownloadImaptest,
                hideStepIf=lambda results, s: results==SKIPPED,
            )
        )
```

and canDownloadImaptest is never even executed, I checked this with log.msg() in the function.

I then tried changing doStepIf=False

and added some logging into buildbot/process/buildstep.py

```py
            log.msg(f"doStep is {self.doStepIf!r} before rendering")
            
            # check doStepIf (after rendering)
            if isinstance(self.doStepIf, bool):
                doStep = self.doStepIf
            else:
                doStep = yield self.doStepIf(self)

            log.msg(f"doStep is {doStep} after rendering")
```

and the output of this logging was

```
2024-12-04 07:43:18+0000 [-] doStep is True before rendering
2024-12-04 07:43:18+0000 [-] doStep is True after rendering
```

which seems to indicate that there is possibly a bug in buildbot.

I also checked that the result is same with the original doStepIf=canDownloadImaptest:

```
2024-12-04 07:55:20+0000 [-] doStep is True before rendering
2024-12-04 07:55:20+0000 [-] doStep is True after rendering
```

**Comment by terencehonles** [comment]
Just taking a quick glance, but I'm pretty sure `steps.ShellSequence` operates as a unit, and the `doStepIf` will only evaluate once and *before* your `ShellArg` `DetermineImaptestDownload()` (I'm assuming based on its name this is what you're expecting to control the `doStepIf`).

How I've implemented things before is to use `steps.SetPropertyFromCommand` (optionally with an `extract_fn`) and then I would have a *separate* `steps.ShellCommand` (or other step) that relies on the `doStepIf`.

Also be aware your `doStepIf` seems to be literal? Is that intended? `doStepIf` should probably be a function of the form: `doStepIf=lambda s: bool(s.getProperty('can-download-imap-test'))` (this does not handle key errors and uses the property's Python truthiness which may or may not be correct for how you're setting the property, but if you need to check something outside your buildmaster configuration you need to use properties).

**Comment by cmouse** [comment]
Hi!

No the canDownloadImaptest is a renderer function, not a literal.

**Comment by cmouse** [comment]
My aim is to skip this sequence fully if canDownloadImaptest returns False for this build.

**Comment by terencehonles** [comment]
I think you need to either provide more of your code or test either a different buildbot version or a different step type. Does it work correctly for a `ShellCommand` instead of a `ShellSequence`?

**Comment by cmouse** [comment]
It worked before 4.0.1, as we use similar construct elsewhere as well.

this is the doStepIf function we use:

```py
@defer.inlineCallbacks
def canDownloadImaptest(step: steps.BuildStep) -> bool:
    os = yield util.Interpolate("%(worker:os_id)s").getRenderingFor(step.build)
    version = yield util.Interpolate("%(worker:os_version_id)s").getRenderingFor(step.build)
    log.msg("In canDownloadImaptest")

    if os in ('debian') and version in ('11', '12'):
        return True
    if os in ('ubuntu') and version in ('20.04', '22.04', '24.04'):
        return True
    if os in ('redhat', 'centos', 'rhel') and re.match(r"^(8|9)\..*", version):
        return True
    if os in ('amzn') and version in ('2023'):
        return True

    log.msg("Leaving canDownloadImaptest with failure")
    return False
```

**Comment by terencehonles** [comment]
I see, I was assuming `DetermineImaptestDownload` did something that was related to your `doStepIf` but it looks like your function only depends on the OS and OS version. This does sound like a regression. I still haven't updated to the latest release and am at 4.0.3, so it's possible this will pop up for me too.

Can you test with 4.0.4 to see if you're seeing it there too? (not sure if it's easy for you to rollback at all). The changelog for 4.1 doesn't seem to suggest this should have broken though.

I was only visiting the repo to see if I wanted to attempt an upgrade now or wait a little (making sure some of my recent commits would be in the release, and I could remove my local patches), but it sounds like I may not be able to help much in this thread.

**Comment by cmouse** [comment]
After some annoying debugging, it seems this is (mostly) limited to ShellSequence. It seems that something in the mix is now filtering out doStepIf.

**Comment by cmouse** [comment]
turns out this was totally a red herring, and was caused by looking at the wrong place. No bug.
